name: solid-vm
version: 0.0.4
build-type: Simple
author: Jamshid
maintainer:    jamshidnh@gmail.com
synopsis: A Haskell version of an Ethereum EVM
category:      Data Structures
license: Apache-2.0
description:
    The client described in the Ethereum Yellowpaper

default-extensions:
  - DeriveGeneric
  - DeriveAnyClass
  - LambdaCase


dependencies:
  - base >= 4 && < 5
  - aeson
  - aeson-casing
  - binary
  - blockapps-data
  - blockapps-datadefs
  - blockapps-mpdbs
  - ethereum-rlp
  - base16-bytestring
  - blockapps-util
  - bytestring
  - containers
  - cryptonite
  - deepseq
  - extra
  - format
  - generic-random
  - hashable
  - lens
  - memory
  - merkle-patricia-db
  - parsec
  - prometheus-client
  - QuickCheck
  - quickcheck-instances
  - resourcet
  - semver-range
  - servant-docs
  - solid-vm-model
  - strato-model
  - swagger2
  - text
  - time
  - transformers
  - unordered-containers
  - vector
  - vm-tools


#  - ethereum-vm
#  - ansi-wl-pprint
#  - base16-bytestring
#  - binary
#  - blockapps-haskoin
#  - bytestring
#  - clockwork
#  - containers
#  - cpu
#  - cryptohash
#  - deepseq
#  - ethereum-encryption
#  - extra
#  - ghc
#  - integer-gmp
#  - lens
#  - merkle-patricia-db
#  - mtl
#  - primitive
#  - resourcet
#  - text
#  - unboxed-ref
#  - vector
#  - vm-tools
#  - http-api-data
#  - persistent
#  - random
#  - servant



library:
  source-dirs: src/
  exposed-modules:
    - Blockchain.SolidVM
    - SolidVM.Solidity.Parse.File
    - SolidVM.Solidity.Parse.Lexer
    - SolidVM.Solidity.Parse.Statement
    - SolidVM.Solidity.Parse.UnParser
    - SolidVM.Solidity.Parse.Declarations
    - SolidVM.Solidity.Xabi.Statement
    - CodeCollection
  ghc-options: -Wall -O2

executables:
  parse-solidvm:
    source-dirs: exec_src
    main: Parse.hs
    dependencies:
      - solid-vm
    ghc-options: -Wall -O2 -threaded -rtsopts



tests:
  solid-vm-spec:
    source-dirs: tests/
    main: Main.hs
    dependencies:
      - async
      - base16-bytestring
      - hflags
      - hspec
      - hspec-expectations-lifted
      - HUnit
      - raw-strings-qq
      - solid-vm

benchmarks:
    codebench:
      source-dirs: bench/
      main: CodeBench.hs
      dependencies:
        - criterion
        - file-embed
        - solid-vm
