name: solid-vm
version: 0.0.4
build-type: Simple
author: Jamshid
maintainer:    jamshidnh@gmail.com
synopsis: A Haskell version of an Ethereum EVM
category:      Data Structures
description:
    The client described in the Ethereum Yellowpaper

dependencies:
  - base

library:
  source-dirs: src/
  exposed-modules:
    - Blockchain.SolidVM
    - Blockchain.SolidVM.SM
    - Blockchain.SolidVM.CodeCollectionDB
    - Blockchain.SolidVM.Exception
    - SolidVM.Solidity.Detectors
    - SolidVM.Solidity.Parse.File
    - SolidVM.Solidity.Parse.Lexer
    - SolidVM.Solidity.Parse.Statement
    - SolidVM.Solidity.Parse.UnParser
    - SolidVM.Solidity.Parse.Declarations
    - SolidVM.Solidity.Xabi.Statement
    - SolidVM.Solidity.Xabi.Type
    - CodeCollection
  ghc-options: -Wall -O2
  dependencies:
  - QuickCheck
  - aeson
  - aeson-casing
  - base16-bytestring
  - binary
  - blockapps-data
  - blockapps-datadefs
  - blockapps-mpdbs
  - blockapps-util
  - bytestring
  - containers
  - cryptonite
  - debugger
  - deepseq
  - ethereum-rlp
  - exceptions
  - extra
  - format
  - generic-random
  - lens
  - memory
  - merkle-patricia-db
  - monad-alter
  - nibblestring
  - parsec
  - prometheus-client
  - quickcheck-instances
  - semver-range
  - servant-docs
  - solid-vm-model
  - source-tools
  - strato-model
  - swagger2
  - text
  - time
  - transformers
  - unliftio
  - unordered-containers
  - utf8-string
  - vector
  - vm-tools
  - x509-certs


executables:
  parse-solidvm:
    source-dirs: exec_src
    other-modules: []
    main: Parse.hs
    dependencies:
      - parsec
      - solid-vm

    ghc-options: -Wall -O2 -threaded -rtsopts

  exprs-needed:
    source-dirs: exec_src
    other-modules: []
    main: ExprsNeeded.hs
    dependencies:
      - containers
      - parsec
      - solid-vm
      - text

tests:
  solid-vm-spec:
    source-dirs: tests/
    main: Main.hs
    dependencies:
      - async
      - base16-bytestring
      - blockapps-datadefs
      - blockapps-mpdbs
      - blockapps-util
      - bytestring
      - containers
      - deepseq
      - ethereum-rlp
      - hflags
      - hspec
      - hspec-expectations-lifted
      - HUnit
      - lens
      - merkle-patricia-db
      - parsec
      - raw-strings-qq
      - solid-vm
      - solid-vm-model
      - strato-model
      - text
      - time
      - vm-tools
      - utf8-string

benchmarks:
    codebench:
      source-dirs: bench/
      main: CodeBench.hs
      dependencies:
        - criterion
        - file-embed
        - solid-vm
