name:                blockapps-vault-wrapper-server
version:             0.1.0.0
github:              "githubuser/vault-wrapper"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/server#readme>

dependencies:
- base
- blockapps-vault-wrapper-api
- common-log
- postgresql-simple

library:
  source-dirs: src
  dependencies:
    - blockapps-ethereum
    - bytestring
    - cache
    - clock
    - haskoin-shim
    - http-client
    - lens
    - monad-control >=1.0 && <1.1
    - mtl
    - opaleye
    - product-profunctors
    - profunctors
    - saltine
    - servant-swagger
    - strato-model
    - swagger2
    - transformers
    - unliftio
    - resource-pool
    - servant
    - servant-server
    - text

executables:
  blockapps-vault-wrapper-server:
    source-dirs: app
    main: Main.hs
    other-modules: [Options]
    dependencies:
      - blockapps-vault-wrapper-server
      - blockapps-init
      - cache
      - clock
      - hflags
      - http-client
      - resource-pool
      - servant
      - servant-options
      - servant-server
      - wai
      - wai-cors
      - wai-extra
      - wai-middleware-prometheus
      - warp
      
  migrate-keys:
    source-dirs: app
    main: MigrateKeys.hs
    other-modules: [Options]
    dependencies:
      - blockapps-vault-wrapper-server
      - bytestring
      - csv
      - hflags
      - lens
      - opaleye
      - text

