name:                blockapps-vault-wrapper-server
version:             0.1.0.0
github:              "githubuser/vault-wrapper"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/server#readme>

dependencies:
- aeson
- ansi-wl-pprint
- base
- base16-bytestring
- binary
- blockapps-ethereum
- blockapps-init
- bytestring
- byteable
- common-log
- conduit
- containers
- cryptonite
- deepseq
- ethereum-rlp
- haskoin-shim
- hflags
- http-client
- lens
- lifted-base
- memory
- monad-control >=1.0 && <1.1
- mtl
- murmur3
- network
- nibblestring
- opaleye
- path-pieces
- pbkdf
- postgresql-simple
- product-profunctors
- profunctors
- QuickCheck
- resource-pool
- saltine
- servant
- servant-client
- servant-client-core
- servant-options
- servant-server
- servant-swagger
- split
- swagger2
- text
- time
- transformers
- transformers-base
- unliftio
- unordered-containers
- blockapps-vault-wrapper-api
- wai
- wai-cors
- wai-extra
- wai-middleware-prometheus
- wai-middleware-static
- warp

library:
  source-dirs: src

executables:
  blockapps-vault-wrapper-server:
    source-dirs: app
    main: Main.hs
    other-modules: [Options]
    dependencies:
      - blockapps-vault-wrapper-server

  migrate-keys:
    source-dirs: app
    main: MigrateKeys.hs
    other-modules: [Options]
    dependencies:
      - csv
      - blockapps-vault-wrapper-server

tests:
  server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blockapps-vault-wrapper-server
