FROM auth.blockapps.net:5000/blockapps/mgit 

MAINTAINER Kristoffer Josefsson <kristoffer@blockapps.net>

ARG USER=anonymous
ARG PASSWORD=

#RUN apt-get update
#RUN apt-get install -y curl
#RUN apt-get install -y git
#RUN curl -sSL https://get.haskellstack.org/ | sh

RUN apt-get install -y postgresql postgresql-server-dev-9.5 libleveldb-dev libpcre3-dev libpcre++-dev wget

RUN echo "https://${USER}:${PASSWORD}@github.com" >~/.git-credentials

#RUN git clone http://github.com/blockapps/mgit -b 131758053_credential-helpers
#RUN cd mgit ; stack setup; stack install alex happy
#RUN cd mgit ; stack install

RUN mgit clone https://${USER}:${PASSWORD}@github.com/blockapps/silo -b 131750813_build-process 

RUN cd silo ; ./install dpkg

#RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
#RUN echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" >> /etc/apt/sources.list.d/docker.list
#RUN apt-get install -y apt-transport-https
#RUN apt-get update
#RUN apt-get install -y docker-engine
#RUN service docker start
#VOLUME /var/run/docker.sock

#RUN docker run hello-world

