FROM ubuntu:16.04
MAINTAINER Ryan Reich <ryan@blockapps.net>

COPY setup-deployment.sh /
RUN \
  export DEBIAN_FRONTEND=noninteractive; \
  sed -i 's/httpredir/ftp.us/' /etc/apt/sources.list; \
  apt-get clean; \
  apt-get update; \
  /setup-deployment.sh; \
  rm /setup-deployment.sh;

