import { Users } from "lucide-react";
import stratoImage from "@/assets/landing/strato.png";
import { EXTERNAL_LINKS } from "@/config/externalLinks";
import type { ProductLandingConfig } from "./types";

export const staking: ProductLandingConfig = {
  slug: "staking",
  documentTitle: "STRATO Staking | Put Your STRATO To Work | STRATO",
  accent: "blue",
  appPath: "/dashboard/earn-staking",

  hero: {
    images: [stratoImage],
    eyebrow: "STRATO Staking",
    headline: "Put your STRATO to work.",
    subhead:
      "Stake with a validator and earn rewards paid in STRATO. A simple way to keep your tokens productive.",
  },

  stats: [
    { value: "3.88%", label: "Current staking APY" },
    { value: "STRATO", label: "Rewards paid in STRATO" },
    { value: "7 days", label: "Unbonding period" },
  ],

  steps: [
    {
      index: "01",
      tag: "Start here",
      title: "Connect wallet",
      body: "Connect the wallet holding your STRATO.",
      cta: "Connect Wallet",
    },
    {
      index: "02",
      tag: "Final",
      title: "Choose a validator & stake",
      body: "Compare validators, choose where to delegate, then confirm your amount and start earning rewards.",
      cta: "Stake STRATO",
    },
  ],

  highlight: {
    eyebrow: "Keep your tokens productive",
    title: "Stake STRATO. Earn STRATO.",
    body: "Delegate to a validator and your position earns staking rewards in the same asset you already hold.",
    flow: {
      fromLabel: "Current staking APY",
      from: "3.88%",
      toLabel: "Reward asset",
      to: "STRATO",
    },
    chips: ["Pick Your Validator", "Rewards Paid In STRATO", "Claim From The App"],
  },

  assurances: {
    items: [
      "Delegate without giving up custody",
      "Rewards paid in STRATO",
      "Track and claim from the app",
    ],
    disclaimer:
      "The APY and validator commission shown reflect the network at the time of publishing. Staking rates and validator performance can change. Validator commission reduces the rewards you receive.",
  },

  bands: [
    {
      tone: "navy",
      eyebrow: "Ahead of the TGE",
      title: "Make your STRATO a productive position.",
      body: "Staking gives STRATO holders a direct way to earn more STRATO. Choose a validator, delegate your tokens and manage your rewards from the app.",
      link: { label: "Explore STRATO Tokenomics", href: EXTERNAL_LINKS.tokenomics },
      aside: {
        kind: "list",
        items: [
          {
            index: "01",
            title: "Earn STRATO",
            body: "Staking rewards are paid in STRATO after validator commission.",
          },
          {
            index: "02",
            title: "Stay in control",
            body: "Track your position and claim available rewards from the app.",
          },
          {
            index: "03",
            title: "Start ahead of TGE",
            body: "Get familiar with STRATO staking before its next phase.",
          },
        ],
      },
    },
    {
      tone: "light",
      eyebrow: "When you unstake",
      title: "Plan for the seven day wait.",
      body: "Unstaking starts an unbonding period. Your STRATO becomes withdrawable after the seven days are complete.",
      aside: {
        kind: "steps",
        items: [
          { index: "1", title: "Request unstake", body: "Choose the delegated amount." },
          { index: "2", title: "Wait seven days", body: "Unbonding period." },
          { index: "3", title: "Withdraw STRATO", body: "Returns to your wallet." },
        ],
      },
    },
  ],

  explainers: [
    {
      icon: Users,
      tag: "Validators",
      title: "Choose who you delegate to.",
      body: "Review validator performance, total stake and commission before choosing. Commission is deducted from the rewards generated by your stake.",
      link: { label: "Explore Validators", href: "/dashboard/earn-staking" },
    },
    {
      images: [stratoImage],
      tag: "Staking rewards",
      title: "Track and claim your rewards.",
      body: "Your staked amount, total rewards and claimable STRATO stay visible in one place. Every staking reward you receive is paid in STRATO.",
      link: { label: "View Staking", href: "/dashboard/earn-staking" },
    },
  ],

  ctaBanner: {
    eyebrow: "STRATO Staking",
    title: "Put your STRATO to work.",
    body: "Choose a validator and start earning rewards in STRATO.",
  },
};
