name:
  blockapps-ecrecover
version:
  0.4
synopsis:
  An implementation of the EC Recover algorithm
copyright:
  2016, Blockapps
build-type:
  Simple
extra-source-files:
  - c-source/secp256k1/*.h
  - c-source/secp256k1/include/*.h

license: Apache-2.0

github: blockapps/strato-platform/core-strato/ecrecover

ghc-options: -O2 -threaded "-with-rtsopts=-N"
ghc-prof-options: -O2 -threaded -fprof-auto "-with-rtsopts=-N -p -s -h -i0.1"

default-extensions:
  - Arrows
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - LiberalTypeSynonyms
  - MagicHash
  - MultiParamTypeClasses
  - MultiWayIf
  - NoMonomorphismRestriction
  - OverloadedStrings
  - PatternGuards
  - ParallelListComp
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - TypeOperators
  - UnboxedTuples

dependencies:
  - text
  - bytestring
  - base-prelude
  - base

library:
  source-dirs:
    src/
  c-sources:
    c-source/recover.cc
  include-dirs:
    c-source/secp256k1
    c-source/secp256k1/include
  extra-libraries:
    gmp

tests:
  blockapps-ecrecover:
    source-dirs: tests/
    main: Main.hs
    dependencies:
      - blockapps-ecrecover
      # testing:
      - tasty
      - tasty-quickcheck
      - tasty-hunit
      - QuickCheck
      # parallelism and concurrency:
      - parallel
      # basics:
      - base
      - bytestring

benchmarks:
  sequential-benchmark:
    source-dirs: sequential-benchmark/
    main: Main.hs
    dependencies:
      - blockapps-ecrecover
      - criterion

  parallel-benchmark:
    source-dirs: parallel-benchmark
    main: Main.hs
    dependencies:
      - blockapps-ecrecover
      - criterion
      - parallel == 3.*
