name:                fastMP
version:             0.1.0.0

dependencies:
- base
- base16-bytestring
- bytestring
- ethereum-rlp
- format
- leveldb-haskell
- merkle-patricia-db
- nibblestring
- resourcet




library:
  source-dirs:         src
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  dependencies:
    - ansi-wl-pprint
    - blockapps-util
    - common-log
    - conduit
    - containers
    - data-default
    - monad-alter
    - monad-loops
    - strato-model
    - text
    - transformers


executables:
  fastMP-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:	 fastMP
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  insertMP:
    main:                insertMP.hs
    source-dirs:         app
    dependencies:
      - conduit
      - fastMP
      - monad-alter
      - transformers
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  insertLDB:
    main:                insertLDB.hs
    source-dirs:         app
    dependencies:
      - conduit
      - fastMP
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  makeSampleKVs:
    main:                makeSampleKVs.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - strato-model