name: vm-runner
version: 0.0.4
build-type: Simple
author: Jamshid
maintainer:    jamshidnh@gmail.com
synopsis: The executable that runs VMs for transactions
category:      Data Structures

dependencies:
  - base
  - blockstanbul # This dependency doesn't appear to be used at all, except for one symbol that doesn't exist.
                 # To avoid breaking builds, please leave this here: https://blockapps.atlassian.net/browse/OPS-65
  - x509-certs

library:
  source-dirs: src/
  exposed-modules:
    - Blockchain.BlockChain
    - Blockchain.Event
    - Executable.EthereumVM
  ghc-options: -Wall -O2
  dependencies:
  - ansi-wl-pprint
  - base16-bytestring
  - binary
  - blockapps-data
  - blockapps-datadefs
  - blockapps-mpdbs
  - bytestring
  - common-log
  - conduit
  - containers
  - cross-monitoring
  - debugger
  - dlist
  - ethereum-rlp
  - ethereum-vm
  - extra
  - format
  - lens
  - merkle-patricia-db
  - milena
  - milena-tools
  - monad-alter
  - mtl
  - prometheus-client
  - seqevents
  - solid-vm
  - strato-adit
  - strato-conf
  - strato-genesis
  - strato-index
  - strato-model
  - strato-statediff
  - text
  - time
  - transformers
  - unliftio
  - util
  - vm-tools
  - x509-certs

executables:
  vm-runner:
    source-dirs: exec_src
    main: Main.hs
    dependencies:
      - async
      - blockapps-init
      - common-log
      - containers
      - debugger
      - hflags
      - milena-tools
      - solid-vm
      - solid-vm-fuzzer
      - strato-conf
      - text
      - transformers
      - unliftio
      - vm-runner
      - vm-tools
      - wai-middleware-prometheus
      - warp
    ghc-options: -Wall -O2 -threaded -rtsopts -fprof-auto

tests:
  ethereum-vm-test:
    source-dirs: test/
    main: Spec.hs
    dependencies:
      - base16-bytestring
      - blockapps-data
      - blockapps-mpdbs
      - bytestring
      - common-log
      - containers
      - ethereum-vm
      - hflags
      - hspec
      - hspec-expectations-lifted
      - labeled-error
      - merkle-patricia-db
      - monad-alter
      - strato-conf
      - strato-model
      - vm-runner
      - vm-tools
    ghc-options: -Wall -Werror -threaded -rtsopts -with-rtsopts=-N

benchmarks:
  microbench:
    source-dirs: bench/
    main: Microbench.hs
    other-modules: []
    dependencies:
      - bytestring
      - containers
      - criterion
      - deepseq
      - ethereum-vm
      - strato-model
      - vector

  extractbench:
    source-dirs: bench/
    main: ExtractBench.hs
    other-modules: []
    dependencies:
      - bytestring
      - criterion
      - ethereum-vm
