name: blockapps-privacy
ghc-options: -Wall -Werror

dependencies:
  - base

library:
  source-dirs: src/
  dependencies:
    - aeson
    - binary
    - blockapps-data
    - blockapps-util
    - containers
    - data-default
    - ethereum-rlp
    - format
    - lens
    - monad-alter
    - prometheus-client
    - seqevents
    - strato-model
    - text

tests:
  privacy-test:
    main: Main.hs
    source-dirs: test/
    dependencies:
      - hspec
