// ROOMS
const LAST_BLOCK_NUMBER = 'LAST_BLOCK_NUMBER';
const USERS_COUNT = 'USERS_COUNT';
const GET_PEERS = 'GET_PEERS';
const CONTRACTS_COUNT = 'CONTRACTS_COUNT';
const TRANSACTIONS_TYPE = 'TRANSACTIONS_TYPE';
const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
const BLOCKS_DIFFICULTY = 'BLOCKS_DIFFICULTY';
const BLOCKS_PROPAGATION = 'BLOCKS_PROPAGATION';
const TRANSACTIONS_COUNT = 'TRANSACTIONS_COUNT';
const GET_COINBASE = 'GET_COINBASE';
const GET_HEALTH = 'GET_HEALTH';
const GET_NODE_UPTIME = 'GET_NODE_UPTIME';
const GET_SYSTEM_INFO = 'GET_SYSTEM_INFO';
const GET_SHARD_COUNT = 'GET_SHARD_COUNT';
const GET_NETWORK_HEALTH ='GET_NETWORK_HEALTH'

module.exports = {
  LAST_BLOCK_NUMBER,
  USERS_COUNT,
  GET_PEERS,
  CONTRACTS_COUNT,
  TRANSACTIONS_TYPE,
  GET_TRANSACTIONS,
  BLOCKS_DIFFICULTY,
  BLOCKS_PROPAGATION,
  TRANSACTIONS_COUNT,
  GET_COINBASE,
  GET_HEALTH,
  GET_NODE_UPTIME,
  GET_SYSTEM_INFO,
  GET_SHARD_COUNT,
  GET_NETWORK_HEALTH
}
