name: blockapps-cirrus-client
version: 0.1.0.0
synopsis: Cirrus microservice
description: Cirrus microservice
github: blockapps/strato-platform/blockapps-haskell/blockapps-cirrus
license-file: LICENSE
author: Eitan Chatav
maintainer: eitan@blockapps.net
copyright: 2016 BlockApps
category: Web
build-type: Simple

ghc-options: -Wall

dependencies:
  - base
  - blockapps-cirrus-api
  - blockapps-solidity
  - aeson
  - containers
  - http-client
  - servant
  - servant-client
  - text

library:
  source-dirs: src/
