name: blockapps-strato-api
version: 0.1.0.0
synopsis: Strato microservice
description: Strato microservice API definitions
github: blockapps/strato-platform/blockapps-haskell/strato/api
license-file: LICENSE
author: Eitan Chatav
maintainer: eitan@blockapps.net
copyright: 2016 BlockApps
category: Web
build-type: Simple

ghc-options: -Wall -Werror

dependencies:
  - base
  - blockapps-ethereum
  - blockapps-solidity
  - binary
  - bytestring
  - aeson
  - aeson-casing
  - containers
  - derive
  - generic-random
  - http-api-data
  - http-client
  - lens
  - QuickCheck
  - quickcheck-instances
  - servant
  - servant-client
  - servant-docs
  - strato-model
  - swagger2
  - text
  - time
  - unordered-containers

library:
  source-dirs: src/

tests:
  blockapps-strato-api-test:
    main: Spec.hs
    source-dirs: test/
    dependencies:
      - aeson-qq
      - blockapps-strato-api
      - hspec
