name: blockapps-strato-api
version: 0.1.0.0
synopsis: Strato microservice
description: Strato microservice API definitions
author: Eitan Chatav
maintainer: eitan@blockapps.net
copyright: 2016 BlockApps
category: Web
build-type: Simple

ghc-options: -Wall -Werror

dependencies:
  - base
  - aeson
  - generic-random
  - QuickCheck
  - quickcheck-instances
  - strato-model

library:
  source-dirs: src/
  dependencies:
  - swagger2

