// ROOMS 
const LAST_BLOCK_NUMBER = 'LAST_BLOCK_NUMBER'
const TRANSACTIONS_COUNT = 'TRANSACTIONS_COUNT'
const USERS_COUNT = 'USERS_COUNT'
const PEERS = 'PEERS'
const CONTRACTS_COUNT = 'CONTRACTS_COUNT'

module.exports = {
  LAST_BLOCK_NUMBER,
  TRANSACTIONS_COUNT,
  USERS_COUNT,
  PEERS,
  CONTRACTS_COUNT
}
