name:                blockapps-highway-wrapper-server
version:             0.1.0.0
github:              "githubuser/blockapps-highway-wrapper-server"
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/server#readme>

dependencies:
- base
- blockapps-highway-wrapper-api
- bytestring
- common-log
- unliftio-core

library:
  source-dirs: src
  dependencies:
    - aws
    - bytestring
    - conduit
    - http-client
    - http-conduit
    - monad-logger
    - mtl
    - resourcet
    - servant
    - servant-multipart
    - strato-model
    - transformers
    - unliftio
    - servant-server
    - text

executables:
  blockapps-highway-wrapper-server:
    source-dirs: app
    main: Main.hs
    other-modules: [Options]
    dependencies:
      - blockapps-highway-wrapper-server
      - blockapps-init
      - hflags
      - http-client
      - raw-strings-qq
      - servant-multipart-client
      - servant-server
      - text
      - wai-cors
      - wai-middleware-prometheus
      - warp
    ghc-options: -threaded 

tests:
  highway-wrapper-spec:
    source-dirs: test/
    main: Spec.hs
    dependencies:
      - blockapps-data
      - bytestring
      - clockwork
      - cryptonite
      - hspec
      - labeled-error
      - secp256k1-haskell
      - strato-model
