#!/bin/bash
set -e

KAFKA=kafka_2.11-0.9.0.1

WORKDIR=/tmp/kafkaworkdir
PKGDIR=$WORKDIR/kafka

mkdir -p $PKGDIR

if [ ! -e $WORKDIR/kafka.tgz ]
then
    wget "http://mirror.cc.columbia.edu/pub/software/apache/kafka/0.9.0.1/$KAFKA.tgz" -O $WORKDIR/kafkadl
    mv $WORKDIR/kafkadl $WORKDIR/kafka.tgz
fi

exec 2> >(while read line; do echo -e "\e[01;31m$line\e[0m" >&2; done)

cd $WORKDIR
tar xf kafka.tgz
cd -


mkdir -p $PKGDIR/DEBIAN/

cp support/control $PKGDIR/DEBIAN/
cp support/postinst $PKGDIR/DEBIAN/
cp support/prerm $PKGDIR/DEBIAN/

mkdir -p $PKGDIR/usr/lib/kafka
cp -a $WORKDIR/$KAFKA/libs $PKGDIR/usr/lib/kafka/
mkdir -p $PKGDIR/usr/lib/kafka/bin
cp $WORKDIR/$KAFKA/bin/kafka-* $PKGDIR/usr/lib/kafka/bin/
mkdir -p $PKGDIR/usr/lib/kafka/config
cp $WORKDIR/$KAFKA/config/* $PKGDIR/usr/lib/kafka/config/
mkdir -p $PKGDIR/usr/bin
cp support/kafka-topics $PKGDIR/usr/bin/

mkdir -p $PKGDIR/etc/init.d/
cp support/startstop $PKGDIR/etc/init.d/kafka

mkdir -p $PKGDIR/etc/kafka/
cp $WORKDIR/$KAFKA/config/server.properties $PKGDIR/etc/kafka/

sed -i 's@/tmp/kafka-logs@/var/lib/kafka@' $PKGDIR/etc/kafka/server.properties

mkdir -p $PKGDIR/var/lib/kafka
mkdir -p $PKGDIR/var/log/kafka/

dpkg-deb --build $PKGDIR

mv $WORKDIR/kafka.deb .
