# Strato Prometheus Configuration
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Processes to scrape
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/prometheus/metrics'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'strato-sequencer'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['strato:8050']
  # Encompasses strato-p2p-server and strato-p2p-client
  - job_name: 'strato-p2p'
    static_configs:
      - targets: ['strato:10248', 'strato:10249']
  - job_name: 'ethereum-vm'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['strato:8000']

#   metric_relabel_configs:
#   - source_labels: [__name__]
#     regex: '(prometheus)_(.*)'
#     replacement: '${2}'
#     target_label: pool
#
#  - source_labels: [__name__]
#   regex: '(go|time_)'
#   action: drop
