name:                blockapps-vault-wrapper-api
version:             0.1.0.0
github:              "githubuser/API"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/API#readme>

dependencies:
  - base >= 4.7 && < 5
  - base16-bytestring
  - binary
  - blockapps-ethereum
  - bytestring
  - cryptonite
  - http-media
  - lens
  - memory
  - saltine
  - secp256k1-haskell
  - servant
  - servant-server
  - swagger2
  - text
  - wai
  - wai-extra
  - wai-middleware-static
  - warp
  - aeson
  - aeson-casing

library:
  source-dirs: src

tests:
  API-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blockapps-vault-wrapper-api
