name: blockapps-vault-wrapper-api
version: 0.1.0.0
synopsis: Vault Wrapper microservice
description: Vault Wrapper microservice API definitions
github: blockapps/blockapps-haskell/vault-wrapper/api
license-file: LICENSE
author: Dustin Norwood
maintainer: dustin@blockapps.net
copyright: 2018 BlockApps
category: Web
build-type: Simple

dependencies:
  - aeson
  - base
  - blockapps-ethereum
  - largeword
  - QuickCheck
  - servant
  - servant-docs
  - text

ghc-options: -Wall -Werror

library:
  source-dirs: src/
