export const SEO = {
  TITLE_META: `STRATO Mercata Marketplace`,
  DESCRIPTION_META: `Join the STRATO Mercata marketplace for buying, selling, and investing in  
    fractionalized assets. Expand your collection or find buyers for your rare carbon,  
    metals, art, collectibles, and clothing.`,
  IMAGE_META: `STRATO Mercata Marketplace Banner`,
  SEO_ROUTES:[
    { url: "/certifier", changefreq: "weekly", priority: 0.5 },
     { url: "/", changefreq: "weekly", priority: 0.5 },
     { url: "/category", changefreq: "weekly", priority: 0.5 },
     { url: "/marketplace", changefreq: "weekly", priority: 0.5 },
     { url: "/profile/:commonName", changefreq: "weekly", priority: 0.5 },
     { url: "/dp/:address/:name", changefreq: "weekly", priority: 0.5 },
     { url: "/login", changefreq: "weekly", priority: 0.5 },
     { url: "/checkout", changefreq: "weekly", priority: 0.5 },
     { url: "/confirmOrder", changefreq: "weekly", priority: 0.5 },
     { url: "/products", changefreq: "weekly", priority: 0.5 },
     { url: "/products/:id", changefreq: "weekly", priority: 0.5 },
     { url: "/mystore", changefreq: "weekly", priority: 0.5 },
     { url: "/inventories/:id/:name", changefreq: "weekly", priority: 0.5 },
     { url: "/inventories/events/serialNumbers", changefreq: "weekly", priority: 0.5 },
     { url: "/items", changefreq: "weekly", priority: 0.5 },
     { url: "/order/:type", changefreq: "weekly", priority: 0.5 },
     { url: "/sold-orders/:id", changefreq: "weekly", priority: 0.5 },
     { url: "/bought-orders/:id", changefreq: "weekly", priority: 0.5 },
     { url: "/order/transfers", changefreq: "weekly", priority: 0.5 },
     { url: "/sold-orders-details/:id", changefreq: "weekly", priority: 0.5 },
     { url: "/bought-orders-details/:id", changefreq: "weekly", priority: 0.5 },
     { url: "/orders/events/:itemId", changefreq: "weekly", priority: 0.5 },
     { url: "/events", changefreq: "weekly", priority: 0.5 },
     { url: "/events/:id", changefreq: "weekly", priority: 0.5 },
     { url: "/inventories/events/:id", changefreq: "weekly", priority: 0.5 },
     { url: "/inventories/events/:inventoryId/:eventTypeId", changefreq: "weekly", priority: 0.5 },
     { url: "/admin", changefreq: "weekly", priority: 0.5 },
     { url: "/events/serialNumbers", changefreq: "weekly", priority: 0.5 },
     { url: "/order/status", changefreq: "weekly", priority: 0.5 },
     { url: "/orders/invoice/:id", changefreq: "weekly", priority: 0.5 },
     { url: "/inventories/stripe/onboarding", changefreq: "weekly", priority: 0.5 }
  ]
}