name: slipstream
version: 0.1.0.0
synopsis: Solidity datatypes
description: Solidity datatypes
homepage: https://github.com/blockapps/blockapps-haskell/slipstream
copyright: 2016 BlockApps
category: Web
license: Apache-2.0


ghc-options: -Wall -Werror -rtsopts

dependencies:
  - base
  - common-log

library:
  source-dirs: src/
  dependencies: 
    - aeson
    - bytestring
    - containers
    - evm-solidity
    - base16-bytestring
    - binary
    - bloc2
    - blockapps-data
    - blockapps-datadefs
    - blockDB
    - conduit
    - containers
    - deepseq
    - esqueleto
    - format
    - lens
    - streaming
    - network
    - persistent
    - persistent-postgresql
    - postgresql-simple
    - prometheus-client
    - resource-pool
    - solid-vm-model
    - scientific
    - source-tools
    - sql-monad
    - strato-conf
    - strato-model
    - strato-redis-blockdb
    - text
    - time
    - transformers
    - unliftio
    - vm-tools
    - ordered-containers

executables:
  slipstream:
    source-dirs: exec_src/
    main: Main.hs
    dependencies:
      - base
      - blockapps-init
      - hflags
      - streaming
      - persistent-postgresql
      - process-monitor
      - resourcet
      - slipstream
      - sql-monad
      - strato-conf
      - text
      - transformers
      - unliftio
      - wai-middleware-prometheus
      - warp

tests:
  slipstream-batching-test:
    main: Main.hs
    source-dirs: tests-batching/
    dependencies:
      - base
      - bytestring
      - conduit
      - containers
      - evm-solidity
      - hspec
      - slipstream
      - text

  slipstream-test:
    main: Main.hs
    source-dirs: tests/
    ghc-options: -dynamic
    dependencies:
      - base
      - aeson
      - aeson-qq
      - bytestring
      - classy-prelude
      - conduit
      - containers
      - data-default
      - hflags
      - hspec
      - hspec-expectations-lifted
      - labeled-error
      - persistent-sqlite
      - QuickCheck
      - slipstream
      - solid-vm-model
      - strato-model
      - text
      - time
      - unliftio
      - vm-tools
      - ordered-containers
      - monad-alter
      - core-api2
      - blockapps-haskoin
      - blockapps-mpdbs
      - data-default
      - blockapps-data
