name: seqevents

dependencies:
  - base
  - binary
  - blockapps-data
  - blockapps-datadefs
  - blockapps-util
  - blockapps-milena
  - blockstanbul
  - bytestring
  - conduit
  - deepseq
  - derive
  - ethereum-rlp
  - format
  - monad-alter
  - prometheus-client
  - strato-conf
  - strato-model
  - QuickCheck
  - text
  - util

library:
  source-dirs: src/

tests:
  seqevents-spec:
    source-dirs: test/
    main: EventSpec.hs
    dependencies:
      - hspec
      - seqevents
