name: seqevents

dependencies:
  - base
  - binary
  - blockapps-data
  - blockapps-datadefs
  - QuickCheck

library:
  source-dirs: src/
  dependencies:
    - aeson
    - blockapps-milena
    - blockapps-util
    - blockstanbul
    - bytestring
    - conduit
    - deepseq
    - derive
    - ethereum-rlp
    - format
    - lens
    - monad-alter
    - prometheus-client
    - strato-conf
    - strato-model
    - text

tests:
  seqevents-spec:
    source-dirs: test/
    main: EventSpec.hs
    dependencies:
      - hspec
      - seqevents
