# base image
FROM node:8.15-stretch-slim
# set working directory
WORKDIR /app
# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH
# install and cache app dependencies
COPY . .
RUN yarn add react-scripts -g
RUN yarn install

EXPOSE 3000

# start app
CMD ["yarn", "start"]