FROM node:18-buster-slim
RUN apt-get update && \
    apt-get install -y git postgresql-client python build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    mkdir -p /usr/src/app \
    # Layer is shared with Apex. TODO: use shared base
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app
RUN npm install
RUN npm test
