// GENERATED by rollup/plonkgen (go run . import /private/tmp/claude-501/-Users-dustinnorwood-BlockApps-pbbo/539a2388-743e-4b34-a61d-3e63d2a059a9/scratchpad/brproof BlockRootsProofFixture) -- do not edit by hand.
//
// A real gnark PLONK/BN254 proof imported from another prover, plus its
// verifying key and public inputs, as word accessors: vkWord(i) is
// PlonkVerifier.initialize's layout (29 words + 3 per Bsb22 commitment),
// proofWord(i) is MarshalSolidity's 32-byte chunks (24 + 3 per commitment).
// The reference verifier accepted this proof when the file was generated.

library BlockRootsProofFixture {
    uint256 constant VK_WORDS = 32;
    uint256 constant PROOF_WORDS = 27;
    uint256 constant NB_PUBLIC_INPUTS = 17;
    uint256 constant NB_COMMITMENTS = 1;

    function vkWord(uint256 i) internal returns (uint256) {
        if (i == 0) { return 0x400000; }
        if (i == 1) { return 0x1ad92f46b1f8d9a7cda0ceb68be08215ec1a1f05359eebbba76dde56a219447e; }
        if (i == 2) { return 0x30644db14ff7d4a4f1cf9ed5406a7e5722d273a7aa184eaa5e1fb0846829b041; }
        if (i == 3) { return 0x5; }
        if (i == 4) { return 0x11; }
        if (i == 5) { return 0x149ee7d2f33466974399a7ddbfedb3fc15d574d80ed55e885b4efe07a3062a75; }
        if (i == 6) { return 0x17dafe8b67920ae1366af659c4f18f8a1e60b0f4c559f38b75b5af38ad87af64; }
        if (i == 7) { return 0x22ec512272e722f6e8a67361fbacaaefbe4584ce8fceb293e03615cf2e7c41a8; }
        if (i == 8) { return 0xda5018e18f891466fe5601257cd5a99fa2dd386378fa4fa76ad851ddfa61ed3; }
        if (i == 9) { return 0x1484dc72754b8530007982ff59ca1801ff57ee0fa37425620b7616323310ca68; }
        if (i == 10) { return 0x194de391ae03c323e30a709db9a7e7f442991e769f6516648b843676427ea279; }
        if (i == 11) { return 0x21cab36c7bcab726dcca9225e5fc9ad8b713cb7bc5b8040fc7d29a001b9f07ca; }
        if (i == 12) { return 0x10a68a4535b71b14f102496fecf9729a8d09874c6c04e5c8fc4c7c1b2240bee0; }
        if (i == 13) { return 0xa3c6527dfdf0fe0a6e34c0e2d75cc32bcb03ade572073211b33d6a32613dc98; }
        if (i == 14) { return 0x1a044918182b63bf719a03c809bd098abd61fa3b63f910223c4057b5b0e008fc; }
        if (i == 15) { return 0x96d4cb02ce13df840e4651d4a7597dbd0a8cdd40d3ada6ff66e4853a033e634; }
        if (i == 16) { return 0x20cba1bfbcd7c37508e1ef98e61d6f7e9406592443a9a6d2a1064f866e153afb; }
        if (i == 17) { return 0x1de0a92322b0fcb09e5a20c98a13b3ec8fe635be2b4bc113136816173fcc9db6; }
        if (i == 18) { return 0x1c880ac93171ebe8841b5a705b169bfe9af48ac228a8eb1435c67945627132b7; }
        if (i == 19) { return 0x30564da27916b9f9f2f23644bf71c6570d3dba8ad97105029a2b998482eaf239; }
        if (i == 20) { return 0x13b48fa3c196ab5c7e69a9ed24870142c45b9cbccb75e7000b88d103fbb28fd4; }
        if (i == 21) { return 0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2; }
        if (i == 22) { return 0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed; }
        if (i == 23) { return 0x90689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b; }
        if (i == 24) { return 0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa; }
        if (i == 25) { return 0x272793233afaf9c6e568c742d6068fd103b6b95b1b757bfe35e01abceddd2f66; }
        if (i == 26) { return 0x24754f5cf8e357103d45d02cbd51513fc5d6739b00bb76f4c3a397a8a6596a0d; }
        if (i == 27) { return 0x1f68b4d39eba11bdf5fe5663b2b259a88d330440518beca40f255e0887ec743; }
        if (i == 28) { return 0x2886df0ce9106bdcf2a36a98030a2f6d74b60e2e01f42123e4f937fb20a77926; }
        if (i == 29) { return 0x2c7f44c23210fa63534791cdab1f2b1f48a5c21d33f2c3274d3268c17af63a4b; }
        if (i == 30) { return 0x2ab079405928fdbfee13f8849f648a5a3108a8c8d244f0643eed303cc12a7cf3; }
        if (i == 31) { return 0x15294b; }
        require(false, "vkWord: no such index");
        return 0;
    }

    function proofWord(uint256 i) internal returns (uint256) {
        if (i == 0) { return 0x440e904436cdb40e2bd0acc5add9e58e2454a0c455846c11b1b4aab652eab72; }
        if (i == 1) { return 0x6a6dad4903801ce08d278bb0335c0a9c7072ce446e685280ef9f43c2cc2b1b; }
        if (i == 2) { return 0x3050803706ec9498bc146218faa44c51fdfc5995e7243dc6474b8e6b414bc83d; }
        if (i == 3) { return 0x16460afa4e1fea1bc5ec05cf908234a5851f7e580026c8e006138ae8d3fce85; }
        if (i == 4) { return 0x2b12d9a32d1bad6eb294452b82c55c34d76d23308557013fcac8b8531e102aeb; }
        if (i == 5) { return 0x2a61b51168ec0a9c35b78880e3ec080a4c134205c2d21fff9af2d7b015bd1fd4; }
        if (i == 6) { return 0x7366fcef95225366d9f7c17ffb4bd154c628f756e4b9346ccbd55df6f67a297; }
        if (i == 7) { return 0xf7c4d573df3068b5d29d38c037879ecd7de93debb41fc2b1121d3df5ece2388; }
        if (i == 8) { return 0x2c2d70e6ddc413a1037dbf7c6806ad91f6ca782197ea34b1e82dc9094546f9f8; }
        if (i == 9) { return 0x1120a1e3763b2d4f9773856257254c5d17032533704202f8a99ee0073c4fb4ed; }
        if (i == 10) { return 0xf02c5c068d56e2a4a012ed022e6632a051146239c37af6226e94122ad3d7e14; }
        if (i == 11) { return 0x2b92c0dfcaf8667d9aed9f91d7c517dac283938fb0eba6644037f24f265903e; }
        if (i == 12) { return 0xc020ce1eca7402210b861c5083a3230cc09c723e08c58c57887c7f38bd7a010; }
        if (i == 13) { return 0x23e2b2bf037467d5e48c7ad7a216fb5cbc8e0ecbc1ede0c70b4ba522381164e5; }
        if (i == 14) { return 0x20a39eee52bfecf6a77642de24abb8459a8c8bb393f62e8bd57db60722a37c9c; }
        if (i == 15) { return 0x23ccc5c965e3b952b24c4fda6bdbe7fc26b380792e3fa62bcd024523a3ec09dc; }
        if (i == 16) { return 0x1fd8e93ec8039cb9411317827cee043f87f6200abd954f0e8ee7d80d6e59a6fb; }
        if (i == 17) { return 0x1754db035ad43e9c55640577cb784fe488e0e63eacd22b214d6cb5f31738173; }
        if (i == 18) { return 0x123bd9e0881631edec527407d429d7a770071592089f85730efd250c2ab1ba30; }
        if (i == 19) { return 0x28e8ed7d683611bc6a73a81178e7de42eaee7ebf768c52777e320b0ee5aa7e6f; }
        if (i == 20) { return 0xa0be4dcae9d868625f3f76d72f95369ecf030eabb8925af208364992c7add66; }
        if (i == 21) { return 0x229764f2d9360416f61297b902ed885f3e40f7676bb1f403229878a1edd630a7; }
        if (i == 22) { return 0x2b793a37c3ad038dc67efad4902575dcf88c1af5233ff50557347cdd7d389e92; }
        if (i == 23) { return 0x1893d44659228cdc90e654f613e18c22cc301464007c8189f1b76982f67eeca6; }
        if (i == 24) { return 0x1ca475c9865f3dd5c3bbfdec2a42de400ba380d693c3a1997fc215e76c35e8b; }
        if (i == 25) { return 0x2c0f168e9cbd33a0c20d0bee2e13cbddcf59ba2dac0b358a793bc67c1da8cc6e; }
        if (i == 26) { return 0x22034bb47325c6e9007c96d0ccb58a76f7eabfa38a970f3d827f3fad3e5cd78d; }
        require(false, "proofWord: no such index");
        return 0;
    }

    function publicInput(uint256 i) internal returns (uint256) {
        if (i == 0) { return 0xffffffffffffffffffffffffffffffff; }
        if (i == 1) { return 0xffffffffffffffffffffffffffffffff; }
        if (i == 2) { return 0xffffffffffffffffffffffffffffffff; }
        if (i == 3) { return 0x3fffffffffffffffffffff; }
        if (i == 4) { return 0x2434338d675befcb; }
        if (i == 5) { return 0xae924010ceed7d18; }
        if (i == 6) { return 0x984cdccd807ba1a9; }
        if (i == 7) { return 0xdf5e149d5309d280; }
        if (i == 8) { return 0xc8124c8d3513c78c; }
        if (i == 9) { return 0xf8b005b3f52b702; }
        if (i == 10) { return 0xb7034b5618ec3575; }
        if (i == 11) { return 0xe1cbc2d4cbee681f; }
        if (i == 12) { return 0x43e091fd1f8f497b; }
        if (i == 13) { return 0xfc377d0ba1d29da6; }
        if (i == 14) { return 0x391a9b7762344b76; }
        if (i == 15) { return 0x27aa49d7a3db09d; }
        if (i == 16) { return 0x92ae0caf9288970aaad9df4e9a5dac059e109c5937e6f05a1af0c1a93e83e72; }
        require(false, "publicInput: no such index");
        return 0;
    }

    // --- expected intermediates (reference verifier) ---
    uint256 constant EXP_GAMMA = 0x1d46c94e8071b5245952072248ed7448675f66e8f07512210060cd73ad7e24ae;
    uint256 constant EXP_BETA = 0x23d4e31099b96a967dc8fd659cc7d8e558ce20896aa3aed5e79ba2121e859ff3;
    uint256 constant EXP_ALPHA = 0x7cfd762102288cff3f126915d9969117ff5df8c663151189ff7f9c4e40ed92;
    uint256 constant EXP_ZETA = 0x1c3548033d186ff35f979e490319ee0d45ec8a6d3ffe8e1ae46aa26a1fb23a8;
    uint256 constant EXP_ZH = 0x2abb6e5be30c9662134e07f4bad68230b4a3877eceffea45212fa8caf1acd9ad;
    uint256 constant EXP_PI = 0x200c2db5b47097e943a9aa2d4b923db598d931e0d7ea95bdeee8b3add4487dcc;
    uint256 constant EXP_LIN_AT_ZETA = 0x269fb79a43b494221e5d067c851e58ae55194188f79f80ad7d45843467235156;
    uint256 constant EXP_LIN_X = 0x2c8d3824ed8e78f39639e6e202f904fc1afd5efd952c7b796b3ac7993e65afbf;
    uint256 constant EXP_LIN_Y = 0x29fb9f4eac121599fc0636e19ab11a359011d6226b875bc76b4dc5a9f69e37dd;
    uint256 constant EXP_GAMMA_KZG = 0x1d38faf3cecb9c3a8df0ec9ed2e06bbd14f6cd05328a769b9c0f87748db57e4;
    uint256 constant EXP_FOLDED_X = 0x2f3d7be6e1474e10a98a8bd8b1c816e0231b8b2f9b187d470773129d8ab8e98a;
    uint256 constant EXP_FOLDED_Y = 0x2180118deacf1927120c56ca7e845e7c9568fbede7f32d4d4668c88110d9aa95;
    uint256 constant EXP_FOLDED_VALUE = 0x132f414aeec92ea2c4a3b3c61643d4b37a80f68b9df3acce23c5ee962abeddcf;
    uint256 constant EXP_RHO = 0x1f2d95351ff57c84a5b1173e0ce8a5d7821f7565a20648e9bf519e7f49e74409;
}
