// GENERATED by rollup/plonkgen (go run . import /private/tmp/claude-501/-Users-dustinnorwood-BlockApps-pbbo/539a2388-743e-4b34-a61d-3e63d2a059a9/scratchpad/sepolia SepoliaAggregateFixture) -- do not edit by hand.
//
// A real gnark PLONK/BN254 proof imported from another prover, plus its
// verifying key and public inputs, as word accessors: vkWord(i) is
// PlonkVerifier.initialize's layout (29 words + 3 per Bsb22 commitment),
// proofWord(i) is MarshalSolidity's 32-byte chunks (24 + 3 per commitment).
// The reference verifier accepted this proof when the file was generated.

library SepoliaAggregateFixture {
    uint256 constant VK_WORDS = 32;
    uint256 constant PROOF_WORDS = 27;
    uint256 constant NB_PUBLIC_INPUTS = 17;
    uint256 constant NB_COMMITMENTS = 1;

    function vkWord(uint256 i) internal returns (uint256) {
        if (i == 0) { return 0x400000; }
        if (i == 1) { return 0x1ad92f46b1f8d9a7cda0ceb68be08215ec1a1f05359eebbba76dde56a219447e; }
        if (i == 2) { return 0x30644db14ff7d4a4f1cf9ed5406a7e5722d273a7aa184eaa5e1fb0846829b041; }
        if (i == 3) { return 0x5; }
        if (i == 4) { return 0x11; }
        if (i == 5) { return 0x2d93d6739bfbf8f3eb1001980fdba00b0525b74d17536377a0b84ade7c586e66; }
        if (i == 6) { return 0x24a3866e95e519ce5191abe3cbd406fb716d8a6b8ad9c42fce160160d991afd8; }
        if (i == 7) { return 0x1104fabad421a56f891848fbdbc3ac9ec843dea0f8f78190b3eeffc6dc6227d; }
        if (i == 8) { return 0x1ece02951844ec42999bc6eca944791f3a3c54afbbd013ce4483a413cdfca1cd; }
        if (i == 9) { return 0x2e4a04c8c1e33c0725de009869f15612841adb608575a0c1099916f93837f889; }
        if (i == 10) { return 0x79b68d0bf0cc5dff9e79461a2550c4075b1502aea6fdd1d81d49979612610ae; }
        if (i == 11) { return 0x2187fb4d3dffe9edbe49d6637d5a61a7156ee27e6885a181817a8056dc91cf5; }
        if (i == 12) { return 0x167af38bc16f40a0e87fca74f6a0adb00923cf75534f1bd098af5a4f4b94a7cb; }
        if (i == 13) { return 0x1e4fdbec2dd3b96c1d746abeca3afbf58866e5cdb2af9610387bfd493ec541ed; }
        if (i == 14) { return 0xfc4af57f69168065e9aaeeab6dd243cd34670da4905cd77e500a9ebf723c; }
        if (i == 15) { return 0x1b347f7321e96c0711365fca72fa3e49efde4f0327451d52d68f36321a4ecaf4; }
        if (i == 16) { return 0x11a597bb76334cb558dcba97fbdaaf77182753f2559e55209b55bf9a9bc8283; }
        if (i == 17) { return 0x1470716a3f07975ce20ea2f40691fdf4522eec515f202d7c4b655ac1630d281d; }
        if (i == 18) { return 0x15bc53c1d37f662560ae527b7f709d7399c4b34563d971dbe33731ef02f59715; }
        if (i == 19) { return 0x82c7a3d6a0f9b40b26638fc2db4befe7ec16982d02389245899931057ff6e18; }
        if (i == 20) { return 0x2b3bf41d9debb48d22b06ba23de9347d4dbe2d48814802288c785a2f18e61d53; }
        if (i == 21) { return 0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2; }
        if (i == 22) { return 0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed; }
        if (i == 23) { return 0x90689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b; }
        if (i == 24) { return 0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa; }
        if (i == 25) { return 0xc675974e94c6d4d1a8d5a3c0eef100c45a90257304f129e2fe62c023ef46c54; }
        if (i == 26) { return 0x2ec3cee56154788dd561795265559d8a9abab1c1e540eeea5802159801604640; }
        if (i == 27) { return 0xcc5f98ace3d7dc35e47fda8d39d573f825c774ea776b5417b0483d52d5618d2; }
        if (i == 28) { return 0xedc7b284a4484e8b85c6394bcc30f2b28750cf10cf10310e3047be33efc75b4; }
        if (i == 29) { return 0x12c9efaca1e0b05373d0299cf236cb3f8b42e6e7513c31876898c8e96c6e9a1e; }
        if (i == 30) { return 0x1af7528ea8d088cce0e4d825a6256338bb76bb0594796ada222d93e7af637d7b; }
        if (i == 31) { return 0x15294b; }
        require(false, "vkWord: no such index");
        return 0;
    }

    function proofWord(uint256 i) internal returns (uint256) {
        if (i == 0) { return 0x95ecb543b1c179918de1b93a0687b76273595c8fd1828f89f827e7743b36647; }
        if (i == 1) { return 0x2f614a86a416debd5cbd38decb059e9eeb3e816e8d445fb01966372910f4926e; }
        if (i == 2) { return 0x20ac7658e2f4d2a23219dc21ba7c0284d8a83cc0bf7b913131ff59de820ed2db; }
        if (i == 3) { return 0x2c79fdff4307b2d05bff2b3f607e7d7a32437a18af87d66a47929361fc238b79; }
        if (i == 4) { return 0x12164e1920815df6bc9d82a89c4e6008be51c9c3946b8de339a0c34ead751a2b; }
        if (i == 5) { return 0x2c0dd4611d76f5da7af256989f102795df748374da50848a98932891e7768fa8; }
        if (i == 6) { return 0x22d7609fed9991bccc7e7688efd5eaaf33cdb773012bd7a007db8eec67f5b660; }
        if (i == 7) { return 0xd5f0c0945749041cefc4709e002c3a364fff7f12230a0fa6b9777865c095d60; }
        if (i == 8) { return 0x10c3bc9af412c2686c672204c28cea8b478b3a889695083da3ce501a0060c680; }
        if (i == 9) { return 0x12c0bab1d6721294040610180955c015251341f6c7e38d767bf3abd2fac004af; }
        if (i == 10) { return 0x1110715be4b959077ca86e0696b016b9b50c9560fd89df76742dce4d14bb26ef; }
        if (i == 11) { return 0x12c684f1eefc3146c2f6547696de1c3f154584c971234e7896bd32ce15c616a1; }
        if (i == 12) { return 0xbe440a5b2d45c30bc98e0b93dcea0546ecbf74d7d334cf79d5534b1a1d7e1c6; }
        if (i == 13) { return 0x2b1d50053a019b7c09749fc11e8fc6a762d5a05491dddc2feb3824a0afe59c6f; }
        if (i == 14) { return 0xb191009a97d934194f6288423f5b914474855692ac053938c3c2a2ceac19426; }
        if (i == 15) { return 0x1105cc967d7956eb7c41b11eac3c98aade0c8fb8e1e7cd418fc9911212a6ba6; }
        if (i == 16) { return 0x2645b117211e5f32daf03d9cfa7c2351fdb54e712fc30d52d01b265b51ea6e33; }
        if (i == 17) { return 0xad891ed3e6016354b9b9ccb1ca028978185c1cf23952b767fe01f73fc1265a2; }
        if (i == 18) { return 0x2cd3e79789beb401dc3a533847b07b59a1408058351afc11c8dff451bc13b2e4; }
        if (i == 19) { return 0x1146590a04c62893b89592a299cac9469f48dbf0659c40b5b5c47b7037b4ae40; }
        if (i == 20) { return 0x3da5563f33c59242c41e74a902b519c57fff9f3bf456110bd7a1289825c3905; }
        if (i == 21) { return 0x866708e53e7b87f71cf1825c5e92d3183a16bf522d9301b143b9a9ecc6945f2; }
        if (i == 22) { return 0x2f115961c88fe7cd72ae4556e288194330e6f9fc651e917b1149ca85a31d270b; }
        if (i == 23) { return 0x1775ab50d38bd4fd71c57b2756d3dbca93047a5bcc9007f8add4321543275d46; }
        if (i == 24) { return 0x37292c534e4c6fe5b20cf22d87fc8f337b5699d5f7673989a3c5ea03fb33fbe; }
        if (i == 25) { return 0x27a6989cfd447f67b75dec8345118e46f0035b48863f27dbeb6ab06734b3ce0f; }
        if (i == 26) { return 0x10f31916c94cc2146773791891c4c380161f130def23852e5d604a0bc12406d3; }
        require(false, "proofWord: no such index");
        return 0;
    }

    function publicInput(uint256 i) internal returns (uint256) {
        if (i == 0) { return 0xbffbffdffffeffffffff7fffffffdffe; }
        if (i == 1) { return 0xeffeefffdfffdfbfbffffff7fbbfdf7f; }
        if (i == 2) { return 0xeb9fbffefffe7ffeffffffeffffffeff; }
        if (i == 3) { return 0xfffffffefafefbffff77efefffbbdfff; }
        if (i == 4) { return 0xb4d41df0cfae8b5e; }
        if (i == 5) { return 0x3e8c52865f647d1b; }
        if (i == 6) { return 0xf64b5324f0b69aa; }
        if (i == 7) { return 0xf9d53f3d0f76877d; }
        if (i == 8) { return 0x9f751fadf029ea18; }
        if (i == 9) { return 0x1335746c5e693cee; }
        if (i == 10) { return 0x80387d5231b96150; }
        if (i == 11) { return 0xe25c137be55b492b; }
        if (i == 12) { return 0x52ff38ab9e95caa7; }
        if (i == 13) { return 0x530a445c23b2e028; }
        if (i == 14) { return 0x70da2e94b248d3a4; }
        if (i == 15) { return 0xb4f7f93c90b8155; }
        if (i == 16) { return 0x1e8042c24f811689ee3b93217ebee2b7e570d579297ff9053f05ddc578db46ad; }
        require(false, "publicInput: no such index");
        return 0;
    }

    // --- expected intermediates (reference verifier) ---
    uint256 constant EXP_GAMMA = 0x2eb32693117e94744a476d59fcb8c1296c20628ef51de1c2684934befc759f71;
    uint256 constant EXP_BETA = 0x2819225bc30860ab92ee7505438741b2c5032c77d7ce754672f6cde57eddb7c9;
    uint256 constant EXP_ALPHA = 0x1188b14d4339072f218f09e25c80558c590524d950e1e7e4d4eac1cf6aa7eee9;
    uint256 constant EXP_ZETA = 0xa19fc7d673b999cdfc9f1d1674acc9c0cc8413f48df5a39a6817ff2e6615ff0;
    uint256 constant EXP_ZH = 0x1776a37fb214df809bf3688dc70be8bcc0707c62f3cc2f1ebd123bf95c3962fd;
    uint256 constant EXP_PI = 0x131d04d95719b790453206cbef0a70d61d8ffda29f405710ee77986838a6b81e;
    uint256 constant EXP_LIN_AT_ZETA = 0x457623932e0bc1ecd38540cd014536fab620f5482dedd0354c9111b318726c3;
    uint256 constant EXP_LIN_X = 0x1fa1c2449a41c2e8bb36a1b96a1cc64f4246e2ca6aa4d30f2be91f3ad6d131e4;
    uint256 constant EXP_LIN_Y = 0xc96a5a59d33cfce01c95e0a768016bfeccfc45dca73d53d198c8a2fb9239be5;
    uint256 constant EXP_GAMMA_KZG = 0xf34cdf9ed532e71a6f372986a3e97678f66e0b23cb63d962e3ba51a2fb5ef4a;
    uint256 constant EXP_FOLDED_X = 0x27430486d6525f42ef73134652624d8d9911e2294135548626349df1f799a68b;
    uint256 constant EXP_FOLDED_Y = 0x260ba3b46bdbb743fe313574513ce9c130b606461f1f7862615569e47bc65ba1;
    uint256 constant EXP_FOLDED_VALUE = 0x22943fb7a00851d1d3edfa1e3cc9f29851254ea78ff485f7a8d17e1be4569130;
    uint256 constant EXP_RHO = 0xc32770bd6e0488cde081817b8075aa489d63c90209dd57a9a44c08f410d34c2;
}
