name:                vrun
version:             0.1.0.0
github:              "githubuser/vrun"
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/vrun#readme>

dependencies:
- base
- ansi-wl-pprint
- blockapps-data
- blockapps-datadefs
- blockapps-init
- blockapps-mpdbs
- bytestring
- common-log
- containers
- data-default
- debugger
- deepseq
- directory
- ethereum-rlp
- exceptions
- extra
- hedis
- hflags
- lens
- leveldb-haskell
- merkle-patricia-db
- milena
- monad-alter
- mtl
- nibblestring
- persistent-sqlite
- prometheus-client
- resourcet
- strato-model
- strato-redis-blockdb
- strato-statediff
- seqevents
- strato-conf
- solid-vm-model
- text
- time
- transformers
- unliftio
- vm-runner
- vm-tools
- x509-certs

executables:
  vrun:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
