{-# LANGUAGE OverloadedStrings #-}
-- | Test suite for Poseidon hash
-- Test vectors from circomlibjs

module Main where

import Test.Hspec
import Crypto.Hash.Poseidon
import qualified Crypto.Hash.Poseidon2 as P2
import qualified Crypto.Hash.Poseidon2Goldilocks as G
import qualified Data.ByteString as B
import qualified Data.ByteString.Char8 as BC
import Numeric (readHex)

main :: IO ()
main = hspec $ do
  describe "Poseidon hash" $ do
    -- Test vectors from circomlibjs test suite
    -- https://github.com/iden3/circomlibjs/blob/main/test/poseidon.js
    
    it "hashes [1] correctly" $ do
      let result = poseidon [toF 1]
      fromF result `shouldBe` 
        18586133768512220936620570745912940619677854269274689475585506675881198879027

    it "hashes [1, 2] correctly" $ do
      let result = poseidon [toF 1, toF 2]
      fromF result `shouldBe` 
        7853200120776062878684798364095072458815029376092732009249414926327459813530

    it "hashes [1, 2, 0, 0, 0] correctly" $ do
      let result = poseidon [toF 1, toF 2, toF 0, toF 0, toF 0]
      fromF result `shouldBe`
        1018317224307729531995786483840663576608797660851238720571059489595066344487

    it "hashes [1, 2, 3, 4] correctly" $ do
      -- From circomlibjs: poseidonperm_x5_254_5 test
      let result = poseidon [toF 1, toF 2, toF 3, toF 4]
      fromF result `shouldBe`
        18821383157269793795438455681495246036402687001665670618754263018637548127333

    it "hashes [1,2,3,4,5,6] correctly" $ do
      -- From circomlibjs with initState=0
      let result = poseidon [toF 1, toF 2, toF 3, toF 4, toF 5, toF 6]
      fromF result `shouldBe`
        20400040500897583745843009878988256314335038853985262692600694741116813247201

    -- Note: Currently only supports up to 8 inputs (t=2 to t=9)
    -- 16-input test would require generating more constants

  describe "Poseidon2 (gnark-crypto BN254 defaults, t=2 rF=6 rP=50)" $ do
    -- Test vectors generated from gnark-crypto v0.20.1 ecc/bn254/fr/poseidon2

    it "permutes (0, 0) correctly" $ do
      let (a, b) = P2.permutation (toF 0, toF 0)
      (fromF a, fromF b) `shouldBe`
        ( 5760396826252723620130659814739767625264053726049147948400048226670170422969
        , 18622970401557034651033185129330286139447343337105683528700775943440799145467 )

    it "permutes (1, 2) correctly" $ do
      let (a, b) = P2.permutation (toF 1, toF 2)
      (fromF a, fromF b) `shouldBe`
        ( 1197409642805673503548047715485910702500396810305169145705533208671921662963
        , 1313337560616139085277676701856612540166622156368305732529371734734451176750 )

    it "compresses (1, 2) with the right-input feed-forward" $ do
      fromF (P2.compress (toF 1) (toF 2)) `shouldBe`
        1313337560616139085277676701856612540166622156368305732529371734734451176752

    it "Merkle-Damgard hashes [1] correctly" $ do
      fromF (P2.hash [toF 1]) `shouldBe`
        12157562999385135173166708316607836110878334226144932937475223226141207470306

    it "Merkle-Damgard hashes [1, 2] correctly" $ do
      fromF (P2.hash [toF 1, toF 2]) `shouldBe`
        4443443265955166080716935670700081889283598504231460571509928329665379862364

    it "Merkle-Damgard hashes [1, 2, 3, 4] correctly" $ do
      fromF (P2.hash (map toF [1, 2, 3, 4])) `shouldBe`
        5402851635480781446751342346210135834226319730389436212287936564310709451361

    it "Merkle-Damgard hashes [0..9] correctly" $ do
      fromF (P2.hash (map toF [0 .. 9])) `shouldBe`
        16191854207462619476933326392729612834530730884080381722066254905795027646701

    it "hash of a single block equals compress with zero IV" $ do
      fromF (P2.hash [toF 42]) `shouldBe` fromF (P2.compress (toF 0) (toF 42))

  describe "Field arithmetic" $ do
    it "handles modular reduction" $ do
      fromF (toF fieldPrime) `shouldBe` 0
      fromF (toF (fieldPrime + 1)) `shouldBe` 1

    it "handles multiplication" $ do
      fromF (fMul (toF 2) (toF 3)) `shouldBe` 6

    it "handles exponentiation" $ do
      fromF (fPow (toF 2) 10) `shouldBe` 1024

  -- Vectors generated by the plonky2 prover (rollup/zk `bench vectors`,
  -- rollup/gl/testdata/vectors.json) and by rollup/perp3 (DACommit): the
  -- builtin must equal what the circuits and the Go executor compute.
  describe "Poseidon2 over Goldilocks (plonky2 parameters)" $ do
    it "hashes [1] to the prover's digest" $
      G.hashNToM 4 [1] `shouldBe` [7431367281668178651, 8673656104435309403, 8585099438262764970, 14879537960188007193]
    it "hashes [1..8] (one full absorb) to the prover's digest" $
      G.hashNToM 4 [1 .. 8] `shouldBe` [11038414124778337341, 8720117733692872911, 15275222608080276643, 7761745982584972927]
    it "hashes [1..9] (two absorbs, overwrite mode) to the prover's digest" $
      G.hashNToM 4 [1 .. 9] `shouldBe` [16227062849557806322, 8564777786625489032, 190117969290264605, 5916077271953608790]
    it "hashes [1..33] to the prover's digest" $
      G.hashNToM 4 [1 .. 33] `shouldBe` [14548599093647915756, 11348138965205028545, 8820638031552347150, 18130297594873324736]
    it "two-to-one == hash of the 8 concatenated limbs" $
      G.hashNToM 4 ([5953741144751523847, 3144292997860177785, 12175764760479242333, 13537202921800866915] ++ [8793438919995366709, 8089750026849064075, 10639673724942322999, 1342500434807852112])
        `shouldBe` [6679411190554291926, 12443903919640065081, 13255071219357807468, 7656083906388922591]
    it "rejects non-canonical inputs" $
      (return $! length (G.hashNToM 4 [G.goldilocksPrime])) `shouldThrow` anyErrorCall
    it "hashBytes matches perp3.DACommit (7-byte LE chunks + length)" $ do
      let digestHex h = -- rollup/gl Digest.String() = %016x limb3 limb2 limb1 limb0
            let word i = case readHex (take 16 (drop (16 * i) h)) of
                  ((w, _) : _) -> w
                  [] -> error "bad hex vector"
             in reverse [ word i | i <- [0 .. 3 :: Int] ]
      G.hashBytes 4 B.empty `shouldBe` digestHex "9587f1d04110452d7a9136b4eb3814288138163c5fd4738263abf1755a14c31c"
      G.hashBytes 4 (B.pack [1]) `shouldBe` digestHex "830c0f40498eabb4120ad1d4eb2bf9c07ff0cd6c15785933063fb891aebf2ccf"
      G.hashBytes 4 (BC.pack "STRATO rollup DA v3 test payload!!") `shouldBe` digestHex "9999154c7e39d6e9b73f5feee00fa9e0a9e22a830074f1beae0e3c2f715ca0a1"
      G.hashBytes 4 (B.replicate 100 0) `shouldBe` digestHex "75b193e52099d2757f06d1d0a240dafea15d9e6787e46580929f8cff0a6a7294"
