# ~/.tmuxinator/strato-dashboard.yml

name: strato
root: ~/

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
#tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
#startup_window: backbone

# Controls whether the tmux session should be attached to automatically. Defaults to true.
#attach: false

# Runs after everything. Use it to attach to tmux with custom options etc.
# post: tmux -CC attach -t strato

windows:
  - backbone:
      layout: even-vertical
      panes:
        - vm:
          - docker exec -it silo_strato_1 tail -f -n 1000 /var/lib/strato/logs/ethereum-vm
        - sequencer:
          - docker exec -it silo_strato_1 tail -f -n 1000 /var/lib/strato/logs/strato-sequencer
        - adit:
          - docker exec -it silo_strato_1 tail -f -n 1000 /var/lib/strato/logs/strato-adit
        - index:
          - docker exec -it silo_strato_1 tail -f -n 1000 /var/lib/strato/logs/strato-index

  - network:
      layout: even-vertical
      panes:
        - ethereum-discover:
          - docker exec -it silo_strato_1 tail -f -n 1000 /var/lib/strato/logs/ethereum-discover
        - p2p-client:
          - docker exec -it silo_strato_1 tail -f -n 1000 /var/lib/strato/logs/strato-p2p-client
        - p2p-server:
          - docker exec -it silo_strato_1 tail -f -n 1000 /var/lib/strato/logs/strato-p2p-server
          
  - apis:
      layout: tiled
      panes: 
        - strato-api:
          - docker logs -ft --tail 1000 silo_strato_1
        - bloc:
          - docker logs -ft --tail 1000 silo_bloc_1
        - cirrus:
          - docker logs -ft --tail 1000 silo_cirrus_1
        - postgrest:
          - docker logs -ft --tail 1000 silo_postgrest_1
   
  - config:
      layout: tiled
      panes:
        - ethconf.yaml:
          - docker exec -it silo_strato_1 bash -c 'cat /var/lib/strato/.ethereumH/ethconf.yaml'

  - queryStrato:
      layout: even-horizontal 
      panes:
        - dumpkafkaunminedblocks:
          - docker exec -it silo_strato_1 bash -c 'cd /var/lib/strato; queryStrato dumpkafkaunminedblocks'
        - dumpkafkablocks:
          - docker exec -it silo_strato_1 bash -c 'cd /var/lib/strato; queryStrato dumpkafkablocks'
        - dumpkafkastatediff:
          - docker exec -it silo_strato_1 bash -c 'cd /var/lib/strato; queryStrato dumpkafkastatediff'
        - dumpkafkaunsequencer:
          - docker exec -it silo_strato_1 bash -c 'cd /var/lib/strato; queryStrato dumpkafkaunsequencer'
        - dumpkafkasequencer:
          - docker exec -it silo_strato_1 bash -c 'cd /var/lib/strato; queryStrato dumpkafkasequencer'

  - checkpoints:
      layout: even-vertical
      panes:
        - sequencer get:
          - watch -n 2 "docker exec -it silo_strato_1 bash -c 'cd /var/lib/strato; queryStrato checkpoints -s sequencer -o get'"
        - evm get:
          - watch -n 2 "docker exec -it silo_strato_1 bash -c 'cd /var/lib/strato; queryStrato checkpoints -s evm -o get'"
        - indexer get:  
          - watch -n 2 "docker exec -it silo_strato_1 bash -c 'cd /var/lib/strato; queryStrato checkpoints -s indexer -o get'"
        - sequencer put:
          - watch -n 2 "docker exec -it silo_strato_1 bash -c 'cd /var/lib/strato; queryStrato checkpoints -s sequencer -o put --offset 0'"
        - evm put:
          - watch -n 2 "docker exec -it silo_strato_1 bash -c 'cd /var/lib/strato; queryStrato checkpoints -s evm -o put --offset 0'"
        - indexer put:  
          - watch -n 2 "docker exec -it silo_strato_1 bash -c 'cd /var/lib/strato; queryStrato checkpoints -s indexer -o put --offset 0'"
             
  - monitor:
      layout: tiled
      panes:
        - htop:
          - htop
  
  - databases:
      layout: tiled
      panes:
        - postgres:
          - env ETHDB = docker exec -it silo_strato_1 bash -c 'cd /var/lib/strato; queryStrato psql | cut -d \' \' -f2'
          - docker exec -it silo_postgres_1 pg_top -d $ETHDB
        - redis:
          - docker exec -it silo_redis_1 bash -c 'redis-cli info'
        - postgres-cirrus:
          - docker exec -it silo_postgres-cirrus_1 bash -c 'su - postgres; pg_top cirrus'

