#!/bin/bash

set -e

if [[ $USER == "root" ]]
then sudo=""
else sudo=sudo
fi

echo "Installing Haskell Stack..."
$sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 575159689BEFB442
echo "deb http://download.fpcomplete.com/ubuntu $(lsb_release -s -c) main" | \
  sudo tee /etc/apt/sources.list.d/fpco.list
$sudo apt-get update
$sudo apt-get -y --allow-unauthenticated install stack git

echo "Compiling and installing mgit..."
# This branch needs to be removed once we merge it
git clone https://github.com/blockapps/mgit -b 131758053_credential-helpers
(
  cd mgit
  stack setup
  stack install
)

if [[ -n $1 ]]
then 
  echo >&2 "Using branch $1"
  branch="-b $1"
else
  echo >&2 "No branch specified"
  echo >&2 "To specify a branch, run $0 <branch>"
fi

if ! [[ -r ~/.git-credentials ]]
then
  echo >&2 "To automate this script, you must place credentials in ~/.git-credentials"
  echo >&2 "in the format 'https://<user>:<password>@github.com'"
fi

mgit --stored-credentials clone https://github.com/blockapps/silo $branch

echo "Installing docker..."
$sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 \
  --recv-keys 58118E89F3A912897C070ADBF76221572C52609D &>/dev/null
echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" \
  | $sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
$sudo apt-get update >&/dev/null
$sudo apt-get -y install docker-engine &>/dev/null
echo "Adding $USER to the docker group..."
$sudo usermod -aG docker $USER >&/dev/null
$sudo su - $USER

