version: '2'

services:

#  postgres:
#    image: postgres:9.6
#    environment:
#      POSTGRES_DB: cirrus
#      POSTGRES_USER: postgres
#      PG_ENV_POSTGRES_DB: cirrus
#      PG_ENV_POSTGRES_USER: postgres    
#    ports:
#      - '5433:5432'
#    networks:
#      - docker_default

#  postgrest:
#    build: ./postgrest_docker
#    #image: cirrus-postgrest
#    environment:
#      POSTGRES_DB: cirrus
#      POSTGRES_USER: postgres
#      PG_ENV_POSTGRES_DB: cirrus
#      PG_ENV_POSTGRES_USER: postgres
#      PG_PORT_5433_TCP_PORT: 5432
#    links:
#      - postgres:postgres
#    ports:
#      - '3001:3001'
#    networks:
#      - docker_default
#   # entrypoint: ./wait-for-it.sh postgres:5432

  cirrus:
    build: .
    command: node_modules/.bin/nodemon main.js
    environment:
      NODE_ENV: development
    ports:
      - '3333:3333'
    volumes:
      - .:/home/app/cirrus
      - /home/app/cirrus/node_modules
      - /home/app/cirrus/lib
      - /var/run/docker.sock:/var/run/docker.sock
 #   links:
 #     - postgrest:postgrest
 #     - postgres:postgres
    networks:
      - silo_default
    external_links:
      - silo_strato_1:strato
      - silo_zookeeper_1:zookeeper
      - silo_kafka_1:kafka
      - silo_postgrest_1:postgrest
      - silo_postgres-cirrus_1:postgres
networks:
  silo_default:
    #driver: bridge
    external: true

#  nginx:
#    image: cirrus-nginx
#    ports:
#      - "3003:3003"
#    depends_on:
#      - postgres
#      - postgrest
#      - cirrus 
