version: "2.1"
volumes:
  dapps:
    driver: local
  pgdata:
    driver: local
services:
  smd:
    depends_on:
    - apex
    - bloc
#    - cirrus
    - strato
    environment:
    - APEX_URL=${APEX_URL}
    - BLOC_DOC_URL=${BLOC_DOC_URL}
    - BLOC_URL=${BLOC_URL}
    - CIRRUS_URL=${CIRRUS_URL}
    - NODE_NAME=${NODE_NAME}
    - SINGLE_NODE=${SINGLE_NODE}
    - ssl=${ssl:-false}
    - STRATO_DOC_URL=${STRATO_DOC_URL}
    - STRATO_GS_MODE=${STRATO_GS_MODE}
    - STRATO_URL=${STRATO_URL}
    - SMD_MODE=${SMD_MODE}
    image: registry-aws.blockapps.net:5000/blockapps/smd:3.0.1-3684463
    restart: always
  apex:
    depends_on:
    - bloc
#    - cirrus
#    - postgres
    - strato
    environment:
    - blocHost=bloc:8000
    - cirrusHost=172.31.48.201:3333
    - NODE_HOST=${NODE_HOST}
    - postgres_host=172.31.48.201
    - postgres_password=${postgres_password:-api}
    - postgres_port=5432
    - postgres_user=postgres
    - PROD_DEV_MODE=${PROD_DEV_MODE:-false}
    - SINGLE_NODE=${SINGLE_NODE}
    - STRATO_GS_MODE=${STRATO_GS_MODE}
    - stratoHost=strato:3000
    image: registry-aws.blockapps.net:5000/blockapps/apex:3.0.1-3684463
    volumes:
    - dapps:/usr/src/app/apps
    restart: always
  dappstore:
    depends_on:
    - bloc
#    - cirrus
    - strato
    environment:
    - BLOC_URL=${BLOC_URL}
    - CIRRUS_URL=${CIRRUS_URL}
    - STRATO_URL=${STRATO_URL}
    image: registry-aws.blockapps.net:5000/blockapps/dappstore:3.0.1-3684463
    restart: always
  bloc:
    depends_on:
    - strato
#    - postgres
    environment:
    - cirrusHost=cirrus:3333
    - loglevel=${loglevel}
    - postgres_host=172.31.48.201
    - postgres_password=${postgres_password:-api}
    - postgres_port=5432
    - postgres_user=postgres
    - ssl=${ssl:-false}
    - stratoHost=strato:3000
    image: registry-aws.blockapps.net:5000/blockapps/bloc:3.0.1-3684463
    restart: always
    ports:
    - 8000:8000
  strato:
#    depends_on:
#    - kafka
#    - postgres
#    - redis
    environment:
    - addBootnodes=${addBootnodes}
    - backupblocks=${backupblocks}
    - blockTime=${blockTime}
    - bootnode=${bootnode}
    - debugFail=${debugFail}
    - evmDebugMode=${evmDebugMode}
    - evmTraceMode=${evmTraceMode}
    - genesis=${genesis}
    - genesisBlock=${genesisBlock}
    - kafkaHost=kafka
    - lazyBlocks=${lazyBlocks}
    - minBlockDifficulty=${minBlockDifficulty}
    - mineBlocks=${mineBlocks:-true}
    - miningAlgorithm=${miningAlgorithm}
    - miningThreads=${miningThreads}
    - networkID=${networkID}
    - numMinPeers=${numMinPeers}
    - postgres_host=postgres
    - postgres_password=${postgres_password:-api}
    - postgres_user=postgres
    - postgresIP=172.31.48.201
    - redisBDBNumber=${redisBDBNumber}
    - redisHost=redis
    - redisIP=172.31.48.201
    - redisPort=6379
    - statsEnable=${statsEnable}
    - statsFlush=${statsFlush}
    - statsHost=${statsHost}
    - statsPort=${statsPort}
    - statsPrefix=${statsPrefix}
    - statsSuffix=${statsSuffix}
    - useSyncMode=${useSyncMode}
    - zkHost=zookeeper
    image: registry-aws.blockapps.net:5000/blockapps/strato:3.0.1-3684463
    ports:
    - 30303:30303
    - 30303:30303/udp
    - 3000:3000
    restart: always

  nginx:
    depends_on:
    - bloc
#    - cirrus
#    - postgrest
    - smd
    - strato
    - apex
    environment:
    - authBasic=${authBasic}
    - blockTime=${blockTime}
    - ssl=${ssl:-false}
    - sslCertFileType=${sslCertFileType:-crt}
    - uiPassword=${uiPassword}
    - cirrusHost=172.31.48.201:3333
    - postgrestHost=172.31.48.201:3333
    image: registry-aws.blockapps.net:5000/blockapps/nginx:3.0.1-3684463
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./ssl:/tmp/ssl:ro
    restart: always
  docs:
    environment:
    - API_URL=/strato-api/eth/v1.2/swagger.json
    image: registry-aws.blockapps.net:5000/blockapps/docs:3.0.1-3684463
    restart: always
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    restart: always
    ports:
    - 2181:2181
  kafka:
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_LOG_CLEANER_ENABLE: "false"
      KAFKA_LOG_RETENTION_HOURS: 2147483647
      KAFKA_OFFSET_METADATA_MAX_BYTES: 1048576
      KAFKA_MAX_REQUEST_SIZE: 33554432
      KAFKA_MESSAGE_MAX_BYTES: 33554432
    image: wurstmeister/kafka:1.1.0
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9092:9092
