version: "2.1"
volumes:
  dapps:
    driver: local
  pgdata:
    driver: local
  prometheusdata:
    driver: local
services:
  smd:
    depends_on:
    - apex
    - bloc
    - postgrest
    - prometheus
    - strato
    environment:
    - APEX_URL=${APEX_URL}
    - BLOC_DOC_URL=${BLOC_DOC_URL}
    - BLOC_URL=${BLOC_URL}
    - CIRRUS_URL=${CIRRUS_URL}
    - EXT_STORAGE_S3_BUCKET=${EXT_STORAGE_S3_BUCKET}
    - EXT_STORAGE_S3_ACCESS_KEY_ID=${EXT_STORAGE_S3_ACCESS_KEY_ID}
    - EXT_STORAGE_S3_SECRET_ACCESS_KEY=${EXT_STORAGE_S3_SECRET_ACCESS_KEY}
    - NODE_NAME=${NODE_NAME}
    - SINGLE_NODE=${SINGLE_NODE}
    - SMD_MODE=${SMD_MODE}
    - ssl=${ssl:-false}
    - STRATO_DOC_URL=${STRATO_DOC_URL}
    - STRATO_GS_MODE=${STRATO_GS_MODE}
    - STRATO_URL=${STRATO_URL}
    build: .
    image: ${SMD_IMAGE:-<REPO_URL>smd:<VERSION>}
    restart: always
  apex:
    depends_on:
    - bloc
    - postgres
    - postgrest
    - strato
    environment:
    - blocHost=bloc:8000
    - EXT_STORAGE_S3_BUCKET=${EXT_STORAGE_S3_BUCKET}
    - EXT_STORAGE_S3_ACCESS_KEY_ID=${EXT_STORAGE_S3_ACCESS_KEY_ID}
    - EXT_STORAGE_S3_SECRET_ACCESS_KEY=${EXT_STORAGE_S3_SECRET_ACCESS_KEY}
    - NODE_HOST=${NODE_HOST}
    - postgres_host=postgres
    - postgres_password=${postgres_password:-api}
    - postgres_port=5432
    - postgres_user=postgres
    - postgrestHost=postgrest:3001
    - PROD_DEV_MODE=${PROD_DEV_MODE:-false}
    - SINGLE_NODE=${SINGLE_NODE}
    - SMD_MODE=${SMD_MODE}
    - STRATO_GS_MODE=${STRATO_GS_MODE}
    - stratoHost=strato:3000
    build: .
    image: ${APEX_IMAGE:-<REPO_URL>apex:<VERSION>}
    volumes:
    - dapps:/usr/src/app/apps
    restart: always
  dappstore:
    depends_on:
    - bloc
    - postgrest
    - strato
    environment:
    - BLOC_URL=${BLOC_URL}
    - CIRRUS_URL=${CIRRUS_URL}
    - STRATO_URL=${STRATO_URL}
    build: .
    image: ${DAPPSTORE_IMAGE:-<REPO_URL>dappstore:<VERSION>}
    restart: always
  bloc:
    depends_on:
    - postgres
    - strato
    - vault-wrapper
    environment:
    - loglevel=${loglevel}
    - kafkaHost=kafka
    - kafkaPort=9092
    - postgres_host=postgres
    - postgres_password=${postgres_password:-api}
    - postgres_port=5432
    - postgres_slipstream_db=cirrus
    - postgres_user=postgres
    - PROCESS_MONITORING=${PROCESS_MONITORING}
    - SMD_MODE=${SMD_MODE}
    - ssl=${ssl:-false}
    #    - stateDiffTopic=${stateDiffTopic}
    - stratoHost=strato:3000
    - vaultWrapperHost=vault-wrapper:8000
    - zookeeper_conn=zookeeper
    build: .
    image: ${BLOC_IMAGE:-<REPO_URL>bloc:<VERSION>}
    restart: always
  redis:
    command: [redis-server, --appendonly, "yes"]
    image: redis:3.2
    restart: always
  vault-wrapper:
    depends_on:
    - postgres
    environment:
    - postgres_host=postgres
    - postgres_password=${postgres_password:-api}
    - postgres_port=5432
    - postgres_user=postgres
    - postgres_vault_wrapper_db=oauth
    build: .
    image: ${VAULTWRAPPER_IMAGE:-<REPO_URL>vault-wrapper:<VERSION>}
    restart: always
  strato:
    depends_on:
    - kafka
    - postgres
    - redis
    environment:
    - addBootnodes=${addBootnodes}
    - backupblocks=${backupblocks}
    - blockstanbul=${blockstanbul}
    - blockstanbulBlockPeriodMs=${blockstanbulBlockPeriodMs}
    - blockstanbulPrivateKey=${blockstanbulPrivateKey}
    - blockstanbulRoundPeriodS=${blockstanbulRoundPeriodS}
    - blockTime=${blockTime}
    - bootnode=${bootnode}
    - connectionTimeout=${connectionTimeout}
    - debugFail=${debugFail}
    - evmDebugMode=${evmDebugMode}
    - evmTraceMode=${evmTraceMode}
    - genesis=${genesis}
    - genesisBlock=${genesisBlock}
    - kafkaHost=kafka
    - lazyBlocks=${lazyBlocks}
    - maxReturnedHeaders=${maxReturnedHeaders}
    - maxTxsPerBlock=${maxTxsPerBlock}
    - minBlockDifficulty=${minBlockDifficulty}
    - mineBlocks=${mineBlocks:-true}
    - miningAlgorithm=${miningAlgorithm}
    - miningThreads=${miningThreads}
    - networkID=${networkID}
    - numMinPeers=${numMinPeers}
    - postgres_host=postgres
    - postgres_password=${postgres_password:-api}
    - postgres_user=postgres
    - PROCESS_MONITORING=${PROCESS_MONITORING}
    - redisBDBNumber=${redisBDBNumber}
    - redisHost=redis
    - redisPort=6379
    - seqDebugMode=${seqDebugMode}
    - useSyncMode=${useSyncMode}
    - validators=${validators:-}
    - zkHost=zookeeper
    build: .
    image: ${STRATO_IMAGE:-<REPO_URL>strato:<VERSION>}
    ports:
    - 30303:30303
    - 30303:30303/udp
    restart: always
  postgrest:
    depends_on:
    - bloc
    - postgres
    environment:
    - blocHost=bloc:8000
    - PG_ENV_POSTGRES_DB=cirrus
    - PG_ENV_POSTGRES_HOST=postgres
    - PG_ENV_POSTGRES_PASSWORD=${postgres_password:-api}
    - PG_ENV_POSTGRES_USER=postgres
    - PG_PORT_5432_TCP_PORT=5432
    build: .
    image: ${POSTGREST_IMAGE:-<REPO_URL>postgrest:<VERSION>}
    restart: always
  postgres:
    environment:
    - POSTGRES_PASSWORD=${postgres_password:-api}
    image: postgres:9.6
    volumes:
    - pgdata:/var/lib/postgresql/data
    restart: always
  nginx:
    depends_on:
    - apex
    - bloc
    - postgrest
    - prometheus
    - smd
    - strato
    - vault-wrapper
    environment:
    - authBasic=${authBasic}
    - blockstanbul=${blockstanbul}
    - blockTime=${blockTime}
    - NODE_HOST=${NODE_HOST}
    - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
    - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
    - OAUTH_DISCOVERY_URL=${OAUTH_DISCOVERY_URL}
    - OAUTH_ENABLED=${OAUTH_ENABLED:-false}
    - OAUTH_JWT_VALIDATION_ENABLED=${OAUTH_JWT_VALIDATION_ENABLED:-false}
    - OAUTH_JWT_VALIDATION_DISCOVERY_URL=${OAUTH_JWT_VALIDATION_DISCOVERY_URL}
    - SMD_MODE=${SMD_MODE}
    - ssl=${ssl:-false}
    - sslCertFileType=${sslCertFileType:-crt}
    - STRATO_GS_MODE=${STRATO_GS_MODE}
    - uiPassword=${uiPassword}
    build: .
    image: ${NGINX_IMAGE:-<REPO_URL>nginx:<VERSION>}
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./ssl:/tmp/ssl:ro
    restart: always
  docs:
    environment:
    - API_URL=/strato-api/eth/v1.2/swagger.json
    build: .
    image: ${DOCS_IMAGE:-<REPO_URL>docs:<VERSION>}
    restart: always
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    restart: always
  kafka:
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_LOG_CLEANER_ENABLE: "false"
      KAFKA_LOG_RETENTION_HOURS: 2147483647
      KAFKA_OFFSET_METADATA_MAX_BYTES: 1048576
      KAFKA_MAX_REQUEST_SIZE: 33554432
      KAFKA_MESSAGE_MAX_BYTES: 33554432
    image: wurstmeister/kafka:1.1.0
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  prometheus:
    build: .
    image: ${PROMETHEUS_IMAGE:-<REPO_URL>prometheus:<VERSION>}
    volumes:
    - prometheusdata:/prometheus
    restart: always
