#rwa-io-version:<VERSION>
services:
  rwa-io:
    environment:
    - RWA_IO_API_KEY=${RWA_IO_API_KEY}
    build: .
    image: ${RWA_IO_IMAGE:-<REPO_URL>mercata-rwa-io-adapter:<VERSION>-<HASH_RWA_IO_ADAPTER>}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
