#stripe-ps-version:<VERSION>
#strato-getting-started-min-version:4.2.1
version: '3'
volumes:
  sqlitedb:
   driver: local
services:
  stripe-ps:
    environment:
    - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
    - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    build: .
    image: ${STRIPE_PS_IMAGE:-<REPO_URL>stripe-ps:<VERSION>}
    volumes:
    - sqlitedb:/sqlitedb
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
  nginx:
    depends_on:
    - stripe-ps
    environment:
    - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
    - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
    - OAUTH_DISCOVERY_URL=${OAUTH_DISCOVERY_URL}
    - OAUTH_SCOPE=${OAUTH_SCOPE}
    - ssl=${ssl}
    - sslCertFileType=${sslCertFileType}
    build: .
    image: ${STRIPEPSNGINX_IMAGE:-<REPO_URL>stripe-ps-nginx:<VERSION>}
    ports:
    - ${HTTP_PORT:-80}:80 #TAG_REMOVE_WHEN_SSL_CUSTOM_HTTPS_PORT
    - ${HTTPS_PORT:-443}:443 #TAG_REMOVE_WHEN_NO_SSL
    volumes:
    - ./ssl:/tmp/ssl:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
