ARG STACK_RESOLVER

FROM fpco/stack-build:${STACK_RESOLVER}

RUN apt-get update && \
    apt-get -y --allow-unauthenticated install autoconf libtool libblas-dev liblapack-dev libsodium-dev && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

# package the pre-built solc (e.g. required for 'stack test blockapps-bloc22-server')
COPY ./solc /usr/local/bin/
