# This is a build base image for the `stack --docker build` mode which is deprecated and not maintained
ARG STACK_RESOLVER

FROM fpco/stack-build:${STACK_RESOLVER}

RUN apt-get update && \
    apt-get -y --allow-unauthenticated install autoconf libtool libblas-dev liblapack-dev libsodium-dev jq vim liblzma-dev libleveldb-dev libpq-dev libsecp256k1-dev pkg-config && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean 
