#vault-version:<VERSION>
#strato-getting-started-min-version:4.2.1
version: "3"
volumes:
  idpconfig:
      driver: local
services:
  identity-provider:
    environment:
    - cacheSize=${cacheSize}
    - IDENTITYPROVIDER_DEBUG=${IDENTITYPROVIDER_DEBUG}
    - identityProviderPort=${identityProviderPort}
    - FALLBACK_NODE_URL=${FALLBACK_NODE_URL}
    - NODE_URL=${NODE_URL}
    - NOTIFICATION_SERVER_URL=${NOTIFICATION_SERVER_URL}
    - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
    - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
    - OAUTH_DISCOVERY_URL=${OAUTH_DISCOVERY_URL}
    - PROCESS_MONITORING=${PROCESS_MONITORING}
    - SENDGRID_APIKEY=${SENDGRID_APIKEY}
    - USER_REGISTRY_ADDRESS=${USER_REGISTRY_ADDRESS}
    - USER_REGISTRY_CODEHASH=${USER_REGISTRY_CODEHASH}
    - USER_CONTRACT_NAME=${USER_CONTRACT_NAME}
    - VAULT_PROXY_DEBUG=${VAULT_PROXY_DEBUG}
    - VAULT_URL=${VAULT_URL}
    build: .
    image: ${IDENTTIYPROVIDER_IMAGE:-<REPO_URL>identity-provider:<VERSION>}
    restart: unless-stopped
    volumes: 
      - ./identity-provider/certs:/identity-provider/certs:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
  nginx:
    depends_on:
    - identity-provider
    environment:
    - ssl=${ssl}
    - sslCertFileType=${sslCertFileType}
    - IDENTITY_PROVIDER_HOSTNAME=${IDENTITY_PROVIDER_HOSTNAME}
    - OAUTH_DISCOVERY_URL=${OAUTH_DISCOVERY_URL}
    build: .
    image: ${IDENTITYNGINX_IMAGE:-<REPO_URL>identity-nginx:<VERSION>}
    ports:
    - ${HTTP_PORT:-8000}:80 #TAG_REMOVE_WHEN_SSL_CUSTOM_HTTPS_PORT
    - ${HTTPS_PORT:-8001}:443 #TAG_REMOVE_WHEN_NO_SSL
    volumes:
    - ./ssl:/tmp/ssl:ro
    - idpconfig:/config
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
