#strato-version:<VERSION>
#strato-getting-started-min-version:4.4.0
version: "3"
volumes:
  marketplacedata:
   driver: local
  stratodata:
    driver: local
services:
  smd:
    depends_on:
    - strato
    environment:
    - NODE_HOST=${NODE_HOST}
    - NODE_NAME=${NODE_NAME}
    - ssl=${ssl:-false}
    build: .
    image: ${SMD_IMAGE:-<REPO_URL>smd:<VERSION>}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
  marketplace-backend:
    depends_on:
    - nginx
    environment:
    - AUTH_MODE=${AUTH_MODE:-OAUTH}
    - BASE_CODE_COLLECTION=${BASE_CODE_COLLECTION}
    - MP_IS_BOOTNODE=${MP_IS_BOOTNODE:-false}
    - MP_API_DEBUG=${MP_API_DEBUG:-false}
    - MP_DELAY_DEPLOYMENT=${MP_DELAY_DEPLOYMENT}
    - MP_SERVER_HOST=${NODE_HOST}
    - MP_SERVER_SSL=${ssl}
    - STRATO_NODE_PROTOCOL=${STRATO_NODE_PROTOCOL}
    - STRATO_NODE_HOST=${STRATO_NODE_HOST}
    - NODE_LABEL=${NODE_NAME} # TODO: obsolete? (label is not used from config.yaml)
    - OAUTH_APP_TOKEN_COOKIE_NAME=${OAUTH_APP_TOKEN_COOKIE_NAME:-stratomp_session}
    - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
    - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
    - OAUTH_SCOPE=${OAUTH_SCOPE:-email openid} # TODO: to be removed after app oauth changes
    - OAUTH_SERVICE_OAUTH_FLOW=client-credential
    - OAUTH_TOKEN_FIELD=access_token
    - OAUTH_TOKEN_USERNAME_PROPERTY=${OAUTH_TOKEN_USERNAME_PROPERTY:-email}
    - OAUTH_TOKEN_USERNAME_PROPERTY_SERVICE_FLOW=${OAUTH_TOKEN_USERNAME_PROPERTY_SERVICE_FLOW:-sub}
    - STRATO_HOSTNAME=${STRATO_HOSTNAME}
    - STRATO_PORT_API=${STRATO_PORT_API}
    - GLOBAL_ADMIN_NAME=${GLOBAL_ADMIN_NAME}
    - GLOBAL_ADMIN_PASSWORD=${GLOBAL_ADMIN_PASSWORD}
    - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    build: .
    image: ${MARKETPLACEBACKEND_IMAGE:-<REPO_URL>marketplace-backend:<VERSION>}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    volumes:
       - marketplacedata:/config:rw
  marketplace-ui:
    depends_on:
      - marketplace-backend
    environment:
      - AUTH_MODE=${AUTH_MODE:-OAUTH}
      - SITE_ID=${SITE_ID:-038fe3fa}
      - STRATO_HOSTNAME=${STRATO_HOSTNAME}
      - STRATO_PORT_API=${STRATO_PORT_API}
    build: .
    image: ${MARKETPLACEUI_IMAGE:-<REPO_URL>marketplace-ui:<VERSION>}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
  strato:
    environment:
    - accountNonceLimit=${accountNonceLimit}
    - addBootnodes=${addBootnodes}
    - API_DEBUG_LOG=${API_DEBUG_LOG:-false}
    - appFetchLimit=${appFetchLimit}
    - AUTH_MODE=${AUTH_MODE:-OAUTH}
    - averageTxsPerBlock=${averageTxsPerBlock}
    - blockstanbul=${blockstanbul}
    - blockstanbulBlockPeriodMs=${blockstanbulBlockPeriodMs}
    - blockstanbulRoundPeriodS=${blockstanbulRoundPeriodS}
    - blockTime=${blockTime}
    - bootnode=${bootnode}
    - connectionTimeout=${connectionTimeout}
    - creatorForkBlockNumber=${creatorForkBlockNumber}
    - debugFail=${debugFail}
    - debugPort=${debugPort}
    - debugWSHost=${debugWSHost}
    - debugWSPort=${debugWSPort}
    - validatorBehavior=${validatorBehavior:-true}
    - evmDebugMode=${evmDebugMode}
    - FILE_SERVER_URL=${FILE_SERVER_URL}
    - FULL_DEBUG_LOG=${FULL_DEBUG_LOG:-false}
    - gasLimit=${gasLimit}
    - generateKey=${generateKey:-true}
    - genesis=${genesis}
    - idServerUrl=${idServerUrl}
    - kafkaHost=kafka
    - kafkaPort=9092
    - lazyBlocks=${lazyBlocks}
    - maxConn=${maxConn}
    - maxReturnedHeaders=${maxReturnedHeaders}
    - maxTxsPerBlock=${maxTxsPerBlock}
    - minBlockDifficulty=${minBlockDifficulty}
    - network=${network}
    - networkID=${networkID}
    - numMinPeers=${numMinPeers}
    - OAUTH_DISCOVERY_URL=${OAUTH_DISCOVERY_URL}
    - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
    - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
    - OAUTH_VAULT_PROXY_ALT_CLIENT_ID=${OAUTH_VAULT_PROXY_ALT_CLIENT_ID}
    - OAUTH_VAULT_PROXY_ALT_CLIENT_SECRET=${OAUTH_VAULT_PROXY_ALT_CLIENT_SECRET}
    - OAUTH_RESERVE_SECONDS=${OAUTH_RESERVE_SECONDS}
    - postgres_host=postgres
    - postgres_password=${postgres_password:-api}
    - postgres_port=5432
    - postgres_slipstream_db=cirrus
    - postgres_user=postgres
    - PROCESS_MONITORING=${PROCESS_MONITORING:-true}
    - redisBDBNumber=${redisBDBNumber}
    - redisHost=redis
    - redisPort=6379
    - requireCerts=${requireCerts:-true}
    - seqEventsBatchSize=${seqEventsBatchSize}
    - seqEventsCostHeuristic=${seqEventsCostHeuristic}
    - seqMaxEventsPerIter=${seqMaxEventsPerIter}
    - seqMaxUsPerIter=${seqMaxUsPerIter}
    - seqRTSOPTs=${seqRTSOPTs}
    - SEQUENCER_DEBUG_LOG=${SEQUENCER_DEBUG_LOG:-false}
    - SERVER_NODE_URL=${SERVER_NODE_URL}
    - SKIP_IDENTITY=${SKIP_IDENTITY:-false}
    - SLIPSTREAM_DEBUG_LOG=${SLIPSTREAM_DEBUG_LOG:-false}
    - SLIPSTREAM_OPTIONAL=${SLIPSTREAM_OPTIONAL}
    - STRATO_MODE=${STRATO_MODE:-CLIENT}
    - STRIPE_PAYMENT_SERVER_URL=${STRIPE_PAYMENT_SERVER_URL}
    - svmTrace=${svmTrace}
    - sqlDiff=${sqlDiff}
    - svmDev=${svmDev}
    - txSizeLimit=${txSizeLimit}
    - MERCATA_USERNAME=${MERCATA_USERNAME}
    - userRegistryAddress=${userRegistryAddress}
    - userRegistryCodeHash=${userRegistryCodeHash}
    - useBuiltinUserRegistry=${useBuiltinUserRegistry}
    - useWalletsByDefault=${useWalletsByDefault}
    - VAULT_URL=${VAULT_URL}
    - VAULT_PROXY_DEBUG=${VAULT_PROXY_DEBUG}
    - VM_DEBUGGER=${VM_DEBUGGER}
    - VM_DEBUG_LOG=${VM_DEBUG_LOG:-false}
    - vmRunnerRTSOPTs=${vmRunnerRTSOPTs}
    - zkHost=zookeeper
    build: .
    image: ${STRATO_IMAGE:-<REPO_URL>strato:<VERSION>}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    volumes:
      - stratodata:/var/lib/strato
      - ./genesis-block.json:/var/lib/strato/${genesis:-gettingStarted}Genesis.json
      - ${PEM_FILE:-./blank.pem}:/var/lib/strato/priv.pem
      - ${BACKUP_PEM_FILE:-./blank.pem}:/var/lib/strato/backup_priv.pem
  nginx:
    depends_on:
    - docs
    - smd
    - strato
    environment:
    - APEX_HOST=${APEX_HOST}
    - AUTH_MODE=${AUTH_MODE:-OAUTH}
    - blockstanbul=${blockstanbul}
    - blockTime=${blockTime}
    - debugPort=${debugPort}
    - debugWSPort=${debugWSPort}
    - DOCS_HOST=${DOCS_HOST}
    - MARKETPLACE_BACKEND_HOST=${MARKETPLACE_BACKEND_HOST}
    - MARKETPLACE_UI_HOST=${MARKETPLACE_UI_HOST}
    - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
    - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
    - OAUTH_SCOPE=${OAUTH_SCOPE}
    - POSTGREST_HOST=${POSTGREST_HOST}
    - PROMETHEUS_HOST=${PROMETHEUS_HOST}
    - SERVE_LOGS=${SERVE_LOGS}
    - SERVER_NODE_URL=${SERVER_NODE_URL}
    - SMD_DEV_MODE=${SMD_DEV_MODE}
    - SMD_DEV_MODE_HOST_IP=${SMD_DEV_MODE_HOST_IP}
    - SMD_HOST=${SMD_HOST}
    - ssl=${ssl}
    - sslCertFileType=${sslCertFileType}
    - STATS_ENABLED=${STATS_ENABLED}
    - STRATO_HOSTNAME=${STRATO_HOSTNAME}
    - STRATO_PORT_API=${STRATO_PORT_API}
    - STRATO_PORT_API2=${STRATO_PORT_API2}
    - STRATO_PORT_LOGS=${STRATO_PORT_LOGS}
    - STRATO_PORT_VAULT_PROXY=${STRATO_PORT_VAULT_PROXY:-8013}
    - STRATO_MODE=${STRATO_MODE:-FULL}
    - VM_DEBUGGER=${VM_DEBUGGER}
    build: .
    image: ${NGINX_IMAGE:-<REPO_URL>nginx:<VERSION>}
    ports:
    - ${HTTP_PORT:-80}:80 #TAG_REMOVE_WHEN_SSL_CUSTOM_HTTPS_PORT
    - ${HTTPS_PORT:-443}:443 #TAG_REMOVE_WHEN_NO_SSL
    volumes:
    - ./ssl:/tmp/ssl:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
  docs:
    environment:
    - API_URL=/strato-api/eth/v1.2/swagger.json
    image: swaggerapi/swagger-ui:v3.22.1
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
