#bridge-version:<VERSION>
services:
  external-bridge-signer:
    environment:
    - PORT=3004
    - DESTINATION_CHAIN_ID=${DESTINATION_CHAIN_ID}
    - DESTINATION_VAULT_ADDRESS=${DESTINATION_VAULT_ADDRESS}
    - SIGNER_RPC_URL=${SIGNER_RPC_URL}
    - SOURCE_CHAIN_ID=${SOURCE_CHAIN_ID}
    - STRATO_NODE_URL=${STRATO_NODE_URL}
    - EXTERNAL_ASSET_BRIDGE_ADDRESS=${EXTERNAL_ASSET_BRIDGE_ADDRESS}
    - SIGNER_OPENID_DISCOVERY_URL=${SIGNER_OPENID_DISCOVERY_URL}
    - SIGNER_CLIENT_ID=${SIGNER_CLIENT_ID}
    - SIGNER_CLIENT_SECRET=${SIGNER_CLIENT_SECRET}
    - SIGNER_BA_USERNAME=${SIGNER_BA_USERNAME}
    - SIGNER_BA_PASSWORD=${SIGNER_BA_PASSWORD}
    - KMS_SIGNER_ADDRESS=${KMS_SIGNER_ADDRESS}
    - KMS_SIGNER_URL=${KMS_SIGNER_URL}
    - KMS_SIGNER_API_TOKEN=${KMS_SIGNER_API_TOKEN}
    - EXTERNAL_BRIDGE_SIGNER_API_TOKEN=${EXTERNAL_BRIDGE_SIGNER_API_TOKEN}
    image: ${BRIDGE_IMAGE:-<REPO_URL>bridge:<VERSION>-<HASH_BRIDGE>}
    command: ["node", "dist/signer/index.js"]
    init: true
    restart: unless-stopped
    ports:
    - ${SIGNER_PORT:-3004}:3004
    healthcheck:
      test: ["CMD-SHELL", "wget --header='Authorization: Bearer $${EXTERNAL_BRIDGE_SIGNER_API_TOKEN}' -qO- http://localhost:3004/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
