#!/bin/bash

set -e
exec 2> >(while read line; do echo -e "\e[01;31m$line\e[0m" >&2; done)

builddir=`mktemp -d /tmp/build.XXXX`

packages=`pwd`/packages

if [ "$1" == "install" ]
then
    bindir=~/.local/bin
fi

for i in `cat mgitmods`
do
	submoddir=`basename $i`
	packagedir=$builddir/$submoddir
	if [ -e $submoddir/BUILD ]
	then
		mkdir $packagedir
		echo "############### Building: $submoddir"
		cd $submoddir
       	     	PKGDIR=$packagedir BINDIR=$bindir ./BUILD
		if [ "$1" == "dpkg" -o "$1" == "docker" ]
		then
		    if [ ! -e "$packages/$submoddir.deb" ]
		    then
			mkdir -p $packages
			dpkg --build $packagedir $packages/$submoddir.deb
		    fi
		fi
		cd ..

		if [ "$1" == "docker" ]
		then
		    cp $packages/$submoddir.deb buildDocker/package.deb
		    docker build -t $submoddir buildDocker
		fi

	fi
done

