
user root;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;

    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    client_body_buffer_size 64K;
    client_header_buffer_size 64k;
    client_max_body_size 1M;
    large_client_header_buffers 4 512k;

    server {
      listen 443;

      ssl    on;
      ssl_certificate    /etc/ssl/certs/server.pem;
      ssl_certificate_key  /etc/ssl/private/server.key;

      resolver 127.0.0.11;

      location / {
        proxy_pass http://explorer:9000;
      }

      location /socket.io-client/ {
        proxy_pass http://explorer:9000/socket.io-client/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
      }


      location /static/bower_components/ {
        proxy_pass http://bloc:8000;
      }

#      location /static/bower_components/bootstrap/dist/js/ {
#        proxy_pass http://bloc:8000;
#      }

#      location /static/bower_components/bootstrap/dist/fonts/ {
#        proxy_pass http://bloc:8000;
#      }

#      location /static/bower_components/jquery/jquery.min.js {
#        proxy_pass http://bloc:8000;
#      }

      location /static/css/ {
        proxy_pass http://bloc:8000;
      }

      location = /explorer {
        return 302 /explorer/;
     }

      location /explorer/ {
        proxy_set_header Accept-Encoding "";
        proxy_pass http://explorer:9000/;
      }

      location /cirrus/contract {
        return 302 /cirrus/contract/;
      }

      location /cirrus/contract/ {
        proxy_set_header Accept-Encoding "";
        proxy_pass http://cirrus:3333/;
      }

      location /cirrus/search {
        return 302 /cirrus/search/;
      }

      location /cirrus/search/ {
        proxy_set_header Accept-Encoding "";
        proxy_pass http://postgrest:3001/;
      }

      location = /bloc {
        return 302 /bloc/;
      }

      location /bloc/ {
        proxy_read_timeout 300;
        proxy_set_header Accept-Encoding "";
        proxy_pass http://bloc:8000/;
      }

      location = /bloch {
        return 302 /bloch/;
      }

      location /bloch/ {
        proxy_read_timeout 300;
        proxy_set_header Accept-Encoding "";
        proxy_pass http://bloch:8000/;
      }


      location = /strato-api {
        return 302 /strato-api/;
      }

      location /strato-api/ {
        proxy_pass http://strato:3000/;
      }

    }
}
