resolver: nightly-2017-02-23
packages:
- bloc
- ethereum
- solidity
- solidity-abi
- state-translate
- strato/api
- strato/client
- location:
    git: https://github.com/blockapps/secp256k1-haskell/
    commit: 0a6db54f31defdd7a5edecdf6932af3deea6ca57
  extra-dep: true
- location:
    git: https://github.com/echatav/servant-aeson-specs/
    commit: cedbf002b0d5855c17dc91de97e966ee339604fa
  extra-dep: true
extra-deps:
  - saltine-0.0.0.4
  - hasql-0.19.16
  - bytestring-tree-builder-0.2.7.1
  - contravariant-extras-0.3.3.1
  - hashtables-1.2.1.0
  - tuple-th-0.2.5
  - vector-0.11.0.0
  - primitive-0.6.1.0
  - hflags-0.4.2
flags: {}
extra-package-dbs: []
