resolver: nightly-2017-01-17
packages:
- blockapps-bloc
- blockapps-data
- blockapps-strato
- solidity-abi
- state-translate
- location:
    git: https://github.com/blockapps/secp256k1-haskell/
    commit: 0a6db54f31defdd7a5edecdf6932af3deea6ca57
  extra-dep: true
- location:
    git: https://github.com/echatav/servant-aeson-specs/
    commit: cedbf002b0d5855c17dc91de97e966ee339604fa
  extra-dep: true
- location:
    git: https://github.com/echatav/hasql/
    commit: 1f9ba4b0aa665b06576d7a5be00038b034fc3e9f
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
