resolver: nightly-2017-01-17
packages:
- blockapps-bloc
- blockapps-data
- blockapps-strato
- location:
    git: https://github.com/blockapps/secp256k1-haskell/
    commit: 0a6db54f31defdd7a5edecdf6932af3deea6ca57
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
