#!/usr/bin/env bash

set -e

if [ "$1" = "" ]
then
	echo "error!  You must supply a directory"
	exit
fi

if [ -e $1 ]
then
	echo "error!  directory $1 already exists"
	exit
fi

if [ -e ~/secrets/oauth_credentials ]
then
    source ~/secrets/oauth_credentials
else
    export DEFAULT_OAUTH_DISCOVERY_URL="https://keycloak.blockapps.net/auth/realms/mercata/.well-known/openid-configuration"
    read -e -p "Enter the OAUTH_DISCOVERY_URL [${DEFAULT_OAUTH_DISCOVERY_URL}]: " OAUTH_DISCOVERY_URL

    OAUTH_DISCOVERY_URL=${OAUTH_DISCOVERY_URL:-$DEFAULT_OAUTH_DISCOVERY_URL}

    read -e -p "Enter the OAUTH_CLIENT_ID: " OAUTH_CLIENT_ID
    read -s -e -p "Enter the OAUTH_CLIENT_SECRET: " OAUTH_CLIENT_SECRET
fi

export OAUTH_DISCOVERY_URL
export OAUTH_CLIENT_ID
export OAUTH_CLIENT_SECRET

export network=helium
export VAULT_URL=https://vault.blockapps.net:8093

####################################

function cleanup {
    docker compose -p strato down -v -t 0 --remove-orphans
    #killall blockapps-vault-proxy-server
}

trap 'cleanup' INT

# "host.docker.internal" is set up in Windows/Mac (to point to the host's localhost),
# but for some reason wasn't set up to work in Linux
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  STRATO_HOSTNAME=172.17.0.1
else
  STRATO_HOSTNAME=host.docker.internal
  export HTTP_PORT=8080 #You can change this to 80 for Linux, Mac seems to forbid it
fi

export STRATO_HOSTNAME

export NODE_HOST="localhost:8080"
export blocHost=$STRATO_HOSTNAME:3000

mkdir $1

docker compose -p strato up -d

sleep 10

PGPASSWORD=api createdb -h localhost -U postgres cirrus

cd $1

mkdir logs

blockapps-vault-proxy-server --OAUTH_DISCOVERY_URL=https://keycloak.blockapps.net/auth/realms/mercata/.well-known/openid-configuration --OAUTH_CLIENT_ID=hq1 --OAUTH_CLIENT_SECRET=2d67202d-76bd-4cc4-b2ab-75b4fea54f6b --OAUTH_RESERVE_SECONDS=13 --VAULT_URL=https://vault.blockapps.net:8093 --VAULT_PROXY_PORT=8013 --VAULT_PROXY_DEBUG=false & > logs/blockapps-vault-proxy-server

echo "Running setup"
strato-setup -p api -K localhost --network=helium > logs/strato-setup 2>&1
echo "Setup complete"

convoke
