#!/bin/bash
set -e

echo "Installing deployment dependencies"
sudo ./setup-ubuntu16.04

echo "Starting docker containers"
docker-compose up -d

echo "Installing test dependencies..."
cd strato/deployments/test
npm install

echo "Running tests..."
node_modules/mocha/bin/mocha --config ./../../../test.config.yaml e2e

if [[ $1 == "docker-down" ]]
then
  echo "Killing docker processes..."
  docker-compose kill && docker-compose down -v
fi
