name:
  fast-ecrecover
version:
  0.1
synopsis:
  Fast implementation of the EC Recover algorithm
copyright:
  2016, Blockapps
build-type:
  Simple

license: Apache-2.0

github: blockapps/strato-platform/core-strato/fast-ecrecover

dependencies:
  - base
  - blockapps-haskoin
  - ethereum-encryption
  - blockapps-util
  - blockapps-ecrecover == 0.4.*
  - binary < 0.9
  - bytestring >= 0.10 && < 0.20

library:
  source-dirs: src/

benchmarks:
  fast-ecrecover-benchmark:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
      - fast-ecrecover
      - criterion
    ghc-options: -O2 -threaded "-with-rtsopts=-N"
    ghc-prof-options: -O2 -threaded -fprof-auto "-with-rtsopts=-N -p -s -h -i0.1"
    default-extensions:
      - Arrows
      - BangPatterns
      - ConstraintKinds
      - DataKinds
      - DefaultSignatures
      - DeriveDataTypeable
      - DeriveFoldable
      - DeriveFunctor
      - DeriveGeneric
      - DeriveTraversable
      - EmptyDataDecls
      - FlexibleContexts
      - FlexibleInstances
      - FunctionalDependencies
      - GADTs
      - GeneralizedNewtypeDeriving
      - LambdaCase
      - LiberalTypeSynonyms
      - MagicHash
      - MultiParamTypeClasses
      - MultiWayIf
      - NoMonomorphismRestriction
      - OverloadedStrings
      - PatternGuards
      - ParallelListComp
      - QuasiQuotes
      - RankNTypes
      - RecordWildCards
      - ScopedTypeVariables
      - StandaloneDeriving
      - TemplateHaskell
      - TupleSections
      - TypeFamilies
      - TypeOperators
      - UnboxedTuples
