name: merkle-patricia-db
version: 0.0.1
build-type: Simple
author: Jamshid
license-file:  LICENSE
maintainer:    jamshidnh@gmail.com
synopsis: A modified Merkle Patricia DB
category:      Data Structures
license: Apache-2.0
description:
    The modified Merkle Patricia DB described in the Ethereum Yellowpaper
github: blockapps/strato-platform/strato-platform/merkle-patricia-db

dependencies:
  - aeson
  - ansi-wl-pprint
  - base >= 4 && < 5
  - base16-bytestring
  - binary
  - blockapps-util
  - bytestring
  - containers
  - cryptohash
  - data-default
  - deepseq
  - ethereum-rlp
  - format
  - leveldb-haskell
  - monad-control
  - mtl
  - nibblestring
  - resourcet
  - strato-model
  - transformers
  - vector

library:
    source-dirs: src

tests:
  test-merkle-patricia-db:
    source-dirs: test
    main:        MerklePatriciaSpec.hs
    dependencies:
      - merkle-patricia-db
      - test-framework
      - test-framework-hunit
      - HUnit
      - hspec
      - hspec-contrib

benchmarks:
  mpbench:
    main: MPBench.hs
    source-dirs: bench/
    dependencies:
      - criterion
      - directory
      - merkle-patricia-db
      - directory
      - unix
      - QuickCheck
