name: merkle-patricia-db
version: 0.0.1
build-type: Simple
author: Jamshid
license-file:  LICENSE
maintainer:    jamshidnh@gmail.com
synopsis: A modified Merkle Patricia DB
category:      Data Structures
license: Apache-2.0
description:
    The modified Merkle Patricia DB described in the Ethereum Yellowpaper

dependencies:
  - base
  - ethereum-rlp
  - leveldb-haskell
  - monad-alter
  - nibblestring
  - resourcet
  - strato-model
  - transformers
  - utf8-string

library:
  source-dirs: src
  dependencies:
  - ansi-wl-pprint
  - base16-bytestring
  - binary
  - bytestring
  - containers
  - data-default
  - deepseq
  - format


tests:
  test-merkle-patricia-db:
    source-dirs: test
    main:        MerklePatriciaSpec.hs
    dependencies:
      - HUnit
      - blockapps-util
      - hspec
      - hspec-contrib
      - merkle-patricia-db

benchmarks:
  mpbench:
    main: MPBench.hs
    source-dirs: bench/
    dependencies:
      - bytestring
      - criterion
      - deepseq
      - directory
      - merkle-patricia-db
      - directory
      - unix
      - QuickCheck
