// ROOMS
export const LAST_BLOCK_NUMBER = 'LAST_BLOCK_NUMBER';
export const USERS_COUNT = 'USERS_COUNT';
export const GET_PEERS = 'GET_PEERS';
export const CONTRACTS_COUNT = 'CONTRACTS_COUNT';
export const TRANSACTIONS_TYPE = 'TRANSACTIONS_TYPE';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const BLOCKS_DIFFICULTY = 'BLOCKS_DIFFICULTY';
export const BLOCKS_FREQUENCY = 'BLOCKS_FREQUENCY';
export const BLOCKS_PROPAGATION = 'BLOCKS_PROPAGATION';
export const TRANSACTIONS_COUNT = 'TRANSACTIONS_COUNT';
export const GET_COINBASE = 'GET_COINBASE';
export const GET_NODE_UPTIME = 'GET_NODE_UPTIME';
export const GET_HEALTH = 'GET_HEALTH';
export const GET_SYSTEM_INFO = 'GET_SYSTEM_INFO';
export const GET_SHARD_COUNT = 'GET_SHARD_COUNT';
export const GET_NETWORK_HEALTH = "GET_NETWORK_HEALTH";
