{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PackageImports #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE Rank2Types #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TupleSections #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE NoMonomorphismRestriction #-}
{-# OPTIONS_GHC -fno-warn-orphans #-}

module SimulatorSpec where

-- import BlockApps.Logging
-- import Blockchain.Blockstanbul
-- import Blockchain.Blockstanbul.Messages (round)
-- import Blockchain.Blockstanbul.StateMachine
-- import Blockchain.DB.RawStorageDB
-- import Blockchain.DB.SolidStorageDB
-- import qualified Blockchain.Data.AlternateTransaction as U
-- import Blockchain.Data.Block
-- import Blockchain.Data.BlockDB ()
-- import qualified Blockchain.Data.TXOrigin as Origin
-- import Blockchain.Data.TransactionDef
-- import Blockchain.EthEncryptionException (EthEncryptionException (..))
-- import Blockchain.Model.SyncState
-- import Blockchain.Model.WrappedBlock
-- import Blockchain.Sequencer.Event
-- import Blockchain.Sequencer.Monad
-- import Blockchain.Strato.Model.Address
-- import Blockchain.Strato.Model.Code
-- import Blockchain.Strato.Model.ExtendedWord
-- import Blockchain.Strato.Model.Gas
-- import Blockchain.Strato.Model.MicroTime
-- import Blockchain.Strato.Model.Nonce
-- import Blockchain.Strato.Model.Secp256k1
-- import Blockchain.Strato.Model.Wei
-- import qualified Blockchain.VMContext as VMC
-- import Conduit
-- import Control.Concurrent.STM.TMChan
-- import Control.Lens hiding (Context, view)
-- import Control.Monad (void)
-- import qualified Control.Monad.Change.Alter as A
-- import Control.Monad.Reader
-- import qualified Data.ByteString.Char8 as BC
-- import Data.Conduit.TQueue
-- import Data.Foldable (for_)
-- import Data.Function (on)
-- import qualified Data.Map.Strict as M
-- import qualified Data.Set as Set
-- import qualified Data.Text as T
-- import Data.Traversable (for)
-- import SolidVM.Model.Storable
-- import Strato.Lite
import Test.Hspec
-- import Test.QuickCheck
-- import Text.RawString.QQ
-- import UnliftIO
-- import UnliftIO.Concurrent (threadDelay)
-- import Prelude hiding (round)
-- 
-- instance Eq SomeException where
--   _ == _ = True -- for the purpose of my test, all exceptions are equal
-- 
spec :: Spec
spec = pure ()
--   describe "network simulation" $ do
--     it "should send a transaction from server to client" $ do
--         serverPKey <- newPrivateKey
--         clientPKey <- newPrivateKey
--         let validatorAddresses = fromPrivateKey <$> [serverPKey, clientPKey]
--             validatorInfos = ["Admin", "Person"]
--             zippedValidators = zip validatorAddresses validatorInfos
--         certs <- traverse (uncurry selfSignCert) $ zip [serverPKey, clientPKey] validatorInfos
--         server' <- createPeer' serverPKey (validatorInfos !! 0) zippedValidators certs "server" "1.2.3.4"
--         client' <- createPeer' clientPKey (validatorInfos !! 1) zippedValidators certs "client" "5.6.7.8"
--         connection <- createConnection server' client'
--         let clearChainId tx = case tx of
--               MessageTX {} -> tx {transactionChainId = Nothing}
--               ContractCreationTX {} -> tx {transactionChainId = Nothing}
--               PrivateHashTX {} -> tx
--         otx <- (\o -> o {otBaseTx = clearChainId (otBaseTx o), otOrigin = Origin.API}) <$> liftIO (generate arbitrary)
--         serverUnseqs <- liftIO $ newIORef []
--         clientUnseqs <- liftIO $ newIORef []
--         let runForTwoSeconds = timeout 2000000
--             run = runForTwoSeconds $ runConnection connection
--             postTxEvent = threadDelay 500000 >> (atomically $ writeTMChan (_p2pPeerSeqP2pSource server') (P2pTx otx))
--         concurrently_
--           (concurrently_
--             (runForTwoSeconds . runConduit $ sourceTQueue (server' ^. p2pPeerUnseqSource) .| mapM_C (liftIO . modifyIORef serverUnseqs . (:)))
--             (runForTwoSeconds . runConduit $ sourceTQueue (client' ^. p2pPeerUnseqSource) .| mapM_C (liftIO . modifyIORef clientUnseqs . (:)))
--           )
--           (concurrently_ run postTxEvent)
--         serverUnseqs' <- liftIO $ readIORef serverUnseqs
--         clientUnseqs' <- liftIO $ readIORef clientUnseqs
--         let serverUnseqEvs = concat $ (\m -> case m of UnseqEvents es -> es; _ -> []) <$> serverUnseqs'
--         serverUnseqEvs `shouldBe` []
--         let clientTxs = [t | UnseqEvents [IETx _ (IngestTx _ t)] <- clientUnseqs']
--         clientTxs `shouldBe` [otBaseTx otx]
-- 
--     it "should update the round number on every node in the network" $ do
--         privKeys <- traverse (const newPrivateKey) [(1 :: Integer) .. 7]
--         let identities =
--               [ "Admin"
--               , "Person"
--               , "Jeff Bezos"
--               , "Tim Apple"
--               , "Block Buster"
--               , "Zark Muckerberg"
--               , "Larry PageRank"
--               ]
--             validatorsPrivKeys' = privKeys
--             validatorAddresses = fromPrivateKey <$> validatorsPrivKeys'
--             validatorInfos = identities
--             zippedValidators = zip validatorAddresses validatorInfos
--         certs <- traverse (uncurry selfSignCert) $ zip privKeys identities
--         peers <-
--           traverse (\((p, c), (n, i)) -> createPeer' p c zippedValidators certs n i) $
--             zip
--               (zip privKeys identities)
--               [ ("node1", "1.2.3.4"),
--                 ("node2", "5.6.7.8"),
--                 ("node3", "9.10.11.12"),
--                 ("node4", "13.14.15.16"),
--                 ("node5", "17.18.19.20"),
--                 ("node6", "21.22.23.24"),
--                 ("node7", "25.26.27.28")
--               ]
--         let validators' = peers
--         connections' <- traverse
--                           (\(a,b) -> createConnection a b)
--                           [ (peers !! 0, peers !! 1),
--                             (peers !! 0, peers !! 2),
--                             (peers !! 0, peers !! 3),
--                             (peers !! 0, peers !! 4),
--                             (peers !! 0, peers !! 5),
--                             (peers !! 0, peers !! 6),
--                             (peers !! 1, peers !! 2),
--                             (peers !! 1, peers !! 3),
--                             (peers !! 1, peers !! 4),
--                             (peers !! 1, peers !! 5)
--                           ]
--         let runForTwoSeconds = void . timeout 2000000
--             postTimeoutEvent = do
--               threadDelay 1000000
--               for_ validators' $ postEvent (TimerFire 0)
--         runForTwoSeconds $ concurrently_ (runNetworkOld peers connections') postTimeoutEvent
--         ctxs <- atomically $ traverse (readTVar . _p2pTestContext) peers
--         ifor_ ctxs $ \i ctx -> (i, _round . _view <$> _blockstanbulContext (_sequencerContext ctx)) `shouldBe` (i, Just 1 :: Maybe Word256)
-- 
--     it "should update the round number after failing on a divided network first" $ do
--       privKeys <- traverse (const newPrivateKey) [(1 :: Integer) .. 3]
--       let validatorsPrivKeys' = privKeys
--           primaryValidatorsPrivKeys = case validatorsPrivKeys' of
--                                         [] -> error "No private keys generated"
--                                         (p:_) -> [p]
--           primaryValidatorAddresses = fromPrivateKey <$> primaryValidatorsPrivKeys
--           validatorInfoHead = "Admin"
--           validatorInfos = [validatorInfoHead, "Person", "Jeff Bezos"]
--           primaryValidatorInfos = [validatorInfoHead]
--           primaryValidators' = zip primaryValidatorAddresses primaryValidatorInfos
--           zippedValidators = makeValidators $ zip validatorsPrivKeys' validatorInfos
--       certs <- traverse (uncurry selfSignCert) $ zip privKeys validatorInfos
--       peers <-
--         traverse (\((p, c), (n, i)) -> createPeer' p c primaryValidators' certs n i) $
--           zip
--             (zip privKeys validatorInfos)
--             [ ("node1", "1.2.3.4"),
--               ("node2", "5.6.7.8"),
--               ("node3", "9.10.11.12")
--             ]
--       let validators' = peers
--           (primaryValidators, secondaryValidators) = case validators' of
--             [] -> error "No validators created"
--             (v:vs) -> ([v], vs)
--       let runForTwoSeconds = void . timeout 2000000
--           postTimeoutPrimary1 = do
--             threadDelay 1000000
--             for_ primaryValidators $ postEvent (TimerFire 0)
--           postTimeoutPrimary2 = do
--             threadDelay 1000000
--             for_ primaryValidators $ postEvent (TimerFire 1)
--           postTimeoutSecondary = do
--             threadDelay 1000000
--             for_ secondaryValidators $ postEvent (TimerFire 1000)
--       do
--         connections' <- traverse
--                           (\(a,b) -> createConnection a b)
--                           [ (peers !! 0, peers !! 1),
--                             (peers !! 0, peers !! 2),
--                             (peers !! 1, peers !! 2)
--                           ]
--         atomically $
--           modifyTVar'
--             ((peers !! 1) ^. p2pTestContext)
--             ( (sequencerContext . blockstanbulContext . _Just . validators .~ (Set.fromList validatorInfos))
--                 . (sequencerContext . blockstanbulContext . _Just . view . round .~ 1000)
--                 . (x509certMap %~ addValidatorsToCertMap zippedValidators)
--             )
--         atomically $
--           modifyTVar'
--             ((peers !! 2) ^. p2pTestContext)
--             ( (sequencerContext . blockstanbulContext . _Just . validators .~ (Set.fromList validatorInfos))
--                 . (sequencerContext . blockstanbulContext . _Just . view . round .~ 1000)
--                 . (x509certMap %~ addValidatorsToCertMap zippedValidators)
--             )
--         runForTwoSeconds $ concurrently_ (runNetworkOld peers connections') (concurrently_ postTimeoutPrimary1 postTimeoutSecondary)
--         ctxs1 <- atomically $ traverse (readTVar . _p2pTestContext) peers
--         ifor_ ctxs1 $ \i ctx -> (i, _round . _view <$> _blockstanbulContext (_sequencerContext ctx)) `shouldBe` (i, if i == 0 then Just (1 :: Word256) else Just 1000)
--       do
--         connections'' <- traverse
--                            (\(a,b) -> createConnection a b)
--                            [ (peers !! 0, peers !! 1),
--                              (peers !! 0, peers !! 2),
--                              (peers !! 1, peers !! 2)
--                            ]
-- 
--         atomically $
--           modifyTVar'
--             ((peers !! 0) ^. p2pTestContext)
--             ( (sequencerContext . blockstanbulContext . _Just . validators .~ (Set.fromList validatorInfos))
--                 . (x509certMap %~ addValidatorsToCertMap zippedValidators)
--                 . (p2pValidators .~ Set.fromList validatorInfos)
--             )
--         runForTwoSeconds $ concurrently_ (runNetworkOld peers connections'') (concurrently_ postTimeoutPrimary2 postTimeoutSecondary)
--         ctxs2 <- atomically $ traverse (readTVar . _p2pTestContext) peers
--         ifor_ ctxs2 $ \i ctx -> (i, _round . _view <$> _blockstanbulContext (_sequencerContext ctx)) `shouldBe` (i, Just 1001 :: Maybe Word256)
-- 
--     it "can register and unregister a cert on the main chain" $ do
--         -- TODO: use registry at 0x509
--         privKeys <- traverse (const newPrivateKey) [(1 :: Integer) .. 2]
--         let globalAdmin = privKeys !! 0
--             orgAdmin = privKeys !! 1
--             validatorAddresses = fromPrivateKey <$> privKeys
--             validatorInfos = ["Admin", "Person"]
--             zippedValidators = zip validatorAddresses validatorInfos
--         certs <- traverse (uncurry selfSignCert) $ zip privKeys validatorInfos
--         peers <-
--           traverse (\((p, c), (n, i)) -> createPeer' p c zippedValidators certs n i) $
--             zip
--               (zip privKeys validatorInfos)
--               [ ("node1", "1.2.3.4"),
--                 ("node2", "5.6.7.8")
--               ]
--         connections' <- traverse
--                           (\(a,b) -> createConnection a b)
--                           [ (peers !! 0, peers !! 1)
--                           ]
--         let src =
--               [r|
--   
--   contract RegisterCert {
--     event CertificateRegistered(string cert);
--   
--     constructor(address _user, string _cert) {
--       emit CertificateRegistered(_cert);
--     }
--   }
--   |]
--             contractName = "RegisterCert"
--         ts <- liftIO getCurrentMicrotime
--         let testCert1 = "-----BEGIN CERTIFICATE-----\nMIIB0jCCAXegAwIBAgIQeEdWygiiwHQ9e5bfkQVdVTAMBggqhkjOPQQDAgUAMGsx\nEjAQBgNVBAMMCUJsb2NrQXBwczExMC8GA1UECgwoM2JhMzA0YjhlODc0MDViYmYy\nMzg4NzQzYjM5NmEyODEzMTcwYzAwZjEUMBIGA1UECwwLZW5naW5lZXJpbmcxDDAK\nBgNVBAYMA1VTQTAeFw0yMTEwMTkxNTE2MzZaFw0yMjEwMTkxNTE2MzZaMGsxEjAQ\nBgNVBAMMCUJsb2NrQXBwczExMC8GA1UECgwoM2JhMzA0YjhlODc0MDViYmYyMzg4\nNzQzYjM5NmEyODEzMTcwYzAwZjEUMBIGA1UECwwLZW5naW5lZXJpbmcxDDAKBgNV\nBAYMA1VTQTBWMBAGByqGSM49AgEGBSuBBAAKA0IABLsHOfw6jXFjQRAoLVDLwsmr\nKtHn5O6Cisa47lzxV0NfXVJXCcVP2N95GAB5/pmLsmE8rcdLQVBQFLWPjhGoCQ4w\nDAYIKoZIzj0EAwIFAANHADBEAiAChH6dQTLS/F/lNt7JkjMpC0uo6MEFI+zV5hCB\noNnc1gIgaMpLif4qKPRfAFjQJCJR8ORV1PEXf9xBK7XtPONqDQ0=\n-----END CERTIFICATE-----"
--             emptyCert = "-----BEGIN CERTIFICATE-----\nMIIBVDCB+aADAgECAhBPjHUswOXtDsbDeQIsdepkMAwGCCqGSM49BAMCBQAwLDEJ\nMAcGA1UEAwwAMQkwBwYDVQQKDAAxCTAHBgNVBAsMADEJMAcGA1UEBgwAMB4XDTIx\nMDUyNTE1MzQxNVoXDTIyMDUyNTE1MzQxNVowLDEJMAcGA1UEAwwAMQkwBwYDVQQK\nDAAxCTAHBgNVBAsMADEJMAcGA1UEBgwAMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE\n4X1p4KE8cB6vYqKzSHIl+V5fDUC9p0j8OfOQOUhCfkjG1ALuRyP68tTohz9TLPLk\nYCVKrCiueuZJbejnGsp21TAMBggqhkjOPQQDAgUAA0gAMEUCIQCVtizg/N3MBdLi\nfHto7tqu1ia6cZpMI/G2bLWSPErK9AIgcBw+S8iVqSjh61CkgBAS066Z7M/W9eeY\n+sm9OKHDfQQ=\n-----END CERTIFICATE-----"
--             args addr cert = "(0x" <> T.pack (formatAddressWithoutColor addr) <> ", \"" <> cert <> "\")"
--             utx =
--               U.UnsignedTransaction
--                 { U.unsignedTransactionNonce = Nonce 0,
--                   U.unsignedTransactionGasPrice = Wei 1,
--                   U.unsignedTransactionGasLimit = Gas 1000000000,
--                   U.unsignedTransactionTo = Nothing,
--                   U.unsignedTransactionValue = Wei 0,
--                   U.unsignedTransactionInitOrData = Code $ BC.pack src,
--                   U.unsignedTransactionChainId = Nothing
--                 }
--             txMd addr cert = M.fromList [("src", src), ("name", contractName), ("args", args addr cert)]
--             mkTx pSigner pCert n =
--               let utx' = utx {U.unsignedTransactionNonce = Nonce n}
--                   addr = fromPrivateKey pCert
--                in mkSignedTx pSigner utx' $ txMd addr testCert1
--             mkEmptyTx pSigner pCert n =
--               let utx' = utx {U.unsignedTransactionNonce = Nonce n}
--                   addr = fromPrivateKey pCert
--                in mkSignedTx pSigner utx' $ txMd addr emptyCert
--             toIetx = IETx ts . IngestTx Origin.API
--             routine = do
--               threadDelay 200000
--               for_ peers $ postEvent (TimerFire 0)
--               threadDelay 200000
--               for_ peers $ postEvent (TimerFire 1)
--               threadDelay 200000
--               let tx1 = mkTx globalAdmin orgAdmin 0
--                   tx2 = mkEmptyTx orgAdmin orgAdmin 0
--               flip postEvent (peers !! 0) $ UnseqEvents [toIetx tx1]
--               threadDelay 1000000
--               flip postEvent (peers !! 0) $ UnseqEvents [toIetx tx2]
--         void . timeout 5000000 $ concurrently_ (runNetworkOld peers connections') routine
--         ctxs1 <- atomically $ traverse (readTVar . _p2pTestContext) peers
--         for_ ctxs1 $ \ctx -> (ctx ^. x509certMap) `shouldNotBe` M.empty
-- 
--     it "can add vote in a new validator" $ do
--         privKeys <- traverse (const newPrivateKey) [(1 :: Integer) .. 3]
--         let validatorAddresses = fromPrivateKey <$> privKeys
--             validatorInfos =
--               [ "Admin",
--                 "Person",
--                 "Jeff Bezos"
--               ]
--             zippedValidators = take 1 $ zip validatorAddresses validatorInfos
--         certs <- traverse (uncurry selfSignCert) $ zip privKeys validatorInfos
--         peers <-
--           traverse (\((p, c), (n, i)) -> createPeer' p c zippedValidators certs n i) $
--             zip
--               (zip privKeys validatorInfos)
--               [ ("node1", "1.2.3.4"),
--                 ("node2", "5.6.7.8"),
--                 ("node3", "9.10.11.12")
--               ]
--         connections' <- traverse
--                           (\(a,b) -> createConnection a b)
--                           [ (peers !! 0, peers !! 1),
--                             (peers !! 0, peers !! 2),
--                             (peers !! 1, peers !! 2)
--                           ]
--         ts <- liftIO getCurrentMicrotime
--         let toIetx = IETx ts . IngestTx Origin.API
--             args = "(\"Microsoft\",\"Sales\",\"Person\")"
--             txMd = M.fromList [("funcName", "voteToAddValidator"), ("args", args)]
--             setupTx =
--               U.UnsignedTransaction
--                 { U.unsignedTransactionNonce = Nonce 0,
--                   U.unsignedTransactionGasPrice = Wei 1,
--                   U.unsignedTransactionGasLimit = Gas 1000000000,
--                   U.unsignedTransactionTo = Just $ Address 0x100,
--                   U.unsignedTransactionValue = Wei 0,
--                   U.unsignedTransactionInitOrData = Code "",
--                   U.unsignedTransactionChainId = Nothing
--                 }
--             signedTx = mkSignedTx (privKeys !! 0) setupTx txMd
-- 
--             routine = do
--               threadDelay 200000
--               for_ peers $ postEvent (TimerFire 0)
--               threadDelay 200000
--               flip postEvent (peers !! 0) $ UnseqEvents [toIetx signedTx]
-- 
--         void . timeout 5000000 $ concurrently_ (runNetworkOld peers connections') routine
--         ctxs <- atomically $ traverse (readTVar . _p2pTestContext) peers
--         ifor_ ctxs $ \i ctx -> (i, Set.size . _validators <$> _blockstanbulContext (_sequencerContext ctx)) `shouldBe` (i, Just 2)
-- 
--     it "can add and remove vote in a new validator" $ do
--         privKeys <- traverse (const newPrivateKey) [(1 :: Integer) .. 3]
--         let validatorAddresses = fromPrivateKey <$> privKeys
--             validatorInfos =
--               [ "Admin"
--               , "Person"
--               , "Jeff Bezos"
--               ]
--             zippedValidators = take 1 $ zip validatorAddresses validatorInfos
--         certs <- traverse (uncurry selfSignCert) $ zip privKeys validatorInfos
--         peers <-
--           traverse (\((p, c), (n, i)) -> createPeer' p c zippedValidators certs n i) $
--             zip
--               (zip privKeys validatorInfos)
--               [ ("node1", "1.2.3.4"),
--                 ("node2", "5.6.7.8"),
--                 ("node3", "9.10.11.12")
--               ]
--         connections' <- traverse
--                           (\(a,b) -> createConnection a b)
--                           [ (peers !! 0, peers !! 1),
--                             (peers !! 0, peers !! 2),
--                             (peers !! 1, peers !! 2)
--                           ]
--         ts <- liftIO getCurrentMicrotime
--         let toIetx = IETx ts . IngestTx Origin.API
--             args = "(\"Microsoft\",\"Sales\",\"Person\")"
--             addTxMd = M.fromList [("funcName", "voteToAddValidator"), ("args", args)]
--             addTx =
--               U.UnsignedTransaction
--                 { U.unsignedTransactionNonce = Nonce 0,
--                   U.unsignedTransactionGasPrice = Wei 1,
--                   U.unsignedTransactionGasLimit = Gas 1000000000,
--                   U.unsignedTransactionTo = Just $ Address 0x100,
--                   U.unsignedTransactionValue = Wei 0,
--                   U.unsignedTransactionInitOrData = Code "",
--                   U.unsignedTransactionChainId = Nothing
--                 }
--             signedAddTx = signMsg (privKeys !! 0) addTx addTxMd
--             removeTxMd = M.fromList [("funcName", "voteToRemoveValidator"), ("args", args)]
--             removeTx =
--               U.UnsignedTransaction
--                 { U.unsignedTransactionNonce = Nonce 1,
--                   U.unsignedTransactionGasPrice = Wei 1,
--                   U.unsignedTransactionGasLimit = Gas 1000000000,
--                   U.unsignedTransactionTo = Just $ Address 0x100,
--                   U.unsignedTransactionValue = Wei 0,
--                   U.unsignedTransactionInitOrData = Code "",
--                   U.unsignedTransactionChainId = Nothing
--                 }
--             signedRemoveTx = mkSignedTx (privKeys !! 0) removeTx removeTxMd
-- 
--             routine1 = do
--               threadDelay 200000
--               for_ peers $ postEvent (TimerFire 0)
--               threadDelay 200000
--               flip postEvent (peers !! 0) $ UnseqEvents [toIetx signedAddTx]
--               threadDelay 5000000
--               ctxs1 <- atomically $ traverse (readTVar . _p2pTestContext) peers
--               ifor_ ctxs1 $ \i ctx -> (i, Set.size . _validators <$> _blockstanbulContext (_sequencerContext ctx)) `shouldBe` (i, Just 2)
--               threadDelay 200000
--               postEvent (TimerFire 1) (peers !! 0)
--               threadDelay 200000
--               postEvent (TimerFire 2) (peers !! 0)
--               threadDelay 200000
--               flip postEvent (peers !! 0) $ UnseqEvents [toIetx signedRemoveTx]
-- 
--         void . timeout 10000000 $ concurrently_ (runNetworkOld peers connections') routine1
--         ctxs2 <- atomically $ traverse (readTVar . _p2pTestContext) peers
--         ifor_ ctxs2 $ \i ctx -> (i, Set.size . _validators <$> _blockstanbulContext (_sequencerContext ctx)) `shouldBe` (i, Just 1)
-- 
--     it "can sync a new node after voting in a new validator" $ do
--         privKeys <- traverse (const newPrivateKey) [(1 :: Integer) .. 4]
--         let validatorAddresses = fromPrivateKey <$> privKeys
--             validatorInfos =
--               [ "Admin",
--                 "Person",
--                 "Jeff Bezos",
--                 "Mark Zuckerberg"
--               ]
--             zippedValidators = take 2 $ zip validatorAddresses validatorInfos
--         certs <- traverse (uncurry selfSignCert) $ zip privKeys validatorInfos
--         peers <-
--           traverse (\((p, c), (n, i)) -> createPeer' p c zippedValidators certs n i) $
--             zip
--               (zip privKeys validatorInfos)
--               [ ("node1", "1.2.3.4"),
--                 ("node2", "5.6.7.8"),
--                 ("node3", "9.10.11.12"),
--                 ("node4", "13.14.15.16")
--               ]
--         connections' <- traverse
--                           (\(a,b) -> createConnection a b)
--                           [ (peers !! 0, peers !! 1),
--                             (peers !! 0, peers !! 2),
--                             (peers !! 1, peers !! 2),
--                             (peers !! 0, peers !! 3),
--                             (peers !! 1, peers !! 3),
--                             (peers !! 2, peers !! 3)
--                           ]
--         ts <- liftIO getCurrentMicrotime
--         let toIetx = IETx ts . IngestTx Origin.API
--             args = "(\"Amazon\",\"Product\",\"Jeff Bezos\")"
--             txMd = M.fromList [("funcName", "voteToAddValidator"), ("args", args)]
--             setupTx =
--               U.UnsignedTransaction
--                 { U.unsignedTransactionNonce = Nonce 0,
--                   U.unsignedTransactionGasPrice = Wei 1,
--                   U.unsignedTransactionGasLimit = Gas 1000000000,
--                   U.unsignedTransactionTo = Just $ Address 0x100,
--                   U.unsignedTransactionValue = Wei 0,
--                   U.unsignedTransactionInitOrData = Code "",
--                   U.unsignedTransactionChainId = Nothing
--                 }
--             signedTx = mkSignedTx (privKeys !! 0) setupTx txMd
--             mainChainSrc =
--               [r|
--   contract B {
--     uint y;
--   
--     constructor() {
--       y = 47;
--     }
--   }
--   |]
--             mainChainContractName = "B"
--             mainChainArgs = "()"
--             mainChainUtx =
--               U.UnsignedTransaction
--                 { U.unsignedTransactionNonce = Nonce 0,
--                   U.unsignedTransactionGasPrice = Wei 1,
--                   U.unsignedTransactionGasLimit = Gas 1000000000,
--                   U.unsignedTransactionTo = Nothing,
--                   U.unsignedTransactionValue = Wei 0,
--                   U.unsignedTransactionInitOrData = Code $ BC.pack mainChainSrc,
--                   U.unsignedTransactionChainId = Nothing
--                 }
--             mainChainTxMd = M.fromList [("src", mainChainSrc), ("name", mainChainContractName), ("args", mainChainArgs)]
--             mkMainChainTx n =
--               let utx = mainChainUtx {U.unsignedTransactionNonce = Nonce n}
--                in mkSignedTx (privKeys !! 1) utx mainChainTxMd
--             mainChainRoutine n = do
--               threadDelay 200000
--               flip postEvent (peers !! 1) $ UnseqEvents [toIetx $ mkMainChainTx n]
--               mainChainRoutine $ n + 1
--             routine = do
--               threadDelay 200000
--               for_ peers $ postEvent (TimerFire 0)
--               threadDelay 1000000
--               flip postEvent (peers !! 0) $ UnseqEvents [toIetx signedTx]
--               threadDelay 10000000
--               runNetworkOld (drop 3 peers) (drop 3 connections')
--   
--         void . timeout 20000000 $ concurrently_ (runNetworkOld (take 3 peers) (take 3 connections')) (concurrently_ (void . timeout 4000000 $ mainChainRoutine 0) routine)
--         ctxs <- atomically $ traverse (readTVar . _p2pTestContext) peers
--         ifor_ ctxs $ \i ctx -> (i, Set.size . _validators <$> _blockstanbulContext (_sequencerContext ctx)) `shouldBe` (i, Just 3)
--     it "will throw an exception if the handshake times out" $ do
--         serverPKey <- newPrivateKey
--         clientPKey <- newPrivateKey
--         let validatorAddresses = fromPrivateKey <$> [serverPKey, clientPKey]
--             validatorInfos = ["GrumpyCat", "Aya"]
--             zippedValidators = zip validatorAddresses validatorInfos
--         certs <- traverse (uncurry selfSignCert) $ zip [serverPKey, clientPKey] validatorInfos
--         server' <- createPeer' serverPKey (validatorInfos !! 0) zippedValidators certs "server" "1.1.1.1"
--         client' <- createPeer' clientPKey (validatorInfos !! 1) zippedValidators certs "client" "2.2.2.2"
--         connection <- createGermophobicConnection server' client'
--         void . timeout (3 * 1000 * 1000) $ runConnection connection
--         clientExcept <- readTVarIO $ connection ^. clientException
--         clientExcept `shouldBe` Just (toException $ HandshakeException "handshake timed out")
--     it "will not get a stateroot mismatch if an exception occurs in the bagger" $ do
--         privKey <- newPrivateKey
--         let validatorAddress = fromPrivateKey privKey
--             validatorInfo = "Admin"
--         cert <- selfSignCert privKey validatorInfo 
--         validator <- createPeer' privKey validatorInfo [(validatorAddress, validatorInfo)] [cert] "node1" "1.1.1.1"
--         ts <- liftIO getCurrentMicrotime
--         let toIetx = IETx ts . IngestTx Origin.API
--             args = "(\"123\")" --dummy address
--             txMd = M.fromList [("funcName", "getUserCert"), ("args", args)]
--             tx n =
--               U.UnsignedTransaction
--                 { U.unsignedTransactionNonce = Nonce n,
--                   U.unsignedTransactionGasPrice = Wei 1,
--                   U.unsignedTransactionGasLimit = Gas 1000000000,
--                   U.unsignedTransactionTo = Just $ Address 0x509,
--                   U.unsignedTransactionValue = Wei 0,
--                   U.unsignedTransactionInitOrData = Code "",
--                   U.unsignedTransactionChainId = Nothing
--                 }
--             signedTx n = mkSignedTx privKey (tx n) txMd
-- 
--             reachNonceLim = do
--               for [0..10] (\n -> flip postEvent validator $ UnseqEvents [toIetx $ signedTx n]) --nonce limit is 10; will trigger]
-- 
--         void . timeout 10000000 $ concurrently_ (runNode validator) reachNonceLim
--         ctx <- atomically $ readTVar . _p2pTestContext $ validator
--         bestBlockNumber (_bestBlock ctx) `shouldNotBe` 0 --create at least 1 block
--     it "will not add a canonical block that causes a stateroot mismatch" $ do
--         privKeys <- traverse (const newPrivateKey) [(1 :: Integer) .. 2]
--         let validatorAddresses = fromPrivateKey <$> privKeys
--             validatorInfos = [ "Node1", "Node2"]
--             zippedValidators = zip validatorAddresses validatorInfos
--         certs <- traverse (uncurry selfSignCert) $ zip privKeys validatorInfos
--         peers <-
--           traverse (\((p, c), (n, i)) -> createPeer' p c zippedValidators certs n i) $
--             zip
--               (zip privKeys validatorInfos)
--               [ ("node1", "1.2.3.4"),
--                 ("node2", "5.6.7.8")
--               ]
--         
--         ts <- liftIO getCurrentMicrotime
--         let toIetx = IETx ts . IngestTx Origin.API
--             src = "contract Test{}"
--             txMd =  M.fromList [("src", src), ("name", "Test"), ("args", "()")]
--             tx n =
--               U.UnsignedTransaction
--                 { U.unsignedTransactionNonce = Nonce n,
--                   U.unsignedTransactionGasPrice = Wei 1,
--                   U.unsignedTransactionGasLimit = Gas 1000000000,
--                   U.unsignedTransactionTo = Nothing,
--                   U.unsignedTransactionValue = Wei 0,
--                   U.unsignedTransactionInitOrData = Code $ BC.pack src,
--                   U.unsignedTransactionChainId = Nothing
--                 }
--             signedTx p n = mkSignedTx (privKeys !! p) (tx n) txMd
--             routine n = do
--               flip postEvent (peers !! 0) $ UnseqEvents [toIetx $ signedTx 1 n]
--               threadDelay 500000
--               routine (n + 1)
--         
--         let corruptPBFT p2pev = case p2pev of 
--               -- sneakily add on an extra tx
--               P2pBlockstanbul (WireMessage auth (Preprepare v b)) -> P2pBlockstanbul (WireMessage auth (Preprepare v b{blockReceiptTransactions = (signedTx 0 0) : blockReceiptTransactions b}))
--               msg -> msg
--         conn <- createConnectionWithModifications (peers !! 0) (peers !! 1) corruptPBFT corruptPBFT -- oh no someone is corrupting msgs! :0
--         
--         void . timeout 2000000 $ concurrently_ (runNetworkOld peers [conn]) (routine 0)
--         ctx <- atomically $ readTVar . _p2pTestContext $ peers !! 0
--         bestBlockNumber (_bestBlock ctx) `shouldBe` -1 -- no canonical blocks added (val starts at -1, not 0)
-- 
--   describe "Testing contracts that call other contracts by addresss" $ do
--     --Note to the developer
--     --These contracts are shoved into the txrIndexer ..... Take this into consideration
--     it "can call delegatecall function and not change state variables of contract being called" $ do
--         privKeys <- traverse (const newPrivateKey) [(1 :: Integer) .. 4]
--         let validatorAddresses = fromPrivateKey <$> privKeys
--             validatorInfos =
--               [ "Admin"
--               , "Person"
--               , "Jeff Bezos"
--               ]
--             zippedValidators = take 2 $ zip validatorAddresses validatorInfos
--         certs <- traverse (uncurry selfSignCert) $ zip privKeys validatorInfos
--         peers <-
--           traverse (\((p, c), (n, i)) -> createPeer' p c zippedValidators certs n i) $
--             zip
--               (zip privKeys validatorInfos)
--               [ ("node1", "1.2.3.4"),
--                 ("node2", "5.6.7.8"),
--                 ("node3", "9.10.11.12")
--               ]
--         connections' <- traverse
--                           (\(a,b) -> createConnection a b)
--                           [ (peers !! 0, peers !! 1),
--                             (peers !! 0, peers !! 2),
--                             (peers !! 1, peers !! 2)
--                           ]
--         ts <- liftIO getCurrentMicrotime
--         let toIetx = IETx ts . IngestTx Origin.API
--             args = "(\"Amazon\",\"Product\",\"Jeff Bezos\")"
--             txMd = M.fromList [("funcName", "voteToAddValidator"), ("args", args)]
--             setupTx =
--               U.UnsignedTransaction
--                 { U.unsignedTransactionNonce = Nonce 0,
--                   U.unsignedTransactionGasPrice = Wei 1,
--                   U.unsignedTransactionGasLimit = Gas 1000000000,
--                   U.unsignedTransactionTo = Just $ Address 0x100,
--                   U.unsignedTransactionValue = Wei 0,
--                   U.unsignedTransactionInitOrData = Code "",
--                   U.unsignedTransactionChainId = Nothing
--                 }
--             signedTx = mkSignedTx (privKeys !! 0) setupTx txMd
--   
--             mainChainSrc =
--               [r|
--   contract B {
--     uint y;
--     string powPow = "Example of Different States";
--   
--     constructor() {
--       y = 47;
--     }
--     function gg() returns(string) {return "Nice I did this";}
--     function gg(int _x) returns(string) { return "Nice I did this taking an int arg";}
--     function gg(int _x, int _b) returns(int) { return _x + _b;}
--     function () external {y +=3; }
--   }
--   |]
--             mainChainContractName = "B"
--             mainChainArgs = "()"
--             mainChainSrcC =
--               [r|
--   contract C {
--     string powPow = "Other Example of different states";
--     string getMoney;
--     int x;
--     uint y = 2;
--     string yes;
--     constructor(address _add) {
--       getMoney = address(_add).delegatecall("gg()");
--       x = address(_add).delegatecall("gg(int, int)", 333333333, 333333333);
--       yes =  _add.delegatecall("gg()");
--       _add.delegatecall("ggg()");
--       //1.delegatecall("ggg()"); //This will make error.... because we shouldn't be able to call delegate on anything but an address type 
--     }
--   }
--   |]
--             mainChainContractNameC = "C"
--             mainChainUtx =
--               U.UnsignedTransaction
--                 { U.unsignedTransactionNonce = Nonce 1,
--                   U.unsignedTransactionGasPrice = Wei 1,
--                   U.unsignedTransactionGasLimit = Gas 1000000000,
--                   U.unsignedTransactionTo = Nothing,
--                   U.unsignedTransactionValue = Wei 0,
--                   U.unsignedTransactionInitOrData = Code $ BC.pack mainChainSrc,
--                   U.unsignedTransactionChainId = Nothing
--                 }
--             mainChainUtx2 =
--               U.UnsignedTransaction
--                 { U.unsignedTransactionNonce = Nonce 2,
--                   U.unsignedTransactionGasPrice = Wei 1,
--                   U.unsignedTransactionGasLimit = Gas 1000000000,
--                   U.unsignedTransactionTo = Nothing,
--                   U.unsignedTransactionValue = Wei 0,
--                   U.unsignedTransactionInitOrData = Code $ BC.pack mainChainSrcC,
--                   U.unsignedTransactionChainId = Nothing
--                 }
--             mainChainTxMd = M.fromList [("src", mainChainSrc), ("name", mainChainContractName), ("args", mainChainArgs)]
--             mkMainChainTx =
--               let utx = mainChainUtx {U.unsignedTransactionNonce = Nonce 1}
--                in mkSignedTx (privKeys !! 1) utx mainChainTxMd
--   
--             mainChainRoutine n = do
--               threadDelay 200000
--               flip postEvent (peers !! 1) $ UnseqEvents [toIetx $ mkMainChainTx]
--               let x = getNewAddress_unsafe (fromPrivateKey (privKeys !! 1)) 1
--   
--               let args' = "(0x" <> T.pack (formatAddressWithoutColor x) <> ")"
--               let mainChainTxMdC = M.fromList [("src", mainChainSrcC), ("name", mainChainContractNameC), ("args", args')]
--               let mkMainChainTx2 n' =
--                     let utx = mainChainUtx2 {U.unsignedTransactionNonce = Nonce n'}
--                      in mkSignedTx (privKeys !! 1) utx mainChainTxMdC
--               flip postEvent (peers !! 1) $ UnseqEvents [toIetx $ mkMainChainTx2 n]
--   
--               mainChainRoutine $ n + 1
--   
--             routine = do
--               threadDelay 200000
--               for_ peers $ postEvent (TimerFire 0)
--               threadDelay 1000000
--               flip postEvent (peers !! 0) $ UnseqEvents [toIetx signedTx]
--               threadDelay 10000000
--               runNetworkOld (drop 3 peers) (drop 3 connections')
--   
--         void . timeout 20000000 $ concurrently_ (runNetworkOld (take 3 peers) (take 3 connections')) (concurrently_ (void . timeout 4000000 $ mainChainRoutine 0) routine)
--   
--         bHash <- fmap (bestBlockHash . _bestBlock) . readTVarIO . _p2pTestContext $ peers !! 1
--         let varsToLookUp = [".powPow", ".getMoney", ".y"]
--         (contractA'sStateVars, contractB'sStateVars) <- runNoLoggingT . runResourceT . flip runReaderT (peers !! 1) $ do
--           let contractLookup n = map (getNewAddress_unsafe (fromPrivateKey (privKeys !! 1)) n,) varsToLookUp :: [(Address, BC.ByteString)]
--               lookupStorageVals = traverse $ fmap (fmap fromVal) . VMC.withCurrentBlockHash bHash . A.lookup (A.Proxy @RawStorageValue)
--           on (liftA2 (,)) (lookupStorageVals . contractLookup) 1 2
--   
--         contractA'sStateVars `shouldBe` [Just (BString "Example of Different States"), Nothing, Just (BInteger 47)]
--         contractB'sStateVars `shouldBe` [Just (BString "Other Example of different states"), Just (BString "Nice I did this"), Just (BInteger 5)]
