name: x509-certs
version: 0.0.1
build-type: Simple
author: dpmesko
maintainer:   daniel@blockapps.net
synopsis: A Haskell x509 certificate generator
category:      Data Structures
license: Apache-2.0
description:
    A Haskell x509 certificate generator

dependencies:
  - base >= 4 && < 5


ghc-options: -Wall -Werror


library:
  source-dirs: src
  ghc-options: -Wall -O2 
  dependencies:
  - asn1-encoding
  - asn1-types
  - bytestring
  - cereal
  - containers
  - cryptonite
  - ecdsa
  - hourglass
  - memory
  - pem
  - random
  - time
  - transformers
  - secp256k1-haskell
  - x509
#   - x509-util
#  - x509-store
#  - x509-validation


executables:
  x509Test:
    source-dirs: exec_src/
    main: x509Test.hs
    dependencies:
      - cryptonite
      - bytestring
      - hflags
      - secp256k1-haskell
      - x509-certs

tests:
  x509-test:
    main: Spec.hs
    source-dirs: test/
    dependencies:
      - x509-certs
      - bytestring
      - cryptonite
      - secp256k1-haskell
      - x509
      - x509-validation
      - hspec
      - QuickCheck
