#!/bin/bash
set -e

function setEnv {
  [[ -n ${!1} ]] || eval $1=$2
  echo "$1 = ${!1}"
}

setEnv blocHost localhost
setEnv blocPort 8000
setEnv stratoUrl "http://tester13.eastus.cloudapp.azure.com/strato-api/eth/v1.2"

function customHttp { # set behavior of http I like....  crash on error, print body to stderr, timeout longer

  set +e
  output=`http -b --check-status --timeout=60 "$@"`
  returnVal=$?
  set -e


  if [ "$returnVal" == "0" ]
  then
    echo "$output"
  else
    echo "$output" >&2
    exit $returnVal
  fi
}

echo "#################################################"
echo "# Creating a new address and running the faucet #"
echo "#################################################"

address=`customHttp --form http://$blocHost:$blocPort/users/fred password=qqqq faucet=1`

echo "Here are the details of the new address '$address':"

customHttp $stratoUrl/account?address=$address | jq

echo ""

#address=c4b355bd46775ccaffd3a70a6c88727e5f99646f

request='
{
  "password":"qqqq",
  "args": {},
  "value": 0,
  "txParams":{},
  "contract":"SimpleStorage",
  "src": "contract SimpleStorage { uint storedData; function set(uint x) { storedData = x; } function get() returns (uint retVal) { return storedData; } }"
}'

echo "########################"
echo "# Uploading a contract #"
echo "########################"

echo "$request" | customHttp POST http://$blocHost:$blocPort/users/fred/$address/contract "Accept: */*"

echo ""

echo "##################################"
echo "# querying state in new contract #"
echo "##################################"

customHttp http://$blocHost:$blocPort/contracts/SimpleStorage/Latest/state
