#!/usr/bin/env sh
set -x
set -e

BRANCH=$(git branch | grep -e "^*" | cut -d ' ' -f 2)
git push origin ${BRANCH}
TOKEN="rdaABqoRvQLjQga"
URL="https://jenkins.blockapps.net/buildByToken/buildWithParameters?job=STRATO_test&token=${TOKEN}&PLATFORM_BRANCH_NAME=${BRANCH}"
echo curl -X POST -L --insecure $URL
curl -X POST -L --insecure $URL
