#!/usr/bin/env bash

if [ $# -lt 2 ]
then
  echo "usage: reflash_exe <base_image> <exe> [<target>]"
  exit 2
fi

set -x
set -e

BASE_IMAGE=$1
EXE=$2
TARGET=${3:-${EXE}}
IMAGE_TAG="flash_${EXE}"
BUILD_DIR="/tmp/flash/${EXE}/"
echo $BASE_IMAGE $EXE $TARGET
mkdir -p ${BUILD_DIR}
stack install ${TARGET}
cat << EOF >| ${BUILD_DIR}/Dockerfile
FROM ${BASE_IMAGE}
COPY ./${EXE} /usr/bin/
EOF
cp -f $(stack exec which ${EXE}) ${BUILD_DIR}
docker build -t ${IMAGE_TAG} ${BUILD_DIR}
echo "Image ${IMAGE_TAG} created"
