name:        strato-index
author:      Jamshid
copyright:   2016 Blockapps
description: Please see README.md
version:     0.1.0.0
github: blockapps/strato-platform/core-strato/strato-index

ghc-options: -threaded -rtsopts -with-rtsopts=-N

dependencies:
  - base
  - binary
  - blockapps-data
  - blockapps-datadefs
  - blockapps-milena
  - blockapps-util
  - bytestring
  - clock
  - containers
  - format
  - hedis
  - hflags
  - persistent
  - persistent-postgresql
  - resourcet
  - strato-conf
  - strato-model
  - strato-redis-blockdb
  - seqevents
  - text
  - transformers

library:
  source-dirs: src/

executables:
  strato-api-indexer:
    main: ApiIndexerMain.hs
    source-dirs: exec_src
    dependencies:
      - strato-index
    other-modules: []

  strato-p2p-indexer:
    main: P2PIndexerMain.hs
    source-dirs: exec_src
    dependencies:
      - strato-index
    other-modules: []

  strato-txr-indexer:
    main: TxrIndexerMain.hs
    source-dirs: exec_src/
    dependencies:
      - strato-index
    other-modules: []
