name: blockstanbul
ghc-options: -Wall -Werror

dependencies:
  - base
  - blockapps-data
  - blockapps-util
  - conduit-combinators
  - strato-model

library:
  source-dirs: src/

tests:
  blockstanbul-test:
    main: Main.hs
    source-dirs: test/
    dependencies:
      - blockstanbul
      - hspec
      - QuickCheck

