name: blockstanbul
ghc-options: -Wall -Werror

dependencies:
  - aeson
  - base
  - binary
  - blockapps-data
  - blockapps-datadefs
  - blockapps-haskoin
  - bytestring
  - containers
  - conduit
  - conduit-combinators
  - cross-monitoring
  - crypto-api
  - cryptonite
  - deepseq
  - derive
  - ethereum-encryption
  - ethereum-rlp
  - ghc
  - fast-ecrecover
  - lens
  - mtl
  - QuickCheck
  - servant-client
  - servant-server
  - stm
  - stm-chans
  - strato-model
  - text
  - transformers
  - monad-logger
  - wai-extra
  - wai-middleware-prometheus
  - wai
  - warp
  - http-client
  - prometheus-client

library:
  source-dirs: src/

executables:
  blockstanbul-vote:
    source-dirs: exec-src/
    main: Main.hs
    dependencies:
      - blockstanbul
      - base16-bytestring
      - base64-bytestring
      - hflags
      - extra

tests:
  blockstanbul-test:
    main: Main.hs
    source-dirs: test/
    dependencies:
      - base16-bytestring
      - blockstanbul
      - hspec
      - hspec-expectations-lifted
      - time

benchmarks:
  one-node:
    source-dirs: bench/
    main: OneNode.hs
    dependencies:
      - blockstanbul
      - criterion
