#!/bin/bash

if [[ $# < 3 ]]; then
    echo >&2 "$0 <remote machine> <remote machine os> <live|dev> [private]"
    exit 1
fi

remote=$1
distro=$2
shift

setup_scripts="setup setup_functions.sh setup_$distro.sh"

scp $setup_scripts strato-files.tar.gz "$remote:~/" &&
ssh "$remote" ./setup "$@"
