#!/bin/bash
# Should really only be called by build-remote-system
distro=$1
mode=$2
priv=$3
shift

. setup_functions.sh &&
# the setup_$1.sh script must define:
# - get_dependencies() (returning an exit status)
# - db_conf_dir (where pg_hba.conf lives)
. setup_$distro.sh &&
get_dependencies &&
get_mgit &&
build_ethereumH &&
setup_dbs "$mode" &&
install_blockappsjs &&
if [[ "$priv" == "private" ]]; then setup_nginx; fi &&
copy_files "$@" &&
rm $build_log setup setup_functions.sh setup_$distro.sh ||
info "Setup failed!  See $build_log."
