name: blockapps-tools
version: 0.0.1
build-type: Simple
author: Jamshid
license-file:  LICENSE
maintainer:    jamshidnh@gmail.com
synopsis: A Haskell version of an Ethereum client
category:      Data Structures
license: Apache-2.0
description:
              Tool to query the ethereum databases

dependencies:
  - base >= 4 && < 5
  - aeson
  - ansi-wl-pprint
  - base16-bytestring
  - base64-bytestring
  - binary
  - blockapps-data
  - blockapps-datadefs
  - blockapps-haskoin
  - blockapps-mpdbs
  - blockapps-privacy
  - blockapps-util
  - blockstanbul
  - bytestring
  - cmdargs
  - common-log
  - conduit
  - data-default
  - ethereum-discovery
  - ethereum-encryption
  - ethereum-rlp
  - filepath
  - format
  - hflags
  - lens
  - leveldb-haskell
  - memory
  - merkle-patricia-db
  - monad-alter
  - blockapps-milena
  - monad-loops
  - nibblestring
  - persistent
  - persistent-postgresql
  - resourcet
  - time
  - strato-conf
  - seqevents
  - strato-index
  - strato-redis-blockdb
  - strato-model
  - strato-p2p
  - strato-sequencer
  - strato-statediff
  - text
  - transformers
  - hedis
  - unliftio

library:
  source-dirs: src/

executables:
  queryStrato:
    source-dirs: exec_src/
    main: Main.hs
    other-modules: []
    dependencies:
      - blockapps-tools

  b16decode:
    source-dirs: exec_src/
    main: B16Decode.hs
    dependencies:
      - base >= 4 && < 5
      - base16-bytestring
      - bytestring
    other-modules: []

  modifyDate:
    source-dirs: exec_src/
    main: ModifyDate.hs
    dependencies:
      - base >=4 && <5
      - base16-bytestring
      - bytestring
      - hflags
      - time
    other-modules: []

tests:
  blockapps-tools-test:
    source-dirs: test/
    main: KafkaSpec.hs
    dependencies:
      - QuickCheck
      - blockapps-tools
      - bytestring-arbitrary
      - hspec
      - temporary
