// ROOMS 
export const LAST_BLOCK_NUMBER = 'LAST_BLOCK_NUMBER'
export const TRANSACTIONS_COUNT = 'TRANSACTIONS_COUNT'
export const USERS_COUNT = 'USERS_COUNT'
export const PEERS = 'PEERS'
export const CONTRACTS_COUNT = 'CONTRACTS_COUNT'

