#!/bin/bash

#On error, crash and paint the error red
set -e
exec 2> >(while read line; do echo -e "\e[01;31m$line\e[0m" >&2; done)

genesisName=${1:-stablenet}

echo "Stopping kafka"
PIDS=$(ps ax | grep -i 'kafka\.Kafka' | grep java | grep -v grep | awk '{print $1}')
if [ -z "$PIDS" ]; then
    echo "kafka already down"
else
    kill -SIGTERM $PIDS
fi
sleep 6

echo "Stopping Zookeeper"
PIDS=$(ps ax | grep java | grep -i QuorumPeerMain | grep -v grep | awk '{print $1}')
if [ -z "$PIDS" ]; then
    echo "zookeeper already down"
else
    sudo service zookeeper stop
fi

echo "Clearing all databases"
rm -rf ~/.ethereumH
mkdir -p ~/.ethereumH/conf/
cp ../blockapps-data/*Genesis.json ~/.ethereumH/conf/
cp ../strato-conf/ethconf.yaml ~/.ethereumH
cp ../strato-conf/peers.yaml ~/.ethereumH
sudo -u postgres dropdb eth
sudo -u postgres createdb eth

echo "Starting Zookeeper"
sudo service zookeeper start
sleep 2

echo "Starting kafka"
~/kafka/doit 
sleep 2

echo "Initializing the database"
strato-setup --genesisBlockName=$genesisName
