user root;
worker_processes  1;

error_log  /tmp/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       mime.types;

    default_type  application/octet-stream;

    log_format json_combined escape=json
      '{'
        '"time_local":"$time_local",'
        '"msec":"$msec",'
        '"remote_addr":"$remote_addr",'
        '"request_method":"$request_method",'
        '"request":"$request",'
        '"status": "$status",'
        '"request_time":"$request_time",'
        '"request_length":"$request_length",'
        '"bytes_sent":"$bytes_sent",'
        '"body_bytes_sent":"$body_bytes_sent",'
        '"http_user_agent":"$http_user_agent",'
        '"http_referrer":"$http_referer",'
        '"remote_user":"$remote_user",'
        '"upstream_addr":"$upstream_addr",'
        '"upstream_status":"$upstream_status",'
        '"upstream_response_time":"$upstream_response_time",'
        '"upstream_connect_time":"$upstream_connect_time",'
        '"upstream_header_time":"$upstream_header_time"'
      '}';

    map $request_uri $loggable {
        default   1;
        /_ping    0;
    }

    access_log  /tmp/access.log  json_combined if=$loggable;

    sendfile        on;

    keepalive_timeout  65;

    client_body_buffer_size 64K;
    client_header_buffer_size 64k;
    client_max_body_size 4M;

    absolute_redirect off;

    limit_req_zone $binary_remote_addr zone=healthcheck:1m rate=3r/s;


    upstream kratos_public {
        server kratos:4433:;  # Kratos service
    }

    upstream hydra_public {
        server hydra:4444;  # Hydra Public API (for OAuth2, OpenID Connect)
    }

    upstream kratos_selfservice_ui {
      server kratos-selfservice-ui-node:4455;  # Kratos Self-Service UI Node
    }


    server {
      listen 443 ssl;

      ssl_certificate    /etc/ssl/certs/server.pem;
      ssl_certificate_key  /etc/ssl/private/server.key;

      # Restrict older SSL and TLS versions for better security
      ssl_protocols TLSv1.2 TLSv1.3;

      resolver 127.0.0.11 8.8.8.8 ipv6=off;

      large_client_header_buffers 4 32k;

      location /_ping {
        return 200 'pong';
      }

      location ~ ^/(.well-known|oauth2/auth|oauth2/token|oauth2/sessions|oauth2/revoke|oauth2/fallbacks/consent|oauth2/fallbacks/error|userinfo)/? {
        proxy_pass http://hydra_public;
        proxy_redirect    off;
        proxy_set_header  Host              $host;
        proxy_set_header  X-Real-IP         $remote_addr;
        proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Proto $http_x_forwarded_proto;
      }

      location / {
        proxy_pass http://public_api;
        proxy_redirect    off;
        proxy_set_header  Host            $host;
        proxy_set_header  X-Real-IP       $remote_addr;
        proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
      }

      location /ui {
        proxy_read_timeout 30s;
        proxy_pass http://kratos_selfservice_ui:4455/ui/;
      }

    }

}
