packages:
- api/bloc2
- api/bloc2api
- api/core-api2
- api/ethereum-jsonrpc
- api/strato-api
- api2/strato-api2

- core/blockapps-data
- core/blockapps-datadefs
- core/blockapps-mpdbs
- core/blockstanbul
- core/ethereum-discovery
- core/ethereum-encryption
- core/fast-keccak256
- core/fastMP
- core/merkle-patricia-db
- core/miner-ethash
- core/privacy
- core/seqevents
- core/strato-adit
- core/strato-conf
- core/strato-genesis
- core/strato-init
- core/strato-model
- core/strato-networks
- core/strato-p2p
- core/strato-redis-blockdb
- core/strato-sequencer
- core/strato-statediff
- core/vm-runner/
- core/vm-tools/

- indexer/slipstream
- indexer/strato-index

- libs/blockapps-haskoin/
- libs/clockwork
- libs/common-log
- libs/composable-monads/bloc-sql-monad
- libs/composable-monads/core-api-monad
- libs/composable-monads/kafka-monad
- libs/composable-monads/sql-monad
- libs/composable-monads/vault-monad
- libs/ethereum-rlp
- libs/format
- libs/labeled-error
- libs/logserver
- libs/kafka/milena
- libs/kafka/milena-tools
- libs/monad-alter
- libs/nibblestring
- libs/partitioner
- libs/prometheus/blockapps-init
- libs/prometheus/cross-monitoring
- libs/secp256k1-haskell
- libs/type-lits

- test-suite

- tools/blockapps-tools
- tools/x509-certs

- vault/api
- vault/client
- vault/server

- VM/EVM/ethereum-vm
- VM/EVM/evm-solidity
- VM/SolidVM/debugger
- VM/SolidVM/solid-vm
- VM/SolidVM/solid-vm-fuzzer
- VM/SolidVM/solid-vm-model
- VM/SolidVM/solid-vm-parser
- VM/SolidVM/solid-vm-static-analysis
- VM/SolidVM/source-tools
- VM/vrun

extra-deps:
- Crypto-4.2.5.1@sha256:52275a055f4adf7c488260fb9fae60d03679632e64d3c8fc69d8b5951e8129cc,3688
- bloomfilter-2.0.1.0@sha256:c72063cc0a3458a5ec6e74e4cabe286ce7f04841624343c1c69d9e0d378726c2,1806
- bytestring-arbitrary-0.1.3@sha256:14db64d4fe126fbad2eb8d3601bfd80a693f3131e2db0e76891feffe44f10df8,1773
- global-lock-0.1@sha256:b7affe140763f53f17fd9c937dfe9b8023c7d209216fb3793933957e49a7446f,1327
- hflags-0.4.3@sha256:f6b85fc7cbd170787f49225646e62d5589e5dd75abe6f26d16287e5fff3e678e,3121
- json-rpc-client-0.2.5.0@sha256:f1ba95a8c8eb25865d34e7d8cc0eca33447e34d114d8b28ea8ece1bde23b6ea7,5343
- json-rpc-server-0.2.6.0@sha256:be5f936ab08e837fc17de6fc6ea0766e6e6b40676707e63333f3caf7e459e231,3585
- json-stream-0.4.4.1@sha256:272cd4aed5d0d9c97978620c1435cd91acaa39c8bddb28cbace9284f58ddc364,4985
- monadIO-0.11.1.0@sha256:2407c8aee3a74f3eba897f7c87f702f502394aec8cd412f3d2334cc353f54f13,964
- normaldistribution-1.1.0.3@sha256:2615b784c4112cbf6ffa0e2b55b76790290a9b9dff18a05d8c89aa374b213477,2160
- semver-range-0.2.8@sha256:44918080c220cf67b6e7c8ad16f01f3cfe1ac69d4f72e528e84d566348bb23c3,1941
- servant-mock-0.8.7@sha256:64cb3e52bbd51ab6cb25e3f412a99ea712c6c26f1efd117f01a8d1664df49c67,2306
- servant-options-0.1.0.0@sha256:39f50166a68006250e79370372f553ca476f14d06d93fa0c401050253aeba803,914
- servant-swagger-tags-0.1.0.1@sha256:2d743e9ad1cfcca537acc99e0b97e0e4feda3b5c842937dbf5895261e3105bf1,1094


#- git: https://github.com/blockapps/milena
#  commit: 39dad725837f8d67721f3ac0f87a047ce36b2889

flags:
  secp256k1-haskell:
    ecdh: true
    recovery: true

resolver: lts-18.8 #also duplicated in docker section below
compiler-check: newer-minor
extra-include-dirs:
- /usr/local/include
- /usr/include

extra-lib-dirs:
- /usr/local/lib
- /usr/lib

allow-newer: true

ghc-options:
  "$locals": -Wall -Werror -fwarn-redundant-constraints

docker:
  enable: true
  image: "strato-buildbase:lts-18.8"
  set-user: true
  run-args: ["--ulimit=nofile=60000"]

nix:
  enable: false
