// GENERATED by rollup/plonkgen (go run . import /private/tmp/claude-501/-Users-dustinnorwood-BlockApps-pbbo/539a2388-743e-4b34-a61d-3e63d2a059a9/scratchpad/e2e BridgeAggregateFixture) -- do not edit by hand.
//
// A real gnark PLONK/BN254 proof imported from another prover, plus its
// verifying key and public inputs, as word accessors: vkWord(i) is
// PlonkVerifier.initialize's layout (29 words + 3 per Bsb22 commitment),
// proofWord(i) is MarshalSolidity's 32-byte chunks (24 + 3 per commitment).
// The reference verifier accepted this proof when the file was generated.

library BridgeAggregateFixture {
    uint256 constant VK_WORDS = 32;
    uint256 constant PROOF_WORDS = 27;
    uint256 constant NB_PUBLIC_INPUTS = 17;
    uint256 constant NB_COMMITMENTS = 1;

    function vkWord(uint256 i) internal returns (uint256) {
        if (i == 0) { return 0x400000; }
        if (i == 1) { return 0x1ad92f46b1f8d9a7cda0ceb68be08215ec1a1f05359eebbba76dde56a219447e; }
        if (i == 2) { return 0x30644db14ff7d4a4f1cf9ed5406a7e5722d273a7aa184eaa5e1fb0846829b041; }
        if (i == 3) { return 0x5; }
        if (i == 4) { return 0x11; }
        if (i == 5) { return 0x17fbde090d546c15b0709288702f854d7194f1519f2a1d85efbf4eccbbff9284; }
        if (i == 6) { return 0x1d6722a5e21ca82d2dd992998a3d90a00f0fde3030f68b1bd3882486580b5585; }
        if (i == 7) { return 0x20c34044c20918b74fec0ecbfdf99aad537c25a3a1bdeb6efd5d0791c6e1bffb; }
        if (i == 8) { return 0x2ad1e47829259e6f8a4ca5931cf66538f2be5566c07de142cbf15d390cd779d4; }
        if (i == 9) { return 0x2222c1a3f2073532b432c1fad2ce6fad7c38a84778aef49721b7ba8d30217d0f; }
        if (i == 10) { return 0x182d4454189aadced90640e0045a061492d891b9cfb2c2a4a33ecde624f6de53; }
        if (i == 11) { return 0x95e7310aad60779ce0cdab4326bab8bc1209c8d5814bb3302911c1a3b9a45e9; }
        if (i == 12) { return 0x1728d02e45af39b234c4082ea5ce7e4c88911b238018997b48f638cbd896442; }
        if (i == 13) { return 0x2b111f6b4da2cabd29edda434475a974ddd52798277ca6542561f2cf652de7e3; }
        if (i == 14) { return 0x2c24ec2d903254d953a1ba950dca54fe744084bdc08bacadbbc7a3d11a738944; }
        if (i == 15) { return 0x13ecb3d4f86722bf8d9b81380692f24e15b8992e25ab116f968155fe493c466d; }
        if (i == 16) { return 0x265a2fab5b27e28b34ce1fc138289182519204af0af37d39264fb819f7db0be1; }
        if (i == 17) { return 0x1923dfd247bbe414d7ab38e561253d6a94fb551ea06b1bea3e3b5cf569d2fbf6; }
        if (i == 18) { return 0x24fcbc36c39acc418b237fd6271ecff2e4439dbc50be09beb85ad37e7dbd4729; }
        if (i == 19) { return 0x1a943f53d459a48b65d43786d230a140e2587cab6ab3e1254f6f77b1cb1085be; }
        if (i == 20) { return 0x1b32dd3316ebec29b2da8e8e485cd1c1c8575996715f4acc86de63b08a44ebcc; }
        if (i == 21) { return 0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2; }
        if (i == 22) { return 0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed; }
        if (i == 23) { return 0x90689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b; }
        if (i == 24) { return 0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa; }
        if (i == 25) { return 0x2f7d3a1cfdb096ebad9cb93def972c7c341a0649c2d689074eab5696c9af429; }
        if (i == 26) { return 0x64e68d799b5099b505af8b7024994ef2dff0de28fbdeef4d6bc6058c356aba3; }
        if (i == 27) { return 0x253d4f44ee1fe0d75f8f819d53a07bee3d2d8d4510d5688fb47b8aec2b757caf; }
        if (i == 28) { return 0xb83f720d5e9c9293fabe525222a7b3f5616957428745165c8c14d7b6c5eddb3; }
        if (i == 29) { return 0x253f16babfeb6cb3113bfa20d9d918b8eab6d84529d279d6be05a7dd2b712a2f; }
        if (i == 30) { return 0x32dee54a116b5d17fa3b7a253add972025635f40215f908b011dcb7e607830f; }
        if (i == 31) { return 0x15294b; }
        require(false, "vkWord: no such index");
        return 0;
    }

    function proofWord(uint256 i) internal returns (uint256) {
        if (i == 0) { return 0xd4943cca8c08b7cb5ef242c682547def7ca67527cee9e01b0d8bec269684312; }
        if (i == 1) { return 0xf8caafe601fd9580fd06e49c66ad30e3c562f66c3ccae380c67c972f5b16e5c; }
        if (i == 2) { return 0x193f4a0bafbf7ce183731b7331d72e1de05d1bc0e43c0a2d3e3b9826ee42033e; }
        if (i == 3) { return 0x2e02cbfd97dedc57c941e7f54e7ab421c16931102c15d1da4a5386e34c157e19; }
        if (i == 4) { return 0x2c9252d5906f7227621b859c9b038fe04e3bf9d1b41ce3d7ef206e0e3062fb19; }
        if (i == 5) { return 0x1385127398b0bdd18d343846b894046248616fe79f16298e40619d78f07568e1; }
        if (i == 6) { return 0x10b46e9c9f28953f71132f576dc666443e901631427841648a73b343036a0b17; }
        if (i == 7) { return 0x2eafd8193f418f097cf0c5a653bc2eadd4b0727c78070d88044e16d14ca634a2; }
        if (i == 8) { return 0x2af38abfda4d2db730d4b7c976474c018280412654b51e95c5bd44d55982a7b3; }
        if (i == 9) { return 0xa8db46ac3a416944c4c8cc36676f4078232a599390580f508b80e55658c2517; }
        if (i == 10) { return 0x2f5c5d9716cf56944b8e7f96ec4273eaacf79deeb4d5acb00e9fc1e6ea6e8a4a; }
        if (i == 11) { return 0x17e056552fdc2e03ea5155d1de44de3df011d1bf6c5ddff9ead2cbfec9da46bf; }
        if (i == 12) { return 0x3d8ecc0a8307651fbe7cc0e8793c77b4a80ec1064d694d47ec85c1d385ad52; }
        if (i == 13) { return 0xcd6255da1f19b46ab1f3aa0995c1be6b2265546efb858a96e6a4f5ba36136c8; }
        if (i == 14) { return 0x2cadddf1f95d351869ba489d78d67134fc93a6520df8f851cf5a3929939aeaed; }
        if (i == 15) { return 0x300e6253806aa207a7f28ea4ae830bdb098d7baea28b24e85bf0d6a7eb2e7c4; }
        if (i == 16) { return 0xdbcf252d8178ccab367e151d60bbe661c34cbb62fe8e00f42ef46cccd78d31e; }
        if (i == 17) { return 0x1f5adbdbb0885ce3b3fedbb0f95ebcfede2ae217e2906753d6481a9bfe2920d2; }
        if (i == 18) { return 0x1ae5faf3c9cd71bbc5ac500c0e49862f6c74f37b67b6e9fbac7f9cdb7f203a16; }
        if (i == 19) { return 0x18d4bd98c274e61fb1078cdffa15a43f6e3818aca359d32dfdd35383da1ea55c; }
        if (i == 20) { return 0x17668bb192c1737a52b564a1cf2a170239da133d82264d9876ddd7bd5d0044c6; }
        if (i == 21) { return 0x10a9edae1b6746adc82f6b06864488c1e2b425ea04c675c7d6728464d1a675da; }
        if (i == 22) { return 0x1e3034629313729aec56567f9b8d67807f6be24bb96c3720ede534ecb568d607; }
        if (i == 23) { return 0x12eb3f3cb2973f75bdbd276ebc93e97be401bcaf3be3f1cf4998744422dc7607; }
        if (i == 24) { return 0x1c6a8b2aead33fd321a1f50f1cfdad696285eec6efa5fa71867d244bd6c831c3; }
        if (i == 25) { return 0x303b96e08d8f05bc6ba79249f3891a83b91d8ac6d478eb956a2b11aff8d53472; }
        if (i == 26) { return 0x1b7f8117f7a3b1b3a18eab516573e51c4dae78cf034ecb2402c6999277cc2207; }
        require(false, "proofWord: no such index");
        return 0;
    }

    function publicInput(uint256 i) internal returns (uint256) {
        if (i == 0) { return 0xffffffffffffffffffffffffffffffff; }
        if (i == 1) { return 0xffffffffffffffffffffffffffffffff; }
        if (i == 2) { return 0xffffffffffffffffffffffffffffffff; }
        if (i == 3) { return 0x3fffffffffffffffffffff; }
        if (i == 4) { return 0x5879c70d492c8de5; }
        if (i == 5) { return 0xc62b2a2781b5366f; }
        if (i == 6) { return 0xd93b458e5fe63005; }
        if (i == 7) { return 0x8276b2d39b3b6eaf; }
        if (i == 8) { return 0xd6705e8165902942; }
        if (i == 9) { return 0x14b7612499d3e581; }
        if (i == 10) { return 0xccdb807df6e791e4; }
        if (i == 11) { return 0x136a4a98c5e0f9e9; }
        if (i == 12) { return 0x6b5441d381449072; }
        if (i == 13) { return 0x7e098aa703b7e602; }
        if (i == 14) { return 0xdd10f9451ce8b906; }
        if (i == 15) { return 0x19775031f0e86efd; }
        if (i == 16) { return 0x2bac3330501c9064e562ac7364985272707e9e459d8a5659fb38f5eac57196dc; }
        require(false, "publicInput: no such index");
        return 0;
    }

    // --- expected intermediates (reference verifier) ---
    uint256 constant EXP_GAMMA = 0xf3a73ca24525d16aad771b01a39db41386747c0af4ae130ced9c8f20d52d3da;
    uint256 constant EXP_BETA = 0x208261548d4e1f67c9b892d8908a951ac77ecdd4d28bde4bd6caa4deec66de0c;
    uint256 constant EXP_ALPHA = 0xb1a3407b3175e6f3bf3aa22326fcf88fe2bd88f40a07294d374ee89dde6aa2b;
    uint256 constant EXP_ZETA = 0xc12e69a5236d6c13142feb936192fc5c00979119befdbd4e849be3e59f09cf4;
    uint256 constant EXP_ZH = 0x1d15f840bb4bca339ce57e1496f1031511cdb9c722f440be22f3fbef23e5ade7;
    uint256 constant EXP_PI = 0x2ae92146588c90e50ecd787f00fa2999cff9f8a6cebb0e4f22690bf66f296d1;
    uint256 constant EXP_LIN_AT_ZETA = 0x23d23a47ae13a7a6622ed4a4a07505c60f3a4860f9171f1c678a65be7680583e;
    uint256 constant EXP_LIN_X = 0x10b7baf2181fbb821522ddd1b09bf5f97a52bab1a07d957728c22385f1182477;
    uint256 constant EXP_LIN_Y = 0x1c14e13103277c31cf05da5338de31ef8e5f13f9de9aa14b6cdf1e1b616fb8e7;
    uint256 constant EXP_GAMMA_KZG = 0xf57766fb26a734df4c88a9bc6dd29aded2cd88b132a0d079fdc7f812be95133;
    uint256 constant EXP_FOLDED_X = 0x2039977a5da1553d2a3927dfdba0dc245ade692512d7f27ce57a513a3904d08f;
    uint256 constant EXP_FOLDED_Y = 0x193097e9f658bcfcd1ce4c8e2f8b0843d91b4c804f62d649ceb02d687bf5375f;
    uint256 constant EXP_FOLDED_VALUE = 0x302bd17b7d0f5677b115c272b09159e349fc26610be255dfc792a85cfb077701;
    uint256 constant EXP_RHO = 0x3df187d521d995784c571c53fa91fb0098cf17cbf42acddb47bcb71d0e46ef6;
}
