// GENERATED by rollup/plonkgen/emit_fixture.py -- do not edit by hand.
//
// A real gnark PLONK/BN254 proof, its verifying key, and every intermediate
// the reference verifier produced while accepting it. The intermediates are
// what make the SolidVM verifier testable one stage at a time: a transcript
// bug otherwise shows up only as 'the proof does not verify', with six
// derivations to choose between.
//
// Circuit: x^3 + x + 5 == y with one Bsb22 commitment to (x, y), public (x, y) = (3, 35)

library PlonkCommitFixture {
    uint256 constant DOMAIN_SIZE = 16;
    uint256 constant OMEGA = 0x21082ca216cbbf4e1c6e4f4594dd508c996dfbe1174efb98b11509c6e306460b;
    uint256 constant INV_DOMAIN_SIZE = 0x2d5e098bb31e86271ccb415b196942d755b0a9c3f21dd9882fa3d63ab1000001;
    uint256 constant COSET_SHIFT = 0x5;
    uint256 constant NB_PUBLIC_INPUTS = 2;

    // --- public inputs ---

    // --- verifying key commitments ---
    uint256 constant PI_0 = 0x3;
    uint256 constant PI_1 = 0x23;

    uint256 constant VK_S1_X = 0x1c1999b899d5ddf0fe7be697d64e88d74fe0a583e18c266a2afa4eacf489acc3;
    uint256 constant VK_S1_Y = 0xc286414c4c3cef1e5aef20c3efb2b059a3f133f688f563976892fce06b3485a;
    uint256 constant VK_S2_X = 0xe77aeacac04766c67bad357402339d78d5b34abb0ee4b53af56d9f1f8a87ede;
    uint256 constant VK_S2_Y = 0x2f0afc98496f747df675a243f0433330090cb8eb8b27980283127703da57e87d;
    uint256 constant VK_S3_X = 0xe83b2e4cd49b2f796007b5845fddd66dd6486ad50b2c9a44ec28294fd866566;
    uint256 constant VK_S3_Y = 0x290b80431eb5feb729b25cdbdad40f4ac1edd517dd52ea760340f98c860ea3c8;
    uint256 constant VK_QL_X = 0x1b12b3edf23e54d45cdb4c3915a47d6f746f04531351393c7555050679701775;
    uint256 constant VK_QL_Y = 0x1d8aa8a516d46549ce67fc6bf3cb517f39b0c9c665d2b797ee72f8285c3ae0d0;
    uint256 constant VK_QR_X = 0x8442d4bc1adb99494f154d2e8bf03b31592d0b41bcc2784bc69e741a8a4b90b;
    uint256 constant VK_QR_Y = 0x8198f88d44eeb3b0e3be055849cfcf16547263f452b46f4a2331a34c32f23f5;
    uint256 constant VK_QM_X = 0x2ebecb9d84fd844ed2da4c8b71054c1869228863d81f4f53289a56b0288a13b5;
    uint256 constant VK_QM_Y = 0x2ab918c79dd678838ae0b2fc4e4b54953d71fc38a96f94431a097d89fca7e33e;
    uint256 constant VK_QO_X = 0x16ce5f808ab1e543aee4a1d17937d9b40394048fef3e83b4bea010db14b7a268;
    uint256 constant VK_QO_Y = 0x1c983d14135dacceb70a21b38c2c404b86228215a4d72d8251bc6777ff18d505;
    uint256 constant VK_QK_X = 0x16a8228c7480b72732852204f40e2dd3bd7251404eae7ed40759e470e0bf3aa7;
    uint256 constant VK_QK_Y = 0x22f76a84179cf7e806f93fbc36a6cfcec28821f32076bb73f4586cb646cac1ba;

    // --- KZG G2 points, EIP-197 order (imaginary part first) ---
    uint256 constant G2_SRS_0_X_0 = 0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2;
    uint256 constant G2_SRS_0_X_1 = 0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed;
    uint256 constant G2_SRS_0_Y_0 = 0x90689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b;
    uint256 constant G2_SRS_0_Y_1 = 0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa;
    uint256 constant G2_SRS_1_X_0 = 0x1868c86095d696bbf067de24725f0e8a6fc7f378cb924fdf573153f64a7372d;
    uint256 constant G2_SRS_1_X_1 = 0xb33e91bba33519ff9d6a09ce81fb7bcdb46ad096ed6ebadb9cd6e6d8dd15d9d;
    uint256 constant G2_SRS_1_Y_0 = 0x1636836dce2ab1c7c88b1e3006a0e46c4f73806dffe5eff716cb6a44b8a9552b;
    uint256 constant G2_SRS_1_Y_1 = 0x16a10bb54f0f8d515525f7ffbfb8d0da4b3999430e09ccc3ed6100d0a975e371;

    // --- proof ---
    uint256 constant PROOF_L_X = 0x1b07708d35c4aa0254919d7473d4950c752fe71f497e8b9e59869d6f233a2571;
    uint256 constant PROOF_L_Y = 0x105982ec7b437cf6b1a09595f6a672f704d5cd9e8bb37b812db4dd1d1442b7f1;
    uint256 constant PROOF_R_X = 0x6311d3e918f3487ec57c64b51272889e14ff1d34259faf6ce2dbc286794f952;
    uint256 constant PROOF_R_Y = 0x92292889c0a802e24da777c54778759d4f402ecb8c7806ac906101d43bff5c7;
    uint256 constant PROOF_O_X = 0x7a142308b668f659b57cbf91d0f11e461cec2a9c09f6c9e6261daee176b3b90;
    uint256 constant PROOF_O_Y = 0x31e56ef5a200ddc5069a0e6a677c1cc2d1d1d80d99957b1fb38fd4ec7711b7b;
    uint256 constant PROOF_Z_X = 0x2c9acfbb520a6f3a822e8107307052f40a0c4852dd104e5258d746df971205d7;
    uint256 constant PROOF_Z_Y = 0x149a449b434f5fbc4c6bbd0adb5ce58e6fac5d318a81e20ff19ee335a737e63c;
    uint256 constant PROOF_H0_X = 0x22409580416a71a59955eddba38409073ab57db76924b51e6f30f6d7c6f9a364;
    uint256 constant PROOF_H0_Y = 0x26cf1d6aa4b8e30d699bbc16febdcf6cd86d217a93231dbe24b2e24a4408c63f;
    uint256 constant PROOF_H1_X = 0x190c785e4d59b4fc02faa9e22e5fec707da49adcfbd4304d06c06190b8d62612;
    uint256 constant PROOF_H1_Y = 0xb3384ce5ad6123b7d7f304e7b2694f8016e91510c7239873bfd511473d9cb57;
    uint256 constant PROOF_H2_X = 0xa82a6d23ed2844a922e757c341103005afc19e29fcee1a5f4cf3aaa59d61219;
    uint256 constant PROOF_H2_Y = 0x1ee7e63b48daa682651c38faf48fd64bfe18d12296fada411168c99d7d5bbf5;
    uint256 constant PROOF_W_ZETA_X = 0x2fea7e05639373271728faec0a545691fd1bd23ef806da116e03133be7cbf713;
    uint256 constant PROOF_W_ZETA_Y = 0x1b2ad7df4e5f4123a2d814724db77d5037366adff2195c68dc5a59bf9fa4387f;
    uint256 constant PROOF_W_ZETA_OMEGA_X = 0xa2a2658e72420369b3941e6a5eeff044c0b765244f77f5e4fea8b93efbcfaac;
    uint256 constant PROOF_W_ZETA_OMEGA_Y = 0xb436ba9a8eee652b273a524663942dd393e72139541d9b1d016b2e9e3271912;
    uint256 constant PROOF_L_AT_ZETA = 0x7fec1a0072b767128c6e2a8accb7ad47100183f2da0da2a1cc68a7c00385c80;
    uint256 constant PROOF_R_AT_ZETA = 0x1cb670ccb521c5e3ba5f8fdd61a477b4ce5b3e8ea2b789f144e26167f1bc4631;
    uint256 constant PROOF_O_AT_ZETA = 0x9ee433df2f30fc04d8105b4849f7979789e8c6cb717353d3662303bfbf7d4b3;
    uint256 constant PROOF_S1_AT_ZETA = 0xd98594ed9a2d9732f86c98b9e91b7c0db482b0d948453cd30792b4e1cf5159b;
    uint256 constant PROOF_S2_AT_ZETA = 0x22667ac7e9e2c22db87c2260a9914ef266916c48484a1829a8c673a318f0c7bb;
    uint256 constant PROOF_Z_AT_ZETA_OMEGA = 0x14e1bf34504d1438255ca803b891f1adc523752186101f9f438b3794df059278;

    uint256 constant NB_COMMITMENTS = 1;
    uint256 constant VK_QCP0_X = 0x1f070b0845569dfba0d19a2e5afcf9a7a5fca83e75bc968679caa784013bacb0;
    uint256 constant VK_QCP0_Y = 0x3030d90c3cb6904ed8c13534e78b89ae0c72fcc4d78ea014bf3472b9d38edb45;
    uint256 constant VK_COMMITMENT_INDEX0 = 6;
    uint256 constant PROOF_QCP0_AT_ZETA = 0x2ddace3aba371e4ce014218f9a8d361ababc5f1fe1fb5d66d5993f32ea2c79e7;
    uint256 constant PROOF_BSB0_X = 0x29b88dd3d7e887b409d1d673adb2381d6ed1a72f643d2e81a2b48ed3d1ca945f;
    uint256 constant PROOF_BSB0_Y = 0xe14a42848ad5b0f9a3571c655f2f6705b9bfd3fa65565f26c40d8c5975c9384;
    uint256 constant EXP_HASH_FR0 = 0x2e53c7d6da8d09df653bb4208be74c7322d2d89991093a8e99ec370aed835f47;
    uint256 constant EXP_PI_COMMIT = 0x2c21ad78e014cb422137fef5994ee37bf82b17c891bc2f671931e7a568d2d59;

    // --- expected intermediates (reference verifier) ---
    uint256 constant EXP_GAMMA_RAW = 0x8a542cb8ed35190c1fb45b2b3178a475b4bc76c4747c0f2b4a6ca8d93eface23;
    uint256 constant EXP_GAMMA = 0x298b8fd32ad1d8b8af13cfbe2e75f3bb6454a63381092e08c2a8bdb15eface21;
    uint256 constant EXP_BETA_RAW = 0x4defef12b23e862177bf0a985c7ac3b4c8589a0cf27632afa11f52fffe3bd260;
    uint256 constant EXP_BETA = 0x1d8ba09fd10ce5f7bf6ec4e1daf96b57a024b1c478bcc21e5d3d5d6c0e3bd25f;
    uint256 constant EXP_ALPHA_RAW = 0x9af0cb9ffd5f5a7b781f42040fd43eca5be960dbc66bb7ce3f27e9ea0c5424e1;
    uint256 constant EXP_ALPHA = 0x9c3e04759ca79fe4f2e70e08b5035b2e34da802593f661a7382092e3c5424de;
    uint256 constant EXP_ZETA_RAW = 0xa4a8c864593778c9ddce8614514a60af8d3a6e3ee01eac0352039049ddcdb803;
    uint256 constant EXP_ZETA = 0x137bdd0bb5a2984cb4ddb4f0ccc65798149eb56572f25a4f865daf8e0dcdb800;
    uint256 constant EXP_GAMMA_KZG = 0xd23bbd9b305b812ad4df451f8806744334380bebf09917a74ab91971cde20a3;
    uint256 constant EXP_RHO = 0x1ff6397b053d35202760ba5cf85baf43b1b384c75f0de86259122a429a1522f;
    uint256 constant EXP_ZH = 0x700c4cfa0a388abbccf12442b5e15d8769f1569efc4ca8595f72f6d2a3044f4;
    uint256 constant EXP_PI = 0x207827294149bf84113cb9f8f4e859046c75161fb640e001ea906df5fa182300;
    uint256 constant EXP_ALPHA_SQ_L0 = 0x284ec72cb1ee20189ba20cdd14b35d1f77044c8194a10dd7278b6997922c3cad;
    uint256 constant EXP_LIN_AT_ZETA = 0x2ab688298894a80b3f5fd3df81b8e38f0fa4cb3c046903aa82277e89231132;
    uint256 constant EXP_LIN_X = 0x28d596a1029ca3ef083d98fe7874c3b8740bd8dbcb847fcac68160f1e51298ee;
    uint256 constant EXP_LIN_Y = 0x28580dcc6773f5a491c0a09015e97a3e166e007f331474d0cbc39fe486ec6648;
    uint256 constant EXP_FOLDED_X = 0xa7c59d2da4bb00296600f7b2cad6c378632295e90b471fd99198b4c7265e93c;
    uint256 constant EXP_FOLDED_Y = 0x1b4bf8bbea9c95f0cef4924686d28c56631331f28d5a58bde7d974b034970378;
    uint256 constant EXP_FOLDED_VALUE = 0x26cc2d66bd75b95d3bb68c8926b0dd396598ad1dbca7c01b1d06f01e44cd984f;
    uint256 constant EXP_FINAL_D_X = 0x18ae59b6706aa82a10460575a4b30c98f320a22add5fbcc18f9a3f3be4b2b5d8;
    uint256 constant EXP_FINAL_D_Y = 0x2421f5d119d2ad69e8027ec55f9c7849bf6ac4cfab1db480bc39298e28a243b6;
    uint256 constant EXP_FINAL_Q_X = 0x17f707af4488dff621e3feac93dae8beb9103506046ab1d2dc0eca74c7025d40;
    uint256 constant EXP_FINAL_Q_Y = 0x169bdb3888a34c02b6fcee5f2df662ad00da48bd5221217880fa1594dc05a306;
}
