// GENERATED by rollup/plonkgen/emit_fixture.py -- do not edit by hand.
//
// A real gnark PLONK/BN254 proof, its verifying key, and every intermediate
// the reference verifier produced while accepting it. The intermediates are
// what make the SolidVM verifier testable one stage at a time: a transcript
// bug otherwise shows up only as 'the proof does not verify', with six
// derivations to choose between.
//
// Circuit: x^3 + x + 5 == y, public (x, y) = (3, 35)

library PlonkFixture {
    uint256 constant DOMAIN_SIZE = 8;
    uint256 constant OMEGA = 0x2b337de1c8c14f22ec9b9e2f96afef3652627366f8170a0a948dad4ac1bd5e80;
    uint256 constant INV_DOMAIN_SIZE = 0x2a57c4a4850b6c2481463cffb1512d51832d6b3f6a82427f1b65b6e172000001;
    uint256 constant COSET_SHIFT = 0x5;
    uint256 constant NB_PUBLIC_INPUTS = 2;

    // --- public inputs ---

    // --- verifying key commitments ---
    uint256 constant PI_0 = 0x3;
    uint256 constant PI_1 = 0x23;

    uint256 constant VK_S1_X = 0x1618fa7619ddc917404453da7f2b455f82d4903ad7b0ad3b14424d84bb614862;
    uint256 constant VK_S1_Y = 0x24751e2f1364fbbeeb3016ec1b099fae2045446474618fbb3b98264c1d4ccd07;
    uint256 constant VK_S2_X = 0x1cbaf3e0887a0fa498f84f5101176947abd0b79b5e30a4748ed24196d75c331f;
    uint256 constant VK_S2_Y = 0x2b76a7bad1ea850cb5cf400295e54abc3c67322918c5d9e775c94faf6095ca5e;
    uint256 constant VK_S3_X = 0xd4777c7825e9d4e5a5a7dbdb69ca7a72efdef6c64481122ead613dc9d4c769f;
    uint256 constant VK_S3_Y = 0x1ec31dbd877d7f716ccc91710ef292b18b895866b9c6812385549ca9d26c127a;
    uint256 constant VK_QL_X = 0x302b98a97c7f79a4b50b043f1e8e3dcce971a973da4cff6dd118706883c044a7;
    uint256 constant VK_QL_Y = 0x23cf6b4c9c36b8a2e9fb389334a05b937d3a4f888b0bfb559f74815a386db03;
    uint256 constant VK_QR_X = 0x214d8694e43a78f50e7c08f16b075e09118d105455d64c508606dd1c16567531;
    uint256 constant VK_QR_Y = 0xb582088dad767287675169335db53eaec24b72b1ce4bd0c6160f8ba97e224b4;
    uint256 constant VK_QM_X = 0x2fce6c08e6226ae05d2f652d05fcc210e0a618c6fab3c5ca26505249cc91262f;
    uint256 constant VK_QM_Y = 0x1aee5f13d57d13092a978adb8a7d1daded283fc5cabe6118035eb0936badb770;
    uint256 constant VK_QO_X = 0x2575a924219ed1c29d83471da16e3cfb8a8d131b5c8c5496304c602c0f4b7016;
    uint256 constant VK_QO_Y = 0x1727125c2f9a4a2f07b944fc6e2686fd434de108a2b03873a412dc9ea665be06;
    uint256 constant VK_QK_X = 0x19da30f50714577dbe2d018881e914e0ae2927857d590821838aced4df4ce7f2;
    uint256 constant VK_QK_Y = 0x184d9d3d8cf74ad00d5841268afab7c9660b4f9ad11c624f25cd64bc933362e3;

    // --- KZG G2 points, EIP-197 order (imaginary part first) ---
    uint256 constant G2_SRS_0_X_0 = 0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2;
    uint256 constant G2_SRS_0_X_1 = 0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed;
    uint256 constant G2_SRS_0_Y_0 = 0x90689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b;
    uint256 constant G2_SRS_0_Y_1 = 0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa;
    uint256 constant G2_SRS_1_X_0 = 0x2ec97c3436070b700f6666a0d6d6828be6bd7eef80c89d57a67dbf0cb2346787;
    uint256 constant G2_SRS_1_X_1 = 0x268f2dbb896485bbce28c6029471a7d84824d4df8aeb72b221a4f454854052e9;
    uint256 constant G2_SRS_1_Y_0 = 0x16599f03211a49807ad72a18ce0802b67f5822a55456b97665bee553963ab232;
    uint256 constant G2_SRS_1_Y_1 = 0x24270a959a37c362457ae9ccd5f10e75bfa2092690109eae7afe75383b660c69;

    // --- proof ---
    uint256 constant PROOF_L_X = 0x1b52d63c98b450827994bf695efff66700b71dbf9794f412b082379cc6f8bb9;
    uint256 constant PROOF_L_Y = 0x42d5bfec22c49e3cda01060a2b3612ab01ce65fe4c3dfd3e70783bcd6462fc3;
    uint256 constant PROOF_R_X = 0x200f4b357c2fe25177f26ba282eacabf49c3e9c6d0f40777788f7fb9d6cf79b;
    uint256 constant PROOF_R_Y = 0xcaf8c344b2aaa7ae32171bd1dcb3c25b9be41200450328f1d4c960e7ba0ccc3;
    uint256 constant PROOF_O_X = 0x1c4ed59674ec8ce3ec08ce5cecdea3e7ba18eeea337e25df673ef64854197747;
    uint256 constant PROOF_O_Y = 0x2873341fb95c6960c01e9fe977ac67f32ae8562c4a488a98f1ba1012105343c3;
    uint256 constant PROOF_Z_X = 0x288abd271d2c9beb95148241da322a422f4a3bfec5fe96896b2f25342c2b82ec;
    uint256 constant PROOF_Z_Y = 0x1b99659b2d75462998be8f6fc9dcb462a76dbb8fe46ec10e8a36aaa6d6025158;
    uint256 constant PROOF_H0_X = 0x3c922c140b41a244b2738fde2214290b8d3433910590340b4d539c22a3e0dc3;
    uint256 constant PROOF_H0_Y = 0x8e4db33088392f1c487c323fb52349150797c3dd58a265277876188c077eac0;
    uint256 constant PROOF_H1_X = 0x2543a411b16cefad680b3f347e080c4a2fe832bab5f423fa7e75ba7311538e6f;
    uint256 constant PROOF_H1_Y = 0x1a175d809195020894d035f73a1f1861f689d1e1b7c045c4286cad052583981e;
    uint256 constant PROOF_H2_X = 0x1f1e274567e241c9c57f18580fc83c284fdd7b30349f7778c27a589d05418fa3;
    uint256 constant PROOF_H2_Y = 0x2583e23965a79ca01007ab14db96ac515a44e0c68edcba0e387ad56c971a7cbd;
    uint256 constant PROOF_W_ZETA_X = 0x47da4b2c864771505f30af7a796f06311c0fe0e9c843aa880e600c4ed0495d;
    uint256 constant PROOF_W_ZETA_Y = 0x2548642388de6379f438272f01c6220bab220cd2b4ab14dd1d460134d419124c;
    uint256 constant PROOF_W_ZETA_OMEGA_X = 0x2977b09f66019ea484f186ffb9d22f979e0670685ed4ad1e8129ae2742dc04e9;
    uint256 constant PROOF_W_ZETA_OMEGA_Y = 0x26685f5f3d65356061ba6ee35a96f92d482c9eaa1d2035b7efecb18cf103fddd;
    uint256 constant PROOF_L_AT_ZETA = 0x189ee359adca55273ab5cdafb6a616b2b3ed796c5a200b0ab432116ba29b4e05;
    uint256 constant PROOF_R_AT_ZETA = 0xdc02b53aaff12d4f4add132408bcc12ad221b5fdf6f9afe76f7f5a781c20c20;
    uint256 constant PROOF_O_AT_ZETA = 0x2cff4dd5fdd956b8265c0dd51c6e36ca5b9ff97826d5361e43243a07dcfc301e;
    uint256 constant PROOF_S1_AT_ZETA = 0x1ff281c8fb455a1d238f7edf6f6229c393730b26828dd196d176811eec9a8fec;
    uint256 constant PROOF_S2_AT_ZETA = 0x2ed814e515d0b50224ad211cb41e410586ebcfd8ada04e6adbde10c68b449af3;
    uint256 constant PROOF_Z_AT_ZETA_OMEGA = 0x2c48934076af17436e343ea408fdb3719dc0f4e1a6b9a68444d37a959b56d0cb;

    // --- expected intermediates (reference verifier) ---
    uint256 constant EXP_GAMMA_RAW = 0xc3f63ed7b31fd9ef5f9dd2783a20a2de45092f824b020a13cd5cd43dec9cc6bb;
    uint256 constant EXP_GAMMA = 0x265050c2e5959487e5cbb9e341b4169a4398e60641c47cebdd4fdee2c9cc6b7;
    uint256 constant EXP_BETA_RAW = 0xfa18ab41f800375eb995d65a0d07d3020a0e0ca254cdfab53bb7f16b47f56e95;
    uint256 constant EXP_BETA = 0x82323039208168e200479c985811930410a8337f42ec7dee84e258797f56e90;
    uint256 constant EXP_ALPHA_RAW = 0x20994c5f84d86b33f0acffa33d5265bfe8240980fae4126382c6c06fc66d23ca;
    uint256 constant EXP_ALPHA = 0x20994c5f84d86b33f0acffa33d5265bfe8240980fae4126382c6c06fc66d23ca;
    uint256 constant EXP_ZETA_RAW = 0x361ec3a7700a5d206289e58bc2b99e8532b0430ac7bbd94b4039b8b62d2c5fdd;
    uint256 constant EXP_ZETA = 0x5ba75348ed8bcf6aa399fd5413846280a7c5ac24e0268b9fc57c3223d2c5fdc;
    uint256 constant EXP_GAMMA_KZG = 0x2984c0448868aad088c98eb515a274badefc90b29fbe6f6ea6c103512f531e2b;
    uint256 constant EXP_RHO = 0x21f9d5733849cf9996982fed74a2e623014d01700f65e2be3eaad1ea4c58a500;
    uint256 constant EXP_ZH = 0x16f096453f9a391937a8f8beff841f144819ac28c65decf95911a45f6eb30b98;
    uint256 constant EXP_PI = 0x174b173b4dc807ab242e36ce1d053f757b62f57151d1cd321331380bbba52334;
    uint256 constant EXP_ALPHA_SQ_L0 = 0x2dbf392846d032231593f944ba35c7350eca1dd88ede9277898eed827f07c43d;
    uint256 constant EXP_LIN_AT_ZETA = 0x10b94616252bb0ccc8fe2a242ed3b637497d50b493bac8062a017105187a8a69;
    uint256 constant EXP_LIN_X = 0x19c19577083dc486e3b61fd1584a8b79bb2438efc828b7aea591acf2c898e731;
    uint256 constant EXP_LIN_Y = 0x26894d518b783de6d079bdd0ab6e37da180142cdb4285b0d8f56893e319736f1;
    uint256 constant EXP_FOLDED_X = 0x7c21b797625562c0b3eb962d1724ebee95298a053fe599ccc434ab45d3e089;
    uint256 constant EXP_FOLDED_Y = 0x10a1da6306dda7a80feaebc84e591f712657d62e423f5ca7f747db69e7aa84fe;
    uint256 constant EXP_FOLDED_VALUE = 0x15f8f84855a8b27095a5bc93787da719ac866cef616a33a7f50d1abeac3e298e;
    uint256 constant EXP_FINAL_D_X = 0x285291f6f84d5e2ba6b5a38cf9bd04fef5104c5f22071acb2c2588b75d983feb;
    uint256 constant EXP_FINAL_D_Y = 0x436d6cfa3db979baf6cc2dc91b25dcd1f31ae689b064d634aba33fc4f1c40a5;
    uint256 constant EXP_FINAL_Q_X = 0x7e4396af243f8ee4b61ea8dafb1a89234c14cdc6a253509f598f63588f9319a;
    uint256 constant EXP_FINAL_Q_Y = 0x133699857b0ea56ffea9230c1efa3467b6aa17d865399dc569b69303841d4d42;
}
