name: ethereum-vm
version: 0.0.4
build-type: Simple
author: Jamshid
maintainer:    jamshidnh@gmail.com
synopsis: A Haskell version of an Ethereum EVM
category:      Data Structures
license: Apache-2.0
description:
    The client described in the Ethereum Yellowpaper

default-extensions:
  - DeriveGeneric
  - DeriveAnyClass

dependencies:
  - base >= 4 && < 5
  - ansi-wl-pprint
  - base16-bytestring
  - binary
  - blockapps-data
  - blockapps-haskoin
  - blockapps-util
  - bytestring
  - clockwork
  - containers
  - cpu
  - cryptohash
  - deepseq
  - ethereum-encryption
  - extra
  - ghc
  - integer-gmp
  - lens
  - merkle-patricia-db
  - monad-logger
  - mtl
  - primitive
  - resourcet
  - strato-model
  - text
  - time
  - transformers
  - unboxed-ref
  - vector
  - vm-tools

library:
  source-dirs: src/
  exposed-modules:
    - Blockchain.VM
    - Blockchain.VM.Code
    - Blockchain.VM.Environment
    - Blockchain.VM.MutableStack
    - Blockchain.VM.Opcodes
    - Blockchain.VM.VMM
    - Blockchain.VM.VMState
  ghc-options: -Wall -O2
