name: ethereum-vm
version: 0.0.4
build-type: Simple
author: Jamshid
maintainer:    jamshidnh@gmail.com
synopsis: A Haskell version of an Ethereum EVM
category:      Data Structures
license: Apache-2.0
description:
    The client described in the Ethereum Yellowpaper

dependencies:
  - base >= 4 && < 5
  - ansi-wl-pprint
  - base16-bytestring
  - binary
  - blockapps-data
  - blockapps-datadefs
  - blockapps-haskoin
  - blockapps-mpdbs
  - blockapps-util
  - bytestring
  - clockwork
  - containers
  - cpu
  - cryptohash
  - data-default
  - deepseq
  - ethereum-encryption
  - ethereum-rlp
  - extra
  - format
  - ghc
  - integer-gmp
  - lens
  - leveldb-haskell
  - merkle-patricia-db
  - monad-alter
  - mtl
  - nibblestring
  - primitive
  - resourcet
  - strato-model
  - text
  - time
  - transformers
  - unboxed-ref
  - unliftio
  - vector
  - vm-tools

library:
  source-dirs: src/
  exposed-modules:
    - Blockchain.EVM
    - Blockchain.EVM.Code
    - Blockchain.EVM.Environment
    - Blockchain.EVM.MutableStack
    - Blockchain.EVM.Opcodes
    - Blockchain.EVM.VMM
    - Blockchain.EVM.VMState
  ghc-options: -Wall -O2
