pipeline {
    agent { label "test3" }
    stages {
        stage('Stage 1') {
            steps {
                sh 'AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test aws eks update-kubeconfig --name ba-dev3 --region us-east-1'
                sh 'AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test AWS_DEFAULT_REGION="us-east-1" /home/ubuntu/bin/kubectl get pods -n strato-platform'
            }
        }
    }
}
