---
apiVersion: v1
kind: Namespace
metadata:
  name: strato-platform
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: strato-platform
  name: ebs-claim-marketplace-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: strato-platform
  name: ebs-claim-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: strato-platform
  name: ebs-claim-prometheus-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: strato-platform
  name: ebs-claim-kafka-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: strato-platform
  name: ebs-claim-redis-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: strato-platform
  name: ebs-claim-zookeeper-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: strato-platform
  name: ebs-claim-strato-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: strato-platform
  name: deployment-strato-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: strato-platform
  template:
    metadata:
      labels:
        app.kubernetes.io/name: strato-platform
    spec:
      containers:
      - image: <REPO_URL>/smd:<VERSION>
        name: smd
        env:
        - name: NODE_HOST
          value: "localhost"
        - name: NODE_NAME
          value: "localhost"
        - name: ssl
          value: "false"
      - image: <REPO_URL>/apex:<VERSION>
        name: apex
        env:
        - name: NODE_HOST
          value: "localhost"
        - name: postgres_host
          value: "localhost"
        - name: postgres_password
          value: "api"
        - name: postgres_port
          value: "5432"
        - name: postgres_user
          value: "postgres"
        - name: PROMETHEUS_HOST
          value: "localhost:9090"
        - name: STRATO_HOSTNAME
          value: "localhost"
        - name: STRATO_PORT_API
          value: ""
        - name: STRATO_PORT_VAULT_PROXY
          value: ""
      - image: <REPO_URL>/marketplace-backend:<VERSION>
        name: marketplace-backend
        env:
        - name: EXT_STORAGE_S3_BUCKET
          value: "mercata-testnet2"
        - name: EXT_STORAGE_S3_ACCESS_KEY_ID
          value: "<REPLACE_WITH_EXT_STORAGE_S3_ACCESS_KEY_ID>"
        - name: EXT_STORAGE_S3_SECRET_ACCESS_KEY
          value: "<REPLACE_WITH_EXT_STORAGE_S3_SECRET_ACCESS_KEY>"
        - name: GLOBAL_ADMIN_NAME
          value: "user1"
        - name: GLOBAL_ADMIN_PASSWORD
          value: "1234"
        - name: MP_IS_BOOTNODE
          value: "true"
        - name: MP_DAPP_ADDRESS
          value: "ec4deef60caaa5209790539abbb0f45e3d691c63"
        - name: MP_API_DEBUG
          value: "false"
        - name: MP_DELAY_DEPLOYMENT
          value: "true"
        - name: MP_SERVER_HOST
          value: "localhost"
        - name: MP_SERVER_SSL
          value: "false"
        - name: NODE_LABEL
          value: ""
        - name: ORG_NAME
          value: "BlockApps"
        - name: ORG_DEPLOY_FILE_NAME
          value: "org.deploy.yaml"
        - name: OAUTH_APP_TOKEN_COOKIE_NAME
          value: "stratomp_session"
        - name: OAUTH_OPENID_DISCOVERY_URL
          value: "https://keycloak.blockapps.net/auth/realms/mercata-testnet2/.well-known/openid-configuration"
        - name: OAUTH_CLIENT_ID
          value: "<REPLACE_WITH_OAUTH_CLIENT_ID>"
        - name: OAUTH_CLIENT_SECRET
          value: "<REPLACE_WITH_OAUTH_CLIENT_SECRET>"
        - name: OAUTH_VAULT_PROXY_ALT_CLIENT_ID
          value: ""
        - name: OAUTH_VAULT_PROXY_ALT_CLIENT_SECRET
          value: ""
        - name: OAUTH_SCOPE
          value: "email openid"
        - name: OAUTH_SERVICE_OAUTH_FLOW
          value: "client-credential"
        - name: OAUTH_TOKEN_FIELD
          value: "access_token"
        - name: OAUTH_TOKEN_USERNAME_PROPERTY
          value: "email"
        - name: OAUTH_TOKEN_USERNAME_PROPERTY_SERVICE_FLOW
          value: "sub"
        - name: STRIPE_PUBLISHABLE_KEY
          value: "<REPLACE_WITH_STRIPE_PUBLISHABLE_KEY>"
        - name: STRIPE_SECRET_KEY
          value: "<REPLACE_WITH_STRIPE_SECRET_KEY>"
        - name: STRATO_NODE_PROTOCOL
          value: ""
        - name: STRATO_NODE_HOST
          value: ""
        volumeMounts:
          - mountPath: /config
            name: marketplace-data
      - image: <REPO_URL>/marketplace-ui:<VERSION>
        name: marketplace-ui
        env:
        - name: NODE_ENV
          value: "production"
      - image: redis:3.2
        name: redis
        command: ["redis-server"]
        args: ["--appendonly", "yes"]
        volumeMounts:
          - mountPath: /data
            name: redis-data
      - image: <REPO_URL>/strato:<VERSION>
        name: strato
        ports:
          - containerPort: 30303
          - containerPort: 30303
            protocol: UDP
        env:
        - name: accountNonceLimit
          value: ""
        - name: addBootnodes
          value: ""
        - name: appFetchLimit
          value: ""
        - name: averageTxsPerBlock
          value: ""
        - name: blockstanbul
          value: "true"
        - name: blockstanbulBlockPeriodMs
          value: ""
        - name: blockstanbulRoundPeriodS
          value: ""
        - name: blockTime
          value: ""
        - name: bootnode
          value: ""
        - name: brokenRefundReenable
          value: ""
        - name: cacheTransactionResults
          value: ""
        - name: certInfo
          value: ""
        - name: connectionTimeout
          value: ""
        - name: debugFail
          value: ""
        - name: debugPort
          value: ""
        - name: debugWSPort
          value: ""
        - name: evmDebugMode
          value: ""
        - name: evmTraceMode
          value: ""
        - name: faucetEnabled
          value: ""
        - name: gasLimit
          value: ""
        - name: gasOn
          value: "false"
        - name: generateKey
          value: "true"
        - name: genesis
          value: ""
        - name: indexEVM
          value: "false"
        - name: kafkaHost
          value: "localhost"
        - name: kafkaPort
          value: "9092"
        - name: lazyBlocks
          value: ""
        - name: maxConn
          value: ""
        - name: maxReturnedHeaders
          value: ""
        - name: maxTxsPerBlock
          value: ""
        - name: minBlockDifficulty
          value: ""
        - name: mineBlocks
          value: "true"
        - name: miningAlgorithm
          value: ""
        - name: miningThreads
          value: ""
        - name: network
          value: "mercata-hydrogen"
        - name: networkID
          value: ""
        - name: numMinPeers
          value: ""
        - name: OAUTH_DISCOVERY_URL
          value: "https://keycloak.blockapps.net/auth/realms/mercata-testnet2/.well-known/openid-configuration"
        - name: OAUTH_CLIENT_ID
          value: "<REPLACE_WITH_OAUTH_CLIENT_ID>"
        - name: OAUTH_CLIENT_SECRET
          value: "<REPLACE_WITH_OAUTH_CLIENT_SECRET>"
        - name: OAUTH_VAULT_PROXY_ALT_CLIENT_ID
          value: ""
        - name: OAUTH_VAULT_PROXY_ALT_CLIENT_SECRET
          value: ""
        - name: OAUTH_RESERVE_SECONDS
          value: ""
        - name: postgres_host
          value: "localhost"
        - name: postgres_password
          value: "api"
        - name: postgres_port
          value: "5432"
        - name: postgres_slipstream_db
          value: "cirrus"
        - name: postgres_user
          value: "postgres"
        - name: PROCESS_MONITORING
          value: ""
        - name: redisHost
          value: "localhost"
        - name: redisPort
          value: "6379"
        - name: redisBDBNumber
          value: ""
        - name: requireCerts
          value: "true"
        - name: seqDebugMode
          value: ""
        - name: seqEventsBatchSize
          value: ""
        - name: seqEventsCostHeuristic
          value: ""
        - name: seqMaxEventsPerIter
          value: ""
        - name: seqMaxUsPerIter
          value: ""
        - name: seqRTSOPTs
          value: ""
        - name: SLIPSTREAM_DEBUG
          value: ""
        - name: SLIPSTREAM_OPTIONAL
          value: ""
        - name: splitinit
          value: "true"
        - name: stratoHost
          value: "localhost:3000"
        - name: svmTrace
          value: ""
        - name: sqlDiff
          value: ""
        - name: svmDev
          value: ""
        - name: txSizeLimit
          value: ""
        - name: useSyncMode
          value: ""
        - name: VAULT_URL
          value: "https://vault.blockapps.net:8093/"
        - name: VAULT_PROXY_DEBUG
          value: ""
        - name: validatorBehavior
          value: "true"
        - name: vmDebug
          value: ""
        - name: vmRunnerRTSOPTs
          value: ""
        - name: wireMessageCacheSize
          value: ""
        - name: wsDebug
          value: ""
        - name: zkHost
          value: "localhost"
        volumeMounts:
          - mountPath: /var/lib/strato
            name: strato-data
      - image: <REPO_URL>/postgrest:<VERSION>
        name: postgrest
        env:
        - name: blocHost
          value: "localhost:3000"
        - name: PG_ENV_POSTGRES_DB
          value: "cirrus"
        - name: PG_ENV_POSTGRES_HOST
          value: "localhost"
        - name: PG_ENV_POSTGRES_PASSWORD
          value: "api"
        - name: PG_ENV_POSTGRES_USER
          value: "postgres"
        - name: PG_PORT_5432_TCP_PORT
          value: "5432"
        - name: POSTGREST_LOG_LEVEL
          value: "error"
      - image: postgres:9.6
        name: postgres
        command: ["docker-entrypoint.sh"]
        args: ["-c", "max_connections=300", "-c", "shared_buffers=512MB"]
        env:
        - name: POSTGRES_PASSWORD
          value: "api"
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
          - mountPath: /var/lib/postgresql/data/
            name: postgres-data
      - image: <REPO_URL>/nginx:<VERSION>
        name: nginx
        ports:
          - containerPort: 80
          - containerPort: 443
        env:
        - name: APEX_HOST
          value: "localhost:3009"
        - name: blockstanbul
          value: ""
        - name: blockTime
          value: ""
        - name: debugPort
          value: ""
        - name: debugWSPort
          value: ""
        - name: DOCS_HOST
          value: "localhost:8080"
        - name: MARKETPLACE_BACKEND_HOST
          value: ""
        - name: MARKETPLACE_UI_HOST
          value: ""
        - name: OAUTH_CLIENT_ID
          value: "<REPLACE_WITH_OAUTH_CLIENT_ID>"
        - name: OAUTH_CLIENT_SECRET
          value: "<REPLACE_WITH_OAUTH_CLIENT_SECRET>"
        - name: OAUTH_DISCOVERY_URL
          value: "https://keycloak.blockapps.net/auth/realms/mercata-testnet2/.well-known/openid-configuration"
        - name: OAUTH_SCOPE
          value: ""
        - name: POSTGREST_HOST
          value: "localhost:3001"
        - name: PROMETHEUS_HOST
          value: "localhost:9090"
        - name: SERVE_LOGS
          value: ""
        - name: SMD_DEV_MODE
          value: ""
        - name: SMD_DEV_MODE_HOST_IP
          value: ""
        - name: SMD_HOST
          value: "localhost:3002"
        - name: ssl
          value: "false"
        - name: sslCertFileType
          value: ""
        - name: STATS_ENABLED
          value: ""
        - name: STRATO_HOSTNAME
          value: "localhost"
        - name: STRATO_PORT_API
          value: ""
        - name: STRATO_PORT_API2
          value: ""
        - name: STRATO_PORT_BLOCKSTANBUL_VOTE
          value: ""
        - name: STRATO_PORT_LOGS
          value: ""
        - name: STRATO_PORT_VAULT_PROXY
          value: ""
        - name: vmDebug
          value: ""
      - image: swaggerapi/swagger-ui:v3.22.1
        name: docs
        env:
        - name: API_URL
          value: "/strato-api/eth/v1.2/swagger.json"
      - image: zookeeper:3.4.14
        name: zookeeper
        volumeMounts:
          - mountPath: /data
            name: zookeeper-data
        env:
        - name: ZOO_DATA_LOG_DIR
          value: "/data"
      - image: wurstmeister/kafka:1.1.0
        name: kafka
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "localhost"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "localhost:2181"
        - name: KAFKA_DELETE_TOPIC_ENABLE
          value: "true"
        - name: KAFKA_LOG_CLEANER_ENABLE
          value: "false"
        - name: KAFKA_LOG_DIRS
          value: "/kafka/kafka-logs"
        - name: KAFKA_OFFSET_METADATA_MAX_BYTES
          value: "1048576"
        - name: KAFKA_OFFSETS_RETENTION_MINUTES
          value: "2147483647"
        - name: KAFKA_MAX_REQUEST_SIZE
          value: "100663296"
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "100663296"
        volumeMounts:
          - mountPath: /kafka
            name: kafka-data
      - image: <REPO_URL>/prometheus:<VERSION>
        name: prometheus
        env:
        - name: NODE_HOST
          value: "localhost"
        volumeMounts:
          - mountPath: /prometheus
            name: prometheus-data
        securityContext:
          runAsUser: 0
      volumes:
        - name: marketplace-data
          persistentVolumeClaim:
            claimName: ebs-claim-marketplace-data
        - name: postgres-data
          persistentVolumeClaim:
            claimName: ebs-claim-postgres-data
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: ebs-claim-prometheus-data
        - name: kafka-data
          persistentVolumeClaim:
            claimName: ebs-claim-kafka-data
        - name: redis-data
          persistentVolumeClaim:
            claimName: ebs-claim-redis-data
        - name: strato-data
          persistentVolumeClaim:
            claimName: ebs-claim-strato-data
        - name: zookeeper-data
          persistentVolumeClaim:
            claimName: ebs-claim-zookeeper-data
---
apiVersion: v1
kind: Service
metadata:
  namespace: strato-platform
  name: service-strato
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: strato-platform
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: strato-platform
  name: ingress-strato
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-strato
              port:
                number: 80
