name: blockapps-vault-wrapper-client
version: 0.1.0.0
synopsis: Vault Wrapper microservice
description: Vault Wrapper microservice
github: blockapps/strato-platform/blockapps-haskell/vault-wrapper
license-file: LICENSE
author: Dustin Norwood
maintainer: dustin@blockapps.net
copyright: 2018 BlockApps
category: Web
build-type: Simple

ghc-options: -Wall

dependencies:
  - base
  - blockapps-ethereum
  - blockapps-vault-wrapper-api
  - aeson
  - containers
  - http-client
  - servant
  - servant-client
  - text

library:
  source-dirs: src/
