name: blockapps-bloc22-api
version: 0.1.0.0
synopsis: Bloc microservice
description: Bloc microservice
github: blockapps/strato-platform/blockapps-haskell/blockapps-bloc
license: BSD3
license-file: LICENSE
author: Eitan Chatav
maintainer: eitan@blockapps.net
copyright: 2016 BlockApps
category: Web
build-type: Simple

ghc-options: -Wall -Werror

dependencies:
  - base
  - aeson
  - aeson-casing
  - base16-bytestring
  - base64-bytestring
  - blockapps-ethereum
  - blockapps-solidity
  - blockapps-strato-api
  - containers
  - cryptonite
  - bytestring
  - generic-random
  - gitrev
  - haskoin-shim
  - http-api-data
  - http-media
  - lens
  - QuickCheck
  - quickcheck-instances
  - saltine
  - servant
  - servant-server
  - servant-swagger
  - servant-swagger-ui
  - servant-docs
  - servant-mock
  - swagger2
  - text

library:
  source-dirs: src/

tests:
  api-test:
    source-dirs: test/
    main: APISpec.hs
    dependencies:
      - aeson-qq
      - blockapps-bloc22-api
      - hspec
