name: seqevents
license: Apache-2.0

dependencies:
  - base
  - binary
  - blockapps-data
  - blockapps-datadefs

library:
  source-dirs: src/
  ghc-options: -fconstraint-solver-iterations=8
  dependencies:
    - blockDB
    - blockstanbul
    - bytestring
    - format
    - kafka-monad
    - merkle-patricia-db
    - monad-alter
    - prometheus-client
    - strato-conf
    - strato-model
    - text

tests:
  seqevents-spec:
    source-dirs: test/
    main: EventSpec.hs
    ghc-options: -dynamic
    dependencies:
      - blockDB
      - hspec
      - seqevents
      - QuickCheck
