name:                ethereum-jsonrpc
version:             0.1.0.0
synopsis:            Initial project template from stack
description:         Please see README.md
category:            Web
build-type:          Simple

executables:
  ethereum-jsonrpc:
    source-dirs:      src
    main:             Main.hs
    ghc-options:      -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - base
      - aeson
      - base16-bytestring
      - binary
      - blaze-builder
      - blockapps-data
      - blockapps-util
      - bytestring
      - containers
      - cryptohash
      - ethereum-rlp
      - blockapps-haskoin
      - http-client
      - http-types
      - json-rpc-server
      - blockapps-milena
      - mtl
      - random
      - strato-conf
      - strato-model
      - seqevents
      - text
      - unordered-containers
      - vector
      - wai
      - warp
