import "../items/contracts/Art.sol";
import "../items/contracts/BridgeableTokens.sol";
import "../items/contracts/CarbonDAO.sol";
import "../items/contracts/CarbonOffset.sol";
import "../items/contracts/Collectibles.sol";
import "../items/contracts/Membership.sol";
import "../items/contracts/Metals.sol";
import "../items/contracts/Spirits.sol";
import "../items/contracts/Tokens.sol";
import "Templates/Escrows/SimpleEscrow.sol";
import "Templates/Payments/ExternalPaymentService.sol";
import "Templates/Payments/TokenPaymentService.sol";
// import "Templates/Payments/TokenPaymentService.sol";
import "Templates/Oracles/SimpleOracleService.sol";
import "Templates/Redemptions/ExternalRedemptionService.sol";
import "Templates/Sales/SimpleSale.sol";
import "Templates/Staking/SimpleReserve.sol";
