dockerauth:
  image: cesanta/docker_auth
  ports:
    - "5001:5001"
  volumes:
    - ./auth_server/config:/config:ro
    - /var/log/docker_auth:/logs
    - ./auth_server/ssl:/ssl
    - ./auth_server/tokens:/tokens 
  command: --v=2 --alsologtostderr /config/auth_config.yml
  restart: always

registry:
  image: registry:2
  ports:
    - "0.0.0.0:5000:5000"
  volumes:
    - ./auth_server/ssl:/ssl
    - /datadrive/docker_registry/data:/var/lib/registry
  restart: always
  environment:
    - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
    # doesn't work https://github.com/docker/distribution/issues/1736
    #- REGISTRY_STORAGE_MAINTENANCE_UPLOADPURGING_ENABLED=true
    #- REGISTRY_STORAGE_MAINTENANCE_UPLOADPURGING_AGE=10m
    #- REGISTRY_STORAGE_MAINTENANCE_UPLOADPURGING_INTERVAL=30s
    #- REGISTRY_STORAGE_MAINTENANCE_UPLOADPURGING_DRYRUN=true
    #- REGISTRY_STORAGE_MAINTENANCE_READONLY_ENABLED=true
    - REGISTRY_AUTH=token
    - REGISTRY_AUTH_TOKEN_REALM=https://auth.blockapps.net:5001/auth
    - REGISTRY_AUTH_TOKEN_SERVICE="Docker registry"
    - REGISTRY_AUTH_TOKEN_ISSUER="BlockApps auth server"
    - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/ssl/server.pem
    - REGISTRY_HTTP_TLS_KEY=/ssl/server.key 
    - REGISTRY_HTTP_TLS_CERTIFICATE=/ssl/server.pem
 
