name:                strato-conf
version:             0.1.0.0
author:              Jamshid
category:            Web
build-type:          Simple

library:
  source-dirs:      src
  dependencies:
    - base
    - bytestring
    - directory
    - filepath
    - hflags
    - network
    - yaml
    - postgresql-simple
    - containers
    - file-embed
    - milena
    - mtl
    - transformers
    - hedis
    - swagger2
