name:                strato-conf
version:             0.1.0.0
author:              Jamshid
category:            Web
build-type:          Simple
license:             Apache-2.0



library:
  source-dirs:      src
  # ghc-options: -Wall -Werror

  # -fsimpl-tick-factor=800 -funfolding-case-threshold=140 -funfolding-case-scaling=8 
  # # 

  dependencies:
    - aeson
    - base
    - bytestring
    - data-default
    - file-embed
    - hedis
    - kafka-monad
    - postgresql-simple
    - process
    - servant-client
    - strato-model
    - template-haskell
    - text
    - yaml
