name: strato-lite
version: 0.0.1
build-type: Simple
author: Dustin Norwood
maintainer:    dustin@blockapps.net
synopsis: An API and server used for simulating a STRATO network
category:      Debuggers
description:
     An API and server used for simulating a STRATO network

dependencies:
  - base
  - strato-networks
  - vm-tools

executables:
  strato-lite:
    source-dirs: exec_src/
    ghc-options: -Wall -Werror 
    main: Main.hs
    dependencies:
      - aeson
      - bytestring
      - hflags
      - strato-lite
      - strato-model
      - strato-p2p
      - vm-tools

library:
  source-dirs: src/
  ghc-options: -Wall -O2 
  dependencies:
  - aeson
  - bloc2
  - bloc2api
  - cache
  - clock
  - core-api2
  - conduit-extra
  - containers
  - crypto-pubkey-types
  - extra
  - filepath
  - hflags
  - monad-alter
  - servant-server
  - text
  - unliftio
  - warp
  - base16-bytestring
  - binary
  - blockDB
  - blockapps-data
  - blockapps-datadefs
  - blockapps-mpdbs
  - blockstanbul
  - bytestring
  - common-log
  - composable-monads-base
  - conduit
  - containers
  - data-default
  - directory
  - debugger
  - ethereum-discovery
  - ethereum-encryption
  - ethereum-rlp
  - exceptions
  - format
  - hflags
  - identity-monad
  - lens
  - leveldb-haskell
  - merkle-patricia-db
  - monad-alter
  - monad-logger
  - monadIO
  - mtl
  - network
  - nibblestring
  - ordered-containers
  - pem
  - persistent
  - persistent-sqlite
  - prometheus-client
  - Ranged-sets
  - resourcet
  - resource-pool
  - seqevents
  - slipstream
  - solid-vm-compiler
  - solid-vm-model
  - sqlite-simple
  - stm-chans
  - stm-conduit
  - strato-genesis
  - strato-index
  - strato-init
  - strato-model
  - strato-p2p
  - strato-sequencer
  - strato-statediff
  - text
  - time
  - transformers
  - unliftio
  - vault-monad
  - vector
  - vm-runner
  - vm-tools

tests:
  simulator-spec:
    source-dirs: tests/
    main: Main.hs
    ghc-options: -Wall -Werror -dynamic
    dependencies:
      - QuickCheck
      - blockDB
      - blockapps-data
      - blockapps-datadefs
      - blockapps-mpdbs
      - blockstanbul
      - bytestring
      - common-log
      - conduit
      - containers
      - ethereum-encryption
      - hflags
      - ki-unlifted
      - labeled-error
      - hspec
      - lens
      - monad-alter
      - mtl
      - raw-strings-qq
      - seqevents
      - solid-vm-model
      - stm-chans
      - stm-conduit
      - strato-lite
      - strato-model
      - strato-p2p
      - strato-sequencer
      - text
      - unliftio
      - vm-tools
