name: strato-lite
version: 0.0.1
build-type: Simple
author: Dustin Norwood
maintainer:    dustin@blockapps.net
synopsis: An API and server used for simulating a STRATO network
category:      Debuggers
description:
     An API and server used for simulating a STRATO network

dependencies:
  - base

executables:
  strato-lite:
    source-dirs: exec_src/
    ghc-options: -Wall -Werror -dynamic
    main: Main.hs
    dependencies:
      - aeson
      - blockapps-init
      - bytestring
      - hflags
      - lifted-async
      - ordered-containers
      - strato-lite
      - strato-p2p
      - vm-tools
      - warp

library:
  source-dirs: src/
  exposed-modules:
    - Strato.Lite
    - Strato.Lite.Options
  ghc-options: -Wall -O2 -dynamic
  dependencies:
  - QuickCheck
  - aeson
  - async
  - containers
  - crypto-pubkey-types
  - deepseq
  - hflags
  - monad-alter
  - parsec
  - QuickCheck
  - quickcheck-instances
  - servant-server
  - source-tools
  - text
  - unliftio
  - warp
  - websockets
  - base16-bytestring
  - blockapps-data
  - blockapps-datadefs
  - blockapps-mpdbs
  - blockapps-privacy
  - blockstanbul
  - bytestring
  - common-log
  - conduit
  - containers
  - data-default
  - debugger
  - ethereum-discovery
  - ethereum-encryption
  - ethereum-rlp
  - hflags
  - hspec
  - hspec-expectations-lifted
  - labeled-error
  - lens
  - merkle-patricia-db
  - monad-alter
  - monadIO
  - mtl
  - network
  - nibblestring
  - ordered-containers
  - Ranged-sets
  - raw-strings-qq
  - secp256k1-haskell
  - seqevents
  - stm-chans
  - stm-conduit
  - strato-index
  - strato-model
  - strato-p2p
  - strato-sequencer
  - text
  - time
  - transformers
  - unliftio
  - vm-runner
  - vm-tools
  - x509-certs

tests:
  simulator-spec:
    source-dirs: tests/
    main: Main.hs
    ghc-options: -Wall -Werror -dynamic
    dependencies:
      - aeson
      - debugger
      - hflags
      - hspec
      - hspec-expectations-lifted
      - QuickCheck
      - async
      - containers
      - crypto-pubkey-types
      - deepseq
      - monad-alter
      - parsec
      - QuickCheck
      - quickcheck-instances
      - servant-server
      - source-tools
      - text
      - unliftio
      - warp
      - websockets
      - base16-bytestring
      - blockapps-data
      - blockapps-datadefs
      - blockapps-mpdbs
      - blockapps-privacy
      - blockstanbul
      - bytestring
      - common-log
      - conduit
      - containers
      - data-default
      - debugger
      - ethereum-discovery
      - ethereum-rlp
      - hflags
      - labeled-error
      - lens
      - merkle-patricia-db
      - monad-alter
      - mtl
      - nibblestring
      - ordered-containers
      - raw-strings-qq
      - secp256k1-haskell
      - seqevents
      - stm-chans
      - stm-conduit
      - strato-index
      - strato-lite
      - strato-model
      - strato-p2p
      - strato-sequencer
      - text
      - transformers
      - unliftio
      - vm-runner
      - vm-tools
      - x509-certs