name: strato-lite
version: 0.0.1
build-type: Simple
author: Dustin Norwood
maintainer:    dustin@blockapps.net
synopsis: An API and server used for simulating a STRATO network
category:      Debuggers
description:
     An API and server used for simulating a STRATO network

dependencies:
  - base

executables:
  strato-lite:
    source-dirs: exec_src/
    main: Main.hs
    dependencies:
      - aeson
      - blockapps-init
      - bytestring
      - hflags
      - lifted-async
      - ordered-containers
      - strato-lite
      - warp

library:
  source-dirs: src/
  exposed-modules:
    - Strato.Lite
    - Strato.Lite.Options
  ghc-options: -Wall -O2
  dependencies:
  - QuickCheck
  - aeson
  - async
  - containers
  - deepseq
  - hflags
  - monad-alter
  - parsec
  - QuickCheck
  - quickcheck-instances
  - servant-server
  - source-tools
  - text
  - unliftio
  - warp
  - websockets
  - base16-bytestring
  - blockapps-data
  - blockapps-datadefs
  - blockapps-mpdbs
  - blockapps-privacy
  - blockstanbul
  - bytestring
  - common-log
  - conduit
  - containers
  - data-default
  - debugger
  - ethereum-discovery
  - ethereum-rlp
  - hflags
  - hspec
  - hspec-expectations-lifted
  - labeled-error
  - lens
  - merkle-patricia-db
  - monad-alter
  - mtl
  - nibblestring
  - ordered-containers
  - raw-strings-qq
  - secp256k1-haskell
  - seqevents
  - stm-chans
  - stm-conduit
  - strato-index
  - strato-model
  - strato-p2p
  - strato-sequencer
  - text
  - transformers
  - unliftio
  - vm-runner
  - vm-tools
  - x509-certs

tests:
  debugger-spec:
    source-dirs: tests/
    main: Main.hs
    dependencies:
      - aeson
      - debugger
      - hflags
      - hspec
      - QuickCheck