name: haskoin-shim
description: "Bindings to make blockapps-haskoin appear like secp256k1"

dependencies:
  - base
  - blockapps-haskoin
  - QuickCheck

library:
  source-dirs:
    src/
  dependencies:
    - binary
    - bytestring
    - ethereum-encryption
    - fast-ecrecover
    - strato-model

tests:
  stolen-secp256k1-tests:
    source-dirs: test/
    main: Spec.hs
    dependencies:
      - haskoin-shim
      - hspec
