name:                test-suite
version:             0.1.0.0
author:              jamshid
maintainer:          jamshid
build-type:          Simple

dependencies:
  - QuickCheck
  - aeson
  - ansi-wl-pprint
  - base
  - base16-bytestring
  - binary
  - blockapps-data
  - blockapps-haskoin
  - blockapps-milena
  - blockapps-util
  - bytestring
  - conduit
  - containers
  - crypto-pubkey-types
  - cryptohash
  - deepseq
  - derive
  - directory
  - either
  - ethereum-discovery
  - ethereum-encryption
  - ethereum-rlp
  - ethereum-vm
  - fast-ecrecover
  - hedis
  - hflags
  - hspec
  - hspec-contrib
  - hspec-expectations-lifted
  - lens-family
  - lens-family-th
  - leveldb-haskell
  - merkle-patricia-db
  - monad-logger
  - mtl
  - network
  - nibblestring
  - resourcet
  - strato-conf
  - strato-model
  - strato-p2p
  - strato-redis-blockdb
  - seqevents
  - text
  - time
  - transformers
  - unboxed-ref
  - unordered-containers
  - vm-runner
  - vm-tools

ghc-options: -Wall -Werror -threaded

library:
  source-dirs: src/

tests:
  vm-tests:
    source-dirs:
      - test/
    main: TestMain.hs
    dependencies:
      - test-suite
    other-modules: []

  unittests:
    source-dirs: test
    main: UnitTest.hs
    dependencies:
      - interpolatedstring-perl6
      - test-suite
    other-modules: []

  test-suite:
    source-dirs: test
    main: Spec.hs
    other-modules: []
