{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
module Blockchain.VM.Opcodes where

import           Control.DeepSeq
import           GHC.Generics
import           Prelude                      hiding (EQ, GT, LT)

type CodePointer = Int

data Operation =
    -- 0x00
    STOP | ADD | MUL | SUB | DIV | SDIV | MOD | SMOD |
    ADDMOD | MULMOD | EXP | SIGNEXTEND | UU0C | UU0D | UU0E | UU0F |
    -- 0x10
    LT | GT | SLT | SGT | EQ | ISZERO | AND | OR |
    XOR | NOT | BYTE | UU1B | UU1C | UU1D | UU1E | UU1F |
    -- 0x20
    SHA3 | UU21 | UU22 | UU23 | UU24 | UU25 | UU26 | UU27 |
    UU28 | UU29 | UU2A | UU2B | UU2C | UU2D | UU2E | UU2F |
    -- 0x30
    ADDRESS | BALANCE | ORIGIN | CALLER | CALLVALUE | CALLDATALOAD | CALLDATASIZE | CALLDATACOPY |
    CODESIZE | CODECOPY | GASPRICE | EXTCODESIZE | EXTCODECOPY | RETURNDATASIZE | RETURNDATACOPY | UU3F |
    -- 0x40
    BLOCKHASH | COINBASE | TIMESTAMP | NUMBER | DIFFICULTY | GASLIMIT | UU46 | UU47 |
    UU48 | UU49 | UU4A | UU4B | UU4C | UU4D | UU4E | UU4F |
    -- 0x50
    POP | MLOAD | MSTORE | MSTORE8 | SLOAD | SSTORE | JUMP | JUMPI |
    PC | MSIZE | GAS | JUMPDEST | UU5C | UU5D | UU5E | UU5F |
    -- 0x60
    PUSH1 | PUSH2 | PUSH3 | PUSH4 | PUSH5 | PUSH6 | PUSH7 | PUSH8 |
    PUSH9 | PUSH10 | PUSH11 | PUSH12 | PUSH13 | PUSH14 | PUSH15 | PUSH16 |
    -- 0x70
    PUSH17 | PUSH18 | PUSH19 | PUSH20 | PUSH21 | PUSH22 | PUSH23 | PUSH24 |
    PUSH25 | PUSH26 | PUSH27 | PUSH28 | PUSH29 | PUSH30 | PUSH31 | PUSH32 |
    -- 0x80
    DUP1 | DUP2 | DUP3 | DUP4 | DUP5 | DUP6 | DUP7 | DUP8 |
    DUP9 | DUP10 | DUP11 | DUP12 | DUP13 | DUP14 | DUP15 | DUP16 |
    -- 0x90
    SWAP1 | SWAP2 | SWAP3 | SWAP4 | SWAP5 | SWAP6 | SWAP7 | SWAP8 |
    SWAP9 | SWAP10 | SWAP11 | SWAP12 | SWAP13 | SWAP14 | SWAP15 | SWAP16 |
    -- 0xa0
    LOG0 | LOG1 | LOG2 | LOG3 | LOG4 | UUA5 | UUA6 | UUA7 |
    UUA8 | UUA9 | UUAA | UUAB | UUAC | UUAD | UUAE | UUAF |
    -- 0xb0
    UUB0 | UUB1 | UUB2 | UUB3 | UUB4 | UUB5 | UUB6 | UUB7 |
    UUB8 | UUB9 | UUBA | UUBB | UUBC | UUBD | UUBE | UUBF |
    -- 0xc0
    UUC0 | UUC1 | UUC2 | UUC3 | UUC4 | UUC5 | UUC6 | UUC7 |
    UUC8 | UUC9 | UUCA | UUCB | UUCC | UUCD | UUCE | UUCF |
    -- 0xd0
    UUD0 | UUD1 | UUD2 | UUD3 | UUD4 | UUD5 | UUD6 | UUD7 |
    UUD8 | UUD9 | UUDA | UUDB | UUDC | UUDD | UUDE | UUDF |
    -- 0xe0
    UUE0 | UUE1 | UUE2 | UUE3 | UUE4 | UUE5 | UUE6 | UUE7 |
    UUE8 | UUE9 | UUEA | UUEB | UUEC | UUED | UUEE | UUEF |
    -- 0xf0
    CREATE | CALL | CALLCODE | RETURN | DELEGATECALL | UUF5 | UUF6 | UUF7 |
    UUF8 | UUF9 | STATICCALL | UUFB | UUFC | REVERT | INVALID | SUICIDE
  deriving (Show, Eq, Ord, Generic, NFData, Enum)
