name: strato
version: 0.1.0.0
github: "githubuser/strato"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2024 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/strato#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - base16-bytestring
  - binary
  - bloc2
  - bloc2api
  - bloc2client
  - blockstanbul
  - bytestring
  - cache
  - clock
  - common-log
  - containers
  - core-api2
  - cryptonite
  - data-default
  - ethereum-discovery
  - ethereum-encryption
  - evm-solidity
  - filepath
  - file-embed
  - haskoin-core
  - hflags
  - http-client
  - jsaddle
  - jsaddle-warp
  - jsaddle-dom
  - lens
  - memory
  - reflex
  - reflex-dom
  - reflex-dom-core
  - resourcet
  - scientific
  - servant
  - servant-client
  - servant-server
  - servant-websockets
  - strato-lite
  - strato-model
  - strato-p2p
  - text
  - unliftio
  - vm-tools
  - wai
  - wai-cors
  - wai-extra
  - wai-middleware-static
  - warp
  - websockets
  - wreq

library:
  source-dirs: 
    - src
  dependencies:
    - aeson
    - bytestring
    - containers
    - filepath
    - lens
    - jsaddle
    - jsaddle-warp
    - jsaddle-dom
    - reflex
    - reflex-dom
    - reflex-dom-core
    - servant
    - servant-client
    - servant-websockets
    - strato-lite
    - text
    - time
    - unix
    - wai
    - wai-middleware-static
    - wai-cors
    - warp
    - wai-extra
    - websockets

executables:
  strato:
    main: Main.hs
    other-modules: []
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N8
    dependencies:
      - strato
      - jsaddle
    when:
      - condition: os(linux)
        then:
          dependencies:
            - jsaddle-webkit2gtk
        else:
          dependencies:
            - jsaddle-wkwebview

tests:
  strato-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - strato 