#!/bin/bash
set -e

function setEnv {
  [[ -n ${!1} ]] || eval $1=$2
  echo "$1 = ${!1}"
}

setEnv blocUrl "http://localhost:10001/bloc/v2.1"
setEnv stratoUrl "http://localhost/strato-api/eth/v1.2"
#setEnv stratoUrl "http://tester13.eastus.cloudapp.azure.com/strato-api/eth/v1.2"

function customHttp { # set behavior of http I like....  crash on error, print body to stderr, timeout longer

  set +e
  output=`http -b --check-status --timeout=60 "$@"`
  returnVal=$?
  set -e
  

  if [ "$returnVal" == "0" ]
  then
    echo "$output"
  else
    echo "$output" >&2
    exit $returnVal
  fi
}

echo "#################################################"
echo "# Creating a new address and running the faucet #"
echo "#################################################"

address=`customHttp --form $blocUrl/users/fred password=qqqq faucet=1`

echo "Here are the details of the new address '$address':"

customHttp $stratoUrl/account?address=$address | jq .
echo ""

src=$(cat ../Contracts/CallTest.sol)
echo $src

request=`echo '{"password":"qqqq", "args": {}, "value": 0, "txParams":{}, "contract":"CallTest"}' | jq --arg src "$src" '.src= $src '`

echo $request

echo "########################"
echo "# Uploading a contract #"
echo "########################"

echo "$request" | customHttp POST $blocUrl/users/fred/$address/contract "Accept: */*"

echo ""

echo "######################################"
echo "# calling a function in new contract #"
echo "######################################"

#customHttp $blocUrl/users/fred/$address/contract/CallTest/Latest/call | jq .
echo '{"password": "qqqq", "method": "getIt", "args":{}, "value": 0}' | customHttp POST $blocUrl/users/fred2/$address/contract/CallTest/45003a173bc74ee7c25c7798e6748a106fac4a72/call "Accept: */*" | jq .

#users/testUser/111dec89c25cbda1c12d67621ee3c10ddb8196bf/contract/SimpleStorage/45003a173bc74ee7c25c7798e6748a106fac4a72/call",
