name: blockapps-bloc22-client
version: 0.1.0.0
synopsis: Bloc microservice client
description: Bloc microservice client
github: blockapps/strato-platform/blockapps-haskell/bloc/client
license-file: LICENSE
author: Eitan Chatav
maintainer: eitan@blockapps.net
copyright: 2016 BlockApps
category: Web
build-type: Simple

ghc-options: -Wall -Werror

dependencies:
  - base
  - blockapps-bloc22-api
  - blockapps-ethereum
  - blockapps-solidity
  - blockapps-strato-api
  - containers
  - servant-client
  - text

library:
  source-dirs: src/

tests:
  blockapps-bloc22-client-test:
    source-dirs: test
    main: Spec.hs
    dependencies:
     - blockapps-bloc22-client
     - blockapps-strato-client
     - base16-bytestring
     - bytestring
     - hspec
     - http-client
     - quickcheck-instances
     - QuickCheck
     - servant-aeson-specs
     - vector
