name:              strato-api
version:           0.0.0
build-type:        Simple

flags:
  dev:
    description:   Turn on development settings, like auto-reload templates.
    default:       True
    manual:        True
  library-only:
    description:   Build for use with "yesod devel"
    default:       False
    manual:        True

default-extensions:
  - TemplateHaskell
  - QuasiQuotes
  - OverloadedStrings
  - NoImplicitPrelude
  - CPP
  - MultiParamTypeClasses
  - TypeFamilies
  - GADTs
  - GeneralizedNewtypeDeriving
  - FlexibleContexts
  - EmptyDataDecls
  - NoMonomorphismRestriction
  - DeriveDataTypeable
  - ViewPatterns
  - TupleSections
  - RecordWildCards

dependencies:
  - base

library:
    source-dirs:
      - src
      - exec_src
    when:
      - condition: flag(dev) || flag(library-only)
        then:
          cpp-options:   -DDEVELOPMENT
          ghc-options:   -Wall -fwarn-tabs -O0
        else:
          ghc-options:   -Wall -fwarn-tabs -O2
    extra-libraries: pthread
    dependencies:
      - aeson
      - base16-bytestring
      - base64-bytestring
      - binary
      - blaze-html
      - blockapps-data
      - blockapps-datadefs
      - blockapps-haskoin
      - blockapps-util
      - bytestring
      - classy-prelude-yesod
      - clock
      - conduit
      - containers
      - directory
      - esqueleto
      - ethereum-discovery
      - extra
      - fast-logger
      - file-embed
      - filepath
      - format
      - monad-alter
      - mtl
      - persistent
      - persistent-postgresql
      - postgresql-simple
      - process
      - seqevents
      - shakespeare
      - strato-conf
      - strato-model
      - template-haskell
      - text
      - time
      - unliftio-core
      - wai
      - wai-extra
      - wai-middleware-prometheus
      - warp
      - warp-tls
      - yaml
      - yesod
      - yesod-core

executables:
  strato-api:
    when:
      - condition: flag(library-only)
        buildable: False
    main:           main.hs
    source-dirs:    exec_src
    dependencies:
      - blockapps-init
      - strato-api
    extra-libraries: pthread
    ghc-options: -threaded -O2 -rtsopts -with-rtsopts=-N

tests:
  strato-api-tests:
    main:           Main.hs
    source-dirs:    test
    ghc-options:    -Wall
    extra-libraries: pthread
    dependencies:
      - aeson
      - blockapps-data
      - blockapps-datadefs
      - blockapps-util
      - bytestring
      - case-insensitive
      - classy-prelude
      - containers
      - ethereum-discovery
      - hspec
      - hspec-expectations
      - HUnit
      - monad-alter
      - mtl
      - persistent
      - QuickCheck
      - strato-api
      - text
      - time
      - unliftio-core
      - wai-extra
      - yaml
      - yesod
      - yesod-core
      - yesod-test

  unittests:
    main: Spec.hs
    source-dirs: unittest
    dependencies:
      - classy-prelude
      - hspec-core
      - hspec-expectations-lifted
      - strato-api
