name:                strato-adit
version:             0.1.0.0
license:             Apache-2.0
license-file:        LICENSE
author:              Kristoffer Josefsson
maintainer:          kristoffer@blockapps.net
build-type:          Simple

ghc-options: -Wall -O2

dependencies:
  - base
  - ansi-wl-pprint
  - blockapps-data
  - blockapps-datadefs
  - blockapps-milena
  - blockapps-util
  - bytestring
  - containers
  - cryptohash
  - ethereum-discovery
  - ethereum-rlp
  - format
  - hflags
  - lens
  - lifted-base
  - mtl
  - normaldistribution
  - random
  - resourcet
  - seqevents
  - stm
  - strato-conf
  - text
  - time
  - unliftio

other-extensions: OverloadedStrings

library:
  source-dirs: src
  other-modules:
    - Executable.AditM

executables:
  strato-adit:
    main:             Main.hs
    source-dirs:      exec_src
    dependencies:
      - strato-adit
