@startuml
autonumber

title "Bridge-In Flow Diagram"

actor "\n User \n" as user
control "\n Mercata UI \n" as mercataUI
control "\n Mercata Backend \n" as mercataBackend
control "\n Metamask \n" as metamask
database "\n  Safe Wallet  \n" as safeWallet
control "\n  Relayer  \n" as bridgingService
control "\n Alchemy API \n" as alchemy
database "\n  STRATO Node \n" as strato
autonumber 100

user -> mercataUI: Access application \n(AUTHENTICATED)
user -> metamask: Authenticate
mercataUI -> metamask: Initialize bridge-in \nw/ token_address, amount, safe_address
user -> metamask: Approve txn
metamask -> safeWallet: (TXN ETH) Submit txn to Safe Wallet (signed via Metamask)
metamask --> mercataUI: return status - txn submitted \nw/ txn_hash
mercataUI -> mercataBackend: call to create MercataEthBridge contract \nw/ user access token, txn_hash, token_address
mercataBackend -> bridgingService: proxy the user request \nw/ user access token, txn_hash, token_address
bridgingService -> strato: obtain user's address by user's access token
bridgingService -> strato: (TXN Mercata) Create MercataEthBridge contract \nw/ txn_hash, token_address and recipient_ (user's address)\nw/relayer access token
bridgingService -> bridgingService: wait for the txn
bridgingService --> mercataBackend: respond contract created
mercataBackend --> mercataUI: proxy the response
mercataUI -> mercataUI: re-render ui to indicate pending bridge-in
group Waiting for new Safe deposits
alchemy -> bridgingService: Emit incoming Safe txns details
loop
bridgingService -> alchemy: Poll for new transactions to Safe Wallet\nw/ safe_address
end
bridgingService -> bridgingService: Keep track of already processed txns \n(TBD: HOW? MAKE SURE NOT TO PROCESS SAME txn_hash twice)
alchemy --> bridgingService: Responds with deposit details \nw/ txn_hash, token name, amount
bridgingService -> strato: Confirm that token by token_address matches \nthe token type received to Safe Wallet \n(?? TBD: how do we know the token_address at this point???) 
end
bridgingService -> strato: Search in Cirrus api \nfor MercataEthBridge contract by txn_hash
bridgingService -> strato: Make the token transaction to the user with address from recipient_
bridgingService -> strato: (TXN Mercata) Change status in MercataEthBridge to Confirmed \nAPI call w/ relayer's access token
user -> mercataUI: refresh page on demand to see bridge status
@enduml
