export const Images = {
  'logo': require("./resources/logo.png"),
  'noProductSymbol': require('./resources/noProductSymbol.png'),
  'noEventPageSymbol': require('./resources/no_event.png'),
  'art': require("./resources/categories/art.png"),
  'carbon': require("./resources/categories/carbon.png"),
  'clothing': require("./resources/categories/clothing.jpg"),
  'realEstate': require("./resources/categories/real_estate.png"),
  'metals': require("./resources/categories/metals.png"),
  'collectibles': require("./resources/categories/collectibles.jpg"),
  'membership': require("./resources/categories/membership.jpg"),
  'category1': require("./resources/categories/category1.png"),
  'category2': require("./resources/categories/category2.png"),
  'category3': require("./resources/categories/category3.png"),
  'category4': require("./resources/categories/category4.png"),
  'category5': require("./resources/categories/category5.png"),
  'category6': require("./resources/categories/category6.png"),
  'topSelling1': require("./resources/topSelling/topSelling1.png"),
  'topSelling2': require("./resources/topSelling/topSelling2.png"),
  'topSelling3': require("./resources/topSelling/topSelling3.png"),
  'hero': require("./resources/hero.png"),
  'hero2': require("./resources/carbon.jpg"),
  'orderImg1': require('./resources/orderImages/orderImg1.png'),
  'orderImg2': require('./resources/orderImages/orderImg2.png'),
  'orderImg3': require('./resources/orderImages/orderImg3.png'),
  'role-request': require('./resources/request-role.png'),
  'newLogo': require('./resources/newLogo.png'),
  'carousel_first': require('./resources/carousel_first_image.png'),
  'carousel_second': require('./resources/carousel_second_image.png'),
  'carousel_third': require('./resources/carousel_third_image.png'),
  'Carbon-category': require("./resources/categories/Carbon_category.png") ,  
  'Art-category': require("./resources/categories/Art_category.png") , 
  'Clothing-category': require("./resources/categories/Clothing_category.png") ,
  'Material-category': require("./resources/categories/Material_category.png") ,
  'Verified': require("./resources/topSelling/verifiedIcon.png"),
  'RemoveIcon' :  require("./resources/Remove.png"),
  'CancelIcon' : require("./resources/Cancel.png"),
  'Dropdown' :  require("./resources/DropDown.png"),
  'Cart' :  require("./resources/Cart.png"),
  'Backward' :  require("./resources/Backward.png"),
  'Forward' :  require("./resources/Forward.png"),
  'AddBlack' :  require("./resources/AddBlack.png"),
  'CreateInventory' :  require("./resources/createInventory.png"),
  'ForwardIcon' : require("./resources/Forward.png"),
  'Metal' : require("./resources/categories/metal.png"),
  'Metal_card' : require("./resources/categories/metal_card.png"),
  'art_card' : require("./resources/categories/art_card.png"),
  'carbon_card' : require("./resources/categories/carbon_card.png"),
  'membership_card' : require("./resources/categories/membership_card.jpg"),
  'menu_icon' : require("./resources/Ham_menu.png"),
  'Responsive_search' :  require("./resources/Responsive_Search.png"),
  'Responsive_cart'  : require("./resources/Responive_Cart.png"),
  'Header_cart' :  require("./resources/Header_Cart.png"),
  'Header_Search' :  require("./resources/Search.png"),
  'Setting_icon' :  require("./resources/Setting.png"),
};