export const Images = {
  'logo': require("./resources/logo.png"),
  'noProductSymbol': require('./resources/noProductSymbol.png'),
  'noEventPageSymbol': require('./resources/no_event.png'),
  'art': require("./resources/categories/art.png"),
  'carbon': require("./resources/categories/carbon.png"),
  'realEstate': require("./resources/categories/real_estate.png"),
  'category1': require("./resources/categories/category1.png"),
  'category2': require("./resources/categories/category2.png"),
  'category3': require("./resources/categories/category3.png"),
  'category4': require("./resources/categories/category4.png"),
  'category5': require("./resources/categories/category5.png"),
  'category6': require("./resources/categories/category6.png"),
  'topSelling1': require("./resources/topSelling/topSelling1.png"),
  'topSelling2': require("./resources/topSelling/topSelling2.png"),
  'topSelling3': require("./resources/topSelling/topSelling3.png"),
  'hero': require("./resources/hero.png"),
  'hero2': require("./resources/hero2.png"),
  'orderImg1': require('./resources/orderImages/orderImg1.png'),
  'orderImg2': require('./resources/orderImages/orderImg2.png'),
  'orderImg3': require('./resources/orderImages/orderImg3.png'),
  'role-request': require('./resources/request-role.png'),
};