name: ethereum-rlp
version: 0.1.0
build-type: Simple
author: Jamshid
license-file:  LICENSE
maintainer:    jamshidnh@gmail.com
synopsis: Ethereum Recursive Length Prefix Encoding
category:      Data Structures
license: Apache-2.0
description:
    RLP, as described in the Ethereum Yellowpaper

github: blockapps/strato-platform/core-strato/ethereum-rlp

default-extensions:
  - Arrows
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - LiberalTypeSynonyms
  - MagicHash
  - MultiParamTypeClasses
  - MultiWayIf
  - NoMonomorphismRestriction
  - OverloadedStrings
  - PatternGuards
  - ParallelListComp
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - TypeOperators
  - UnboxedTuples

dependencies:
  - bytestring == 0.10.*
  - base16-bytestring == 0.1.*
  - ansi-wl-pprint == 0.6.*
  - base >= 4 && < 5
  - containers == 0.5.11.0
  - deepseq
  - binary
  - text
  - transformers

library:
  source-dirs: library/
  exposed-modules: Blockchain.Data.RLP

tests:
  test:
    source-dirs: test/
    main: Main.hs
    dependencies:
      - test-framework == 0.8.*
      - test-framework-hunit == 0.3.*
      - HUnit == 1.*
      - hspec
      - ethereum-rlp

benchmarks:
  rlpserial:
    source-dirs: bench/
    main: RLPShootout.hs
    other-modules: []
    dependencies:
      - ethereum-rlp
      - criterion
      - random-bytestring

  zipbench:
    source-dirs: bench/
    main: ZipBench.hs
    other-modules: []
    dependencies:
      - ethereum-rlp
      - criterion
      - zlib
