version: '2'

services:
  zookeeper:
    image: $zookeeperImage
    restart: always
    ports:
      - "2181:2181"
  kafka:
    image: $kafkaImage
    restart: always
    links:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_LOG_CLEANER_ENABLE: "false"
      KAFKA_LOG_RETENTION_HOURS: 2147483647
  postgres:
    image: $postgresImage
    restart: always
  global-db:
    image: $globaldbImage
    links:
      - postgres
    environment:
      pghost : postgres
  strato:
    image: $stratoImage
    links:
      - zookeeper
      - kafka
      - postgres
    restart: always
    ports:
      - "30303:30303"
      - "30303:30303/udp"
    environment:
      fqdn : "${fqdn}"
      networkId : "${networkId}"
      genesis: "${genesis}"
      genesisBlock: "${genesisBlock}"
      bootnode: "${bootnode}"
      addBootnodes: "${addBootnodes}"
  bloc:
    image: $blocImage
    restart: always
    environment:
      fqdn: "${fqdn}/strato-api"
  explorer:
    image: $explorerImage
    depends_on:
      - bloc
    restart: always
    environment:
      peers: "${peers}"
  nginx:
    image: $nginxImage
    restart: always    
    volumes: 
      - /etc/ssl/private:/etc/ssl/private
      - /etc/ssl/certs:/etc/ssl/certs
    ports:
      - "443:443"
    depends_on:
      - strato
      - bloc
      - explorer
