name: blockapps-ethereum
version: 0.1.0.0
synopsis: Ethereum datatypes
description: Ethereum datatypes
author: Eitan Chatav
maintainer: eitan@blockapps.net
copyright: 2016 BlockApps
category: Web
build-type: Simple

ghc-options: -Wall -Werror

dependencies:
  - base
  - aeson
  - deepseq
  - http-api-data
  - QuickCheck
  - quickcheck-instances
  - relapse
  - strato-model

library:
  source-dirs: src/
  dependencies:
    - bytestring
    - containers
    - cryptonite
    - generic-random
    - lens
    - memory
    - servant
    - swagger2
    - text

tests:
  blockapps-ethereum-test:
    main: Main.hs
    source-dirs: test/
    dependencies:
      - base16-bytestring
      - blockapps-ethereum
      - clock
      - hspec
