name: blockapps-ethereum
version: 0.1.0.0
synopsis: Ethereum datatypes
description: Ethereum datatypes
github: blockapps/strato-platform/blockapps-haskell/blockapps-ethereum
license: BSD3
license-file: LICENSE
author: Eitan Chatav
maintainer: eitan@blockapps.net
copyright: 2016 BlockApps
category: Web
build-type: Simple

ghc-options: -Wall -Werror

dependencies:
  - base
  - aeson
  - base16-bytestring
  - binary
  - bytestring
  - classy-prelude
  - containers
  - cryptonite
  - deepseq
  - generic-random
  - hashable
  - http-api-data
  - largeword
  - lens
  - memory
  - QuickCheck
  - quickcheck-instances
  - relapse
  - secp256k1
  - servant
  - servant-docs
  - swagger2
  - text
  - time

library:
  source-dirs: src/

tests:
  blockapps-ethereum-test:
    main: Spec.hs
    source-dirs: test/
    dependencies:
      - blockapps-ethereum
      - clock
      - hspec
