name: strato-p2p
version: 0.0.4
build-type: Simple
author: Jamshid
license-file:  LICENSE
maintainer:    jamshidnh@gmail.com
synopsis: A Haskell version of an Ethereum client
category:      Data Structures
license: Apache-2.0
description:
    The client described in the Ethereum Yellowpaper
github: blockapps/strato-platform/core-strato/strato-p2p

dependencies:
  - array
  - async
  - base >= 4 && < 5
  - base16-bytestring
  - binary
  - aeson
  - blockapps-data
  - blockapps-datadefs
  - blockapps-util
  - bytestring
  - classy-prelude
  - conduit
  - conduit-combinators
  - conduit-extra
  - containers
  - cross-monitoring
  - cryptohash
  - crypto-pubkey
  - crypto-pubkey-types
  - dns
  - either
  - esqueleto
  - ethereum-discovery
  - ethereum-encryption
  - ethereum-rlp
  - exceptions
  - format
  - ghc
  - blockapps-haskoin
  - hflags
  - iproute
  - json-rpc-server
  - json-rpc-client
  - lens
  - lifted-base
  - monad-alter
  - monad-control
  - monadIO
  - blockapps-milena
  - mtl
  - network
  - persistent
  - prometheus-client
  - random
  - resourcet
  - SafeSemaphore
  - split
  - stm
  - stm-conduit
  - streaming-commons
  - strato-conf
  - text
  - time
  - transformers
  - transformers-base
  - wai-middleware-prometheus
  - warp
  - ansi-wl-pprint
  - strato-conf
  - seqevents
  - strato-model
  - strato-redis-blockdb
  - hedis
  - lifted-async
  - blockstanbul
  - unliftio-core
  - unliftio

ghc-options: -Wall -threaded

executables:
  strato-p2p:
    source-dirs: exec_src/
    main: StratoP2PMain.hs
    dependencies:
      - strato-p2p

library:
  source-dirs: src
  ghc-options: -Wall -O2

tests:
  strato-p2p-client-test:
    source-dirs: test
    ghc-options: -Wall -Werror
    main: Main.hs
    dependencies:
      - QuickCheck
      - hspec
      - hspec-expectations-lifted
      - persistent-sqlite
      - stm-chans
      - stm-conduit
      - strato-p2p
      - temporary
