name:                strato-api2

dependencies:
- base
- persistent
- persistent-postgresql
- servant-server
- strato-conf

executables:
  strato-api2:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - bloc2
    - bloc2api
    - blockapps-data
    - blockapps-init
    - blockapps-util
    - bytestring
    - core-api2
    - format
    - hflags
    - http-types
    - insert-ordered-containers
    - lens
    - monad-alter
    - monad-logger
    - mtl
    - servant-multipart
    - servant-swagger
    - servant-swagger-ui
    - sql-monad
    - swagger2
    - transformers
    - unliftio
    - wai
    - wai-cors
    - wai-extra
    - wai-middleware-prometheus
    - warp
