#!/bin/sh
set -e

### BEGIN INIT INFO
# Provides:          kafka
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Apache Kafka
# Description:       Apache Kafka, a high-throughput distributed messaging system.
### END INIT INFO

case "$1" in
    start)
	export KAFKA_HEAP_OPTS="-Xmx256M -Xms128M"
	/usr/lib/kafka/bin/kafka-server-start.sh /etc/kafka/server.properties > /var/log/kafka/kafka.log 2>&1 &
	exit 0
	;;
    stop)
	PIDS=$(ps ax | grep -i 'kafka\.Kafka' | grep java | grep -v grep | awk '{print $1}')
	if [ -z "$PIDS" ]; then
	    echo "kafka already down"
	    exit 1
	else
	    kill -TERM $PIDS
	    exit 0
	fi
        ;;
    status)
	PIDS=$(ps ax | grep -i 'kafka\.Kafka' | grep java | grep -v grep | awk '{print $1}')
	if [ -z "$PIDS" ]; then
	    exit 0
	else
	    exit 1
	fi
	;;
    *)
        echo "Usage: $0 {start|stop|restart|reload|force-reload|status} [version ..]"
        exit 1
        ;;
esac

exit 0

