{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE OverloadedStrings #-}

module Blockchain.Init.DockerComposeAllDocker (generateDockerComposeAllDocker) where

import Blockchain.Init.DirHash (computeDirHash)
import Blockchain.Strato.Version (stratoVersionTag)
import Data.List (foldl')
import Language.Haskell.TH
import System.Environment (lookupEnv)
import System.Process (readProcess)

readTemplateAtCompileTime :: Q Exp
readTemplateAtCompileTime = do
  content <- runIO $ readProcess "sh" ["-c",
    "cd $(git rev-parse --show-toplevel) && cat docker-compose.allDocker.tpl.yml"
    ] ""
  litE $ stringL content

templateContent :: String
templateContent = $(readTemplateAtCompileTime)

hashMercataBackend, hashMercataUi, hashSmd, hashApex :: String
hashPostgrest, hashNginx, hashPrometheus :: String
hashMercataBackend = $(computeDirHash "mercata/backend")
hashMercataUi = $(computeDirHash "mercata/ui")
hashSmd = $(computeDirHash "smd-ui")
hashApex = $(computeDirHash "apex")
hashPostgrest = $(computeDirHash "postgrest-packager")
hashNginx = $(computeDirHash "nginx-packager")
hashPrometheus = $(computeDirHash "prometheus-packager")

substituteAll :: [(String, String)] -> String -> String
substituteAll subs content = foldl' (\c (old, new) -> replace old new c) content subs
  where
    replace :: String -> String -> String -> String
    replace _ _ [] = []
    replace old new str@(x:xs)
      | take (length old) str == old = new ++ replace old new (drop (length old) str)
      | otherwise = x : replace old new xs

generateDockerComposeAllDocker :: IO ()
generateDockerComposeAllDocker = do
  repoUrl <- maybe "" id <$> lookupEnv "REPO_URL"
  
  -- Read the postgres password that was generated by Generator.hs
  pgPassword <- readFile "secrets/postgres_password"
  
  let substitutions =
        [ ("<VERSION>", stratoVersionTag)
        , ("<HASH_MERCATA_BACKEND>", hashMercataBackend)
        , ("<HASH_MERCATA_UI>", hashMercataUi)
        , ("<HASH_SMD>", hashSmd)
        , ("<HASH_APEX>", hashApex)
        , ("<HASH_POSTGREST>", hashPostgrest)
        , ("<HASH_NGINX>", hashNginx)
        , ("<HASH_PROMETHEUS>", hashPrometheus)
        , ("<REPO_URL>", repoUrl)
        , ("${postgres_password:-api}", pgPassword)
        ]
      
      result = substituteAll substitutions templateContent
  
  writeFile "docker-compose.yml" result
  putStrLn "  ✓ Generated docker-compose.yml (allDocker)"
