name: blockapps-bloc22-server
version: 0.1.0.0
synopsis: Bloc microservice
description: Bloc microservice
author: Eitan Chatav
maintainer: eitan@blockapps.net
copyright: 2016 BlockApps
category: Web
build-type: Simple


dependencies:
  - base
  - blockapps-solidity
  - containers
  - text

library:
  source-dirs: src/
  ghc-options: -Wall -Werror -fsimpl-tick-factor=15000
  dependencies:
    - aeson
    - base16-bytestring
    - bloc2api
    - blockapps-strato-api
    - bytestring
    - cache
    - clock
    - common-log
    - directory
    - filepath
    - http-client
    - mtl
    - opaleye
    - postgresql-simple
    - process
    - product-profunctors
    - profunctors
    - relapse
    - resource-pool
    - servant-client
    - servant-server
    - strato-model
    - temporary
    - transformers
    - unliftio
