name: blockapps-bloc22-server
version: 0.1.0.0
synopsis: Bloc microservice
description: Bloc microservice
github: blockapps/strato-platform/blockapps-haskell/blockapps-bloc
license: BSD3
license-file: LICENSE
author: Eitan Chatav
maintainer: eitan@blockapps.net
copyright: 2016 BlockApps
category: Web
build-type: Simple


dependencies:
  - base
  - aeson
  - aeson-casing
  - bimap
  - binary
  - blockapps-ethereum
  - blockapps-solidity
  - blockapps-bloc22-api
  - blockapps-strato-api
  - blockapps-strato-client
  - blockapps-vault-wrapper-api
  - blockapps-vault-wrapper-client
  - classy-prelude
  - clock
  - common-log
  - containers
  - contravariant
  - cryptonite
  - directory
  - extra
  - filepath
  - bytestring
  - base16-bytestring
  - generic-random
  - either
  - hflags
  - http-client
  - http-conduit
  - http-media
  - http-types
  - insert-ordered-containers
  - lens
  - lifted-async
  - lifted-base
  - memory
  - monad-control
  - monad-loops
  - mtl
  - network
  - opaleye
  - ordered-containers
  - postgresql-simple
  - prettyprinter
  - process
  - product-profunctors
  - profunctors
  - QuickCheck
  - quickcheck-instances
  - relapse
  - resource-pool
  - saltine
  - secp256k1
  - servant
  - servant-client
  - servant-docs
  - servant-mock
  - servant-server
  - servant-swagger
  - servant-swagger-ui
  - stm
  - strato-model
  - swagger2
  - text
  - temporary
  - time
  - transformers
  - transformers-base
  - unordered-containers
  - wai-cors
  - wai-extra
  - warp
  - wl-pprint-text

library:
  source-dirs: src/
  ghc-options: -Wall -Werror -fsimpl-tick-factor=15000

tests:
  blockapps-bloc22-server-test:
    source-dirs: test/
    main: Spec.hs
    ghc-options: -Wall -Werror
    dependencies:
      - blockapps-bloc22-server
      - hspec
      - parsec
