name:                strato-model
version:             0.1.0.0
author:              BlockApps
maintainer:          blockapps
build-type:          Simple
license:             Apache-2.0

library:
  dependencies:
    - aeson
    - ansi-wl-pprint
    - base
    - base16-bytestring
    - containers
    - ethereum-rlp
    - binary
    - bytestring
    - cryptonite
    - deepseq
    - lens
    - path-pieces
    - memory
    - nibblestring
    - blockapps-haskoin
    - text
    - time
    - QuickCheck
    - http-api-data
  source-dirs: src
  default-extensions:
    - MultiParamTypeClasses
    - FlexibleContexts
    - FlexibleInstances
    - GeneralizedNewtypeDeriving
    - GADTs
    - LambdaCase
    - RecordWildCards
    - FunctionalDependencies
  ghc-options: -Wall -Werror -fno-warn-warnings-deprecations
