name:                strato-model
version:             0.1.0.0
author:              BlockApps
maintainer:          blockapps
build-type:          Simple
license:             Apache-2.0

dependencies:
  - QuickCheck
  - aeson
  - ansi-wl-pprint
  - base
  - base16-bytestring
  - binary
  - blockapps-haskoin
  - bytestring
  - containers
  - cpu
  - cryptonite
  - deepseq
  - ethereum-rlp
  - fast-keccak256
  - hashable
  - http-api-data
  - integer-gmp
  - lens
  - memory
  - nibblestring
  - path-pieces
  - primitive
  - text
  - time
  - unordered-containers

ghc-options: -Wall -Werror -fno-warn-warnings-deprecations

library:
  source-dirs: src
  default-extensions:
    - MultiParamTypeClasses
    - FlexibleContexts
    - FlexibleInstances
    - GeneralizedNewtypeDeriving
    - GADTs
    - LambdaCase
    - RecordWildCards
    - FunctionalDependencies

tests:
  word256-tests:
    source-dirs: test/
    main: Spec.hs
    dependencies:
      - strato-model
      - hspec
      - QuickCheck

benchmarks:
  word256:
    source-dirs: bench/
    main: Word256Bench.hs
    dependencies:
      - strato-model
      - criterion
