name: strato-init
version: 0.0.1
build-type: Simple

author: Jamshid
maintainer: jamshidnh@gmail.com
synopsis: A tool to setup the DBs for a Strato instance
category: Data Structures
description: A tool to setup the DBs for a Strato instance
license: Apache-2.0

ghc-options: -Wall -O2 -threaded

dependencies:
  - base

library:
  source-dirs: src/
  exposed-modules:
    - Blockchain.Init.ComposeTypes
    - Blockchain.Init.DockerCompose
    - Blockchain.Init.DockerComposeAllDocker
    - Blockchain.Init.EthConf
    - Blockchain.Init.Generator
    - Blockchain.Init.LocalAuth
    - Blockchain.Init.BuildMetadata
    - Blockchain.Init.BuildMetadata.TH
    - Blockchain.Init.Monad
    - Blockchain.Init.Options
  dependencies:
  - aeson
  - blockapps-data
  - data-default
  - blockapps-mpdbs
  - blockapps-vault-wrapper-api
  - blockapps-vault-wrapper-client
  - bytestring
  - common-log
  - conduit
  - containers
  - directory
  - filepath
  - format
  - hflags
  - http-types
  - leveldb-haskell
  - merkle-patricia-db
  - monad-alter
  - nibblestring
  - entropy
  - process
  - resourcet
  - servant-client
  - strato-auth
  - solid-vm-model
  - strato-conf
  - strato-genesis
  - strato-model
  - strato-version
  - streaming
  # - strato-p2p
  - template-haskell
  - transformers
  - turtle
  - unix
  - unliftio
  - yaml

executables:

  strato-setup:
    source-dirs: exec_src/
    main: Main.hs
    dependencies:
      - hflags
      - strato-init
      - strato-model

    other-modules: []

  genesis-builder:
    source-dirs: exec_src/
    main: GenesisBuilder.hs
    dependencies:
      - aeson
      - blockapps-data
      - blockapps-mpdbs
      - bytestring
      - common-log
      - conduit
      - data-default
      - strato-genesis
      - strato-init
      - strato-model
    other-modules: []

