name: strato-init
version: 0.0.1
build-type: Simple
author: Jamshid
maintainer: jamshidnh@gmail.com
synopsis: A tool to setup the DBs for a Strato instance
category: Data Structures
description: A tool to setup the DBs for a Strato instance
license: Apache-2.0

ghc-options: -Wall -O2 -threaded

dependencies:
  - base

library:
  source-dirs: src/
  dependencies:
  - aeson
  - base16-bytestring
  - blockapps-data
  - data-default
  - blockapps-datadefs
  - blockapps-mpdbs
  - blockapps-vault-wrapper-api
  - blockapps-vault-wrapper-client
  - blockDB
  - bytestring
  - common-log
  - conduit
  - containers
  - directory
  - ethereum-rlp
  - evm-solidity
  - exceptions
  - file-embed
  - filepath
  - format
  - hflags
  - http-client
  - http-types
  - kafka-monad
  - lens
  - leveldb-haskell
  - merkle-patricia-db
  - monad-alter
  - nibblestring
  - persistent-postgresql
  - entropy
  - process
  - raw-strings-qq
  - redis-monad
  - resourcet
  - servant-client
  - strato-auth
  - solid-vm
  - solid-vm-compiler
  - solid-vm-model
  - sql-monad
  - strato-conf
  - strato-genesis
  - strato-index
  - strato-model
  - strato-sequencer
  - strato-statediff
  # - strato-p2p
  - template-haskell
  - text
  - transformers
  - turtle
  - unix
  - unliftio
  - vm-tools
  - yaml
  - ordered-containers

executables:

  strato-setup:
    source-dirs: exec_src/
    main: Main.hs
    dependencies:
      - common-log
      - hflags
      - strato-init
      - strato-model

    other-modules: []

  genesis-builder:
    source-dirs: exec_src/
    main: GenesisBuilder.hs
    dependencies:
      - aeson
      - blockapps-data
      - blockapps-mpdbs
      - bytestring
      - common-log
      - conduit
      - data-default
      - strato-genesis
      - strato-init
      - strato-model
      - text
    other-modules: []

