import Distribution.Simple
import System.Process (readProcess)
import System.Directory (doesFileExist)
import Control.Exception (try, SomeException)
import System.Exit (exitFailure)

main :: IO ()
main = do
  generateHashesFile
  defaultMain

generateHashesFile :: IO ()
generateHashesFile = do
  -- Find git root (Setup.hs runs from package directory)
  gitRootResult <- try $ readProcess "git" ["rev-parse", "--show-toplevel"] "" :: IO (Either SomeException String)
  
  gitRoot <- case gitRootResult of
    Right r -> return $ trim r
    Left _ -> do
      putStrLn "Setup.hs: ERROR - Not in a git repository."
      putStrLn "Building from source requires git. Please clone the repository."
      exitFailure
  
  -- Compute hashes using git ls-files
  hashStrato <- computeHash gitRoot "strato"
  hashMercataBackend <- computeHash gitRoot "mercata/backend"
  hashMercataUi <- computeHash gitRoot "mercata/ui"
  hashSmd <- computeHash gitRoot "smd-ui"
  hashApex <- computeHash gitRoot "apex"
  hashPostgrest <- computeHash gitRoot "postgrest-packager"
  hashNginx <- computeHash gitRoot "nginx-packager"
  hashPrometheus <- computeHash gitRoot "prometheus-packager"
  writeHashesFile hashStrato hashMercataBackend hashMercataUi hashSmd hashApex hashPostgrest hashNginx hashPrometheus

writeHashesFile :: String -> String -> String -> String -> String -> String -> String -> String -> IO ()
writeHashesFile hashStrato hashMercataBackend hashMercataUi hashSmd hashApex hashPostgrest hashNginx hashPrometheus = do
  
  let newContent = unlines
        [ "{-# LANGUAGE OverloadedStrings #-}"
        , ""
        , "-- AUTO-GENERATED by Setup.hs - do not edit manually"
        , ""
        , "module Blockchain.Init.Hashes where"
        , ""
        , "hashStrato :: String"
        , "hashStrato = " ++ show hashStrato
        , ""
        , "hashMercataBackend :: String"
        , "hashMercataBackend = " ++ show hashMercataBackend
        , ""
        , "hashMercataUi :: String"
        , "hashMercataUi = " ++ show hashMercataUi
        , ""
        , "hashSmd :: String"
        , "hashSmd = " ++ show hashSmd
        , ""
        , "hashApex :: String"
        , "hashApex = " ++ show hashApex
        , ""
        , "hashPostgrest :: String"
        , "hashPostgrest = " ++ show hashPostgrest
        , ""
        , "hashNginx :: String"
        , "hashNginx = " ++ show hashNginx
        , ""
        , "hashPrometheus :: String"
        , "hashPrometheus = " ++ show hashPrometheus
        ]
  
  let hashesFile = "src/Blockchain/Init/Hashes.hs"
  
  -- Only write if content changed (read strictly to avoid file locking)
  exists <- doesFileExist hashesFile
  oldContent <- if exists 
    then do
      c <- readFile hashesFile
      length c `seq` return c  -- force strict read
    else return ""
  
  if oldContent /= newContent
    then do
      writeFile hashesFile newContent
      putStrLn $ "Setup.hs: Updated " ++ hashesFile
    else
      putStrLn $ "Setup.hs: " ++ hashesFile ++ " unchanged"

computeHash :: FilePath -> String -> IO String
computeHash gitRoot dir = do
  let cmd = "cd " ++ gitRoot ++ " && git ls-files " ++ dir ++ " 2>/dev/null | sort | xargs sha256sum 2>/dev/null | sha256sum | cut -c1-12"
  result <- try $ readProcess "sh" ["-c", cmd] "" :: IO (Either SomeException String)
  case result of
    Right h -> return $ trim h
    Left _ -> return "unknown"

trim :: String -> String
trim = takeWhile (\c -> c /= '\n' && c /= '\r')
