name: strato-p2p
build-type: Simple
author: Jamshid
maintainer:    jamshidnh@gmail.com
synopsis: a microservice that handles peer to peer connections for strato

dependencies:
  - base
  - blockapps-data
  - common-log

ghc-options: -Wall -threaded

executables:
  strato-p2p:
    source-dirs: exec_src/
    main: StratoP2PMain.hs
    dependencies:
      - blockapps-init
      - ethereum-discovery
      - hflags
      - lifted-async
      - milena-tools
      - ordered-containers
      - strato-p2p
      - wai-middleware-prometheus
      - warp
      - x509-certs
      
library:
  source-dirs: src
  ghc-options: -Wall -O2
  dependencies:
    - SafeSemaphore
    - aeson
    - alarmclock
    - ansi-wl-pprint
    - base16-bytestring
    - blockapps-datadefs
    - blockapps-vault-wrapper-api
    - blockapps-vault-wrapper-client
    - blockstanbul
    - bytestring
    - common-log
    - conduit
    - conduit-extra
    - containers
    - cross-monitoring
    - crypto-pubkey-types
    - data-default
    - dlist
    - dns
    - either
    - ethereum-discovery
    - ethereum-encryption
    - ethereum-rlp
    - format
    - ghc
    - hedis
    - hflags
    - http-client
    - iproute
    - json-rpc-server
    - json-rpc-client
    - lens
    - lifted-base
    - milena
    - milena-tools
    - monad-alter
    - monadIO
    - mtl
    - network
    - ordered-containers
    - persistent
    - prometheus-client
    - random
    - resourcet
    - seqevents
    - servant-client
    - servant-server
    - split
    - stm-conduit
    - strato-conf
    - strato-model
    - strato-redis-blockdb
    - text
    - these
    - time
    - transformers
    - unliftio-core
    - unliftio
    - vm-tools
    - warp
    - x509-certs


tests:
  strato-p2p-client-test:
    source-dirs: test
    ghc-options: -Wall -Werror -dynamic
    main: Main.hs
    dependencies:
      - QuickCheck
      - base16-bytestring
      - blockapps-data
      - blockapps-datadefs
      - blockapps-privacy
      - blockapps-util
      - blockstanbul
      - bytestring
      - conduit
      - containers
      - data-default
      - ethereum-discovery
      - hflags
      - hspec
      - hspec-expectations-lifted
      - lens
      - monad-alter
      - mtl
      - ordered-containers
      - seqevents
      - stm-chans
      - stm-conduit
      - strato-model
      - strato-p2p
      - strato-sequencer
      - text
      - unliftio
  
