name:                  blockapps-haskoin
version:               1.0.0.1
synopsis:              Blockapps fork of the "haskoin" library
description:           A fork from an outdated commit,
                       which our infrastructure happens to depend upon.
                       .
                       This package needs to be maintained until we remove
                       the dependencies from it from our codebase.
stability:             stable
license:               PublicDomain
license-file:          UNLICENSE
author:                Philippe Laprade, Jean-Pierre Rupp
maintainer:            plaprade+hackage@gmail.com
category:              Bitcoin, Finance, Network
build-type:            Simple
extra-source-files:
  - tests/data/*.json
github: blockapps/strato-platform/core-strato/blockapps-haskoin

ghc-options: -Wall

dependencies:
  - base                     >= 4.8          && < 5

library:
  source-dirs: ./
  exposed-modules:
    - Network.Haskoin.Util
    - Network.Haskoin.Crypto
    - Network.Haskoin.Node
    - Network.Haskoin.Script
    - Network.Haskoin.Transaction
    - Network.Haskoin.Block
    - Network.Haskoin.Constants
    - Network.Haskoin.Test
    - Network.Haskoin.Internals
  default-extensions:
    - EmptyDataDecls
    - OverloadedStrings
    - FlexibleInstances
    - FlexibleContexts
    - RecordWildCards
    - DeriveDataTypeable
    - GADTs
  dependencies:
  - QuickCheck               >= 2.6          && < 3
  - aeson                    >= 0.7          && < 2
  - base16-bytestring        >= 0.1          && < 0.2
  - binary                   >= 0.7          && < 0.9
  - byteable                 >= 0.1          && < 0.2
  - bytestring               >= 0.10         && < 0.11
  - bytestring-arbitrary
  - conduit                  >= 1.2          && < 1.4
  - containers               >= 0.5          && < 0.6
  - cryptohash               >= 0.11         && < 0.12
  - deepseq                  >= 1.4          && < 2
  - hashable
  - mtl                      >= 2.2          && < 3
  - murmur3                  >= 1.0          && < 2
  - network                  >= 2.6          && < 3
  - pbkdf                    >= 1.1          && < 2
  - split                    >= 0.2          && < 0.3
  - text                     >= 0.11         && < 2
  - time                     >= 1.4          && < 2
  - transformers


tests:
  test-blockapps-haskoin:
    main:           Main.hs
    source-dirs: tests/
    dependencies:
      - aeson                    >= 0.7          && < 2
      - binary                   >= 0.7          && < 0.9
      - blockapps-haskoin
      - bytestring               >= 0.10         && < 0.11
      - containers               >= 0.5          && < 0.6
      - HUnit
      - mtl                      >= 2.2          && < 3
      - split                    >= 0.2          && < 0.3
      - test-framework                 >= 0.8        && < 0.9
      - test-framework-quickcheck2     >= 0.3        && < 0.4
      - test-framework-hunit           >= 0.3        && < 0.4

benchmarks:
  bigword:
    main: Bigword.hs
    source-dirs: bench/
    dependencies:
      - blockapps-haskoin
      - criterion
      - deepseq                  >= 1.4          && < 2
      - largeword
      - data-dword


