name:                strato-api

dependencies:
- base
- bloc-sql-monad
- bloc2
- blockapps-util
- hflags
- monad-alter
- mtl
- postgresql-simple
- transformers

executables:
  strato-api:
    main:                Main.hs
    source-dirs:         app
    other-modules:
    - Options
    - SelectAccessible
    dependencies:
    - aeson
    - bloc2api
    - blockapps-init
    - bytestring
    - cache
    - clock
    - core-api-monad
    - core-api2
    - format
    - http-types
    - insert-ordered-containers
    - lens
    - servant-multipart
    - servant-server
    - servant-swagger
    - servant-swagger-ui
    - sql-monad
    - swagger2
    - unliftio
    - vault-monad
    - wai
    - wai-cors
    - wai-extra
    - wai-middleware-prometheus
    - warp

  strato-api-init:
    main:                StratoAPIInit.hs
    source-dirs:         app
    other-modules:
    - SelectAccessible

  post-raw-transaction:
    main:                PostRawTransaction.hs
    source-dirs:         app
    other-modules:
    - Options
    dependencies:
    - bloc2api
    - blockapps-ethereum
    - containers
    - format
    - http-client
    - servant-client
    - strato-model
    - text
