paths:
  /productFile/:
    get:
      security:              
        - bearerAuth: []                    
      tags:               
        - ProductFile        
      summary: Retrieve productFile
      produces:
      - application/json
      responses:         
        200:
          description: Array of productFiles
    post:  
      security:              
        - bearerAuth: []                  
      tags:               
        - ProductFile        
      summary: Create a productFile
      produces:
      - application/json
      requestBody:         
        description: It enable user to create productFile
        required: true
        content:
          'application/json': 
            schema:       
              $ref: '#/definitions/createProductFile' 
      responses:         
        200:
          description: Object of create productFile
  /productFile/{address}/{chainId}:
    get:                 
      security:              
        - bearerAuth: []   
      tags:               
        - ProductFile        
      summary: Retrieve a productFile
      produces:
      - application/json
      parameters:         
      - in: path          
        name: address     
        description: address to retrieve the productFile
        required: true
      - in: path          
        name: chainId     
        description: chainId corresponding to the address
        required: true
        schema:       
          $ref: '#/definitions/fetchProductFile' 
      responses:         
        200:
          description: Retrieve a productFile
  /productFile/update:
    put:    
      security:              
        - bearerAuth: []                
      tags:               
        - ProductFile        
      summary: Update a productFile
      produces:
      - application/json
      requestBody:         
        description: It enable user to update a productFile
        required: true
        content:
          'application/json':
            schema:       
              $ref: '#/definitions/updateProductFile' 
      responses:         
        200:
          description: Retrieve a updated productFile
  /productFile/{address}/{chainId}/audit:
    get:     
      security:              
        - bearerAuth: []               
      tags:               
        - ProductFile        
      summary: Audit productFile
      produces:
      - application/json
      parameters:         
      - in: path          
        name: address     
        description: address to retrieve the productFile
        required: true
      - in: path          
        name: chainId     
        description: chainId corresponding to the address
        required: true
        schema:       
          $ref: '#/definitions/auditProductFile' 
      responses:         
        200:
          description: List of audit
  /productFile/transferOwnership:
    post:              
      security:              
        - bearerAuth: []      
      tags:               
        - ProductFile        
      summary: Transfer ownership
      produces:
      - application/json
      requestBody:         
        description: It enable user to transfer ownership
        required: true
        content:
          'application/json':
            schema:       
              $ref: '#/definitions/transferOwnership' 
      responses:         
        200:
          description: indicates success of transfer ownership
definitions:        
  fetchProductFile:
    address:
      type: string
    chainId:
      type: string
  createProductFile:
    type: object
    properties:
      machineArgs:
        type: object
        properties:
          fileLocation:
            type: string
          fileHash:
            type: string
          fileName:
            type: string
          uploadDate:
            type: number
      isPublic:
        type: boolean
  updateProductFile:
    type: object
    properties:
      address:
        type: string
      chainId:
        type: string
      updates:
        type: object
        properties:
          fileLocation:
            type: string
          fileHash:
            type: string
          fileName:
            type: string
          uploadDate:
            type: number
  auditProductFile:
    address:
      type: string
    chainId:
      type: string
  transferOwnership:
    type: object
    properties:
      address:
        type: string
      chainId:
        type: string
      newOwner:
        type: string