export const HomeTypeData = [
  { value: 'apartment', label: 'Apartment' },
  { value: 'condo', label: 'Condo' },
  { value: 'coopUnit', label: 'Coop Unit' },
  { value: 'mobileManufactured', label: 'Mobile / Manufactured' },
  { value: 'multiFamily', label: 'Multi Family' },
  { value: 'singleFamily', label: 'Single Family' },
  { value: 'townhome', label: 'Townhome' },
  { value: 'vacantLand', label: 'Vacant Land' },
  { value: 'other', label: 'Other' },
];

export const appliancesData = [
  { value: 'dishwasher', label: 'Dishwasher' },
  { value: 'dryer', label: 'Dryer' },
  { value: 'freezer', label: 'Freezer' },
  { value: 'garbageDisposal', label: 'Garbage Disposal' },
  { value: 'microwave', label: 'Microwave' },
  { value: 'ovenRange', label: 'Oven / Range' },
  { value: 'trashCompactor', label: 'Trash Compactor' },
  { value: 'refrigerator', label: 'Refrigerator' },
  { value: 'washer', label: 'Washer' },
  { value: 'other', label: 'Other' },
]

export const coolingData = [
  { value: 'central', label: 'Central' },
  { value: 'evaporative', label: 'Evaporative' },
  { value: 'geothermal', label: 'Geothermal' },
  { value: 'refrigeration', label: 'Refrigeration' },
  { value: 'solar', label: 'Solar' },
  { value: 'wall', label: 'Wall' },
  { value: 'other', label: 'Other' },
]

export const flooringData = [
  { value: 'carpet', label: 'Carpet' },
  { value: 'concrete', label: 'Concrete' },
  { value: 'hardwood', label: 'Hardwood' },
  { value: 'laminate', label: 'Laminate' },
  { value: 'linoleumVinyl', label: 'Linoleum / Vinyl' },
  { value: 'slate', label: 'Slate' },
  { value: 'softwood', label: 'Softwood' },
  { value: 'tile', label: 'Tile' },
  { value: 'other', label: 'Other' },
]

export const heatingData = [
  { value: 'baseboard', label: 'Baseboard' },
  { value: 'forcedAir', label: 'Forced Air' },
  { value: 'geothermal', label: 'Geothermal' },
  { value: 'heatPump', label: 'Heat Pump' },
  { value: 'radiant', label: 'Radiant' },
  { value: 'stove', label: 'Stove' },
  { value: 'wall', label: 'Wall' },
  { value: 'other', label: 'Other' },
]

export const parkingFeaturesData = [
  { value: 'carport', label: 'Carport' },
  { value: 'attachedGarage', label: 'Garage - Attached' },
  { value: 'detachedGarage', label: 'Garage - Detached' },
  { value: 'offStreet', label: 'Off-Street' },
  { value: 'onStreet', label: 'On-Street' },
  { value: 'other', label: 'Other' },
]

export const interiorFeaturesData = [
  { value: 'attic', label: 'Attic' },
  { value: 'cableReady', label: 'Cable Ready' },
  { value: 'ceilingFan', label: 'Ceiling Fan' },
  { value: 'doublePaneWindows', label: 'Double Pane / Storm Windows' },
  { value: 'fireplace', label: 'Fireplace' },
  { value: 'flooring', label: 'Flooring' },
  { value: 'furnished', label: 'Furnished' },
  { value: 'jettedTub', label: 'Jetted Tub' },
  { value: 'securitySystem', label: 'Security System' },
  { value: 'vaultedCeiling', label: 'Vaulted Ceiling' },
  { value: 'wetBar', label: 'Wet Bar' },
  { value: 'wired', label: 'Wired' },
  { value: 'other', label: 'Other' },
]

export const exteriorFeaturesData = [
  { value: 'barbecueArea', label: 'Barbecue Area' },
  { value: 'deck', label: 'Deck' },
  { value: 'dock', label: 'Dock' },
  { value: 'fencedYard', label: 'Fenced Yard' },
  { value: 'garden', label: 'Garden' },
  { value: 'hotTubSpa', label: 'Hot Tub / Spa' },
  { value: 'lawn', label: 'Lawn' },
  { value: 'patio', label: 'Patio' },
  { value: 'pond', label: 'Pond' },
  { value: 'pool', label: 'Pool' },
  { value: 'porch', label: 'Porch' },
  { value: 'rvParking', label: 'RV Parking' },
  { value: 'sauna', label: 'Sauna' },
  { value: 'sprinklerSystem', label: 'Sprinkler System' },
  { value: 'waterfront', label: 'Waterfront' },
  { value: 'other', label: 'Other' },
]

export const utilitiesData = [
]

export const StateData = [
  { value: 'AL', label: 'AL' },
  { value: 'AK', label: 'AK' },
  { value: 'AZ', label: 'AZ' },
  { value: 'AR', label: 'AR' },
  { value: 'CA', label: 'CA' },
  { value: 'CO', label: 'CO' },
  { value: 'CT', label: 'CT' },
  { value: 'DE', label: 'DE' },
  { value: 'FL', label: 'FL' },
  { value: 'GA', label: 'GA' },
  { value: 'HI', label: 'HI' },
  { value: 'ID', label: 'ID' },
  { value: 'IL', label: 'IL' },
  { value: 'IN', label: 'IN' },
  { value: 'IA', label: 'IA' },
  { value: 'KS', label: 'KS' },
  { value: 'KY', label: 'KY' },
  { value: 'LA', label: 'LA' },
  { value: 'ME', label: 'ME' },
  { value: 'MD', label: 'MD' },
  { value: 'MA', label: 'MA' },
  { value: 'MI', label: 'MI' },
  { value: 'MN', label: 'MN' },
  { value: 'MS', label: 'MS' },
  { value: 'MO', label: 'MO' },
  { value: 'MT', label: 'MT' },
  { value: 'NE', label: 'NE' },
  { value: 'NV', label: 'NV' },
  { value: 'NH', label: 'NH' },
  { value: 'NJ', label: 'NJ' },
  { value: 'NM', label: 'NM' },
  { value: 'NY', label: 'NY' },
  { value: 'NC', label: 'NC' },
  { value: 'ND', label: 'ND' },
  { value: 'OH', label: 'OH' },
  { value: 'OK', label: 'OK' },
  { value: 'OR', label: 'OR' },
  { value: 'PA', label: 'PA' },
  { value: 'RI', label: 'RI' },
  { value: 'SC', label: 'SC' },
  { value: 'SD', label: 'SD' },
  { value: 'TN', label: 'TN' },
  { value: 'TX', label: 'TX' },
  { value: 'UT', label: 'UT' },
  { value: 'VT', label: 'VT' },
  { value: 'VA', label: 'VA' },
  { value: 'WA', label: 'WA' },
  { value: 'WV', label: 'WV' },
  { value: 'WI', label: 'WI' },
  { value: 'WY', label: 'WY' }
];
