export const homeTypeData = [
  { value: "apartment", label: "Apartment" },
  { value: "condo", label: "Condo" },
  { value: "coopUnit", label: "Coop Unit" },
  { value: "mobileManufactured", label: "Mobile / Manufactured" },
  { value: "multiFamily", label: "Multi Family" },
  { value: "singleFamily", label: "Single Family" },
  { value: "townhome", label: "Townhome" },
  { value: "vacantLand", label: "Vacant Land" },
  { value: "other", label: "Other" },
];

export const categoriesObj = {
  appliances: [
    { value: "dishwasher", label: "Dishwasher" },
    { value: "dryer", label: "Dryer" },
    { value: "freezer", label: "Freezer" },
    { value: "garbageDisposal", label: "Garbage Disposal" },
    { value: "microwave", label: "Microwave" },
    { value: "ovenOrRange", label: "Oven / Range" },
    // { value: 'trashCompactor', label: 'Trash Compactor' },
    { value: "refrigerator", label: "Refrigerator" },
    { value: "washer", label: "Washer" },
    { value: "waterHeater", label: "Water Heater" },
    // { value: 'other', label: 'Other' },
  ],
  flooring: [
    { value: "carpet", label: "Carpet" },
    { value: "concrete", label: "Concrete" },
    { value: "hardwood", label: "Hardwood" },
    { value: "laminate", label: "Laminate" },
    { value: "linoleumVinyl", label: "Linoleum / Vinyl" },
    { value: "slate", label: "Slate" },
    { value: "softwood", label: "Softwood" },
    { value: "tile", label: "Tile" },
  ],
  interior_features: [
    { value: "attic", label: "Attic" },
    { value: "cableReady", label: "Cable Ready" },
    { value: "ceilingFan", label: "Ceiling Fan" },
    { value: "doublePaneWindows", label: "Double Pane / Storm Windows" },
    { value: "elevator", label: "Elevator" },
    { value: "fireplace", label: "Fireplace" },
    { value: "flooring", label: "Flooring" },
    { value: "furnished", label: "Furnished" },
    { value: "jettedTub", label: "Jetted Tub" },
    { value: "securitySystem", label: "Security System" },
    { value: "vaultedCeiling", label: "Vaulted Ceiling" },
    { value: "skylight", label: "Skylight" },
    { value: "wetBar", label: "Wet Bar" },
    // { value: 'wired', label: 'Wired' },
  ],
  cooling: [
    { value: "centralAir", label: "Central" },
    { value: "evaporative", label: "Evaporative" },
    { value: "geoThermal", label: "Geothermal" },
    { value: "refrigeration", label: "Refrigeration" },
    { value: "solar", label: "Solar" },
    { value: "wallUnit", label: "Wall" },
  ],
  heating: [
    { value: "baseboard", label: "Baseboard" },
    { value: "forceAir", label: "Forced Air" },
    { value: "geoThermalHeat", label: "Geothermal" },
    { value: "heatPump", label: "Heat Pump" },
    { value: "hotWater", label: "Hot Water" },
    { value: "radiant", label: "Radiant" },
    { value: "solarHeat", label: "Solar Heat" },
    { value: "steam", label: "Steam" },
  ],
  parking_features: [
    { value: "carport", label: "Carport" },
    { value: "garage", label: "Garage" },
    // { value: 'attachedGarage', label: 'Garage - Attached' },
    // { value: 'detachedGarage', label: 'Garage - Detached' },
    { value: "offStreet", label: "Off-Street" },
    { value: "onStreet", label: "On-Street" },
  ],
  exterior_features: [
    { value: "barbecueArea", label: "Barbecue Area" },
    { value: "deck", label: "Deck" },
    { value: "dock", label: "Dock" },
    { value: "fence", label: "Fenced Yard" },
    { value: "garden", label: "Garden" },
    { value: "hotTubOrSpa", label: "Hot Tub / Spa" },
    { value: "lawn", label: "Lawn" },
    { value: "patio", label: "Patio" },
    { value: "pond", label: "Pond" },
    { value: "pool", label: "Pool" },
    { value: "porch", label: "Porch" },
    { value: "rvParking", label: "RV Parking" },
    { value: "sauna", label: "Sauna" },
    { value: "sprinklerSystem", label: "Sprinkler System" },
    { value: "waterFront", label: "Waterfront" },
  ],
};

export const stateData = [
  { value: "AL", label: "AL" },
  { value: "AK", label: "AK" },
  { value: "AZ", label: "AZ" },
  { value: "AR", label: "AR" },
  { value: "CA", label: "CA" },
  { value: "CO", label: "CO" },
  { value: "CT", label: "CT" },
  { value: "DE", label: "DE" },
  { value: "FL", label: "FL" },
  { value: "GA", label: "GA" },
  { value: "HI", label: "HI" },
  { value: "ID", label: "ID" },
  { value: "IL", label: "IL" },
  { value: "IN", label: "IN" },
  { value: "IA", label: "IA" },
  { value: "KS", label: "KS" },
  { value: "KY", label: "KY" },
  { value: "LA", label: "LA" },
  { value: "ME", label: "ME" },
  { value: "MD", label: "MD" },
  { value: "MA", label: "MA" },
  { value: "MI", label: "MI" },
  { value: "MN", label: "MN" },
  { value: "MS", label: "MS" },
  { value: "MO", label: "MO" },
  { value: "MT", label: "MT" },
  { value: "NE", label: "NE" },
  { value: "NV", label: "NV" },
  { value: "NH", label: "NH" },
  { value: "NJ", label: "NJ" },
  { value: "NM", label: "NM" },
  { value: "NY", label: "NY" },
  { value: "NC", label: "NC" },
  { value: "ND", label: "ND" },
  { value: "OH", label: "OH" },
  { value: "OK", label: "OK" },
  { value: "OR", label: "OR" },
  { value: "PA", label: "PA" },
  { value: "RI", label: "RI" },
  { value: "SC", label: "SC" },
  { value: "SD", label: "SD" },
  { value: "TN", label: "TN" },
  { value: "TX", label: "TX" },
  { value: "UT", label: "UT" },
  { value: "VT", label: "VT" },
  { value: "VA", label: "VA" },
  { value: "WA", label: "WA" },
  { value: "WV", label: "WV" },
  { value: "WI", label: "WI" },
  { value: "WY", label: "WY" },
];

export const propertyCheckBox = {
  dishwasher: false,
  dryer: false,
  freezer: false,
  garbageDisposal: false,
  microwave: false,
  ovenOrRange: false,
  refrigerator: false,
  washer: false,
  waterHeater: false,

  centralAir: false,
  evaporative: false,
  geoThermal: false,
  refrigeration: false,
  solar: false,
  wallUnit: false,

  baseboard: false,
  forceAir: false,
  geoThermalHeat: false,
  heatPump: false,
  hotWater: false,
  radiant: false,
  solarHeat: false,
  steam: false,

  carpet: false,
  concrete: false,
  hardwood: false,
  laminate: false,
  linoleumVinyl: false,
  slate: false,
  softwood: false,
  tile: false,

  carport: false,
  garage: false,
  offStreet: false,
  onStreet: false,

  attic: false,
  cableReady: false,
  ceilingFan: false,
  doublePaneWindows: false,
  elevator: false,
  fireplace: false,
  flooring: false,
  furnished: false,
  jettedTub: false,
  securitySystem: false,
  vaultedCeiling: false,
  skylight: false,
  wetBar: false,

  barbecueArea: false,
  deck: false,
  dock: false,
  fence: false,
  garden: false,
  hotTubOrSpa: false,
  lawn: false,
  patio: false,
  pond: false,
  pool: false,
  porch: false,
  rvParking: false,
  sauna: false,
  sprinklerSystem: false,
  waterFront: false,
};

export const propertyConstants = {
  LIMIT_PER_PAGE: 10,
  MAX_PRICE_VALUE: 0
}

export const filterlabel = {
  sort_By: "Sort By",
  min_Price: "Minimum Price",
  max_Price: "Maximum Price",
  zip_code: "ZipCode",
  state: "State",
  min_Bedrooms: "Minimum Bedroom",
  min_Bathrooms: "Minimum Bathroom",
  amenities: "Amenities",
  lot_Size_Area: "Minimum Lot Area",
  parking_Type: "Parking Type",
  property_Type: "Property Type",

  minlistPrice: "Lowest Price",
  maxlistPrice: "Highest Price",
  minlotSizeArea: "Lowest Area",
  maxlotSizeArea: "Highest Area",
};

export const QueryKeys = {
  min_Price: "listPrice",
  max_Price: "listPrice",
  zip_code: "postalcode",
  state: "stateOrProvince",
  min_Bedrooms: "bedroomsTotal",
  min_Bathrooms: "bathroomsTotalInteger",
  lot_Size_Area: "lotSizeArea",
  property_Type: "propertyType",
  minlistPrice: "-listPrice",
  maxlistPrice: "+listPrice",
  minlotSizeArea: "-lotSizeArea",
  maxlotSizeArea: "+lotSizeArea",
  ownerOrganization:"ownerOrganization",
}

export const createPropertyFormInitialData = {
  lotSizeUnits: "sqft",
  livingAreaUnits: "sqft",
  numberOfUnitsTotal: 1,
  ...propertyCheckBox
}