export const sampleProperties = [
  {
    ParcelNumber: "1234567890",
    PropertyType: 'Residential',
    ListPrice: 1000000,
    UnparsedAddress: "123 Main St.",
    UnitNumber: 123,
    PostalCity: "San Diego",
    StateOrProvince: "CA",
    PostalCode: "92101",
    BathroomsTotalInteger: 2,
    BedroomsTotal: 2,
    StandardStatus: 'Active',
    LotSizeArea: 1000,
    LotSizeUnits: 'SqFt',
    LivingArea: 1000,
    LivingAreaUnits: 'SqFt',
    Latitude: 32.7157,
    Longitude: 117.1611,
    ListAgentFullName: "John Doe",
    ListAgentEmail: 'johndoe2@gmail.com',
    ListAgentPreferredPhone: '123-456-7890',
    Appliances: ['Dishwasher', 'Disposal', 'Microwave', 'Refrigerator', 'Gas', 'Oven', 'Gas', 'Cooktop'],
    Cooling: true,
    Flooring: true,
    Heating: true,
    NumberOfUnitsTotal: 1,
    ParkingFeatures: true,
    InteriorFeatures: true,
    ExteriorFeatures: true,
    WaterfrontFeatures: true,
    Utilities: true,
    PatioAndPorchFeatures: true,
    images: ['https://www.bhg.com/thmb/H9VV9JNnKl-H1faFXnPlQfNprYw=/1799x0/filters:no_upscale():strip_icc()/white-modern-house-curved-patio-archway-c0a4a3b3-aa51b24d14d0464ea15d36e05aa85ac9.jpg']
  }
]