name: strato-init
version: 0.0.1
build-type: Simple
author: Jamshid
license-file: LICENSE
maintainer: jamshidnh@gmail.com
synopsis: A tool to setup the DBs for a Strato instance
category: Data Structures
license: Apache-2.0
description: A tool to setup the DBs for a Strato instance
github: blockapps/strato-platform/core-strato/strato-init

ghc-options: -Wall -O2 -threaded

dependencies:
  - base >= 4 && < 5
  - aeson
  - base16-bytestring
  - base64-bytestring
  - binary
  - blockapps-data
  - blockapps-datadefs
  - blockapps-haskoin
  - blockapps-milena
  - blockapps-mpdbs
  - blockapps-util
  - bytestring
  - containers
  - cryptohash
  - cryptonite
  - crypto-api
  - csv
  - deepseq
  - directory
  - entropy
  - ethereum-discovery
  - ethereum-rlp
  - extra
  - file-embed
  - filepath
  - format
  - hedis
  - hflags
  - json-stream
  - leveldb-haskell
  - memory
  - merkle-patricia-db
  - monad-alter
  - mtl
  - nibblestring
  - persistent-postgresql
  - resourcet
  - scientific
  - seqevents
  - split
  - strato-conf
  - strato-genesis
  - strato-index
  - strato-model
  - strato-redis-blockdb
  - strato-sequencer
  - strato-statediff
  - stm
  - stm-chans
  - text
  - time
  - transformers
  - unliftio-core
  - unordered-containers
  - utf8-string
  - vector
  - yaml

library:
  source-dirs: src/

executables:
  strato-setup:
    source-dirs: exec_src/
    main: Main.hs
    dependencies:
      - strato-init
    other-modules: []

  mk-init-topic:
    source-dirs: exec_src/
    main: MkInitTopic.hs
    dependencies:
      - strato-init
    other-modules: []

  tabula-rasa:
    source-dirs: exec_src/
    main: TabulaRasa.hs
    dependencies:
      - strato-init
    other-modules: []

  from-volume:
    source-dirs: exec_src/
    main: FromVolume.hs
    dependencies:
      - strato-init
    other-modules: []

  from-restore:
    source-dirs: exec_src/
    main: FromRestore.hs
    dependencies:
      - strato-init
    other-modules: []

  init-worker:
    source-dirs: exec_src/
    main: InitWorker.hs
    dependencies:
      - strato-init
    other-modules: []

tests:
  strato-init-test:
    source-dirs: test/
    main: Main.hs
    dependencies:
      - aeson-diff
      - hspec
      - strato-init
