name: strato-init
version: 0.0.1
build-type: Simple
author: Jamshid
license-file: LICENSE
maintainer: jamshidnh@gmail.com
synopsis: A tool to setup the DBs for a Strato instance
category: Data Structures
license: Apache-2.0
description: A tool to setup the DBs for a Strato instance
github: blockapps/strato-platform/core-strato/strato-init

ghc-options: -Wall -O2 -threaded

dependencies:
  - base

library:
  source-dirs: src/
  dependencies:
  - aeson
  - base16-bytestring
  - base64-bytestring
  - blockapps-data
  - blockapps-datadefs
  - blockapps-haskoin
  - blockapps-mpdbs
  - blockapps-util
  - blockapps-vault-wrapper-api
  - blockapps-vault-wrapper-client
  - bytestring
  - common-log
  - conduit
  - containers
  - directory
  - either
  - entropy
  - ethereum-discovery
  - ethereum-rlp
  - extra
  - file-embed
  - filepath
  - format
  - hedis
  - hflags
  - http-client
  - http-types
  - json-stream
  - lens
  - leveldb-haskell
  - merkle-patricia-db
  - milena
  - monad-alter
  - nibblestring
  - persistent-postgresql
  - resourcet
  - secp256k1-haskell
  - seqevents
  - servant-client
  - split
  - strato-conf
  - strato-genesis
  - strato-index
  - strato-model
  - strato-networks
  - strato-redis-blockdb
  - strato-sequencer
  - strato-statediff
  - temporary
  - text
  - transformers
  - turtle
  - unliftio
  - unliftio-core
  - yaml

executables:
  strato-setup:
    source-dirs: exec_src/
    main: Main.hs
    dependencies:
      - blockapps-util
      - common-log
      - hflags
      - strato-init
    other-modules: []

  tabula-rasa:
    source-dirs: exec_src/
    main: TabulaRasa.hs
    dependencies:
      - common-log
      - hflags
      - strato-init

    other-modules: []

  from-restore:
    source-dirs: exec_src/
    main: FromRestore.hs
    other-modules: []

  init-worker:
    source-dirs: exec_src/
    main: InitWorker.hs
    dependencies:
      - common-log
      - hflags
      - strato-init
    other-modules: []

tests:
  strato-init-test:
    source-dirs: test/
    main: Main.hs
    dependencies:
      - aeson
      - base16-bytestring
      - blockapps-data
      - bytestring
      - hspec
      - json-stream
      - merkle-patricia-db
      - strato-genesis
      - strato-model
      - time
