{-# LANGUAGE BangPatterns #-}
-- |
-- Module      : Crypto.Hash.Poseidon2Goldilocks
-- Description : Poseidon2 over the Goldilocks field (plonky2 / Plonky3 parameters)
--
-- Poseidon2 over GF(p), p = 2^64 - 2^32 + 1 (Goldilocks), WIDTH 12, RATE 8,
-- S-box x^7, 8 full + 22 partial rounds — the algebraic hasher of the
-- plonky2 (elliottech fork) / Plonky3 Goldilocks ecosystem: Polygon's
-- Plonky2/3-based provers, zkSync's Boojum, Lighter, and STRATO's own
-- rollup use this exact instance for state trees, DA commitments and
-- signature messages. It is bit-for-bit @plonky2::hash::poseidon2@ with the
-- fork's constants ('Crypto.Hash.Poseidon2Goldilocks.Constants'); the test
-- suite pins vectors generated by that prover.
--
-- Provided: the permutation, plonky2's @hash_n_to_m_no_pad@ sponge (absorb
-- 8 elements per permutation by OVERWRITING the rate lanes, no padding, so
-- callers hash fixed-shape inputs exactly as circuits do), and a
-- byte-string convenience that packs 7-byte little-endian chunks (always
-- canonical) followed by the byte length.
module Crypto.Hash.Poseidon2Goldilocks
  ( goldilocksPrime
  , isCanonical
  , permutation
  , hashNToM
  , hashBytes
  , packBytes
  ) where

import Crypto.Hash.Poseidon2Goldilocks.Constants
import Data.Bits (shiftL, (.|.))
import qualified Data.ByteString as B
import Data.List (foldl')
import Data.Word (Word64)

-- | p = 2^64 - 2^32 + 1
goldilocksPrime :: Word64
goldilocksPrime = 0xFFFFFFFF00000001

isCanonical :: Word64 -> Bool
isCanonical x = x < goldilocksPrime

-- ---------------------------------------------------------------- field

-- Elements are canonical Word64s. Products go through Integer for the
-- 128-bit intermediate; everything else stays in Word64.

addF :: Word64 -> Word64 -> Word64
addF a b =
  let !s = a + b            -- wraps mod 2^64
      !carried = s < a      -- overflow past 2^64 == subtract p and add 2^32-1... see below
   in if carried
        then canon (s + 0xFFFFFFFF)     -- 2^64 ≡ 2^32 - 1 (mod p)
        else canon s

canon :: Word64 -> Word64
canon x = if x >= goldilocksPrime then x - goldilocksPrime else x

mulF :: Word64 -> Word64 -> Word64
mulF a b = fromInteger ((toInteger a * toInteger b) `rem` toInteger goldilocksPrime)

-- x^7
sbox :: Word64 -> Word64
sbox x =
  let !x2 = mulF x x
      !x4 = mulF x2 x2
      !x6 = mulF x4 x2
   in mulF x6 x

-- ---------------------------------------------------------- linear layers

-- circulant M4 on a 4-lane block: (2 3 1 1 / 1 2 3 1 / 1 1 2 3 / 3 1 1 2)
mat4 :: [Word64] -> [Word64]
mat4 [x0, x1, x2, x3] =
  let t01 = addF x0 x1
      t23 = addF x2 x3
      t0123 = addF t01 t23
      t01123 = addF t0123 x1
      t01233 = addF t0123 x3
      y3 = addF t01233 (addF x0 x0)
      y1 = addF t01123 (addF x2 x2)
      y0 = addF t01123 t01
      y2 = addF t01233 t23
   in [y0, y1, y2, y3]
mat4 _ = error "Poseidon2Goldilocks: mat4 needs 4 lanes"

externalLayer :: [Word64] -> [Word64]
externalLayer s =
  let blocks = map mat4 (chunks4 s)
      s' = concat blocks
      sums = [ foldl' addF 0 [ s' !! (4 * j + k) | j <- [0 .. 2] ] | k <- [0 .. 3] ]
   in [ addF (s' !! i) (sums !! (i `mod` 4)) | i <- [0 .. 11] ]
  where
    chunks4 [] = []
    chunks4 xs = take 4 xs : chunks4 (drop 4 xs)

internalLayer :: [Word64] -> [Word64]
internalLayer s =
  let total = foldl' addF 0 s
   in zipWith (\x d -> addF total (mulF x d)) s matrixDiag

addRC :: Int -> [Word64] -> [Word64]
addRC r = zipWith addF (externalConstants !! r)

-- | The Poseidon2 permutation on 12 canonical elements.
permutation :: [Word64] -> [Word64]
permutation input
  | length input /= 12 = error "Poseidon2Goldilocks: permutation needs 12 elements"
  | otherwise =
      let s0 = externalLayer input
          full s r = externalLayer (map sbox (addRC r s))
          s1 = foldl' full s0 [0 .. 3]
          partial s r = case s of
            (h : t) -> internalLayer (sbox (addF h (internalConstants !! r)) : t)
            [] -> error "Poseidon2Goldilocks: empty state"
          s2 = foldl' partial s1 [0 .. 21]
          s3 = foldl' full s2 [4 .. 7]
       in s3

-- | plonky2 @hash_n_to_m_no_pad@: absorb 8 elements per permutation by
-- overwriting the first lanes, then squeeze @m@ elements (8 per
-- permutation). Inputs must be canonical.
hashNToM :: Int -> [Word64] -> [Word64]
hashNToM m inputs
  | any (not . isCanonical) inputs = error "Poseidon2Goldilocks: non-canonical input"
  | otherwise = squeeze m (absorbAll (replicate 12 0) inputs)
  where
    absorbAll st [] = st
    absorbAll st xs =
      let (blk, rest) = splitAt 8 xs
          st' = permutation (blk ++ drop (length blk) st)
       in absorbAll st' rest
    squeeze n st
      | n <= 8 = take n st
      | otherwise = take 8 st ++ squeeze (n - 8) (permutation st)

-- | Pack bytes into canonical elements: 7-byte little-endian chunks (the
-- last one zero-padded), followed by ONE element holding the byte length so
-- payloads differing only in trailing zeros commit differently.
packBytes :: B.ByteString -> [Word64]
packBytes bs = go bs ++ [fromIntegral (B.length bs)]
  where
    go b
      | B.null b = []
      | otherwise =
          let (c, rest) = B.splitAt 7 b
           in le c : go rest
    le c = foldr (\w acc -> (acc `shiftL` 8) .|. fromIntegral w) 0 (B.unpack c)

-- | hashNToM over 'packBytes'.
hashBytes :: Int -> B.ByteString -> [Word64]
hashBytes m = hashNToM m . packBytes

