
module Blockchain.Sequencer.ExtraCertsHack where

import BlockApps.X509.Certificate
import Blockchain.Strato.Model.Address
import qualified Data.ByteString.Char8 as BC


getCert :: [String] -> X509Certificate
getCert certLines =
  let eCert = 
        bsToCert $
          BC.pack $
            unlines certLines
   in case eCert of
        Left _ -> error $ "malformed cert passed to getCert: " <> unlines certLines
        Right c -> c

--0x94f5f0f4d60635324bb2a4dde14c0101bfc92cb1
troubleCert :: [String]
troubleCert =
  [ "-----BEGIN CERTIFICATE-----",
    "MIIBqzCCAVCgAwIBAgIRAK2hc+TQ4jH11q+Ogf5qvGUwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDMyODIxMjU0NloXDTI1MDMy",
    "ODIxMjU0NlowZjExMC8GA1UEAwwoc2VydmljZS1hY2NvdW50LWlvLXN0cmF0b21l",
    "cmNhdGEtdHJvdWJsZTExMC8GA1UECgwoc2VydmljZS1hY2NvdW50LWlvLXN0cmF0",
    "b21lcmNhdGEtdHJvdWJsZTBWMBAGByqGSM49AgEGBSuBBAAKA0IABKkkF/LGEY67",
    "YL9SMzIBb+wzZV9uYwOePWMstGkdm3F3sBz7Jbigk9kS8DzmHmBWQ3qmAcoDgVWs",
    "8vZwiopMr/MwDAYIKoZIzj0EAwIFAANHADBEAiAme5CoTnALethPtUvyVSPilZAM",
    "ushbAwhMrqjkmuVDkQIgRdScp27rcgHVumJRerrzloUZbSEUq9kM47oONAsBWJg=",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]


--94f5dc46e634d405b23b187fe8889b4777b6771a
witmkCert :: [String]
witmkCert =
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBpzCCAUygAwIBAgIRAMl4n0xrJmbcFGICZv6yzxwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDMyODIxMjIzMVoXDTI1MDMy",
    "ODIxMjIzMVowYjEvMC0GA1UEAwwmc2VydmljZS1hY2NvdW50LWlvLXN0cmF0b21l",
    "cmNhdGEtd2l0bWsxLzAtBgNVBAoMJnNlcnZpY2UtYWNjb3VudC1pby1zdHJhdG9t",
    "ZXJjYXRhLXdpdG1rMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEILu6iw762puMMW5Z",
    "Hsi679nOOh5OukxrO9SmcC7UAvP1Pz/YVPh9tn0Z6n8/yBv1VFsmEp1YUlmfT+ah",
    "AqyKAjAMBggqhkjOPQQDAgUAA0cAMEQCIGHxHQM6pmundoLj+GcMNbJZ0uMQiBmB",
    "nRU9bhOnLZs7AiAZtqdkMbBstvr3F5K/Hbl+XXXZWPBwDdxWm1R0f81K5Q==",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]


--d59214182be7bf96fb8155b178683b9b18e97eae
jpowellCert :: [String]
jpowellCert =
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBqzCCAVCgAwIBAgIRAKhbiqKXXuu4HaP/ddCnzdEwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDMyODIxMDgxNloXDTI1MDMy",
    "ODIxMDgxNlowZjExMC8GA1UEAwwoc2VydmljZS1hY2NvdW50LWlvLXN0cmF0b21l",
    "cmNhdGEtanBvd2VsbDExMC8GA1UECgwoc2VydmljZS1hY2NvdW50LWlvLXN0cmF0",
    "b21lcmNhdGEtanBvd2VsbDBWMBAGByqGSM49AgEGBSuBBAAKA0IABMgKZNt+MyIh",
    "j6eQs20ndPDlQtywNn3emd3o46J3/pMC93A5pq1thCC9hILII26bPJDTzWE8fY3I",
    "crw1m1BWpocwDAYIKoZIzj0EAwIFAANHADBEAiBep/vzAN3iKHCEDB3IQTFEQzkp",
    "LKH1vhoR41cuVUj1KwIgfx7EKlg2D7/jhtLVeGYupm2Spg3PLC4U+QpmhbCBHTE=",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]


chessCert :: [String]
chessCert = 
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBrTCCAVGgAwIBAgIQaAF1HrTNFSIN2/7p1QOppjAMBggqhkjOPQQDAgUAMEgx",
    "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu",
    "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjQwMzI5MTcyMjQwWhcNMjUwMzI5",
    "MTcyMjQwWjBoMTIwMAYDVQQDDClzZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRvbWVy",
    "Y2F0YS1DaGVzc0dNOTEyMDAGA1UECgwpc2VydmljZS1hY2NvdW50LWlvLXN0cmF0",
    "b21lcmNhdGEtQ2hlc3NHTTkwVjAQBgcqhkjOPQIBBgUrgQQACgNCAASS4/DfUqtu",
    "0/l5wtVb28jRgssTEfK7oPKw4v/G9v/TglowiPfI+B69hPRFpGV/2bDBATlDQD2L",
    "kxb/3e0rRYVSMAwGCCqGSM49BAMCBQADSAAwRQIhAL3PLQYQ8zngen3pIeuCR4dT",
    "YjuddndHZUyidAvq3490AiAJ/lOS2Jx+xhm9vd78E6WVIX+qKQTNVW5/Hlz36ArS",
    "7A==",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]

  
--15da843f489440e9b7f47d824b295f698b4a112a
aaaCert :: [String]
aaaCert =
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBozCCAUigAwIBAgIRAIz+ALn+2FIny20dvFE9hL4wDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDMyODIxMjcxN1oXDTI1MDMy",
    "ODIxMjcxN1owXjEtMCsGA1UEAwwkc2VydmljZS1hY2NvdW50LWlvLXN0cmF0b21l",
    "cmNhdGEtYWFhMS0wKwYDVQQKDCRzZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRvbWVy",
    "Y2F0YS1hYWEwVjAQBgcqhkjOPQIBBgUrgQQACgNCAASnxGg2073E2DieYq6A1Vkx",
    "H5BGe47cHMtwDaHLBgeMNzpuvmAVS5WIOwZVaUefp0og3vEEd5RibddmtS+5/Ndz",
    "MAwGCCqGSM49BAMCBQADRwAwRAIgeGeAR6eotLI8vZ/mOxNhPBFJhazB10+62jyb",
    "CBL70lECIHl0QK/yADCNavzyC/ekoehwh0L3PZUKK1crT45wL2+r",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]
  
--75c42fe751cc3dd9ce4bfdbedba99e75c034377a
dsnallapuCert :: [String]
dsnallapuCert =
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBrzCCAVSgAwIBAgIRAJE2RKKAUGSSuPdNV2GTmv4wDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDMyODIxMzY0MVoXDTI1MDMy",
    "ODIxMzY0MVowajEzMDEGA1UEAwwqc2VydmljZS1hY2NvdW50LWlvLXN0cmF0b21l",
    "cmNhdGEtZHNuYWxsYXB1MTMwMQYDVQQKDCpzZXJ2aWNlLWFjY291bnQtaW8tc3Ry",
    "YXRvbWVyY2F0YS1kc25hbGxhcHUwVjAQBgcqhkjOPQIBBgUrgQQACgNCAAQDZaje",
    "DGSvsqjF4OpJBl268CJRECe5+wVIbc+VfXzQtlVvSSwY/gIJvfVEs7mXEdmBg1Du",
    "uTAyKrzyGjLAfyxdMAwGCCqGSM49BAMCBQADRwAwRAIgJVS/t2DG5NFU4oJzlUjy",
    "X+LUTXMf2phGCIXCgkGYMcMCIBz1IfEDy41X8CDfSkSsuKgod2Fhe2F6JWxnJfhl",
    "zm2+",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]

dustinNodeCert :: [String]
dustinNodeCert =
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBgDCCASSgAwIBAgIRAKr5Ov1ZzUja9sqeTIhVMEswDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDMyODE5MzUzM1oXDTI1MDMy",
    "ODE5MzUzM1owOjEUMBIGA1UEAwwLZHVzdGluLW5vZGUxCTAHBgNVBAoMADEJMAcG",
    "A1UECwwAMQwwCgYDVQQGDANVU0EwVjAQBgcqhkjOPQIBBgUrgQQACgNCAARM/sOa",
    "isJiPam6gObGJFq8UDt06FYWO2+edBkSVdUcwDrGD4un0ggVOTvqq5xH8WtGDpv6",
    "BtQA/FEwW2Ky0/qeMAwGCCqGSM49BAMCBQADSAAwRQIhANHQM2M9cPMdJHk+UD4F",
    "wZU7wbB65cD3Q+vFfbSYPGyoAiA7mMg7DZrAhAvG9Pg0A2O/9rd4jHh75UuFViQ1",
    "GTfIrQ==",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]

kierensNodeCert :: [String]
kierensNodeCert =
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBszCCAVigAwIBAgIRAIiTYIFFIZ0qzuOHa+hdynkwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDMyODIxMDQ1MFoXDTI1MDMy",
    "ODIxMDQ1MFowbjE1MDMGA1UEAwwsc2VydmljZS1hY2NvdW50LWlvLXN0cmF0b21l",
    "cmNhdGEta2llcmVuc25vZGUxNTAzBgNVBAoMLHNlcnZpY2UtYWNjb3VudC1pby1z",
    "dHJhdG9tZXJjYXRhLWtpZXJlbnNub2RlMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE",
    "O32NpbDBs7kJ63s48j09fRlyJo/8i6F8NWDLmBzBev3201ZaZB4yozfdh5+9jG5B",
    "SJduhBHMkcKekCb3Pbwb1TAMBggqhkjOPQQDAgUAA0cAMEQCIADA/DuU/Tb7GGuP",
    "5hZUrH6WGHLwpoXBceciFxQmJSddAiAgYJok4oZZhcI1dhO4yYzN3oR/gokzzWuh",
    "KllTbqWoDg==",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]

wongwayCert :: [String]
wongwayCert =
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBqzCCAU+gAwIBAgIQUsdBA4EOYfIqpA1iCg6NezAMBggqhkjOPQQDAgUAMEgx",
    "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu",
    "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjQwMzI4MjA0OTA1WhcNMjUwMzI4",
    "MjA0OTA1WjBmMTEwLwYDVQQDDChzZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRvbWVy",
    "Y2F0YS13b25nd2F5MTEwLwYDVQQKDChzZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRv",
    "bWVyY2F0YS13b25nd2F5MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE2R5VXfkLhJOp",
    "OHgztwLtHM/zYKWDDzigkW80zcI4/n5MtlPZLfCYGdSTlunQcqZlghvMfy50nT2k",
    "OZKkOZFbMjAMBggqhkjOPQQDAgUAA0gAMEUCIQDuo0BG+Xs85YIWek06e5+DsBoh",
    "P2LnSRuDEEJJ+Ap9+QIgTqHnpX7x3p8pBzJsT8IYvaRup+NV3JM474L6t1JF+Ug=",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]

tysonCert :: [String]
tysonCert =
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBqDCCAUygAwIBAgIRAIEKqwfuPLSejKxQBMx/yT8wDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDUxMDE2NTQyNFoXDTI1MDUx",
    "MDE2NTQyNFowYjEvMC0GA1UEAwwmc2VydmljZS1hY2NvdW50LWlvLXN0cmF0b21l",
    "cmNhdGEtdHlzb24xLzAtBgNVBAoMJnNlcnZpY2UtYWNjb3VudC1pby1zdHJhdG9t",
    "ZXJjYXRhLXR5c29uMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEVcWIhYZ/gFY5TZyf",
    "mX5ZiNbwkcc/LMEE2UfW3o8EegVSytf3wQpZ1WLrSou9FSMSI1z7mQmRxeitcZP0",
    "t5M3BjAMBggqhkjOPQQDAgUAA0gAMEUCIQCSJMPwnHu8fD+1JmCu4bny3dJCLy8X",
    "op1mB4ZUiYVNOQIgM7g1LhNPk1Mfcsi78n7IOA0iBXPSseq6zC+QxqpG9GI=",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]


neelCert :: [String]
neelCert =
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBpDCCAUmgAwIBAgIQEUV0619wSldWQLF2VOdKJjAMBggqhkjOPQQDAgUAMEgx",
    "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu",
    "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjQwNjA3MTcwMTM3WhcNMjUwNjA3",
    "MTcwMTM3WjBgMS4wLAYDVQQDDCVzZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRvbWVy",
    "Y2F0YS1uZWVsMS4wLAYDVQQKDCVzZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRvbWVy",
    "Y2F0YS1uZWVsMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEWlUjyWK5Q8z9P7+gVZIl",
    "wDPW4yN9Y+vfj58ZoWUXfnC7RUkaicJtiiAFvtwHVdwRuzoeq+Akh0/WlOGSLoQP",
    "YjAMBggqhkjOPQQDAgUAA0cAMEQCIBIWc+Gt91Ui4ZOocLW2gwINNHvc1sxuDkfM",
    "SMptp2z/AiBqP267OO4qBHm17RDB5V8IN3gj4N+Q87KzkWsrpzw73w==",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]


drewbabyCert :: [String]
drewbabyCert =
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBrTCCAVGgAwIBAgIQXIRMjgxrarIElLVLGJSzgzAMBggqhkjOPQQDAgUAMEgx",
    "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu",
    "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjQwNjE3MTg1NDE3WhcNMjUwNjE3",
    "MTg1NDE3WjBoMTIwMAYDVQQDDClzZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRvbWVy",
    "Y2F0YS1kcmV3YmFieTEyMDAGA1UECgwpc2VydmljZS1hY2NvdW50LWlvLXN0cmF0",
    "b21lcmNhdGEtZHJld2JhYnkwVjAQBgcqhkjOPQIBBgUrgQQACgNCAAQ0vKTJAkSl",
    "8qxqSKXL4wsFL6qyhOArq41QxhWn8RQPWQmkF2x2qwO4iCUvpq/l7U7K3NR/iKaS",
    "07V2/Zte7L/GMAwGCCqGSM49BAMCBQADSAAwRQIhALFEbqlUUqRNEw1kR3MUBnBh",
    "6NtHk/5x2ecoJUaRFqNpAiBBILW/JW+HASD8pehEugTfFKNzT+vUtY+vwzXoKp/3",
    "hw==",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]
 

michaelCert :: [String]
michaelCert = 
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBqzCCAVCgAwIBAgIRALvn+fwsfRF8yAeDvQbyr5swDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDYxNDIwMTYxNFoXDTI1MDYx",
    "NDIwMTYxNFowZjExMC8GA1UEAwwoc2VydmljZS1hY2NvdW50LWlvLXN0cmF0b21l",
    "cmNhdGEtbWljaGFlbDExMC8GA1UECgwoc2VydmljZS1hY2NvdW50LWlvLXN0cmF0",
    "b21lcmNhdGEtbWljaGFlbDBWMBAGByqGSM49AgEGBSuBBAAKA0IABFp+fJbehq8W",
    "uCMM3EXKtUPlIEDUsyfzn9Kluq4ZRKTvZX9H41vm8YjCGqO7OYHFvHB4elM90s+W",
    "/SqRpixRDCkwDAYIKoZIzj0EAwIFAANHADBEAiBCAXoM53QSNDYzjyLbJeHm5SB1",
    "b7Eh9bHilqKrskSL1QIgaETlYuHdgNf4Y1jFp3gAh8Lh2Lx50ZZcnAHBvZmV0lE=",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]


drebbelCert :: [String]
drebbelCert = 
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBqzCCAU+gAwIBAgIQAeRpQD5XarisNXjqDcvVGDAMBggqhkjOPQQDAgUAMEgx",
    "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu",
    "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjQwNjE3MTU1MjQwWhcNMjUwNjE3",
    "MTU1MjQwWjBmMTEwLwYDVQQDDChzZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRvbWVy",
    "Y2F0YS1kcmViYmVsMTEwLwYDVQQKDChzZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRv",
    "bWVyY2F0YS1kcmViYmVsMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEZlu2Ogx2a7pD",
    "I+GwVGNpzaX1OqY3kmGYQfFoL0mCK/j4zPCvMsgZ3lYjoOGNLomDC+Z1Zz/Hn/7q",
    "od6QkzidCDAMBggqhkjOPQQDAgUAA0gAMEUCIQCpFAiZUgdPgZG+Sfg556fiQRgO",
    "PnRksNMj/TsWybnkogIgVhOZ/W9G9rBDj5eMdVAeFanvmpyu3M2WdCXrg00yTJA=",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]


keepethCert :: [String]
keepethCert = 
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBqzCCAU+gAwIBAgIQT3bwSp8OGlKesLtvhr0TzDAMBggqhkjOPQQDAgUAMEgx",
    "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu",
    "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjQwNjIxMTc1NzM1WhcNMjUwNjIx",
    "MTc1NzM1WjBmMTEwLwYDVQQDDChzZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRvbWVy",
    "Y2F0YS1rZWVwZXRoMTEwLwYDVQQKDChzZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRv",
    "bWVyY2F0YS1rZWVwZXRoMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE4TbETqgzP2dq",
    "ibgJnViHtyjL3ESQSzoIOmc+LtImjDA889Jr66FKZKG+eL6POSxapbP5ExQoHMfi",
    "9AxwKqSSijAMBggqhkjOPQQDAgUAA0gAMEUCIQDiqCbYHkwKhL+5mV24/CD2Ef5P",
    "b8uchmB61dHOTFYXcQIgAQE+tsw3rq6CfCI7Xc/uwkiuhvEY9Wee50gZqHdZ1ZQ=",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]


mercataDGSCert :: [String]
mercataDGSCert = 
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBlzCCATygAwIBAgIRAJCkh5op10we2lqvpgAI3NUwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDYyNDE2MzQxNloXDTI1MDYy",
    "NDE2MzQxNlowUjEnMCUGA1UEAwwec2VydmljZS1hY2NvdW50LWlvLW1lcmNhdGEt",
    "ZGdzMScwJQYDVQQKDB5zZXJ2aWNlLWFjY291bnQtaW8tbWVyY2F0YS1kZ3MwVjAQ",
    "BgcqhkjOPQIBBgUrgQQACgNCAATiuMhHbFf2tHrVrLadm6yM+16dOml+7r9Pg1hz",
    "wTGVDPxwdUiWtdTj9n35mzSem3m9gu2EYIGmk8wsmiIAtUfcMAwGCCqGSM49BAMC",
    "BQADRwAwRAIgG0fycHlvyPVjBuVLbV2QCqLjJVPt2FptBs4e4U4s7PUCICcGJDIW",
    "vI+3oEiwo9j/hcbB82yki3yxVUy7UJljqJ5r",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]


goldbergCert :: [String]
goldbergCert = 
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBrTCCAVKgAwIBAgIRAK9BV4vILe62O4hgjhdPiH8wDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDYyNDE4NTYxNloXDTI1MDYy",
    "NDE4NTYxNlowaDEyMDAGA1UEAwwpc2VydmljZS1hY2NvdW50LWlvLXN0cmF0b21l",
    "cmNhdGEtZ29sZGJlcmcxMjAwBgNVBAoMKXNlcnZpY2UtYWNjb3VudC1pby1zdHJh",
    "dG9tZXJjYXRhLWdvbGRiZXJnMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEbEnypHmA",
    "nu+YJIhV4PsZmqy3AVpdB5sm7fkbaVpTr96u+gs6/M7+pZWf5TjfKpA6psIeYUp0",
    "HSKXc3V8kmlVIjAMBggqhkjOPQQDAgUAA0cAMEQCIHhYPT02KHswqXhjEaQMG+5A",
    "YTBViUmoZODXtksyNvJYAiAIMbMEWDTafoWxAHWeRgvqdadkmnJN0f/Dcpu3DJHC",
    "Yw==",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]


hasanCert :: [String]
hasanCert = 
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIB2TCCAX6gAwIBAgIRAM57i/ALvYS3hhSu7AsFsIUwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDYyNzE5MjU1OFoXDTI1MDYy",
    "NzE5MjU1OFowgZMxOzA5BgNVBAMMMnNlcnZpY2UtYWNjb3VudC1Jby1zdHJhdG9t",
    "ZXJjYXRhLWhhc2FudGhldmFsaWRhdG9yMTswOQYDVQQKDDJzZXJ2aWNlLWFjY291",
    "bnQtSW8tc3RyYXRvbWVyY2F0YS1oYXNhbnRoZXZhbGlkYXRvcjEJMAcGA1UECwwA",
    "MQwwCgYDVQQGDANVU0EwVjAQBgcqhkjOPQIBBgUrgQQACgNCAAScWZtdlFbdNuXJ",
    "CVSYG1+zVQUhbClZvGa4u/Ieo0UkvlFLJZFdaJjOtbhFLuhLrFE2I+ptjf0LyiMT",
    "BzwFIO+5MAwGCCqGSM49BAMCBQADRwAwRAIgO4oIx91FT4YjS9u+wHbQpiSv4R66",
    "M4mwqLO7JaZYrwACICMApvTtC3Yjekkx1JS2A2930DqLAOb14qJ5Zl/007Q/",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]


numbatCert :: [String]
numbatCert = 
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIB0zCCAXegAwIBAgIQBwuDoh/QpQDDS09jTJhKpTAMBggqhkjOPQQDAgUAMEgx",
    "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu",
    "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjQwNjI3MTkzMTM3WhcNMjUwNjI3",
    "MTkzMTM3WjCBjTE4MDYGA1UEAwwvc2VydmljZS1hY2NvdW50LUlvLXN0cmF0b21l",
    "cmNhdGEtbnVtYmF0d29wZW5jaWwxODA2BgNVBAoML3NlcnZpY2UtYWNjb3VudC1J",
    "by1zdHJhdG9tZXJjYXRhLW51bWJhdHdvcGVuY2lsMQkwBwYDVQQLDAAxDDAKBgNV",
    "BAYMA1VTQTBWMBAGByqGSM49AgEGBSuBBAAKA0IABKMw/tYOtIwacNbeL77nsR0D",
    "OwU06LY+t6zvdfM7egml0CtKw3NNMumKdlDL7LJ3uSjYgOjLjGzRqdU/71wnUhsw",
    "DAYIKoZIzj0EAwIFAANIADBFAiEA2GALTswkKusmZuW7LuGZ9yhsulGrR1wotKrx",
    "HP4W9hkCIHMxf+h66i0V1ZiOFRHql5XtG+t3DJ3LEyn6B5lKAQtT",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]


jaimeCert :: [String]
jaimeCert =
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBqjCCAU6gAwIBAgIRAOwWKTwYmgMWrd3BM+Y9Tb0wDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDYyNjE3Mjk0MFoXDTI1MDYy",
    "NjE3Mjk0MFowZDEwMC4GA1UEAwwnc2VydmljZS1hY2NvdW50LWlvLXN0cmF0b21l",
    "cmNhdGEtamdvbnpvMTAwLgYDVQQKDCdzZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRv",
    "bWVyY2F0YS1qZ29uem8wVjAQBgcqhkjOPQIBBgUrgQQACgNCAAROrgUxqBJcd32T",
    "3mTAQnhbM4K/bJZCJ2pU4vsm0lGLcFBp23iz9Ez+DesD3Yc+lLe0t1CuWc36Mh+X",
    "wPGUJia2MAwGCCqGSM49BAMCBQADSAAwRQIhANWoTXZYwD1Wf7ETXD0X0z9CL/eC",
    "v7KgF9Ml26Nl8d2vAiBizvYyHtkf2Qek58RAm3X9hYYB1NvlMZeLhaaxlXWCJw==",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]


jacoboCert :: [String]
jacoboCert = 
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBrjCCAVKgAwIBAgIRAPrEt+ogxcJgTF03LmQ/J5gwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDYyNjE3MzAxOFoXDTI1MDYy",
    "NjE3MzAxOFowaDEyMDAGA1UEAwwpc2VydmljZS1hY2NvdW50LWlvLXN0cmF0b21l",
    "cmNhdGEtamFjb2d1em8xMjAwBgNVBAoMKXNlcnZpY2UtYWNjb3VudC1pby1zdHJh",
    "dG9tZXJjYXRhLWphY29ndXpvMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE0iEiJK2V",
    "i7pg1iWFDgOtrvVvh/dEQnqttlMrQnMQDOaXnoYt3WJifMhm/HBEs9JapVZVj0bk",
    "VOSSlrMFmj9z/DAMBggqhkjOPQQDAgUAA0gAMEUCIQC0EOETgbD2yNaXs4HJqEdu",
    "jlqlqQxkLS+KN36gn4bNjwIgWJdz3SlymqAytL1aEWfdCzg49kv/wKJguJqsskNN",
    "H3o=",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]


zeekCert :: [String]
zeekCert = 
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBpDCCAUmgAwIBAgIQWLLpZK0bVNHWK8l899AcszAMBggqhkjOPQQDAgUAMEgx",
    "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu",
    "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjQwNjI3MTM0ODEyWhcNMjUwNjI3",
    "MTM0ODEyWjBgMS4wLAYDVQQDDCVzZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRvbWVy",
    "Y2F0YS16ZWVrMS4wLAYDVQQKDCVzZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRvbWVy",
    "Y2F0YS16ZWVrMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEq1F8QudarncN15ZoQwY+",
    "jiS5UpZ1JqcrKcIT+epYc3p59na2ubTgEB6fjFGeQ60wJVsjM6if9L5FePZcgUMX",
    "WjAMBggqhkjOPQQDAgUAA0cAMEQCIAt6qjveB7xwrTFH3RHjw/o3eqhhsPksI5qb",
    "rxaO2+B7AiANwl8diOnWNawS63vq+cmm/Fb6MZYMsasNrOXUGTU6SQ==",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]


mecmo4mopmCert :: [String]
mecmo4mopmCert = 
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBsDCCAVWgAwIBAgIQdU4Sgkd43QUSy9Anvk+L6zAMBggqhkjOPQQDAgUAMEgx",
    "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu",
    "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjQwNjI4MTQzNTI3WhcNMjUwNjI4",
    "MTQzNTI3WjBsMTQwMgYDVQQDDCtzZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRvbWVy",
    "Y2F0YS1tZWNtbzRtb3BtMTQwMgYDVQQKDCtzZXJ2aWNlLWFjY291bnQtaW8tc3Ry",
    "YXRvbWVyY2F0YS1tZWNtbzRtb3BtMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAED5Wm",
    "+JJMpnB0JgyjcDYu7yygGn7hvaSSVHQQeSGC7XpUEfoGUE0oZ+usl4gp636Jhlk+",
    "Y9QYVuTbbR7IPpT/VjAMBggqhkjOPQQDAgUAA0cAMEQCIG54P1vUSb4EVaINXbWN",
    "qwqqPAsqbbSNjwy7UEATGCShAiBiwHistPWHB/pixsxqjfeGKFQXcFsPYbIAYO+u",
    "cFWLHA==",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]



goldbackCert :: [String]
goldbackCert = 
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBtjCCAVugAwIBAgIQLEdXMCAV5SQ/DLzPMYttqTAMBggqhkjOPQQDAgUAMEgx",
    "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu",
    "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjQwNjI4MTQ0MTU2WhcNMjUwNjI4",
    "MTQ0MTU2WjByMTcwNQYDVQQDDC5zZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRvbWVy",
    "Y2F0YS1nb2xkYmFja3Rva2VuMTcwNQYDVQQKDC5zZXJ2aWNlLWFjY291bnQtaW8t",
    "c3RyYXRvbWVyY2F0YS1nb2xkYmFja3Rva2VuMFYwEAYHKoZIzj0CAQYFK4EEAAoD",
    "QgAEkd9T2aWszple7+lvUJoyTQKDejYhJRfvo+WmNhh6DcbK8G9QFX7GK2RLaeDk",
    "j9NyDyGk0XsRhxFSM3i9IZ0YWDAMBggqhkjOPQQDAgUAA0cAMEQCIGJXNb6LgY7K",
    "KI7vxvUlNmYYzb4a5/E5mfLQpKaGtEVZAiAYb8Wgveay5VOoF/RJpknZtjKrKXcG",
    "6m4El9UmaIXz+A==",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]

itaugmentationCert :: [String]
itaugmentationCert = 
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBuDCCAV2gAwIBAgIQFEBGklTtJTwqu9dDIaO85TAMBggqhkjOPQQDAgUAMEgx",
    "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu",
    "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjQwNjI4MTQ0MDE0WhcNMjUwNjI4",
    "MTQ0MDE0WjB0MTgwNgYDVQQDDC9zZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRvbWVy",
    "Y2F0YS1pdGF1Z21lbnRhdGlvbjE4MDYGA1UECgwvc2VydmljZS1hY2NvdW50LWlv",
    "LXN0cmF0b21lcmNhdGEtaXRhdWdtZW50YXRpb24wVjAQBgcqhkjOPQIBBgUrgQQA",
    "CgNCAARgc9X8D6my/xG5BqGN8VkoTZ6I5nDzi8Xn1sdO7nkr7aT7v+PYvFc/HQUQ",
    "bfNv3S760Yrqkk0X8tvzH4J8yJySMAwGCCqGSM49BAMCBQADRwAwRAIgZtdY2qBl",
    "MhuOoZtCePP78YwzaMHeRcekUyVbTjNhIU8CIBgU1B9VdoxN6L35ay0+5HF+0mrO",
    "mEifG+mFHuMqyvjn",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]

vinfraCert :: [String]
vinfraCert = 
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBqTCCAU2gAwIBAgIQbMMZKaCOd9eJSe3KkhHcNjAMBggqhkjOPQQDAgUAMEgx",
    "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu",
    "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjQwNzAxMjA1NjU4WhcNMjUwNzAx",
    "MjA1NjU4WjBkMTAwLgYDVQQDDCdzZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRvbWVy",
    "Y2F0YS12aW5mcmExMDAuBgNVBAoMJ3NlcnZpY2UtYWNjb3VudC1pby1zdHJhdG9t",
    "ZXJjYXRhLXZpbmZyYTBWMBAGByqGSM49AgEGBSuBBAAKA0IABOxK2ulte28QaTzo",
    "c1LGo4VFiSbCDqDS14ahZnT1T2SvoAufDIytHs00z4fuK+/OdVLb6fK519qkzjhb",
    "OTy9ZJEwDAYIKoZIzj0EAwIFAANIADBFAiEAsSUlPwM0/RzUe3Tqycz7Ur9R0Me/",
    "nIn8b0e3KQQzzpwCICoEXw4iQ4lcFiwmTWcRrNyU4tal11KqgOfdKKWOTOb2",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]


bibleCert :: [String]
bibleCert = 
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBpjCCAUugAwIBAgIQYNoyZV6t3o91EfKP0BfdczAMBggqhkjOPQQDAgUAMEgx",
    "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu",
    "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjQwNjI3MTUzNTM3WhcNMjUwNjI3",
    "MTUzNTM3WjBiMS8wLQYDVQQDDCZzZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRvbWVy",
    "Y2F0YS1iaWJsZTEvMC0GA1UECgwmc2VydmljZS1hY2NvdW50LWlvLXN0cmF0b21l",
    "cmNhdGEtYmlibGUwVjAQBgcqhkjOPQIBBgUrgQQACgNCAATbdHOEx9p7KyqYS/RM",
    "BDmpiF4KJix8eEc/9g1oHwz6C+F0PHL5GiqCFNZ2d5X3tnaFIaqc0tukpeESh0IF",
    "1mk4MAwGCCqGSM49BAMCBQADRwAwRAIgEsJOrgcSrft1bS+CrshzTGszGdLBrCvN",
    "5MXKQgtNKncCICQ6eNkKES+zd+C9QtIv0jCPwgQ2EsDHwsVStBbcD0gV",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]

jamroseCert :: [String]
jamroseCert = 
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBszCCAVigAwIBAgIQBzaBOIqnPR8c2v5EyRTouTAMBggqhkjOPQQDAgUAMEgx",
    "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu",
    "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjQwNzA4MTU0MzMyWhcNMjUwNzA4",
    "MTU0MzMyWjBvMSEwHwYDVQQDDBhqYW1yb3NlLnN0cmF0b21lcmNhdGEuaW8xMTAv",
    "BgNVBAoMKHNlcnZpY2UtYWNjb3VudC1pby1zdHJhdG9tZXJjYXRhLWphbXJvc2Ux",
    "CTAHBgNVBAsMADEMMAoGA1UEBgwDVVNBMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE",
    "Enx13VFoFZvPXB31BTLGiGeJbEDsE1kHALV0CnSeW+CBts//iSugLNIgBfDoXm5Z",
    "tl3Jku2Gz6HXFykldOjqgDAMBggqhkjOPQQDAgUAA0cAMEQCIFPsMeZi4l+rXSLU",
    "HMvoz/il0fp6djnTEHwX68xnwSvMAiAqPkMpV1WSXXU4wC4+j+gAksABZFa20+gs",
    "GE/2qcyepg==",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]

dttr1Cert :: [String]
dttr1Cert = 
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBpzCCAUugAwIBAgIQDCdLDHLomyVv5YtFgH/ErjAMBggqhkjOPQQDAgUAMEgx",
    "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu",
    "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjQwNzExMjAwNjUyWhcNMjUwNzEx",
    "MjAwNjUyWjBiMS8wLQYDVQQDDCZzZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRvbWVy",
    "Y2F0YS1kdHRyMTEvMC0GA1UECgwmc2VydmljZS1hY2NvdW50LWlvLXN0cmF0b21l",
    "cmNhdGEtZHR0cjEwVjAQBgcqhkjOPQIBBgUrgQQACgNCAATEXxE7cR3SoKmKbgUf",
    "WarK/mTjmtVYRJsQgu6kKf14W1i/cjYqGa8vwSGHqC7p1War6gR9n3Qk2hkhMyka",
    "/WPZMAwGCCqGSM49BAMCBQADSAAwRQIhAKB/8NjftE7BzNp2ab4d3uK9mKRPCc29",
    "yqyFRm80b2uHAiBez4y94FUR/PtrTPhbQbC/kGUmICueiViB3a+wC2sFyw==",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]

dttr2Cert :: [String]
dttr2Cert = 
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBpzCCAUugAwIBAgIQJ9tp5q8RzBt0HximVFZQ7jAMBggqhkjOPQQDAgUAMEgx",
    "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu",
    "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjQwNzExMjAwODEzWhcNMjUwNzEx",
    "MjAwODEzWjBiMS8wLQYDVQQDDCZzZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRvbWVy",
    "Y2F0YS1kdHRyMjEvMC0GA1UECgwmc2VydmljZS1hY2NvdW50LWlvLXN0cmF0b21l",
    "cmNhdGEtZHR0cjIwVjAQBgcqhkjOPQIBBgUrgQQACgNCAAQU7LcXBoMUT5/t2veF",
    "cmKU7yK2nPkHpoT9I6MnmqP9Z+4jRHqCAi4ERPP6tzcvbm4kYfef6E+OfMK8ELcb",
    "+c5GMAwGCCqGSM49BAMCBQADSAAwRQIhAO1LmZ3dFnIV7Btg+rcZIcACyQNZGKbE",
    "dVzWhWld72TYAiBtI0TRLN4CGjjBKf6gck/297MIFPLkRGApVlnk50mGYg==",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]

illerChillerCert :: [String]
illerChillerCert =
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBazCCARCgAwIBAgIRALbOF9UYi3by+UhPUB3HBoswDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDkwNDE3Mjg0OFoXDTI1MDkw",
    "NDE3Mjg0OFowJjEZMBcGA1UEAwwQaWxsZXJjaGlsbGVyLmNvbTEJMAcGA1UECgwA",
    "MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEmQS+a+LcpWh02ikISK09zRvelhWeiiiZ",
    "dE0Yx3V8S8TOKBCiy+tFUtooLHXChFoCxaGMZ1mbijFclePbXg2uNzAMBggqhkjO",
    "PQQDAgUAA0cAMEQCIGU7LYck3KOpnPHuSFRyI0WVMkXY1lhyDY73g2NUTfHcAiA0",
    "NSlNvaN5ZC2Lh6zew/8AFkQIIvApLB9g6x27ZKnb+Q==",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]

greenrubricOpenwealthfiCert :: [String]
greenrubricOpenwealthfiCert =
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBjjCCATKgAwIBAgIRAPVJgkW4YcOBK8CKWEzVN3kwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDkxMDE2MjQ0NloXDTI1MDkx",
    "MDE2MjQ0NlowSDElMCMGA1UEAwwcZ3JlZW5ydWJyaWMub3BlbndlYWx0aGZpLmNv",
    "bTEfMB0GA1UECgwWaWRlbnRpdHkuYmxvY2thcHBzLm5ldDBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABOAYGn5SVny3wK6MHp4Ln+U/65FgPdbAEpSF3qjUwP8j2zW1PoIP",
    "T3lW87+0Vw0iI0IAUvRng5IYKxDDQPCQ2+kwDAYIKoZIzj0EAwIFAANIADBFAiEA",
    "8kT4XUwJykqWc13C03NmDDllMbXHoYZJKXLBilrW+voCIBGTDk+L0ZNLmB0OmySj",
    "iUe8CPWrM3TCfozkrk/Ii8gb",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]

events34OpenwealthfiCert :: [String]
events34OpenwealthfiCert =
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBijCCAS6gAwIBAgIQTfCTdYMxtSI595eB59LyQjAMBggqhkjOPQQDAgUAMEgx",
    "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu",
    "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjQwOTExMTQxNjEwWhcNMjUwOTEx",
    "MTQxNjEwWjBFMSIwIAYDVQQDDBlldmVudHMzNC5vcGVud2VhbHRoZmkuY29tMR8w",
    "HQYDVQQKDBZpZGVudGl0eS5ibG9ja2FwcHMubmV0MFYwEAYHKoZIzj0CAQYFK4EE",
    "AAoDQgAE+IiwXz2mTLM+QAjiEYHyikAqAH7HApJIgh6rBUwXknDP11IUllXXUg24",
    "Cc4ZIOKmBm2BCIbOROLude7XuCq+bjAMBggqhkjOPQQDAgUAA0gAMEUCIQCmi3z0",
    "BCJEVPdlIZO7OdxWs4uO5hCijbTjWLQ3Sk/FwgIgLInCR8vg4DjOWT3+do7GwT1o",
    "ybb9AdOiUnWZaDwQ1j8=",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]

coachInstanodesCert :: [String]
coachInstanodesCert =
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBbjCCAROgAwIBAgIRALdDZ207QkaxVegb9HIxN04wDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDkwNjE2MTI1N1oXDTI1MDkw",
    "NjE2MTI1N1owKTEcMBoGA1UEAwwTY29hY2guaW5zdGFub2Rlcy5pbzEJMAcGA1UE",
    "CgwAMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEU9v406kjcCF82tEg09stFn58SFz1",
    "YMP60e0BdnNguOB6ebQqgYLqMY6KjSmlBiHPTvOb7UfouwEmiG6QzIg20jAMBggq",
    "hkjOPQQDAgUAA0cAMEQCIHh4xAbnp9e2Qb99KEshjwSB5bYrx26UKXYrBLLVZkub",
    "AiATsRt5eC1GTJI6kEMr1uGfbWthbaWOSLpFod1M6E6IIQ==",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]

joyzOpenwealthfiCert :: [String]
joyzOpenwealthfiCert =
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBbzCCARSgAwIBAgIQJWfxHNXw9RoQSwCkWiqMbjAMBggqhkjOPQQDAgUAMEgx",
    "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu",
    "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjQwOTA2MTYwODEzWhcNMjUwOTA2",
    "MTYwODEzWjArMR4wHAYDVQQDDBVqb3l6Lm9wZW53ZWFsdGhmaS5jb20xCTAHBgNV",
    "BAoMADBWMBAGByqGSM49AgEGBSuBBAAKA0IABD+iLR5UFe6Ep0ZHqcULw4TopbM5",
    "iCAOPtUMSSUG8/sRjeDPHuNoSRfYz+OT1U+p6sUhM6L8qVeVIVGUUPZpIZYwDAYI",
    "KoZIzj0EAwIFAANHADBEAiBn9W5FZAc5VmOdMsat4sHGr5mxygonhTHF9ZVfAgQb",
    "ygIgDiCMLQWV6f5TZzcI46gIpnfaj5OZbK1RyNIu1p+UY8M=",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]

-- testnet certs
wongwayTestnetCert :: [String]
wongwayTestnetCert = 
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBrDCCAVCgAwIBAgIRALcxCPz8/sY2mDwguBzujZcwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDMxMzE0MTQ1M1oXDTI1MDMx",
    "MzE0MTQ1M1owZjExMC8GA1UEAwwoc2VydmljZS1hY2NvdW50LWlvLXN0cmF0b21l",
    "cmNhdGEtd29uZ3dheTExMC8GA1UECgwoc2VydmljZS1hY2NvdW50LWlvLXN0cmF0",
    "b21lcmNhdGEtd29uZ3dheTBWMBAGByqGSM49AgEGBSuBBAAKA0IABEpx2//l2yLd",
    "fxdyuMTJ2T+BnIuEwOU2SoQ0FKXFOIIZF69ga8aUcQbczL0AykuyusY3eJjZGzCg",
    "p/HcVHZK+ZowDAYIKoZIzj0EAwIFAANIADBFAiEA9CL7qhNCPCJcICEGonf7SEcd",
    "gklZQRk3Brn+vC20dooCIBKnf5BqCg4l0IQALx+Fnr1j9vNqKmvv1FYtwVIBnNdw",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBojCCAUagAwIBAgIQbcliNO33GaGDMmm2KNvuKTAMBggqhkjOPQQDAgUAMEgx",
    "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu",
    "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjMwODAyMTgyMzI3WhcNMjQwODAy",
    "MTgyMzI3WjBdMSMwIQYDVQQDDBpJRCBTZXJ2ZXIgbWVyY2F0YS10ZXN0bmV0MjES",
    "MBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtFbmdpbmVlcmluZzEMMAoGA1UE",
    "BgwDVVNBMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE0KUM1Qj3Ly+1fIy8V1mpQdZk",
    "JU3O/vh53vF6mEIvHfdxOoFCbFXZntfHVvBGydVIPOrg+xiYBIOsiqrpfVA41DAM",
    "BggqhkjOPQQDAgUAA0gAMEUCIQD0BUEg4V5s+ox+vnlJwwShJO+Yz5Jhow8I8lh0",
    "EwL2HgIgeISfz3+oTjYXLvTI87gQNX4TicwTH8hCAfFyQRUhSQw=",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]

kierensNodeTestnetCert :: [String]
kierensNodeTestnetCert = 
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBvjCCAWKgAwIBAgIQBVrzjO9qo1uvpgdfnQpj4TAMBggqhkjOPQQDAgUAMEgx",
    "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu",
    "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjQwMzE4MTkyODMyWhcNMjUwMzE4",
    "MTkyODMyWjB5MTUwMwYDVQQDDCxzZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRvbWVy",
    "Y2F0YS1raWVyZW5zbm9kZTE1MDMGA1UECgwsc2VydmljZS1hY2NvdW50LWlvLXN0",
    "cmF0b21lcmNhdGEta2llcmVuc25vZGUxCTAHBgNVBAsMADBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABEQJrfKVneqe18B8fIWIAfLQdobnmi8MoT05fJbJBF48WBoLAEvf",
    "GD9QlhQeTtk/AtWtHwzHjIJtoceYkY2yCw8wDAYIKoZIzj0EAwIFAANIADBFAiEA",
    "0XxMEzZUprgkMBjc7eSC/XfwZY/hd3MIOnyH3uQ8llACICpN+NwVDPa8RAVb62sE",
    "p4j2CqF7MdGjNeqmMN6wBlnz",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]

dustinNodeTestnetCert :: [String]
dustinNodeTestnetCert = 
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBfzCCASOgAwIBAgIQBu4M1uqyyZAO4LVDaTlgNDAMBggqhkjOPQQDAgUAMEgx",
    "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu",
    "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjQwMzI1MTc1OTIwWhcNMjUwMzI1",
    "MTc1OTIwWjA6MRQwEgYDVQQDDAtkdXN0aW4tbm9kZTEJMAcGA1UECgwAMQkwBwYD",
    "VQQLDAAxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEGBSuBBAAKA0IABGo/XDRp",
    "wejuMkBApchlyMcqptlb73qbL1GRh9bWXw63W08ZnhIGdbvaDqT2gh6xMHkI803+",
    "Md4QWXXKfgzrVDQwDAYIKoZIzj0EAwIFAANIADBFAiEAoKjLugusQaCM4971buEA",
    "XVHnYGtA8KEhyYI8w5D3INsCIHBkxc1GtA7/n1Dew8aGjdMDL5K/2D5/264Hxz2o",
    "AUZf",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]

multinode302TestnetCert :: [String]
multinode302TestnetCert = 
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBkDCCATWgAwIBAgIRAN97g6SFz1/OnJJPHg0CExIwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDQwNDIxMTcwMVoXDTI1MDQw",
    "NDIxMTcwMVowSzEVMBMGA1UEAwwMTXVsdGlub2RlMzAyMRIwEAYDVQQKDAlCbG9j",
    "a0FwcHMxEDAOBgNVBAsMB01lcmNhdGExDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49",
    "AgEGBSuBBAAKA0IABPGtdYrmzUAXT7RBy+274rmpJEexjQj5nWrpCpICPD1RlQI4",
    "EigbFx6/nJ8b/HuFDDZKuenpsPCsXxnlrIpndwowDAYIKoZIzj0EAwIFAANHADBE",
    "AiBGoInsSUB2s5RLiSINWrkUJrebnSKh1iVjsAOwe5vzcQIgGKMPENmsKQMuIbuv",
    "MI9N1JlDsqmHiqV+ul01cUZEw4E=",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]

dmoneyTestnetCert :: [String]
dmoneyTestnetCert = 
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBhjCCASugAwIBAgIQB22BFCJXO8hLVHnnkSLlzzAMBggqhkjOPQQDAgUAMEgx",
    "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu",
    "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjQwNTEwMTc0MTE5WhcNMjUwNTEw",
    "MTc0MTE5WjBCMRgwFgYDVQQDDA9kbW9uZXktdGVzdG5ldDIxDTALBgNVBAoMBEFD",
    "TUUxCTAHBgNVBAsMADEMMAoGA1UEBgwDVVNBMFYwEAYHKoZIzj0CAQYFK4EEAAoD",
    "QgAEsFkq1BUKp9looEGZ6ygneRTB/v+3yLnIB/2eWYATQV79vaeoq4xThnLoX2P1",
    "HsVGvUMU+8+2slANgJ8dcIz/9jAMBggqhkjOPQQDAgUAA0cAMEQCIFY4FPXbZ/L/",
    "GUSYR19IS/kHDhZdnElbHqHpz4lXrg+bAiBpKzS/osBhARz8MCUVZgl8x/DFPXyT",
    "FsrCplaFD3hBCQ==",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]

mercataUraniumCerts :: [[String]]
mercataUraniumCerts = [
    ["-----BEGIN CERTIFICATE-----\nMIIBnDCCAUGgAwIBAgIRAKExeJ+d9E5YGovR5rtGsPYwDAYIKoZIzj0EAwIFADBI\nMQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF\nbmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDkxMTE1NTM0MVoXDTI1MDkx\nMTE1NTM0MVowVzEdMBsGA1UEAwwUbWVyY2F0YS1kZXZuZXQtbm9kZTUxNjA0BgNV\nBAoMLWlkZW50aXR5Lm1lcmNhdGEtZGV2bmV0LTN2ejJocWYuYmxvY2thcHBzLm5l\ndDBWMBAGByqGSM49AgEGBSuBBAAKA0IABPsGN7aMsIl4lGnhiYQ/OkfboG9WS3Mm\n1kH94eX+b8DbpNSSDryuVQxhlVP+bcD9nOiB1yIYwhygIJuIG9IuZjwwDAYIKoZI\nzj0EAwIFAANHADBEAiAuL9f+ssG6vZUYjrXFUBq4DptERTc55Ot2tLW2jjZosAIg\nKak9wahjl4ioKORYaQvMWTanvM7y97uhM9RXfovJ6Ok=\n-----END CERTIFICATE-----\n-----BEGIN CERTIFICATE-----\nMIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI\nMQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF\nbmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy\nMDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU\nMBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG\nBSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs\n9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8\nR0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n\nN8txKc8G9R27ZYAUuz15zF0=\n-----END CERTIFICATE-----\n"
  ],["-----BEGIN CERTIFICATE-----\nMIIBmzCCAUCgAwIBAgIQGnQWzkp6yomu1hZrjJCCDTAMBggqhkjOPQQDAgUAMEgx\nDjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu\nZ2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjQwOTExMTY1MzUzWhcNMjUwOTEx\nMTY1MzUzWjBXMR0wGwYDVQQDDBRtZXJjYXRhLWRldm5ldC1ub2RlNjE2MDQGA1UE\nCgwtaWRlbnRpdHkubWVyY2F0YS1kZXZuZXQtM3Z6MmhxZi5ibG9ja2FwcHMubmV0\nMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEs6jQ5kPF7dRgyvfe0iCWEf1kh5J8R33c\nErlxaCZZYwHoC+nAwe4hFcvg0HL+cNY5mhv2M6Dje/zamuGwHMtJPDAMBggqhkjO\nPQQDAgUAA0cAMEQCIDSoBX60pdQNIMf31atpf7VEr1LVhHRpIEIMplm4tUWJAiAw\nVWrcqD8nSvpcC5vgs/cvjGAtDpqPZSrI55xht/0AAQ==\n-----END CERTIFICATE-----\n-----BEGIN CERTIFICATE-----\nMIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI\nMQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF\nbmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy\nMDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU\nMBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG\nBSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs\n9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8\nR0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n\nN8txKc8G9R27ZYAUuz15zF0=\n-----END CERTIFICATE-----\n"
  ]]

extraCertsHack :: [(Address, X509CertInfoState)]
extraCertsHack =
  map
    ((\val -> (userAddress val, val)) . x509CertToCertInfoState . getCert) $
    [
      witmkCert,
      jpowellCert,
      chessCert,
      aaaCert,
      troubleCert,
      dsnallapuCert,
      kierensNodeCert,
      wongwayCert,
      dustinNodeCert,
      tysonCert, 
      neelCert,
      drewbabyCert,
      michaelCert,
      drebbelCert,
      keepethCert,
      mercataDGSCert,
      goldbergCert,
      hasanCert,
      numbatCert,
      jaimeCert,
      jacoboCert,
      zeekCert,
      mecmo4mopmCert,
      goldbackCert,
      itaugmentationCert,
      vinfraCert,
      bibleCert,
      jamroseCert,
      dttr1Cert,
      dttr2Cert,
      illerChillerCert,
      greenrubricOpenwealthfiCert,
      events34OpenwealthfiCert,
      coachInstanodesCert,
      joyzOpenwealthfiCert,
      -- testnet certs
      wongwayTestnetCert,
      kierensNodeTestnetCert,
      dustinNodeTestnetCert,
      multinode302TestnetCert,
      dmoneyTestnetCert
    ] ++ mercataUraniumCerts
