
module Blockchain.Sequencer.ExtraCertsHack where

import BlockApps.X509.Certificate
import Blockchain.Strato.Model.Address
import qualified Data.ByteString.Char8 as BC


getCert :: [String] -> X509Certificate
getCert certLines =
  let eCert = 
        bsToCert $
          BC.pack $
            unlines certLines
   in case eCert of
        Left _ -> error "malformed cert passed to getCert"
        Right c -> c

--0x94f5f0f4d60635324bb2a4dde14c0101bfc92cb1
troubleCert :: [String]
troubleCert =
  [ "-----BEGIN CERTIFICATE-----",
    "MIIBqzCCAVCgAwIBAgIRAK2hc+TQ4jH11q+Ogf5qvGUwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDMyODIxMjU0NloXDTI1MDMy",
    "ODIxMjU0NlowZjExMC8GA1UEAwwoc2VydmljZS1hY2NvdW50LWlvLXN0cmF0b21l",
    "cmNhdGEtdHJvdWJsZTExMC8GA1UECgwoc2VydmljZS1hY2NvdW50LWlvLXN0cmF0",
    "b21lcmNhdGEtdHJvdWJsZTBWMBAGByqGSM49AgEGBSuBBAAKA0IABKkkF/LGEY67",
    "YL9SMzIBb+wzZV9uYwOePWMstGkdm3F3sBz7Jbigk9kS8DzmHmBWQ3qmAcoDgVWs",
    "8vZwiopMr/MwDAYIKoZIzj0EAwIFAANHADBEAiAme5CoTnALethPtUvyVSPilZAM",
    "ushbAwhMrqjkmuVDkQIgRdScp27rcgHVumJRerrzloUZbSEUq9kM47oONAsBWJg=",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]
{-
--94f5dc46e634d405b23b187fe8889b4777b6771a
theCert2 :: [String]
theCert2 =
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBpzCCAUygAwIBAgIRAMl4n0xrJmbcFGICZv6yzxwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDMyODIxMjIzMVoXDTI1MDMy",
    "ODIxMjIzMVowYjEvMC0GA1UEAwwmc2VydmljZS1hY2NvdW50LWlvLXN0cmF0b21l",
    "cmNhdGEtd2l0bWsxLzAtBgNVBAoMJnNlcnZpY2UtYWNjb3VudC1pby1zdHJhdG9t",
    "ZXJjYXRhLXdpdG1rMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEILu6iw762puMMW5Z",
    "Hsi679nOOh5OukxrO9SmcC7UAvP1Pz/YVPh9tn0Z6n8/yBv1VFsmEp1YUlmfT+ah",
    "AqyKAjAMBggqhkjOPQQDAgUAA0cAMEQCIGHxHQM6pmundoLj+GcMNbJZ0uMQiBmB",
    "nRU9bhOnLZs7AiAZtqdkMbBstvr3F5K/Hbl+XXXZWPBwDdxWm1R0f81K5Q==",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]
-}
--94f5dc46e634d405b23b187fe8889b4777b6771a
witmkCert :: [String]
witmkCert =
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBqDCCAU2gAwIBAgIQQh8kvRQy4eLpClNElBhE8jAMBggqhkjOPQQDAgUAMEgx",
    "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu",
    "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjQwMzI4MjEwMTUxWhcNMjUwMzI4",
    "MjEwMTUxWjBkMS8wLQYDVQQDDCZzZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRvbWVy",
    "Y2F0YS13aXRtazExMC8GA1UECgwoc2VydmljZS1hY2NvdW50LWlvLXN0cmF0b21l",
    "cmNhdGEtd29uZ3dheTBWMBAGByqGSM49AgEGBSuBBAAKA0IABCC7uosO+tqbjDFu",
    "WR7Iuu/ZzjoeTrpMazvUpnAu1ALz9T8/2FT4fbZ9Gep/P8gb9VRbJhKdWFJZn0/m",
    "oQKsigIwDAYIKoZIzj0EAwIFAANHADBEAiA/LBAjSXf1Riak75NLDGl/h1stc3wD",
    "I8RaDKYPzwgamgIgG3krnPnaXWyPS++kLuDEtCBMcdMg4n1oL+7KhFTDBnE=",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]


--d59214182be7bf96fb8155b178683b9b18e97eae
jpowellCert :: [String]
jpowellCert =
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBqzCCAVCgAwIBAgIRAKhbiqKXXuu4HaP/ddCnzdEwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDMyODIxMDgxNloXDTI1MDMy",
    "ODIxMDgxNlowZjExMC8GA1UEAwwoc2VydmljZS1hY2NvdW50LWlvLXN0cmF0b21l",
    "cmNhdGEtanBvd2VsbDExMC8GA1UECgwoc2VydmljZS1hY2NvdW50LWlvLXN0cmF0",
    "b21lcmNhdGEtanBvd2VsbDBWMBAGByqGSM49AgEGBSuBBAAKA0IABMgKZNt+MyIh",
    "j6eQs20ndPDlQtywNn3emd3o46J3/pMC93A5pq1thCC9hILII26bPJDTzWE8fY3I",
    "crw1m1BWpocwDAYIKoZIzj0EAwIFAANHADBEAiBep/vzAN3iKHCEDB3IQTFEQzkp",
    "LKH1vhoR41cuVUj1KwIgfx7EKlg2D7/jhtLVeGYupm2Spg3PLC4U+QpmhbCBHTE=",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]

  
--15da843f489440e9b7f47d824b295f698b4a112a
aaaCert :: [String]
aaaCert =
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBozCCAUigAwIBAgIRAIz+ALn+2FIny20dvFE9hL4wDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDMyODIxMjcxN1oXDTI1MDMy",
    "ODIxMjcxN1owXjEtMCsGA1UEAwwkc2VydmljZS1hY2NvdW50LWlvLXN0cmF0b21l",
    "cmNhdGEtYWFhMS0wKwYDVQQKDCRzZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRvbWVy",
    "Y2F0YS1hYWEwVjAQBgcqhkjOPQIBBgUrgQQACgNCAASnxGg2073E2DieYq6A1Vkx",
    "H5BGe47cHMtwDaHLBgeMNzpuvmAVS5WIOwZVaUefp0og3vEEd5RibddmtS+5/Ndz",
    "MAwGCCqGSM49BAMCBQADRwAwRAIgeGeAR6eotLI8vZ/mOxNhPBFJhazB10+62jyb",
    "CBL70lECIHl0QK/yADCNavzyC/ekoehwh0L3PZUKK1crT45wL2+r",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]
  
--75c42fe751cc3dd9ce4bfdbedba99e75c034377a
dsnallapuCert :: [String]
dsnallapuCert =
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBrzCCAVSgAwIBAgIRAJE2RKKAUGSSuPdNV2GTmv4wDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDMyODIxMzY0MVoXDTI1MDMy",
    "ODIxMzY0MVowajEzMDEGA1UEAwwqc2VydmljZS1hY2NvdW50LWlvLXN0cmF0b21l",
    "cmNhdGEtZHNuYWxsYXB1MTMwMQYDVQQKDCpzZXJ2aWNlLWFjY291bnQtaW8tc3Ry",
    "YXRvbWVyY2F0YS1kc25hbGxhcHUwVjAQBgcqhkjOPQIBBgUrgQQACgNCAAQDZaje",
    "DGSvsqjF4OpJBl268CJRECe5+wVIbc+VfXzQtlVvSSwY/gIJvfVEs7mXEdmBg1Du",
   "uTAyKrzyGjLAfyxdMAwGCCqGSM49BAMCBQADRwAwRAIgJVS/t2DG5NFU4oJzlUjy",
    "X+LUTXMf2phGCIXCgkGYMcMCIBz1IfEDy41X8CDfSkSsuKgod2Fhe2F6JWxnJfhl",
    "zm2+",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]

dustinNodeCert :: [String]
dustinNodeCert =
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBgDCCASSgAwIBAgIRAKr5Ov1ZzUja9sqeTIhVMEswDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDMyODE5MzUzM1oXDTI1MDMy",
    "ODE5MzUzM1owOjEUMBIGA1UEAwwLZHVzdGluLW5vZGUxCTAHBgNVBAoMADEJMAcG",
    "A1UECwwAMQwwCgYDVQQGDANVU0EwVjAQBgcqhkjOPQIBBgUrgQQACgNCAARM/sOa",
    "isJiPam6gObGJFq8UDt06FYWO2+edBkSVdUcwDrGD4un0ggVOTvqq5xH8WtGDpv6",
    "BtQA/FEwW2Ky0/qeMAwGCCqGSM49BAMCBQADSAAwRQIhANHQM2M9cPMdJHk+UD4F",
    "wZU7wbB65cD3Q+vFfbSYPGyoAiA7mMg7DZrAhAvG9Pg0A2O/9rd4jHh75UuFViQ1",
    "GTfIrQ==",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]

kierensNodeCert :: [String]
kierensNodeCert =
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBszCCAVigAwIBAgIRAIiTYIFFIZ0qzuOHa+hdynkwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDMyODIxMDQ1MFoXDTI1MDMy",
    "ODIxMDQ1MFowbjE1MDMGA1UEAwwsc2VydmljZS1hY2NvdW50LWlvLXN0cmF0b21l",
    "cmNhdGEta2llcmVuc25vZGUxNTAzBgNVBAoMLHNlcnZpY2UtYWNjb3VudC1pby1z",
    "dHJhdG9tZXJjYXRhLWtpZXJlbnNub2RlMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE",
    "O32NpbDBs7kJ63s48j09fRlyJo/8i6F8NWDLmBzBev3201ZaZB4yozfdh5+9jG5B",
    "SJduhBHMkcKekCb3Pbwb1TAMBggqhkjOPQQDAgUAA0cAMEQCIADA/DuU/Tb7GGuP",
    "5hZUrH6WGHLwpoXBceciFxQmJSddAiAgYJok4oZZhcI1dhO4yYzN3oR/gokzzWuh",
    "KllTbqWoDg==",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]

wongwayCert :: [String]
wongwayCert =
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBqzCCAU+gAwIBAgIQUsdBA4EOYfIqpA1iCg6NezAMBggqhkjOPQQDAgUAMEgx",
    "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu",
    "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjQwMzI4MjA0OTA1WhcNMjUwMzI4",
    "MjA0OTA1WjBmMTEwLwYDVQQDDChzZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRvbWVy",
    "Y2F0YS13b25nd2F5MTEwLwYDVQQKDChzZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRv",
    "bWVyY2F0YS13b25nd2F5MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE2R5VXfkLhJOp",
    "OHgztwLtHM/zYKWDDzigkW80zcI4/n5MtlPZLfCYGdSTlunQcqZlghvMfy50nT2k",
    "OZKkOZFbMjAMBggqhkjOPQQDAgUAA0gAMEUCIQDuo0BG+Xs85YIWek06e5+DsBoh",
    "P2LnSRuDEEJJ+Ap9+QIgTqHnpX7x3p8pBzJsT8IYvaRup+NV3JM474L6t1JF+Ug=",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]

tysonCert :: [String]
tysonCert =
  [
    "-----BEGIN CERTIFICATE-----",
    "MIIBqDCCAUygAwIBAgIRAIEKqwfuPLSejKxQBMx/yT8wDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTI0MDUxMDE2NTQyNFoXDTI1MDUx",
    "MDE2NTQyNFowYjEvMC0GA1UEAwwmc2VydmljZS1hY2NvdW50LWlvLXN0cmF0b21l",
    "cmNhdGEtdHlzb24xLzAtBgNVBAoMJnNlcnZpY2UtYWNjb3VudC1pby1zdHJhdG9t",
    "ZXJjYXRhLXR5c29uMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEVcWIhYZ/gFY5TZyf",
    "mX5ZiNbwkcc/LMEE2UfW3o8EegVSytf3wQpZ1WLrSou9FSMSI1z7mQmRxeitcZP0",
    "t5M3BjAMBggqhkjOPQQDAgUAA0gAMEUCIQCSJMPwnHu8fD+1JmCu4bny3dJCLy8X",
    "op1mB4ZUiYVNOQIgM7g1LhNPk1Mfcsi78n7IOA0iBXPSseq6zC+QxqpG9GI=",
    "-----END CERTIFICATE-----",
    "-----BEGIN CERTIFICATE-----",
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI",
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF",
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy",
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU",
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG",
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs",
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8",
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n",
    "N8txKc8G9R27ZYAUuz15zF0=",
    "-----END CERTIFICATE-----"
  ]



mysteryCert :: [String]
mysteryCert =
  [
    "-----BEGIN CERTIFICATE-----", 
    "MIIBrTCCAVGgAwIBAgIQK00bO64kT3bMDHA2YrsrKDAMBggqhkjOPQQDAgUAMEgx", 
    "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu", 
    "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjQwMzI4MjExNTMyWhcNMjUwMzI4", 
    "MjExNTMyWjBoMTIwMAYDVQQDDClzZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRvbWVy", 
    "Y2F0YS1jaGVzc2dtOTEyMDAGA1UECgwpc2VydmljZS1hY2NvdW50LWlvLXN0cmF0", 
    "b21lcmNhdGEtQ2hlc3NHTTkwVjAQBgcqhkjOPQIBBgUrgQQACgNCAASS4/DfUqtu", 
    "0/l5wtVb28jRgssTEfK7oPKw4v/G9v/TglowiPfI+B69hPRFpGV/2bDBATlDQD2L", 
    "kxb/3e0rRYVSMAwGCCqGSM49BAMCBQADSAAwRQIhANlnAAP0+8YN81CmESUGiXYJ", 
    "avKMI5gvVgv6/TbHTmZqAiBEkArjLA5rTJ8xB+/INC2jJeVtJEdxTlX4FYJ5LwY2", 
    "Pg==", 
    "-----END CERTIFICATE-----", 
    "-----BEGIN CERTIFICATE-----", 
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI", 
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF", 
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy", 
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU", 
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG", 
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs", 
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8", 
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n", 
    "N8txKc8G9R27ZYAUuz15zF0=", 
    "-----END CERTIFICATE-----"
  ]

{-
mysteryCert :: [String]
mysteryCert =
  [
    "-----BEGIN CERTIFICATE-----", 
    "MIIBrTCCAVGgAwIBAgIQaAF1HrTNFSIN2/7p1QOppjAMBggqhkjOPQQDAgUAMEgx", 
    "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu", 
    "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjQwMzI5MTcyMjQwWhcNMjUwMzI5", 
    "MTcyMjQwWjBoMTIwMAYDVQQDDClzZXJ2aWNlLWFjY291bnQtaW8tc3RyYXRvbWVy", 
    "Y2F0YS1DaGVzc0dNOTEyMDAGA1UECgwpc2VydmljZS1hY2NvdW50LWlvLXN0cmF0", 
    "b21lcmNhdGEtQ2hlc3NHTTkwVjAQBgcqhkjOPQIBBgUrgQQACgNCAASS4/DfUqtu", 
    "0/l5wtVb28jRgssTEfK7oPKw4v/G9v/TglowiPfI+B69hPRFpGV/2bDBATlDQD2L", 
    "kxb/3e0rRYVSMAwGCCqGSM49BAMCBQADSAAwRQIhAL3PLQYQ8zngen3pIeuCR4dT", 
    "YjuddndHZUyidAvq3490AiAJ/lOS2Jx+xhm9vd78E6WVIX+qKQTNVW5/Hlz36ArS", 
    "7A==", 
    "-----END CERTIFICATE-----", 
    "-----BEGIN CERTIFICATE-----", 
    "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI", 
    "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF", 
    "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy", 
    "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU", 
    "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG", 
    "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs", 
    "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8", 
    "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n", 
    "N8txKc8G9R27ZYAUuz15zF0=", 
    "-----END CERTIFICATE-----"
  ]
-}  



extraCertsHack :: [(Address, X509CertInfoState)]
extraCertsHack =
  map
    ((\val -> (userAddress val, val)) . x509CertToCertInfoState . getCert)
    [troubleCert, witmkCert, jpowellCert, aaaCert, dsnallapuCert, dustinNodeCert, kierensNodeCert, wongwayCert, tysonCert, mysteryCert]
