name: common-log

dependencies:
  - base
  - bytestring
  - fast-logger
  - format
  - global-lock
  - hflags
  - monad-logger
  - template-haskell
  - text
  - time

library:
  source-dirs: src

tests:
  common-log-test:
    main: LogSpec.hs
    source-dirs: test/
    dependencies:
      - common-log
      - hspec
