name: blockapps-init

dependencies:
  - base
  - cross-monitoring
  - text
  - unix

library:
  source-dirs: src

executables:
  test-reload:
    source-dirs: exec_src/
    main: TestReload.hs
    other-modules: []
    dependencies:
      - blockapps-init
