import "../../concrete/BaseCodeCollection.sol";
import "../../concrete/Pools/PoolV3Factory.sol";
import "../../abstract/ERC20/access/Authorizable.sol";

/*
 * PoolV3 test suite — canonical Uniswap V3 parity.
 *
 * Every pinned constant below is generated by tests/Pool/poolv3_reference.py, which
 * replicates canonical Uniswap V3 integer math (TickMath, SqrtPriceMath, SwapMath,
 * the tick-crossing swap loop) exactly. Values marked CANONICAL are therefore the
 * bit-for-bit outputs of UniswapV3Pool.sol for the same inputs.
 */

contract User {
    function do(address a, string f, variadic args) public returns (variadic) {
        variadic result = address(a).call(f, args);
        return result;
    }
}

contract Describe_PoolV3 is Authorizable {

    Mercata m;
    string[] emptyArray;

    PoolV3Factory factory;
    address token0Address;
    address token1Address;
    address poolAddress;
    PoolV3 pool;

    // CANONICAL: TickMath constants
    uint constant Q96 = 79228162514264337593543950336;
    uint constant Q128 = 340282366920938463463374607431768211456;
    uint constant MIN_SQRT_RATIO = 4295128739;
    uint constant MAX_SQRT_RATIO = 1461446703485210103287273052203988822378723970342;
    int constant MIN_TICK = -887272;
    int constant MAX_TICK = 887272;

    uint constant DEADLINE_OFFSET = 3600;
    uint constant BIG = 100000000e18;

    function beforeAll() {
        bypassAuthorizations = true;
        m = new Mercata();
        require(address(m) != address(0), "Mercata address is 0");
        emptyArray = new string[](0);
    }

    function beforeEach() {
        // Create fresh tokens for each test
        token0Address = m.tokenFactory().createToken(
            "Token 0", "Test Token 0", emptyArray, emptyArray, emptyArray, "TK0", 10000000e18, 18
        );
        token1Address = m.tokenFactory().createToken(
            "Token 1", "Test Token 1", emptyArray, emptyArray, emptyArray, "TK1", 10000000e18, 18
        );

        // Activate tokens
        Token(token0Address).setStatus(2); // ACTIVE
        Token(token1Address).setStatus(2); // ACTIVE

        // Mint tokens to test contract
        Token(token0Address).mint(address(this), BIG);
        Token(token1Address).mint(address(this), BIG);

        // Create standalone V3 factory owned by this test contract
        factory = new PoolV3Factory(address(this));
        factory.initialize(address(m.tokenFactory()), address(m.feeCollector()));

        // Create pool at the 0.30% tier (3000 pips) with initial price 1.0 (sqrtPriceX96 = 2^96, tick 0)
        poolAddress = factory.createPoolV3(token0Address, token1Address, 3000, Q96);
        pool = PoolV3(poolAddress);
    }

    // ============ HELPERS ============

    function _approveBoth(uint amount0, uint amount1) internal {
        require(ERC20(token0Address).approve(address(pool), amount0), "Token0 approval failed");
        require(ERC20(token1Address).approve(address(pool), amount1), "Token1 approval failed");
    }

    function _mintRange(int tickLower, int tickUpper, uint liquidityAmount) internal returns (uint, uint) {
        _approveBoth(BIG, BIG);
        return pool.mint(address(this), tickLower, tickUpper, liquidityAmount, BIG, BIG, block.timestamp + DEADLINE_OFFSET);
    }

    /// @dev Exact-input swap; returns the output amount received
    function _swap(bool zeroForOne, uint amountIn) internal returns (uint) {
        address tokenIn = zeroForOne ? token0Address : token1Address;
        require(ERC20(tokenIn).approve(address(pool), amountIn), "Swap approval failed");
        (int a0, int a1) = pool.swap(address(this), zeroForOne, int(amountIn), 0, 1, block.timestamp + DEADLINE_OFFSET);
        return uint(-(zeroForOne ? a1 : a0));
    }

    /// @dev Exact-output swap; returns the input amount paid
    function _swapExactOut(bool zeroForOne, uint amountOut, uint maxIn) internal returns (uint) {
        address tokenIn = zeroForOne ? token0Address : token1Address;
        require(ERC20(tokenIn).approve(address(pool), maxIn), "Swap approval failed");
        (int a0, int a1) = pool.swap(address(this), zeroForOne, -int(amountOut), 0, maxIn, block.timestamp + DEADLINE_OFFSET);
        return uint(zeroForOne ? a0 : a1);
    }

    /// @dev Create a user with token balances and pool approvals for both tokens
    function _newUser() internal returns (User) {
        User u = new User();
        Token(token0Address).mint(address(u), BIG);
        Token(token1Address).mint(address(u), BIG);
        u.do(token0Address, "approve", poolAddress, BIG);
        u.do(token1Address, "approve", poolAddress, BIG);
        return u;
    }

    function _userMint(User u, int tickLower, int tickUpper, uint liquidityAmount) internal {
        u.do(poolAddress, "mint", address(u), tickLower, tickUpper, liquidityAmount, BIG, BIG, block.timestamp + DEADLINE_OFFSET);
    }

    function _userPoke(User u, int tickLower, int tickUpper) internal {
        u.do(poolAddress, "burn", tickLower, tickUpper, 0, block.timestamp + DEADLINE_OFFSET);
    }

    function _cumulativeNow() internal returns (int) {
        (int tickCum, ) = pool.observeSingle(0);
        return tickCum;
    }

    // ============ FACTORY TESTS ============

    function it_factory_creates_pool_successfully() {
        require(address(pool) != address(0), "Pool should be created");
        require(pool.fee() == 3000, "Fee should be 3000 pips");
        require(pool.tickSpacing() == 60, "Tick spacing should be 60");
        require(pool.sqrtPriceX96() == Q96, "Initial sqrt price should be 2^96");
        require(pool.currentTick() == 0, "Initial tick should be 0");
        require(factory.pools(token0Address, token1Address, 3000) == poolAddress, "Registry 0->1 missing");
        require(factory.pools(token1Address, token0Address, 3000) == poolAddress, "Registry 1->0 missing");
    }

    function it_factory_rejects_duplicate_pool() {
        bool thrown = false;
        try {
            factory.createPoolV3(token0Address, token1Address, 3000, Q96);
        } catch {
            thrown = true;
        }
        require(thrown, "Duplicate pool should revert");
    }

    function it_factory_rejects_unknown_fee_tier() {
        bool thrown = false;
        try {
            factory.createPoolV3(token0Address, token1Address, 777, Q96);
        } catch {
            thrown = true;
        }
        require(thrown, "Unknown fee tier should revert");
    }

    function it_factory_allows_same_pair_different_tier() {
        address pool2 = factory.createPoolV3(token0Address, token1Address, 10000, Q96);
        require(pool2 != address(0) && pool2 != poolAddress, "Second tier pool should be distinct");
        require(PoolV3(pool2).tickSpacing() == 200, "1% tier should use spacing 200");
    }

    function it_factory_rejects_identical_tokens() {
        bool thrown = false;
        try {
            factory.createPoolV3(token0Address, token0Address, 10000, Q96);
        } catch {
            thrown = true;
        }
        require(thrown, "Identical tokens should revert");
    }

    function it_factory_rejects_zero_initial_price() {
        bool thrown = false;
        try {
            factory.createPoolV3(token0Address, token1Address, 10000, 0);
        } catch {
            thrown = true;
        }
        require(thrown, "Zero initial price should revert");
    }

    function it_factory_rejects_inactive_token() {
        Token(token0Address).setStatus(1); // not ACTIVE
        bool thrown = false;
        try {
            factory.createPoolV3(token0Address, token1Address, 10000, Q96);
        } catch {
            thrown = true;
        }
        require(thrown, "Inactive token should revert");
        Token(token0Address).setStatus(2); // restore
    }

    function it_factory_enable_new_fee_tier_and_create_pool() {
        factory.enableFeeTier(550, 11);
        address p550 = factory.createPoolV3(token0Address, token1Address, 550, Q96);
        require(p550 != address(0), "550-pip pool should be created");
        require(PoolV3(p550).fee() == 550, "Fee should be 550 pips");
        require(PoolV3(p550).tickSpacing() == 11, "Tick spacing should be 11");
    }

    function it_factory_fee_tier_validation() {
        bool thrown = false;
        try {
            factory.enableFeeTier(3000, 60); // already exists
        } catch {
            thrown = true;
        }
        require(thrown, "Duplicate fee tier should revert");

        thrown = false;
        try {
            factory.enableFeeTier(0, 60);
        } catch {
            thrown = true;
        }
        require(thrown, "Zero fee should revert");

        thrown = false;
        try {
            factory.enableFeeTier(1000000, 60); // fee must be < 1e6 (canonical bound)
        } catch {
            thrown = true;
        }
        require(thrown, "Fee of 100% should revert");

        thrown = false;
        try {
            factory.enableFeeTier(40, 0);
        } catch {
            thrown = true;
        }
        require(thrown, "Zero tick spacing should revert");

        thrown = false;
        try {
            factory.enableFeeTier(40, 16384); // canonical bound: tickSpacing < 16384
        } catch {
            thrown = true;
        }
        require(thrown, "Tick spacing of 16384 should revert");

        factory.enableFeeTier(40, 16383);
        require(factory.feeTiers(40) == 16383, "Max valid spacing should be accepted");
    }

    function it_factory_non_owner_cannot_admin() {
        User stranger = new User();
        bool thrown = false;
        try {
            stranger.do(address(factory), "createPoolV3", token0Address, token1Address, 10000, Q96);
        } catch {
            thrown = true;
        }
        require(thrown, "Non-owner createPoolV3 should revert");

        thrown = false;
        try {
            stranger.do(address(factory), "enableFeeTier", 40, 60);
        } catch {
            thrown = true;
        }
        require(thrown, "Non-owner enableFeeTier should revert");

        thrown = false;
        try {
            stranger.do(address(factory), "setLpSharePercent", 5000);
        } catch {
            thrown = true;
        }
        require(thrown, "Non-owner setLpSharePercent should revert");
    }

    function it_factory_lp_share_bounds_and_pool_override() {
        bool thrown = false;
        try {
            factory.setLpSharePercent(0);
        } catch {
            thrown = true;
        }
        require(thrown, "Factory LP share 0 should revert");

        thrown = false;
        try {
            factory.setLpSharePercent(10001);
        } catch {
            thrown = true;
        }
        require(thrown, "Factory LP share > 100% should revert");

        // Pool-specific override, then reset to factory default
        factory.setPoolLpSharePercent(poolAddress, 5000);
        require(pool.lpSharePercent() == 5000, "Pool LP share override failed");
        factory.setPoolLpSharePercent(poolAddress, 0);
        require(pool.lpSharePercent() == 0, "Pool LP share reset failed");

        thrown = false;
        try {
            factory.setPoolLpSharePercent(poolAddress, 10001);
        } catch {
            thrown = true;
        }
        require(thrown, "Pool LP share > 100% should revert");
    }

    function it_factory_initialize_only_once() {
        bool thrown = false;
        try {
            factory.initialize(address(m.tokenFactory()), address(m.feeCollector()));
        } catch {
            thrown = true;
        }
        require(thrown, "Re-initialize should revert");
        require(factory.lpSharePercent() == 7000, "Factory state must be unchanged");
    }

    function it_factory_create_requires_initialization() {
        // setTokenFactory + enableFeeTier alone must not be enough to mint pools:
        // an uninitialized factory has feeCollector == 0 and every swap would revert
        PoolV3Factory bare = new PoolV3Factory(address(this));
        bare.setTokenFactory(address(m.tokenFactory()));
        bare.enableFeeTier(40, 60);

        bool thrown = false;
        try {
            bare.createPoolV3(token0Address, token1Address, 40, Q96);
        } catch {
            thrown = true;
        }
        require(thrown, "Uninitialized factory must not create pools");

        bare.initialize(address(m.tokenFactory()), address(m.feeCollector()));
        address p = bare.createPoolV3(token0Address, token1Address, 40, Q96);
        require(p != address(0), "Initialized factory should create pools");
    }

    // ============ TICK MATH TESTS (canonical TickMath parity) ============

    function it_tick_math_exact_values() {
        // CANONICAL: sqrt(1.0001^0) == 2^96 exactly
        require(pool.getSqrtRatioAtTick(0) == Q96, "Tick 0 should be 2^96");
        // CANONICAL neighbors of tick 0
        require(pool.getSqrtRatioAtTick(1) == 79232123823359799118286999568, "tick 1 mismatch");
        require(pool.getSqrtRatioAtTick(-1) == 79224201403219477170569942574, "tick -1 mismatch");
        // Reciprocal symmetry: p(t) * p(-t) ~ 2^192
        uint p = pool.getSqrtRatioAtTick(100);
        uint n = pool.getSqrtRatioAtTick(-100);
        uint product = (p * n) / Q96;
        require(product >= Q96 - 2 && product <= Q96 + 2, "p(t) * p(-t) should be ~2^192");
    }

    function it_tick_math_matches_uniswap_reference() {
        // CANONICAL: bit-for-bit TickMath.getSqrtRatioAtTick outputs (poolv3_reference.py,
        // constants validated to <1 ULP against a 120-digit reference)
        require(pool.getSqrtRatioAtTick(60) == 79466191966197645195421774833, "tick 60 mismatch");
        require(pool.getSqrtRatioAtTick(-60) == 78990846045029531151608375686, "tick -60 mismatch");
        require(pool.getSqrtRatioAtTick(100) == 79625275426524748796330556128, "tick 100 mismatch");
        require(pool.getSqrtRatioAtTick(-100) == 78833030112140176575862854579, "tick -100 mismatch");
        require(pool.getSqrtRatioAtTick(1000) == 83290069058676223003182343270, "tick 1000 mismatch");
        require(pool.getSqrtRatioAtTick(10000) == 130621891405341611593710811006, "tick 10000 mismatch");
        require(pool.getSqrtRatioAtTick(-10000) == 48055510970269007215549348797, "tick -10000 mismatch");
        require(pool.getSqrtRatioAtTick(887271) == 1461373636630004318706518188784493106690254656249, "tick 887271 mismatch");
        require(pool.getSqrtRatioAtTick(-887271) == 4295343490, "tick -887271 mismatch");
    }

    function it_tick_math_bounds() {
        // CANONICAL: MIN_SQRT_RATIO / MAX_SQRT_RATIO are TickMath's published constants
        require(pool.getSqrtRatioAtTick(MIN_TICK) == MIN_SQRT_RATIO, "MIN_TICK sqrt ratio wrong");
        require(pool.getSqrtRatioAtTick(MAX_TICK) == MAX_SQRT_RATIO, "MAX_TICK sqrt ratio wrong");

        bool thrown = false;
        try {
            pool.getSqrtRatioAtTick(-887273);
        } catch {
            thrown = true;
        }
        require(thrown, "Below MIN_TICK should revert (T)");

        thrown = false;
        try {
            pool.getSqrtRatioAtTick(887273);
        } catch {
            thrown = true;
        }
        require(thrown, "Above MAX_TICK should revert (T)");

        thrown = false;
        try {
            pool.getTickAtSqrtRatio(MIN_SQRT_RATIO - 1);
        } catch {
            thrown = true;
        }
        require(thrown, "Ratio below MIN should revert (R)");

        // Canonical domain is [MIN_SQRT_RATIO, MAX_SQRT_RATIO): the max ratio itself is excluded
        thrown = false;
        try {
            pool.getTickAtSqrtRatio(MAX_SQRT_RATIO);
        } catch {
            thrown = true;
        }
        require(thrown, "Ratio at MAX should revert (R)");
        require(pool.getTickAtSqrtRatio(MAX_SQRT_RATIO - 1) == 887271, "Just below MAX should be tick 887271");
        require(pool.getTickAtSqrtRatio(MIN_SQRT_RATIO) == MIN_TICK, "MIN ratio should be MIN_TICK");
    }

    function it_tick_at_sqrt_ratio_boundary_exact() {
        uint s60 = pool.getSqrtRatioAtTick(60);
        require(pool.getTickAtSqrtRatio(s60) == 60, "Exact boundary should map to its tick");
        require(pool.getTickAtSqrtRatio(s60 - 1) == 59, "1 wei below boundary should map to tick-1");
        require(pool.getTickAtSqrtRatio(s60 + 1) == 60, "1 wei above boundary should stay at tick");
    }

    function property_tick_sqrt_ratio_roundtrip(uint seed) {
        // getTickAtSqrtRatio's domain excludes MAX_SQRT_RATIO, so the roundtrip
        // property holds on [-887272, 887271]
        int tick = int(seed % 1774544) - 887272;
        uint sq = pool.getSqrtRatioAtTick(tick);
        int back = pool.getTickAtSqrtRatio(sq);
        require(back == tick, "Roundtrip failed for tick " + string(tick) + " got " + string(back));
    }

    function property_tick_math_monotonic(uint seed) {
        int tick = int(seed % 1774544) - 887272; // [-887272, 887271]
        require(pool.getSqrtRatioAtTick(tick) < pool.getSqrtRatioAtTick(tick + 1),
            "sqrt ratio not strictly increasing at tick " + string(tick));
    }

    // ============ AMOUNT MATH TESTS ============

    function it_amounts_match_closed_form_reference() {
        // CANONICAL: L=1000e18 over [-600,600) at price 1.0 needs identical amounts of
        // both tokens (symmetric range), rounded up
        (uint amount0, uint amount1) = pool.getAmountsForLiquidity(-600, 600, 1000e18);
        require(amount0 == 29553010879137169681, "amount0 mismatch: " + string(amount0));
        require(amount1 == 29553010879137169681, "amount1 mismatch: " + string(amount1));
    }

    function it_amounts_at_range_boundaries_single_sided() {
        // Price exactly at lower bound: position is in range but needs only token0
        (uint amount0, uint amount1) = pool.getAmountsForLiquidity(0, 60, 100000e18);
        require(amount0 > 0, "Lower boundary should need token0");
        require(amount1 == 0, "Lower boundary should need no token1");

        // Price exactly at upper bound: position is out of range (upper-exclusive), all token1
        (uint amount0b, uint amount1b) = pool.getAmountsForLiquidity(-60, 0, 100000e18);
        require(amount0b == 0, "Upper boundary should need no token0");
        require(amount1b > 0, "Upper boundary should need token1");

        // Liquidity activation matches: [0,60) is active at tick 0, [-60,0) is not
        _mintRange(0, 60, 100000e18);
        require(pool.liquidity() == 100000e18, "[0,60) should be active at tick 0");
        _mintRange(-60, 0, 100000e18);
        require(pool.liquidity() == 100000e18, "[-60,0) should not be active at tick 0");
    }

    function it_mint_dust_liquidity_rounds_up_against_user() {
        // 1 wei of liquidity: both amounts round up to 1 wei (pool never undercharges)
        (uint amount0, uint amount1) = _mintRange(-60, 60, 1);
        require(amount0 == 1, "Dust amount0 should round up to 1");
        require(amount1 == 1, "Dust amount1 should round up to 1");
    }

    // ============ MINT TESTS ============

    function it_mint_in_range_takes_both_tokens() {
        (uint amount0, uint amount1) = _mintRange(-600, 600, 1000e18);
        require(amount0 == 29553010879137169681, "amount0 mismatch: " + string(amount0));
        require(amount1 == 29553010879137169681, "amount1 mismatch: " + string(amount1));
        require(pool.liquidity() == 1000e18, "Pool liquidity should be active");
        require(pool.token0Balance() == amount0, "token0Balance mismatch");
        require(pool.token1Balance() == amount1, "token1Balance mismatch");
    }

    function it_mint_above_range_takes_only_token0() {
        (uint amount0, uint amount1) = _mintRange(600, 1200, 1000e18);
        require(amount0 > 0, "Should need token0");
        require(amount1 == 0, "Should not need token1");
        require(pool.liquidity() == 0, "Out-of-range liquidity should not be active");
    }

    function it_mint_below_range_takes_only_token1() {
        (uint amount0, uint amount1) = _mintRange(-1200, -600, 1000e18);
        require(amount0 == 0, "Should not need token0");
        require(amount1 > 0, "Should need token1");
        require(pool.liquidity() == 0, "Out-of-range liquidity should not be active");
    }

    function it_mint_rejects_bad_ticks() {
        _approveBoth(1000e18, 1000e18);
        bool thrown = false;
        try {
            // 61 is not a multiple of tickSpacing 60
            pool.mint(address(this), -61, 61, 1000e18, 1000e18, 1000e18, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "Off-spacing ticks should revert");

        thrown = false;
        try {
            pool.mint(address(this), 600, 600, 1000e18, 1000e18, 1000e18, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "Empty range should revert (TLU)");
    }

    function it_mint_rejects_out_of_bounds_ticks() {
        _approveBoth(1000e18, 1000e18);
        bool thrown = false;
        try {
            // -887280 is a multiple of 60 but below MIN_TICK
            pool.mint(address(this), -887280, 600, 1000e18, 1000e18, 1000e18, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "tickLower below MIN_TICK should revert (TLM)");

        thrown = false;
        try {
            pool.mint(address(this), -600, 887280, 1000e18, 1000e18, 1000e18, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "tickUpper above MAX_TICK should revert (TUM)");
    }

    function it_mint_rejects_zero_liquidity() {
        _approveBoth(1000e18, 1000e18);
        bool thrown = false;
        try {
            pool.mint(address(this), -600, 600, 0, 1000e18, 1000e18, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "Zero liquidity mint should revert");
    }

    function it_mint_rejects_expired_deadline() {
        _approveBoth(1000e18, 1000e18);
        fastForward(100);
        bool thrown = false;
        try {
            pool.mint(address(this), -600, 600, 1000e18, 1000e18, 1000e18, block.timestamp - 1);
        } catch {
            thrown = true;
        }
        require(thrown, "Expired mint deadline should revert");
    }

    function it_mint_slippage_protection() {
        _approveBoth(BIG, BIG);
        bool thrown = false;
        try {
            // Needs ~29.5e18 of each; cap token0 at 1e18
            pool.mint(address(this), -600, 600, 1000e18, 1e18, 1000e18, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "Mint over amount0Max should revert");

        thrown = false;
        try {
            pool.mint(address(this), -600, 600, 1000e18, 1000e18, 1e18, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "Mint over amount1Max should revert");
    }

    function it_mint_twice_same_range_accumulates() {
        (uint first0, uint first1) = _mintRange(-600, 600, 1000e18);
        (uint second0, uint second1) = _mintRange(-600, 600, 1000e18);

        require(second0 >= first0 - 1 && second0 <= first0 + 1, "Second mint amount0 mismatch");
        require(second1 >= first1 - 1 && second1 <= first1 + 1, "Second mint amount1 mismatch");

        (uint posLiquidity, , ) = pool.getPosition(address(this), -600, 600);
        require(posLiquidity == 2000e18, "Position should accumulate to 2000e18");
        require(pool.liquidity() == 2000e18, "Pool liquidity should accumulate");
    }

    function it_mint_to_recipient_credits_recipient_position() {
        // V3 semantics: msg.sender pays, `recipient` owns the position
        User owner_ = new User();
        _approveBoth(BIG, BIG);
        pool.mint(address(owner_), -600, 600, 1000e18, BIG, BIG, block.timestamp + DEADLINE_OFFSET);

        (uint mintedToRecipient, , ) = pool.getPosition(address(owner_), -600, 600);
        (uint mintedToSender, , ) = pool.getPosition(address(this), -600, 600);
        require(mintedToRecipient == 1000e18, "Recipient should own the position");
        require(mintedToSender == 0, "Sender should own nothing");

        // Only the recipient can burn it
        uint balBefore = ERC20(token1Address).balanceOf(address(owner_));
        owner_.do(poolAddress, "burn", int(-600), int(600), 1000e18, block.timestamp + DEADLINE_OFFSET);
        owner_.do(poolAddress, "collect", address(owner_), int(-600), int(600), BIG, BIG);
        require(ERC20(token1Address).balanceOf(address(owner_)) > balBefore, "Recipient should collect the principal");
    }

    function it_mint_multiple_users_positions_independent() {
        User u1 = _newUser();
        User u2 = _newUser();
        _userMint(u1, -600, 600, 30000e18);
        _userMint(u2, -600, 600, 70000e18);

        (uint liq1, , ) = pool.getPosition(address(u1), -600, 600);
        (uint liq2, , ) = pool.getPosition(address(u2), -600, 600);
        require(liq1 == 30000e18, "User1 position liquidity wrong");
        require(liq2 == 70000e18, "User2 position liquidity wrong");
        require(pool.liquidity() == 100000e18, "Pool should sum both positions");

        // u1's burn must not touch u2's position
        u1.do(poolAddress, "burn", int(-600), int(600), 30000e18, block.timestamp + DEADLINE_OFFSET);
        (uint liq1After, , ) = pool.getPosition(address(u1), -600, 600);
        (uint liq2After, , ) = pool.getPosition(address(u2), -600, 600);
        require(liq1After == 0, "User1 position should be empty");
        require(liq2After == 70000e18, "User2 position should be untouched");
        require(pool.liquidity() == 70000e18, "Pool liquidity should reflect burn");
    }

    function it_max_liquidity_per_tick_enforced() {
        // CANONICAL: Tick.tickSpacingToMaxLiquidityPerTick(60)
        require(pool.maxLiquidityPerTick() == 11505743598341114571880798222544994,
            "maxLiquidityPerTick mismatch: " + string(pool.maxLiquidityPerTick()));

        _approveBoth(BIG, BIG);
        bool thrown = false;
        try {
            pool.mint(address(this), -60, 60, 11505743598341114571880798222544995, BIG, BIG, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "Exceeding maxLiquidityPerTick should revert (LO)");
    }

    // ============ SWAP TESTS ============

    function it_swap_output_matches_uniswap_v3_exactly() {
        // CANONICAL: price 1.0, L = 100000e18, fee 3000 pips, 10e18 token0 exact-in.
        // UniswapV3Pool.sol returns amount1 = -9969006090092817746 for these inputs.
        _mintRange(-6000, 6000, 100000e18);
        uint bal0Before = ERC20(token0Address).balanceOf(address(this));
        uint bal1Before = ERC20(token1Address).balanceOf(address(this));

        require(ERC20(token0Address).approve(address(pool), 10e18), "Approval failed");
        (int a0, int a1) = pool.swap(address(this), true, int(10e18), 0, 1, block.timestamp + DEADLINE_OFFSET);

        require(a0 == int(10e18), "amount0 delta should be +10e18");
        require(a1 == -9969006090092817746, "amount1 delta mismatch: " + string(a1));
        require(bal0Before - ERC20(token0Address).balanceOf(address(this)) == 10e18, "Full input should be pulled");
        require(ERC20(token1Address).balanceOf(address(this)) == bal1Before + 9969006090092817746, "Output not received");

        // CANONICAL post-swap state
        require(pool.sqrtPriceX96() == 79220264253918221946815852796, "Post-swap sqrt price mismatch: " + string(pool.sqrtPriceX96()));
        require(pool.currentTick() == -2, "Post-swap tick should be -2, got " + string(pool.currentTick()));
    }

    function it_swap_both_directions() {
        _mintRange(-6000, 6000, 100000e18);

        uint out1 = _swap(true, 10e18);
        require(out1 > 0, "0->1 swap failed");

        uint out2 = _swap(false, 5e18);
        require(out2 > 0, "1->0 swap failed");
        require(pool.sqrtPriceX96() < Q96, "Price should still be below start after partial reversal");
    }

    function it_swap_output_goes_to_recipient() {
        _mintRange(-6000, 6000, 100000e18);
        User receiver = new User();

        require(ERC20(token0Address).approve(address(pool), 10e18), "Approval failed");
        pool.swap(address(receiver), true, int(10e18), 0, 1, block.timestamp + DEADLINE_OFFSET);
        require(ERC20(token1Address).balanceOf(address(receiver)) == 9969006090092817746,
            "Recipient should receive the canonical output");
    }

    function it_swap_sends_protocol_fee_to_collector() {
        _mintRange(-6000, 6000, 100000e18);

        address collector = factory.feeCollector();
        uint collectorBefore = ERC20(token0Address).balanceOf(collector);

        _swap(true, 100e18);

        // CANONICAL fee split: total fee 0.3% of 100e18; protocol share 30% = 0.09e18 exactly
        uint protocolFee = ERC20(token0Address).balanceOf(collector) - collectorBefore;
        require(protocolFee == 90000000000000000, "Protocol fee mismatch: " + string(protocolFee));
    }

    function it_swap_crosses_tick_and_drops_liquidity() {
        // Wide backstop position + narrow position around current price
        _mintRange(-6000, 6000, 50000e18);
        _mintRange(-60, 60, 50000e18);
        require(pool.liquidity() == 100000e18, "Both positions should be active");

        uint amountOut = _swap(true, 500e18);
        require(amountOut > 0, "Cross-tick swap failed");
        require(pool.currentTick() < -60, "Price should have crossed below -60");
        require(pool.liquidity() == 50000e18, "Only the wide position should remain active");
    }

    function it_swap_respects_price_limit() {
        _mintRange(-6000, 6000, 100000e18);

        uint limit = pool.getSqrtRatioAtTick(-10);
        uint bal0Before = ERC20(token0Address).balanceOf(address(this));
        require(ERC20(token0Address).approve(address(pool), 10000e18), "Approval failed");
        (int a0, ) = pool.swap(address(this), true, int(10000e18), limit, 1, block.timestamp + DEADLINE_OFFSET);

        require(pool.sqrtPriceX96() == limit, "Price should stop at the limit");
        uint consumed = bal0Before - ERC20(token0Address).balanceOf(address(this));
        require(consumed < 10000e18, "Should not consume full input when limit hit");
        // Partial fills must be visible to on-chain callers via the signed deltas
        require(a0 == int(consumed), "Returned amount0 must match actual transfer");
    }

    function it_swap_reverts_when_no_liquidity() {
        require(ERC20(token0Address).approve(address(pool), 10e18), "Approval failed");
        bool thrown = false;
        try {
            pool.swap(address(this), true, int(10e18), 0, 1, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "Swap with no liquidity should revert");
    }

    function it_swap_slippage_check() {
        _mintRange(-6000, 6000, 100000e18);
        require(ERC20(token0Address).approve(address(pool), 10e18), "Approval failed");
        bool thrown = false;
        try {
            pool.swap(address(this), true, int(10e18), 0, 100e18, block.timestamp + DEADLINE_OFFSET); // impossible min out
        } catch {
            thrown = true;
        }
        require(thrown, "Slippage check should revert");
    }

    function it_swap_rejects_zero_inputs() {
        _mintRange(-6000, 6000, 100000e18);
        require(ERC20(token0Address).approve(address(pool), 10e18), "Approval failed");

        bool thrown = false;
        try {
            pool.swap(address(this), true, 0, 0, 1, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "Zero amountSpecified should revert (AS)");

        thrown = false;
        try {
            pool.swap(address(this), true, int(10e18), 0, 0, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "Zero amountLimit should revert");
    }

    function it_swap_dust_input_reverts_without_output() {
        _mintRange(-6000, 6000, 100000e18);
        require(ERC20(token0Address).approve(address(pool), 1), "Approval failed");
        bool thrown = false;
        try {
            // 1 wei in: fee rounding leaves zero output -> below amountLimit of 1
            pool.swap(address(this), true, 1, 0, 1, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "Dust swap with zero output should revert");
    }

    function it_expired_deadline_rejected() {
        _mintRange(-6000, 6000, 100000e18);
        fastForward(100);
        require(ERC20(token0Address).approve(address(pool), 10e18), "Approval failed");
        bool thrown = false;
        try {
            pool.swap(address(this), true, int(10e18), 0, 1, block.timestamp - 1);
        } catch {
            thrown = true;
        }
        require(thrown, "Expired deadline should revert");
    }

    function it_swap_roundtrip_never_profits_user() {
        // CANONICAL: two 0.30% fees + price impact
        _mintRange(-6000, 6000, 100000e18);
        uint bal0Before = ERC20(token0Address).balanceOf(address(this));

        uint outB = _swap(true, 10e18);
        require(outB == 9969006090092817746, "First leg output mismatch");
        uint backA = _swap(false, outB);
        require(backA == 9940092972785421452, "Return leg output mismatch: " + string(backA));

        require(backA < 10e18, "Round trip must never profit the user");
        require(ERC20(token0Address).balanceOf(address(this)) == bal0Before - 10e18 + backA, "Balance accounting wrong");
    }

    function it_swap_multi_tick_staircase_down() {
        // Three stacked ranges with increasing depth below the price
        _mintRange(-60, 60, 100000e18);
        _mintRange(-180, -60, 200000e18);
        _mintRange(-300, -180, 300000e18);
        require(pool.liquidity() == 100000e18, "Only [-60,60) should start active");

        address collector = factory.feeCollector();
        uint collectorBefore = ERC20(token0Address).balanceOf(collector);

        // CANONICAL: crossing -60 and -180, finishing at tick -213 in the deepest range
        uint amountOut = _swap(true, 2000e18);
        require(amountOut == 1969258559869827750472, "Staircase-down output mismatch: " + string(amountOut));
        require(pool.currentTick() == -213, "Final tick should be -213, got " + string(pool.currentTick()));
        require(pool.liquidity() == 300000e18, "Only the deepest range should be active");

        // Protocol fee: 30% of 0.3% of 2000e18 = 1.8e18 (per-step rounding may add wei dust)
        uint protocolFee = ERC20(token0Address).balanceOf(collector) - collectorBefore;
        require(protocolFee >= 18e17 - 5 && protocolFee <= 18e17 + 10, "Protocol fee wrong: " + string(protocolFee));
    }

    function it_swap_multi_tick_staircase_up() {
        _mintRange(-60, 60, 100000e18);
        _mintRange(60, 180, 200000e18);
        _mintRange(180, 300, 300000e18);
        require(pool.liquidity() == 100000e18, "Only [-60,60) should start active");

        // CANONICAL mirror of the down case
        uint amountOut = _swap(false, 2000e18);
        require(amountOut == 1969258559869827750472, "Staircase-up output mismatch: " + string(amountOut));
        require(pool.currentTick() == 212, "Final tick should be 212, got " + string(pool.currentTick()));
        require(pool.liquidity() == 300000e18, "Only the top range should be active");
    }

    function it_swap_across_liquidity_gap() {
        // Liquidity at [-60,60) and [-360,-240) with an empty gap between
        _mintRange(-60, 60, 100000e18);
        _mintRange(-360, -240, 100000e18);

        // CANONICAL: drains [-60,60), jumps the gap without trading, lands at tick -280
        uint amountOut = _swap(true, 500e18);
        require(amountOut == 492525674171347212827, "Gap swap output mismatch: " + string(amountOut));
        require(pool.currentTick() == -280, "Final tick should be -280, got " + string(pool.currentTick()));
        require(pool.liquidity() == 100000e18, "Far range should be the only active liquidity");
    }

    function it_swap_partial_fill_when_liquidity_exhausted() {
        // One narrow range; a huge order can only consume what the range holds
        (, uint deposited1) = _mintRange(-60, 60, 100000e18);
        require(deposited1 == 299535495591078093768, "Deposit reference mismatch");

        uint bal0Before = ERC20(token0Address).balanceOf(address(this));
        uint amountOut = _swap(true, 1000e18);
        uint consumed = bal0Before - ERC20(token0Address).balanceOf(address(this));

        // CANONICAL partial fill values
        require(consumed == 301339424547836073619, "Consumed mismatch: " + string(consumed));
        require(amountOut == 299535495591078093767, "Output mismatch: " + string(amountOut));
        require(pool.liquidity() == 0, "No liquidity should remain active");
        // Price rides to one wei above the canonical minimum and stays representable
        require(pool.sqrtPriceX96() == MIN_SQRT_RATIO + 1, "Price must stop 1 wei above MIN_SQRT_RATIO");
        require(pool.currentTick() == MIN_TICK, "currentTick must stay at MIN_TICK");
    }

    function it_swap_invalid_price_limits_revert() {
        _mintRange(-6000, 6000, 100000e18);
        require(ERC20(token0Address).approve(address(pool), 10e18), "Approval failed");
        require(ERC20(token1Address).approve(address(pool), 10e18), "Approval failed");

        bool thrown = false;
        try {
            // 0->1 moves price down; limit above current price is invalid
            pool.swap(address(this), true, int(10e18), pool.getSqrtRatioAtTick(100), 1, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "0->1 limit above price should revert (SPL)");

        thrown = false;
        try {
            pool.swap(address(this), true, int(10e18), pool.sqrtPriceX96(), 1, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "Limit equal to price should revert (SPL)");

        thrown = false;
        try {
            pool.swap(address(this), false, int(10e18), pool.getSqrtRatioAtTick(-100), 1, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "1->0 limit below price should revert (SPL)");

        thrown = false;
        try {
            // Canonical strict bound: MIN_SQRT_RATIO itself is invalid
            pool.swap(address(this), true, int(10e18), MIN_SQRT_RATIO, 1, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "Limit at MIN_SQRT_RATIO should revert (SPL)");

        thrown = false;
        try {
            pool.swap(address(this), false, int(10e18), MAX_SQRT_RATIO, 1, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "Limit at MAX_SQRT_RATIO should revert (SPL)");
    }

    function it_swap_stop_exactly_on_initialized_tick_boundary() {
        // When a swap stops exactly at a price limit that coincides with an initialized
        // tick, the tick must be crossed (canonical V3 semantics), otherwise currentTick
        // and active liquidity disagree
        _mintRange(0, 60, 100000e18);   // active at tick 0
        _mintRange(60, 120, 50000e18);  // above range

        uint limit = pool.getSqrtRatioAtTick(60);
        require(ERC20(token1Address).approve(address(pool), 1000e18), "Approval failed");
        pool.swap(address(this), false, int(1000e18), limit, 1, block.timestamp + DEADLINE_OFFSET);

        require(pool.sqrtPriceX96() == limit, "Price should stop exactly at the limit");
        require(pool.currentTick() == 60, "Tick should be 60, got " + string(pool.currentTick()));
        // Tick 60 must have been crossed: [0,60) leaves range, [60,120) enters
        require(pool.liquidity() == 50000e18,
            "Tick 60 not crossed: phantom liquidity " + string(pool.liquidity()));

        // Swapping back down must cross tick 60 again and re-activate [0,60)
        _swap(true, 1e18);
        require(pool.currentTick() < 60, "Price should be back below tick 60");
        require(pool.liquidity() == 100000e18,
            "Cross-back should restore [0,60) liquidity, got " + string(pool.liquidity()));
    }

    // ============ EXACT-OUTPUT SWAP TESTS (canonical amountSpecified < 0) ============

    function it_swap_exact_output_within_range() {
        _mintRange(-6000, 6000, 100000e18);
        uint bal1Before = ERC20(token1Address).balanceOf(address(this));

        // CANONICAL: exactly 5e18 token1 out costs 5015295900201228719 token0 (incl. fee)
        uint paid = _swapExactOut(true, 5e18, 100e18);
        require(paid == 5015295900201228719, "Exact-out input mismatch: " + string(paid));
        require(ERC20(token1Address).balanceOf(address(this)) == bal1Before + 5e18, "Should receive exactly 5e18");
        require(pool.sqrtPriceX96() == 79224201106138624376664273138, "Post-swap sqrt price mismatch");
        require(pool.currentTick() == -2, "Post-swap tick should be -2");
    }

    function it_swap_exact_output_larger_request() {
        _mintRange(-60, 60, 100000e18);
        _mintRange(-180, -60, 200000e18);
        uint bal1Before = ERC20(token1Address).balanceOf(address(this));

        // CANONICAL: 200e18 token1 out costs 201003813042333413066 token0
        uint paid = _swapExactOut(true, 200e18, 500e18);
        require(paid == 201003813042333413066, "Exact-out input mismatch: " + string(paid));
        require(ERC20(token1Address).balanceOf(address(this)) == bal1Before + 200e18, "Should receive exactly 200e18");
        require(pool.currentTick() == -41, "Post-swap tick should be -41, got " + string(pool.currentTick()));
    }

    function it_swap_exact_output_max_input_slippage() {
        _mintRange(-6000, 6000, 100000e18);
        require(ERC20(token0Address).approve(address(pool), 100e18), "Approval failed");
        bool thrown = false;
        try {
            // Needs ~5.015e18 in; cap the input below that
            pool.swap(address(this), true, -int(5e18), 0, 5e18, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "Exact-out over max input should revert");
    }

    function it_swap_exact_output_roundtrip_conservation() {
        _mintRange(-6000, 6000, 100000e18);

        // Exact-in of the exact-out's input should give back at least the requested output
        uint paid = _swapExactOut(true, 5e18, 100e18);
        uint outFromSameInput = _swap(false, 5e18); // move price back roughly
        require(paid > 5e18, "Exact-out must cost more than the output at price ~1");
        require(outFromSameInput > 0, "Reverse swap should work");
    }

    // ============ FEE / POSITION TESTS ============

    function it_lp_fees_accrue_and_collect() {
        _mintRange(-6000, 6000, 100000e18);
        _swap(true, 100e18);

        // Poke (burn 0) to accrue fees to the position
        pool.burn(-6000, 6000, 0, block.timestamp + DEADLINE_OFFSET);
        (uint posLiquidity, uint owed0, uint owed1) = pool.getPosition(address(this), -6000, 6000);
        require(posLiquidity == 100000e18, "Position liquidity wrong");
        // CANONICAL (platform fee routing): LP share = 70% of 0.3% of 100e18, floored via
        // Q128 fee growth = 209999999999999999
        require(owed0 == 209999999999999999, "LP fee owed mismatch: " + string(owed0));
        require(owed1 == 0, "No token1 fees expected");

        uint bal0Before = ERC20(token0Address).balanceOf(address(this));
        (uint got0, uint got1) = pool.collect(address(this), -6000, 6000, 1000000e18, 1000000e18);
        require(got0 == owed0, "Collected amount mismatch");
        require(got1 == 0, "Unexpected token1 collected");
        require(ERC20(token0Address).balanceOf(address(this)) == bal0Before + got0, "Fees not received");
    }

    function it_out_of_range_position_earns_no_fees() {
        _mintRange(-6000, 6000, 100000e18);
        _mintRange(6000, 12000, 100000e18); // far above price, never in range

        _swap(true, 100e18);

        pool.burn(6000, 12000, 0, block.timestamp + DEADLINE_OFFSET);
        (, uint owed0, uint owed1) = pool.getPosition(address(this), 6000, 12000);
        require(owed0 == 0 && owed1 == 0, "Out-of-range position should earn nothing");
    }

    function it_burn_and_collect_full_exit() {
        (uint deposited0, uint deposited1) = _mintRange(-600, 600, 1000e18);

        pool.burn(-600, 600, 1000e18, block.timestamp + DEADLINE_OFFSET);
        (uint posLiquidity, uint owed0, uint owed1) = pool.getPosition(address(this), -600, 600);
        require(posLiquidity == 0, "Position should be empty");
        // Rounding favors the pool: owed <= deposited, within a couple wei
        require(owed0 <= deposited0 && deposited0 - owed0 <= 2, "Token0 principal mismatch");
        require(owed1 <= deposited1 && deposited1 - owed1 <= 2, "Token1 principal mismatch");
        require(pool.liquidity() == 0, "Pool liquidity should be zero");

        (uint got0, uint got1) = pool.collect(address(this), -600, 600, 1000000e18, 1000000e18);
        require(got0 == owed0 && got1 == owed1, "Collect should pay out full owed amounts");
    }

    function it_two_positions_share_fees_pro_rata() {
        _mintRange(-6000, 6000, 75000e18);
        _mintRange(-12000, 12000, 25000e18);
        require(pool.liquidity() == 100000e18, "Total liquidity wrong");

        _swap(true, 100e18);

        pool.burn(-6000, 6000, 0, block.timestamp + DEADLINE_OFFSET);
        pool.burn(-12000, 12000, 0, block.timestamp + DEADLINE_OFFSET);
        (, uint owedNarrow, ) = pool.getPosition(address(this), -6000, 6000);
        (, uint owedWide, ) = pool.getPosition(address(this), -12000, 12000);

        require(owedNarrow > 0 && owedWide > 0, "Both positions should earn");
        uint ratio = (owedNarrow * 100) / owedWide;
        require(ratio >= 297 && ratio <= 303, "Fee split not pro-rata: ratio*100 = " + string(ratio));
    }

    function it_same_range_two_users_split_fees_equally() {
        User u1 = _newUser();
        User u2 = _newUser();
        _userMint(u1, -6000, 6000, 50000e18);
        _userMint(u2, -6000, 6000, 50000e18);

        _swap(true, 100e18);

        _userPoke(u1, -6000, 6000);
        _userPoke(u2, -6000, 6000);
        (, uint owed1, ) = pool.getPosition(address(u1), -6000, 6000);
        (, uint owed2, ) = pool.getPosition(address(u2), -6000, 6000);

        require(owed1 == owed2, "Equal positions must earn equal fees");
        require(owed1 >= 105e15 - 2 && owed1 <= 105e15, "Per-user fee wrong: " + string(owed1));
    }

    function it_fees_stop_when_position_exits_range() {
        _mintRange(-60, 60, 100000e18);     // narrow
        _mintRange(-6000, 6000, 100000e18); // wide backstop

        // Swap 1: pushes price below -60, narrow range exits partway through
        _swap(true, 800e18);
        require(pool.currentTick() < -60, "Price should be below the narrow range");

        pool.burn(-60, 60, 0, block.timestamp + DEADLINE_OFFSET);
        (, uint narrowOwedAfterExit, ) = pool.getPosition(address(this), -60, 60);
        require(narrowOwedAfterExit > 0, "Narrow position should have earned during swap 1");

        pool.burn(-6000, 6000, 0, block.timestamp + DEADLINE_OFFSET);
        (, uint wideOwedAfterExit, ) = pool.getPosition(address(this), -6000, 6000);

        // Swap 2: entirely below the narrow range; only the wide position may earn
        _swap(true, 100e18);
        pool.burn(-60, 60, 0, block.timestamp + DEADLINE_OFFSET);
        pool.burn(-6000, 6000, 0, block.timestamp + DEADLINE_OFFSET);
        (, uint narrowOwedFinal, ) = pool.getPosition(address(this), -60, 60);
        (, uint wideOwedFinal, ) = pool.getPosition(address(this), -6000, 6000);

        require(narrowOwedFinal == narrowOwedAfterExit, "Out-of-range narrow position must not earn");
        require(wideOwedFinal > wideOwedAfterExit, "In-range wide position must keep earning");
    }

    function it_fees_accrue_in_both_tokens() {
        _mintRange(-6000, 6000, 100000e18);
        _swap(true, 100e18);
        _swap(false, 100e18);

        pool.burn(-6000, 6000, 0, block.timestamp + DEADLINE_OFFSET);
        (, uint owed0, uint owed1) = pool.getPosition(address(this), -6000, 6000);
        require(owed0 >= 21e16 - 2 && owed0 <= 21e16, "Token0 fee wrong: " + string(owed0));
        require(owed1 >= 21e16 - 2 && owed1 <= 21e16, "Token1 fee wrong: " + string(owed1));
    }

    function it_late_lp_earns_no_prior_fees() {
        User u1 = _newUser();
        User u2 = _newUser();
        _userMint(u1, -6000, 6000, 100000e18);

        _swap(true, 100e18); // fees only u1 was present for

        _userMint(u2, -6000, 6000, 100000e18);
        _userPoke(u2, -6000, 6000);
        (, uint owed2, ) = pool.getPosition(address(u2), -6000, 6000);
        require(owed2 == 0, "Late LP must not earn past fees: " + string(owed2));

        _swap(true, 100e18); // now both earn
        _userPoke(u1, -6000, 6000);
        _userPoke(u2, -6000, 6000);
        (, uint owed1After, ) = pool.getPosition(address(u1), -6000, 6000);
        (, uint owed2After, ) = pool.getPosition(address(u2), -6000, 6000);
        require(owed2After > 0, "Late LP should earn from the second swap");
        require(owed1After > owed2After * 2, "Early LP should have earned strictly more");
    }

    function it_multiple_small_swaps_accumulate_exact_fees() {
        _mintRange(-6000, 6000, 100000e18);

        for (uint i = 0; i < 5; i++) {
            _swap(true, 20e18);
        }

        pool.burn(-6000, 6000, 0, block.timestamp + DEADLINE_OFFSET);
        (, uint owed0, ) = pool.getPosition(address(this), -6000, 6000);
        // 5 swaps x 20e18 x 0.3% x 70%, floored per-swap via Q128 growth
        require(owed0 >= 21e16 - 5 && owed0 <= 21e16, "Accumulated fee wrong: " + string(owed0));
    }

    function it_swap_lp_share_10000_sends_no_protocol_fee() {
        factory.setPoolLpSharePercent(poolAddress, 10000);
        _mintRange(-6000, 6000, 100000e18);

        address collector = factory.feeCollector();
        uint collectorBefore = ERC20(token0Address).balanceOf(collector);
        _swap(true, 100e18);
        require(ERC20(token0Address).balanceOf(collector) == collectorBefore, "Collector should receive nothing");

        // The entire 0.3% fee accrues to the LP
        pool.burn(-6000, 6000, 0, block.timestamp + DEADLINE_OFFSET);
        (, uint owed0, ) = pool.getPosition(address(this), -6000, 6000);
        require(owed0 >= 3e17 - 2 && owed0 <= 3e17, "LP should earn the full fee: " + string(owed0));
    }

    function it_full_exit_after_prior_fee_history_earns_no_phantom_fees() {
        // Regression for V3 tick-clearing order: flipped ticks must be cleared only AFTER
        // the position's final fee accrual
        User lp1 = _newUser();
        User lp2 = _newUser();
        _userMint(lp1, -6000, 6000, 100000e18);
        _swap(true, 100e18); // fee history exists before lp2 arrives

        uint bal0Before = ERC20(token0Address).balanceOf(address(lp2));
        uint bal1Before = ERC20(token1Address).balanceOf(address(lp2));
        _userMint(lp2, -600, 600, 1000000e18);
        uint deposited0 = bal0Before - ERC20(token0Address).balanceOf(address(lp2));
        uint deposited1 = bal1Before - ERC20(token1Address).balanceOf(address(lp2));

        lp2.do(poolAddress, "burn", int(-600), int(600), 1000000e18, block.timestamp + DEADLINE_OFFSET);
        (, uint owed0, uint owed1) = pool.getPosition(address(lp2), -600, 600);

        require(owed0 <= deposited0 && deposited0 - owed0 <= 4,
            "Phantom token0 fees: deposited " + string(deposited0) + " owed " + string(owed0));
        require(owed1 <= deposited1 && deposited1 - owed1 <= 4,
            "Phantom token1 fees: deposited " + string(deposited1) + " owed " + string(owed1));

        // lp1's fees are intact and payable after lp2 leaves
        lp2.do(poolAddress, "collect", address(lp2), int(-600), int(600), BIG, BIG);
        _userPoke(lp1, -6000, 6000);
        (, uint lp1Owed0, ) = pool.getPosition(address(lp1), -6000, 6000);
        require(lp1Owed0 == 209999999999999999, "LP1 fee wrong: " + string(lp1Owed0));
        lp1.do(poolAddress, "collect", address(lp1), int(-6000), int(6000), BIG, BIG);
        require(ERC20(token0Address).balanceOf(address(pool)) == pool.token0Balance(), "Token0 sync broken");
        require(ERC20(token1Address).balanceOf(address(pool)) == pool.token1Balance(), "Token1 sync broken");
    }

    // ============ BURN / COLLECT TESTS ============

    function it_burn_rejects_more_than_position() {
        _mintRange(-600, 600, 1000e18);
        bool thrown = false;
        try {
            pool.burn(-600, 600, 1001e18, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "Burning more than position should revert");
    }

    function it_burn_from_stranger_reverts() {
        _mintRange(-600, 600, 1000e18);
        User stranger = new User();
        bool thrown = false;
        try {
            stranger.do(poolAddress, "burn", int(-600), int(600), 1000e18, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "Stranger burning someone else's position should revert");
    }

    function it_burn_partial_is_proportional() {
        (uint deposited0, uint deposited1) = _mintRange(-600, 600, 1000e18);
        (uint burned0, uint burned1) = pool.burn(-600, 600, 500e18, block.timestamp + DEADLINE_OFFSET);

        require(burned0 <= deposited0 / 2 && deposited0 / 2 - burned0 <= 2, "Partial burn amount0 not proportional");
        require(burned1 <= deposited1 / 2 && deposited1 / 2 - burned1 <= 2, "Partial burn amount1 not proportional");

        (uint posLiquidity, , ) = pool.getPosition(address(this), -600, 600);
        require(posLiquidity == 500e18, "Position should have half liquidity left");
        require(pool.liquidity() == 500e18, "Pool liquidity should be halved");
    }

    function it_burn_poke_empty_position_reverts() {
        // CANONICAL: poking (burn 0) a position with no liquidity reverts 'NP'
        bool thrown = false;
        try {
            pool.burn(-600, 600, 0, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "Poking an empty position should revert (NP)");
        (uint posLiquidity, uint owed0, uint owed1) = pool.getPosition(address(this), -600, 600);
        require(posLiquidity == 0 && owed0 == 0 && owed1 == 0, "Empty position should stay empty");
    }

    function it_burn_after_price_moves_into_range_returns_both_tokens() {
        // Mint above range: all token0
        (uint deposited0, uint deposited1) = _mintRange(60, 120, 100000e18);
        require(deposited1 == 0, "Above-range mint should take no token1");
        require(pool.liquidity() == 0, "Position should start inactive");

        // Swap 1->0: price rises through the gap into [60,120)
        _swap(false, 150e18);
        require(pool.currentTick() >= 60 && pool.currentTick() < 120, "Price should be inside the range");
        require(pool.liquidity() == 100000e18, "Position should be active after gap jump");

        (uint burned0, uint burned1) = pool.burn(60, 120, 100000e18, block.timestamp + DEADLINE_OFFSET);
        require(burned0 > 0, "Should return remaining token0");
        require(burned1 > 0, "Should return converted token1");
        require(burned0 < deposited0, "Some token0 must have been sold");
    }

    function it_burn_full_then_remint_no_stale_fees() {
        _mintRange(-600, 600, 100000e18);
        _swap(true, 100e18); // accrue fees

        pool.burn(-600, 600, 100000e18, block.timestamp + DEADLINE_OFFSET);
        pool.collect(address(this), -600, 600, 1000000e18, 1000000e18);

        _mintRange(-600, 600, 50000e18);
        pool.burn(-600, 600, 0, block.timestamp + DEADLINE_OFFSET);
        (, uint owed0, uint owed1) = pool.getPosition(address(this), -600, 600);
        require(owed0 == 0 && owed1 == 0, "Re-minted position must not inherit old fees: " + string(owed0));
    }

    function it_collect_partial_leaves_remainder() {
        _mintRange(-600, 600, 1000e18);
        (uint burned0, uint burned1) = pool.burn(-600, 600, 1000e18, block.timestamp + DEADLINE_OFFSET);

        (uint got0, uint got1) = pool.collect(address(this), -600, 600, burned0 / 2, 0);
        require(got0 == burned0 / 2, "Partial collect amount0 wrong");
        require(got1 == 0, "Capped token1 collect should be zero");

        (, uint owed0, uint owed1) = pool.getPosition(address(this), -600, 600);
        require(owed0 == burned0 - burned0 / 2, "Remainder 0 wrong");
        require(owed1 == burned1, "Token1 owed should be untouched");

        (uint got0b, uint got1b) = pool.collect(address(this), -600, 600, 1000000e18, 1000000e18);
        require(got0b == owed0 && got1b == owed1, "Second collect should drain remainder");
        (, uint owed0Final, uint owed1Final) = pool.getPosition(address(this), -600, 600);
        require(owed0Final == 0 && owed1Final == 0, "Nothing should remain owed");
    }

    function it_collect_empty_position_returns_zero() {
        (uint got0, uint got1) = pool.collect(address(this), -600, 600, 1000000e18, 1000000e18);
        require(got0 == 0 && got1 == 0, "Collecting empty position should return zeros");
    }

    function it_collect_only_owner_position_pays() {
        User u1 = _newUser();
        _userMint(u1, -6000, 6000, 100000e18);
        _swap(true, 100e18);

        // Test contract has no position at these ticks: collect pays nothing
        (uint got0, uint got1) = pool.collect(address(this), -6000, 6000, 1000000e18, 1000000e18);
        require(got0 == 0 && got1 == 0, "Non-owner should collect nothing");

        // The actual LP can collect its fees, to any recipient it chooses
        _userPoke(u1, -6000, 6000);
        (, uint owed0, ) = pool.getPosition(address(u1), -6000, 6000);
        require(owed0 > 0, "LP should have fees owed");
        uint balBefore = ERC20(token0Address).balanceOf(address(u1));
        u1.do(poolAddress, "collect", address(u1), int(-6000), int(6000), BIG, BIG);
        require(ERC20(token0Address).balanceOf(address(u1)) == balBefore + owed0, "LP should receive its fees");
    }

    // ============ INVARIANT TESTS ============

    function it_tracked_balances_match_erc20_balances() {
        _mintRange(-6000, 6000, 100000e18);
        _mintRange(-600, 600, 50000e18);
        _swap(true, 100e18);
        _swap(false, 50e18);
        pool.burn(-600, 600, 25000e18, block.timestamp + DEADLINE_OFFSET);
        pool.collect(address(this), -600, 600, 1000000e18, 1000000e18);
        pool.burn(-6000, 6000, 0, block.timestamp + DEADLINE_OFFSET);

        require(ERC20(token0Address).balanceOf(address(pool)) == pool.token0Balance(),
            "Token0 tracked balance out of sync");
        require(ERC20(token1Address).balanceOf(address(pool)) == pool.token1Balance(),
            "Token1 tracked balance out of sync");
    }

    function it_all_lps_can_exit_after_trading() {
        User u1 = _newUser();
        User u2 = _newUser();
        _userMint(u1, -6000, 6000, 100000e18);
        _userMint(u2, -1200, 1200, 50000e18);

        _swap(true, 300e18);
        _swap(false, 500e18);
        _swap(true, 250e18);

        u1.do(poolAddress, "burn", int(-6000), int(6000), 100000e18, block.timestamp + DEADLINE_OFFSET);
        u2.do(poolAddress, "burn", int(-1200), int(1200), 50000e18, block.timestamp + DEADLINE_OFFSET);
        u1.do(poolAddress, "collect", address(u1), int(-6000), int(6000), BIG, BIG);
        u2.do(poolAddress, "collect", address(u2), int(-1200), int(1200), BIG, BIG);

        (uint liq1, uint owed01, uint owed11) = pool.getPosition(address(u1), -6000, 6000);
        (uint liq2, uint owed02, uint owed12) = pool.getPosition(address(u2), -1200, 1200);
        require(liq1 == 0 && owed01 == 0 && owed11 == 0, "User1 should be fully exited");
        require(liq2 == 0 && owed02 == 0 && owed12 == 0, "User2 should be fully exited");
        require(pool.liquidity() == 0, "No liquidity should remain");

        require(ERC20(token0Address).balanceOf(address(pool)) == pool.token0Balance(), "Token0 sync broken");
        require(ERC20(token1Address).balanceOf(address(pool)) == pool.token1Balance(), "Token1 sync broken");
        require(pool.token0Balance() < 1e6, "Excess token0 dust: " + string(pool.token0Balance()));
        require(pool.token1Balance() < 1e6, "Excess token1 dust: " + string(pool.token1Balance()));
    }

    function property_mint_burn_roundtrip_never_profits(uint seed) {
        int tickLower = -60 * int(1 + seed % 50);
        int tickUpper = 60 * int(1 + (seed / 50) % 50);
        uint liquidityAmount = 1e18 + (seed % 1000) * 1e18;

        (uint deposited0, uint deposited1) = _mintRange(tickLower, tickUpper, liquidityAmount);
        (uint burned0, uint burned1) = pool.burn(tickLower, tickUpper, liquidityAmount, block.timestamp + DEADLINE_OFFSET);

        require(burned0 <= deposited0, "Burn must not return more token0 than deposited");
        require(burned1 <= deposited1, "Burn must not return more token1 than deposited");
        require(deposited0 - burned0 <= 4, "Excessive token0 rounding loss: " + string(deposited0 - burned0));
        require(deposited1 - burned1 <= 4, "Excessive token1 rounding loss: " + string(deposited1 - burned1));

        (uint got0, uint got1) = pool.collect(address(this), tickLower, tickUpper, BIG, BIG);
        require(got0 == burned0 && got1 == burned1, "Collect should pay exactly what burn credited");
    }

    function property_swap_roundtrip_never_profits(uint seed) {
        _mintRange(-12000, 12000, 200000e18);
        uint amountIn = 1e15 + seed % 5000e18;

        uint bal0Before = ERC20(token0Address).balanceOf(address(this));
        uint bal1Before = ERC20(token1Address).balanceOf(address(this));

        uint outB = _swap(true, amountIn);
        uint backA = _swap(false, outB);

        require(backA < amountIn, "Swap round trip must never profit: in " + string(amountIn) + " back " + string(backA));
        require(ERC20(token1Address).balanceOf(address(this)) == bal1Before, "All token1 should be swapped back");
        require(ERC20(token0Address).balanceOf(address(this)) == bal0Before - amountIn + backA, "Token0 accounting wrong");
    }

    // ============ SLOT0 / VIEW TESTS ============

    function it_slot0_view_matches_state() {
        _mintRange(-6000, 6000, 100000e18);
        _swap(true, 10e18);

        (uint sqrtP, int tick_, uint obsIdx, uint obsCard, uint obsCardNext, uint feeProtocol_, bool unlocked_) = pool.slot0();
        require(sqrtP == pool.sqrtPriceX96(), "slot0 sqrtPriceX96 mismatch");
        require(tick_ == pool.currentTick(), "slot0 tick mismatch");
        require(obsIdx == pool.observationIndex(), "slot0 observationIndex mismatch");
        require(obsCard == pool.observationCardinality(), "slot0 cardinality mismatch");
        require(obsCardNext == pool.observationCardinalityNext(), "slot0 cardinalityNext mismatch");
        require(feeProtocol_ == 0, "feeProtocol is always 0 (platform fee routing)");
        require(unlocked_, "Pool should be unlocked at rest");
    }

    // ============ TWAP ORACLE TESTS ============

    function it_twap_accumulator_tracks_tick_over_time() {
        _mintRange(-6000, 6000, 100000e18);

        int cumStart = _cumulativeNow();

        // Hold tick 0 for 100 seconds: accumulator unchanged (tick 0 contributes 0)
        fastForward(100);
        int cumAfterHold = _cumulativeNow();
        require(cumAfterHold == cumStart, "Tick 0 should contribute nothing");

        _swap(true, 500e18);
        int tickAfterSwap = pool.currentTick();
        require(tickAfterSwap < 0, "Tick should be negative after 0->1 swap");

        fastForward(100);
        int cumEnd = _cumulativeNow();

        int twapTick = (cumEnd - cumAfterHold) / 100;
        require(twapTick == tickAfterSwap, "TWAP tick mismatch: " + string(twapTick) + " vs " + string(tickAfterSwap));
        (int cumBack, ) = pool.observeSingle(100);
        require(cumBack == cumAfterHold, "observeSingle(100) should reproduce the saved snapshot");
    }

    function it_twap_time_weighted_average_across_price_changes() {
        _mintRange(-6000, 6000, 100000e18);

        int cum0 = _cumulativeNow();

        fastForward(100);
        int cum1 = _cumulativeNow();
        require(cum1 == cum0, "Tick 0 period should contribute zero");

        _swap(true, 500e18);
        int tickAfter = pool.currentTick();
        require(tickAfter < 0, "Tick should be negative");
        fastForward(300);
        int cum2 = _cumulativeNow();

        require((cum2 - cum1) / 300 == tickAfter, "300s window TWAP wrong");
        (int cum300Ago, ) = pool.observeSingle(300);
        require((cum2 - cum300Ago) / 300 == tickAfter, "observe-based 300s TWAP wrong");
        require(cum2 - cum0 == tickAfter * 300, "Full accumulator mismatch");
        require(cum2 < cum0, "Accumulator should decrease at negative ticks");
    }

    function it_twap_oracle_updates_on_liquidity_events() {
        _mintRange(-6000, 6000, 100000e18);
        _swap(true, 500e18);
        int tickHeld = pool.currentTick();

        // An in-range mint after 100s must fold the elapsed tick-seconds into a stored observation
        fastForward(100);
        _mintRange(-600, 600, 1000e18);
        (uint obsTimestamp, int obsCumulative, , bool obsInitialized) = pool.getObservation(pool.observationIndex());
        require(obsInitialized, "Latest observation should be initialized");
        require(obsCumulative == tickHeld * 100, "Mint should update the stored accumulator");
        require(obsTimestamp == block.timestamp, "Timestamp should advance");
    }

    function it_observe_array_api() {
        _mintRange(-6000, 6000, 100000e18);
        _swap(true, 500e18);
        int tickHeld = pool.currentTick();
        fastForward(200);

        // Canonical V3 observe(secondsAgos[]) shape: both accumulator arrays, index-aligned
        (int[] memory tickCums, int[] memory splCums) = pool.observe([uint(200), 100, 0]);
        require(tickCums.length == 3 && splCums.length == 3, "Array lengths wrong");
        require(tickCums[2] - tickCums[0] == tickHeld * 200, "200s window via array API wrong");
        require(tickCums[2] - tickCums[1] == tickHeld * 100, "100s window via array API wrong");
        require(splCums[2] > splCums[0], "secondsPerLiquidity must accumulate");
    }

    function it_seconds_per_liquidity_accumulates() {
        _mintRange(-6000, 6000, 100000e18);
        (, int splStart) = pool.observeSingle(0);

        fastForward(100);
        (, int splEnd) = pool.observeSingle(0);

        // 100 seconds at L = 100000e18: delta = 100 * 2^128 / 1e23 (floored)
        int expected = int((100 * Q128) / 100000e18);
        require(splEnd - splStart == expected,
            "secondsPerLiquidity delta mismatch: " + string(splEnd - splStart));
    }

    function it_snapshot_cumulatives_inside_tracks_range_time() {
        _mintRange(-6000, 6000, 100000e18);

        (int tickCumIn1, int splIn1, int secIn1) = pool.snapshotCumulativesInside(-6000, 6000);
        fastForward(100);
        (int tickCumIn2, int splIn2, int secIn2) = pool.snapshotCumulativesInside(-6000, 6000);

        // The whole 100s elapsed inside the range at tick 0
        require(secIn2 - secIn1 == 100, "secondsInside should advance by 100");
        require(tickCumIn2 - tickCumIn1 == 0, "tick 0 contributes nothing to tickCumulativeInside");
        require(splIn2 - splIn1 == int((100 * Q128) / 100000e18), "splInside delta mismatch");

        // A range far above the price accrues no inside time
        _mintRange(6000, 12000, 1000e18);
        (, , int secOut1) = pool.snapshotCumulativesInside(6000, 12000);
        fastForward(50);
        (, , int secOut2) = pool.snapshotCumulativesInside(6000, 12000);
        require(secOut2 - secOut1 == 0, "Out-of-range range must accrue no secondsInside");

        // Uninitialized ticks revert
        bool thrown = false;
        try {
            pool.snapshotCumulativesInside(-1200, 1200);
        } catch {
            thrown = true;
        }
        require(thrown, "Snapshot of uninitialized ticks should revert");
    }

    // ============ ORACLE RING BUFFER TESTS ============

    function it_oracle_cardinality_growth_and_history() {
        _mintRange(-6000, 6000, 100000e18);
        pool.increaseObservationCardinalityNext(8);
        require(pool.observationCardinalityNext() == 8, "cardinalityNext should grow");
        require(pool.observationCardinality() == 1, "cardinality grows only on the next write");

        fastForward(100);
        _swap(true, 100e18); // checkpoint 1; ring grows to 8 on this write
        require(pool.observationCardinality() == 8, "cardinality should grow on write");
        int tick1 = pool.currentTick();

        fastForward(100);
        _swap(true, 100e18); // checkpoint 2
        int tick2 = pool.currentTick();

        fastForward(100);
        int cumNow = _cumulativeNow();

        (int cum200, ) = pool.observeSingle(200);
        require(cumNow - cum200 == tick1 * 100 + tick2 * 100,
            "Two-checkpoint window mismatch: " + string(cumNow - cum200));
    }

    function it_oracle_interpolates_between_observations() {
        _mintRange(-6000, 6000, 100000e18);
        pool.increaseObservationCardinalityNext(4);

        fastForward(100);
        _swap(true, 500e18); // checkpoint at t1; tick becomes tickHeld from here on
        int tickHeld = pool.currentTick();

        fastForward(100);
        pool.burn(-6000, 6000, 0, block.timestamp + DEADLINE_OFFSET); // poke: no checkpoint (no liquidity change)
        _mintRange(-6000, 6000, 1); // in-range mint writes checkpoint at t2 = t1+100
        (int cumAtT2, ) = pool.observeSingle(0);

        fastForward(100); // now = t2 + 100

        (int cumAtT1, ) = pool.observeSingle(200);  // t1 exactly: a stored checkpoint
        (int cumMid, ) = pool.observeSingle(150);   // t1 + 50: between checkpoints, interpolated
        require(cumAtT2 - cumAtT1 == tickHeld * 100, "Checkpoint delta wrong");
        require(cumMid == cumAtT1 + tickHeld * 50, "Interpolated cumulative wrong: " + string(cumMid));
    }

    function it_oracle_ring_wraps_and_overwrites_oldest() {
        _mintRange(-6000, 6000, 100000e18);
        pool.increaseObservationCardinalityNext(3);

        fastForward(100);
        _swap(true, 50e18); // t1
        fastForward(100);
        _swap(true, 50e18); // t2
        int tickAfterT2 = pool.currentTick();
        fastForward(100);
        _swap(true, 50e18); // t3
        int tickAfterT3 = pool.currentTick();
        fastForward(100);
        _swap(true, 50e18); // t4: ring has wrapped; oldest retained checkpoint is t2
        int tickAfterT4 = pool.currentTick();

        fastForward(50); // now = t4 + 50

        int cumNow = _cumulativeNow();
        (int cumT2, ) = pool.observeSingle(250);
        require(cumNow - cumT2 == tickAfterT2 * 100 + tickAfterT3 * 100 + tickAfterT4 * 50,
            "Wrapped-ring accumulator mismatch: " + string(cumNow - cumT2));

        bool thrown = false;
        try {
            pool.observeSingle(360);
        } catch {
            thrown = true;
        }
        require(thrown, "History overwritten by ring wrap must revert (OLD)");
    }

    function it_oracle_old_history_reverts() {
        _mintRange(-6000, 6000, 100000e18);
        fastForward(100);
        _swap(true, 100e18); // overwrites the single slot at the current timestamp

        bool thrown = false;
        try {
            pool.observeSingle(50); // target predates the only retained observation
        } catch {
            thrown = true;
        }
        require(thrown, "History beyond the ring must revert (OLD)");
    }

    function it_oracle_cardinality_validation() {
        bool thrown = false;
        try {
            pool.increaseObservationCardinalityNext(0);
        } catch {
            thrown = true;
        }
        require(thrown, "Zero cardinality should revert");

        thrown = false;
        try {
            pool.increaseObservationCardinalityNext(65536);
        } catch {
            thrown = true;
        }
        require(thrown, "Cardinality above 65535 should revert");

        pool.increaseObservationCardinalityNext(4);
        pool.increaseObservationCardinalityNext(2);
        require(pool.observationCardinalityNext() == 4, "Shrink attempts must be no-ops");
    }

    // ============ TICK BITMAP TESTS ============

    function it_swap_across_multi_word_gap() {
        // Spacing 60: one bitmap word spans 15360 ticks. These ranges sit three words apart,
        // so the swap must step word-by-word across empty bitmap words in both directions
        _mintRange(-60, 60, 100000e18);
        _mintRange(-33600, -33540, 100000e18);

        uint amountOut = _swap(true, 500e18);
        require(amountOut > 0, "Gap swap should trade");
        require(pool.currentTick() >= -33600 && pool.currentTick() < -33540,
            "Should land in the far range, got " + string(pool.currentTick()));
        require(pool.liquidity() == 100000e18, "Only the far range should be active");

        uint amountBack = _swap(false, 500e18);
        require(amountBack > 0, "Return swap should trade");
        require(pool.currentTick() >= -60 && pool.currentTick() < 60,
            "Should return to the near range, got " + string(pool.currentTick()));
        require(pool.liquidity() == 100000e18, "Near range should be active again");
    }

    function it_swap_crosses_word_boundary_ticks() {
        // Spacing 60: tick 15360 = compressed 256 = bit 0 of word 1; tick -15360 = bit 0 of word -1
        _mintRange(0, 60, 50000e18);
        _mintRange(15360, 15420, 50000e18);
        _mintRange(-15420, -15360, 500000e18);

        _swap(false, 400e18);
        require(pool.currentTick() >= 15360 && pool.currentTick() < 15420,
            "Should land in the word-boundary range, got " + string(pool.currentTick()));
        require(pool.liquidity() == 50000e18, "Boundary range must be active");

        _swap(true, 800e18);
        require(pool.currentTick() >= -15420 && pool.currentTick() < -15360,
            "Should land in the negative word-boundary range, got " + string(pool.currentTick()));
        require(pool.liquidity() == 500000e18, "Negative boundary range must be active");
    }

    // ============ GUARD / ADMIN TESTS ============

    function it_paused_pool_rejects_swaps_and_mints() {
        _mintRange(-6000, 6000, 100000e18);
        pool.setPaused(true);

        require(ERC20(token0Address).approve(address(pool), 10e18), "Approval failed");
        bool thrown = false;
        try {
            pool.swap(address(this), true, int(10e18), 0, 1, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "Paused pool should reject swaps");

        thrown = false;
        try {
            pool.mint(address(this), -600, 600, 1000e18, 1000e18, 1000e18, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "Paused pool should reject mints");

        // Burn and collect must still work while paused (LP exit path)
        pool.burn(-6000, 6000, 100000e18, block.timestamp + DEADLINE_OFFSET);
        (uint got0, uint got1) = pool.collect(address(this), -6000, 6000, 1000000e18, 1000000e18);
        require(got0 > 0 && got1 > 0, "Exit while paused should work");
    }

    function it_disabled_pool_freezes_everything_until_reenabled() {
        _mintRange(-6000, 6000, 100000e18);
        pool.setDisabled(true);
        require(pool.isPaused(), "Disable should force pause");

        require(ERC20(token0Address).approve(address(pool), 10e18), "Approval failed");
        bool thrown = false;
        try {
            pool.swap(address(this), true, int(10e18), 0, 1, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "Disabled pool should reject swaps");

        thrown = false;
        try {
            pool.burn(-6000, 6000, 1000e18, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "Disabled pool should reject burns");

        thrown = false;
        try {
            pool.collect(address(this), -6000, 6000, 1e18, 1e18);
        } catch {
            thrown = true;
        }
        require(thrown, "Disabled pool should reject collects");

        thrown = false;
        try {
            pool.setPaused(false);
        } catch {
            thrown = true;
        }
        require(thrown, "Cannot unpause while disabled");

        pool.setDisabled(false);
        require(pool.isPaused(), "Pause should persist after re-enable");
        pool.setPaused(false);
        uint amountOut = _swap(true, 10e18);
        require(amountOut > 0, "Swap should work after full re-enable");
    }

    function it_inactive_token_blocks_trading_allows_exit() {
        _mintRange(-6000, 6000, 100000e18);
        _swap(true, 100e18); // accrue some fees first
        Token(token0Address).setStatus(1); // deactivate

        require(ERC20(token0Address).approve(address(pool), 10e18), "Approval failed");
        bool thrown = false;
        try {
            pool.swap(address(this), true, int(10e18), 0, 1, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "Inactive token should block swaps");

        thrown = false;
        try {
            pool.mint(address(this), -600, 600, 1000e18, 1000e18, 1000e18, block.timestamp + DEADLINE_OFFSET);
        } catch {
            thrown = true;
        }
        require(thrown, "Inactive token should block mints");

        // LP exit path still works with an inactive token
        pool.burn(-6000, 6000, 100000e18, block.timestamp + DEADLINE_OFFSET);
        (uint got0, uint got1) = pool.collect(address(this), -6000, 6000, BIG, BIG);
        require(got0 > 0 && got1 > 0, "Exit must work with inactive token");

        Token(token0Address).setStatus(2);
    }

    function it_initialize_only_once() {
        _mintRange(-600, 600, 1000e18);
        bool thrown = false;
        try {
            pool.initialize(token0Address, token1Address, 3000, 60, 2 * Q96, address(factory));
        } catch {
            thrown = true;
        }
        require(thrown, "Re-initialize should revert");
        require(pool.sqrtPriceX96() == Q96 && pool.currentTick() == 0, "Pool state must be unchanged");
    }

    function it_non_owner_cannot_admin_pool() {
        User stranger = new User();

        bool thrown = false;
        try {
            stranger.do(poolAddress, "setPaused", true);
        } catch {
            thrown = true;
        }
        require(thrown, "Non-owner setPaused should revert");

        thrown = false;
        try {
            stranger.do(poolAddress, "setDisabled", true);
        } catch {
            thrown = true;
        }
        require(thrown, "Non-owner setDisabled should revert");

        thrown = false;
        try {
            stranger.do(poolAddress, "setLpSharePercent", 5000);
        } catch {
            thrown = true;
        }
        require(thrown, "Non-factory setLpSharePercent should revert");

        thrown = false;
        try {
            stranger.do(poolAddress, "transferPoolToFactory", address(stranger));
        } catch {
            thrown = true;
        }
        require(thrown, "Non-factory transferPoolToFactory should revert");

        require(!pool.isPaused() && !pool.isDisabled(), "Pool state must be untouched");
    }

    // ============ SYNC / SKIM TESTS ============

    function it_skim_recovers_donated_tokens() {
        _mintRange(-600, 600, 1000e18);
        uint tracked0 = pool.token0Balance();
        uint tracked1 = pool.token1Balance();

        Token(token0Address).mint(poolAddress, 5e18);
        Token(token1Address).mint(poolAddress, 7e18);
        require(ERC20(token0Address).balanceOf(poolAddress) == tracked0 + 5e18, "Donation 0 should land");

        User receiver = new User();
        pool.skim(address(receiver));
        require(ERC20(token0Address).balanceOf(address(receiver)) == 5e18, "Skim should pay excess 0");
        require(ERC20(token1Address).balanceOf(address(receiver)) == 7e18, "Skim should pay excess 1");
        require(pool.token0Balance() == tracked0 && pool.token1Balance() == tracked1, "Tracked balances must not change");
        require(ERC20(token0Address).balanceOf(poolAddress) == tracked0, "Pool 0 balance should match tracked");

        pool.burn(-600, 600, 1000e18, block.timestamp + DEADLINE_OFFSET);
        (uint got0, uint got1) = pool.collect(address(this), -600, 600, BIG, BIG);
        require(got0 > 0 && got1 > 0, "Exit after skim should work");
    }

    function it_sync_repairs_tracked_balances() {
        _mintRange(-600, 600, 1000e18);
        Token(token0Address).mint(poolAddress, 5e18);

        factory.syncPools([poolAddress]);
        require(pool.token0Balance() == ERC20(token0Address).balanceOf(poolAddress), "Sync should adopt actual 0 balance");
        require(pool.token1Balance() == ERC20(token1Address).balanceOf(poolAddress), "Sync should adopt actual 1 balance");

        User receiver = new User();
        factory.skimPools([poolAddress], address(receiver));
        require(ERC20(token0Address).balanceOf(address(receiver)) == 0, "Nothing to skim after sync");
    }

    function it_sync_skim_reject_strangers() {
        _mintRange(-600, 600, 1000e18);
        User stranger = new User();

        bool thrown = false;
        try {
            stranger.do(poolAddress, "skim", address(stranger));
        } catch {
            thrown = true;
        }
        require(thrown, "Stranger skim should revert");

        thrown = false;
        try {
            stranger.do(poolAddress, "sync");
        } catch {
            thrown = true;
        }
        require(thrown, "Stranger sync should revert");
    }

    // ============ FACTORY MIGRATION TESTS ============

    function it_transfer_pool_to_new_factory() {
        PoolV3Factory factory2 = new PoolV3Factory(address(this));
        factory2.initialize(address(m.tokenFactory()), address(m.feeCollector()));

        pool.transferPoolToFactory(address(factory2));
        require(address(pool.poolV3Factory()) == address(factory2), "Factory pointer should update");

        // Old factory loses admin rights over the pool
        bool thrown = false;
        try {
            factory.setPoolLpSharePercent(poolAddress, 5000);
        } catch {
            thrown = true;
        }
        require(thrown, "Old factory should lose pool admin");

        // New factory gains them
        factory2.setPoolLpSharePercent(poolAddress, 4000);
        require(pool.lpSharePercent() == 4000, "New factory should administer the pool");

        // The new factory adopts the pool into its registry
        factory2.registerPoolsFromFactory([poolAddress]);
        require(factory2.pools(token0Address, token1Address, 3000) == poolAddress, "Registry should adopt the pool");
        require(factory2.pools(token1Address, token0Address, 3000) == poolAddress, "Reverse registry should adopt the pool");

        thrown = false;
        try {
            factory2.createPoolV3(token0Address, token1Address, 3000, Q96);
        } catch {
            thrown = true;
        }
        require(thrown, "Duplicate creation after adoption should revert");

        thrown = false;
        try {
            pool.transferPoolToFactory(address(0));
        } catch {
            thrown = true;
        }
        require(thrown, "Zero factory address should revert");
    }

    function it_factory_batch_migration_with_registry_adoption() {
        address pool10000 = factory.createPoolV3(token0Address, token1Address, 10000, Q96);

        PoolV3Factory factory2 = new PoolV3Factory(address(this));
        factory2.initialize(address(m.tokenFactory()), address(m.feeCollector()));

        bool thrown = false;
        try {
            factory2.registerPoolsFromFactory([poolAddress]);
        } catch {
            thrown = true;
        }
        require(thrown, "Adopting a foreign pool should revert");

        factory.transferPoolsToFactory(address(factory2));
        require(address(pool.poolV3Factory()) == address(factory2), "Pool 1 should point at factory2");
        require(address(PoolV3(pool10000).poolV3Factory()) == address(factory2), "Pool 2 should point at factory2");

        factory2.registerPoolsFromFactory([poolAddress, pool10000]);
        require(factory2.pools(token0Address, token1Address, 3000) == poolAddress, "0.3% pool adopted");
        require(factory2.pools(token0Address, token1Address, 10000) == pool10000, "1% pool adopted");

        factory2.registerPoolsFromFactory([poolAddress]);
        require(factory2.pools(token0Address, token1Address, 3000) == poolAddress, "Re-registration stays consistent");
    }
}
