name:                strato-sequencer
version:             0.1.0.0
license:             MIT
author:              Ilya Ostrovskiy
maintainer:          ilya@blockapps.net
copyright:           2016 BlockApps Inc
category:            Blockchain
build-type:          Simple


dependencies:
  - aeson
  - alarmclock
  - async
  - base >=4.8 && <4.12
  - base16-bytestring
  - base64-bytestring
  - bimap
  - binary
  - blockapps-data
  - blockapps-datadefs
  - blockapps-haskoin
  - blockapps-init
  - blockapps-milena
  - blockapps-privacy
  - blockapps-util
  - blockstanbul
  - bytestring
  - classy-prelude
  - clock
  - conduit
  - conduit-combinators
  - containers
  - cross-monitoring
  - data-default
  - deepseq
  - directory
  - ethereum-rlp
  - exceptions
  - extra
  - format
  - lens
  - leveldb-haskell
  - lifted-async
  - monad-alter
  - monad-control
  - mtl
  - prometheus-client
  - resourcet
  - seqevents
  - servant-client
  - stm
  - stm-chans
  - stm-conduit
  - strato-conf
  - strato-genesis
  - strato-model
  - text
  - time
  - transformers
  - unliftio
  - wai-extra
  - wai-middleware-prometheus
  - warp

ghc-options: -Wall -O2 -threaded -rtsopts -fprof-auto

library:
  source-dirs:     src

executables:
  strato-sequencer:
    source-dirs:      exec-src
    main:             Main.hs
    dependencies:
      - hflags
      - safe
      - strato-sequencer
    other-modules: [Flags]

  keygen:
    source-dirs: exec-src/
    main: KeyGen.hs
    dependencies:
      - strato-sequencer
      - aeson-pretty
      - entropy
      - hflags
    other-modules: [Flags]

  forced-config-change:
    source-dirs: exec-src
    main: ForcedConfigChange.hs
    other-modules: []
    dependencies:
      - hflags
      - seqevents

tests:
  strato-sequencer-spec:
    source-dirs:   test
    main:          Main.hs
    ghc-options: -threaded
    dependencies:
      - HUnit
      - QuickCheck
      - derive
      - entropy
      - ethereum-rlp
      - hflags
      - hspec
      - hspec-core
      - hspec-contrib
      - strato-sequencer
      - hspec-expectations-lifted

benchmarks:
  send-to-blockstanbul:
    source-dirs: bench/
    main: BlockstanbulSend.hs
    dependencies:
      - blockstanbul
      - strato-sequencer
      - criterion
      - parallel
