name:                strato-sequencer
version:             0.1.0.0
license:             MIT
author:              Ilya Ostrovskiy
maintainer:          ilya@blockapps.net
copyright:           2016 BlockApps Inc
category:            Blockchain
build-type:          Simple


dependencies:
  - base >=4.8 && <4.10
  - alarmclock
  - bimap
  - classy-prelude
  - strato-model
  - blockapps-data
  - blockapps-util
  - strato-conf
  - clock
  - containers
  - directory
  - extra
  - mtl
  - resourcet
  - monad-logger
  - text
  - strato-genesis
  - leveldb-haskell
  - blockapps-milena
  - binary
  - base64-bytestring
  - base16-bytestring
  - bytestring
  - ethereum-rlp
  - time
  - stm
  - stm-chans
  - conduit-combinators
  - blockstanbul
  - stm-chans
  - lens
  - blockapps-haskoin
  - aeson
  - async
  - prometheus-client
  - warp
  - servant-server
  - wai-extra
  - wai-middleware-prometheus

ghc-options: -Wall -O2 -threaded

library:
  source-dirs:     src

executables:
  strato-sequencer:
    source-dirs:      exec-src
    main:             Main.hs
    dependencies:
      - hflags
      - safe
      - strato-sequencer

  keygen:
    source-dirs: exec-src/
    main: KeyGen.hs
    dependencies:
      - strato-sequencer
      - aeson-pretty
      - entropy
      - hflags

tests:
  strato-sequencer-spec:
    source-dirs:   test
    main:          Main.hs
    dependencies:
      - HUnit
      - QuickCheck
      - derive
      - hflags
      - hspec
      - hspec-core
      - hspec-contrib
      - strato-sequencer
      - hspec-expectations-lifted

benchmarks:
  send-to-blockstanbul:
    source-dirs: bench/
    main: BlockstanbulSend.hs
    dependencies:
      - blockstanbul
      - strato-sequencer
      - criterion
      - parallel
