FROM node:14-slim

RUN mkdir blockapps-rest

WORKDIR blockapps-rest

COPY gulpfile.js package.json ./

RUN yarn

COPY . ./

ARG host

RUN sed -i 's|http://localhost|http://'"${host}"'|g' .oauth-test-config && \
    cat .oauth-test-config && \
    cp .oauth-test-env .env && \
    cp .oauth-test-config src/test/fixtures/config.yaml && \
    cp .oauth-test-config src/util/test/fixtures/config.yaml

RUN yarn build

RUN yarn test
