FROM node:10-jessie

RUN npm install -g yarn &&\
    mkdir blockapps-rest

WORKDIR blockapps-rest

COPY package.json ./

RUN npm i

COPY . ./

ARG host

RUN sed -i 's|http://localhost|http://'"${host}"'|g' .oauth-test-config && \
    cat .oauth-test-config && \
    cp .oauth-test-env .env && \
    cp .oauth-test-config lib/test/fixtures/config.yaml && \
    cp .oauth-test-config lib/util/test/fixtures/config.yaml

RUN npm run test
