contract record Args {

  enum Args {
    UID,
    IS_BUY_DEAL,
    TRADER_ID,
    COUNTER_PARTY_ID,
    BUY_PARTY,
    SELL_PARTY,
    DEAL_PRICE,
    PRICE_TYPE,
    DEAL_DATE,
    INDEX_PRICE_ADDER,
    BEGIN_FLOW_DATE,
    END_FLOW_DATE,
    SOURCE,
    SINK,
    PIPELINE_EBB,
    RECEIPT_LOCATION,
    VOLUME,
    GAS_VOLUME_UNITS,
    STRATEGY,
    MAX
  }
}
