
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    client_body_buffer_size 64K;
    client_header_buffer_size 64k;
    client_max_body_size 1M;
    large_client_header_buffers 4 512k;

    server {
      resolver 127.0.0.11;

      location = /bloc {
        return 302 /bloc/;
      }

      location /bloc/ {
        #proxy_redirect http://localhost:8000 /bloc; 

        proxy_set_header Accept-Encoding "";
#        proxy_pass http://localhost:8080
        proxy_pass http://bloc:8000/;
      }

      location / {
        proxy_pass http://strato:3000;
      }

    }
}