name: solid-vm-native
license: Apache-2.0

dependencies:
  - base

library:
  source-dirs: src/
  exposed-modules:
    - SolidVM.Core
    - SolidVM.Compile
    - SolidVM.Gas
    - SolidVM.Values
    - SolidVM.Events
    - SolidVM.Storage
    - SolidVM.Builtins
  ghc-options: -O1
  dependencies:
    - Decimal
    - base16-bytestring
    - bytestring
    - containers
    - lens
    - mtl
    - solid-vm-model
    - source-tools
    - strato-model
    - text
    - blockapps-data
    - blockapps-mpdbs
    - evm-solidity
    - solid-vm
    - solid-vm-static-analysis
    - unliftio
    - vector
    - solid-vm-parser
    - monad-alter
    - vm-tools
    - common-log
    - ethereum-rlp
    - strato-conf
    - utf8-string
