#!/bin/bash

set -e


# Taken from https://superuser.com/questions/590099/can-i-make-curl-fail-with-an-exitcode-different-than-0-if-the-http-status-code-i
#This should be replaced with the new `--fail-with-body` flag once we are all using curl 7.76+
curlf() {
    OUTPUT_FILE=$(mktemp)
    HTTP_CODE=$(curl --silent --show-error --output $OUTPUT_FILE --write-out "%{http_code}" "$@")
    if [[ ${HTTP_CODE} -lt 200 || ${HTTP_CODE} -gt 299 ]] ; then
	>&2 echo -e '\033[31;1m'
	#cat $OUTPUT_FILE | jq -r >&2
	cat $OUTPUT_FILE >&2
	>&2 echo -e '\033[m\n'
	return 22
    fi
    cat $OUTPUT_FILE
    rm $OUTPUT_FILE
}



token=`cat .token`

curlf -H"Authorization: Bearer $token" -H "Content-Type: application/json" "$@"

