name: blockapps-datadefs

dependencies:
  - aeson
  - ansi-wl-pprint
  - base
  - base16-bytestring
  - binary
  - bytestring
  - crypto-pubkey-types
  - deepseq
  - ethereum-rlp
  - format
  - generic-arbitrary
  - generic-random
  - labeled-error
  - lens
  - persistent
  - persistent-template
  - QuickCheck
  - servant-docs
  - strato-model
  - swagger2
  - text
  - time
  - transformers

ghc-options: -Wall -O2

library:
  source-dirs: src/
  default-extensions: TemplateHaskell
