name: blockapps-datadefs

dependencies:
  - aeson
  - base
  - base16-bytestring
  - binary
  - bytestring
  - crypto-pubkey-types
  - deepseq
  - format
  - lens
  - persistent
  - persistent-template
  - strato-model
  - text
  - time
  - transformers

ghc-options: -Wall -O2

library:
  source-dirs: src/
  default-extensions: TemplateHaskell
