#!/bin/bash

set -e

if ! type jq &>/dev/null
then echo "Please install 'jq' (https://stedolan.github.io/jq/download/), as JSON parsing is required."
     exit 1
fi

read -e -p "Resource group name: " resourceGroup

read -e -p "Region [eastus]: " region
region=${region:-eastus}

read -e -p "Storage account name: " storageAccount

azure group create $resourceGroup $region

if ! azure storage account show -g $resourceGroup $storageAccount >&/dev/null
then azure storage account create -g $resourceGroup $storageAccount --sku-name LRS --location $region --kind Storage
fi

eval "storageKey=$(azure storage account keys list --json -g $resourceGroup $storageAccount | jq '.[0].value')"

container=vhds

if ! azure storage container show --container $container -a $storageAccount -k $storageKey >&/dev/null
then azure storage container create --container $container -a $storageAccount -k $storageKey
fi

blob=wan2.vhd
sas='st=2016-07-02T06%3A08%3A12Z&se=2016-07-09T07%3A08%3A12Z&sp=rl&sv=2015-02-21&sr=c&sig=tLgmdK95ngMFb5MJ3UUUfw2WkiemaGOwae4C%2FlkxISI%3D'

azure storage blob copy start \
  -a bamarketstorage --source-sas $sas \
  --source-container $container --source-blob $blob \
  --dest-account-name $storageAccount --dest-account-key $storageKey \
  --dest-container $container --dest-blob $blob

while read -p "Press enter to refresh the copy status; Ctrl-D to continue"
do azure storage blob copy show -a $storageAccount -k $storageKey --container $container --blob $blob
done

echo
echo "Writing deployment script"

echo >makeStrato "#!/bin/bash
set -e

if [[ \$# == 0 ]]
then read -e -p \"Node name: \" nodeName
else nodeName=\$1
fi

azure group deployment create -f mainTemplate.json -n \$nodeName $resourceGroup -p \"{
  \\\"nodeName\\\": {\\\"value\\\": \\\"\$nodeName\\\"},
  \\\"storageAccount\\\": {\\\"value\\\": \\\"$storageAccount\\\"}
}\"

azure network public-ip show -g $resourceGroup -n \${nodeName}publicip

echo 'Username: strato'
echo 'Password: BlockappsPassword123!'
"
chmod +x makeStrato

