#!/bin/bash

set -e

container="system"
blob="Microsoft.Compute/Images/vhds/marketvm2-osDisk.c900c70b-c9f1-4d48-94d7-9e58d9c01220.vhd"
accountName="stratodev31481"
resourceGroup="strato-dev3"

stime="$(date -d "last hour" -u)"
etime="$(date -d "next week" -u)"
permissions="rl"
eval "accountKey=$(azure storage account keys list --json -g $resourceGroup $accountName | jq .[0].value)"

eval "SAS=$(azure storage container sas create --json \
  --account-name "$accountName" --account-key $accountKey \
  --container "$container" --permissions "$permissions" \
  --start "$stime" --expiry "$etime" | jq .sas)"

echo "http://$accountName.blob.core.windows.net/$container/$blob?$SAS"

