#!/bin/bash
set -e

if [[ $# -ne 1 ]]
then echo >&2 "Please provide your name"
     exit 1
fi
name=$1

azure group deployment create -f cd-machine/mainTemplate.json -p "{\"name\":{\"value\":\"$name\"}}" blockapps
azure network public-ip show -g blockapps -n $name-buildpublicip

