#!/bin/bash
set -e

# Make a gocd build machine VM
resourceGroup='blockapps'
storageAccount='blockapps8018'
imageURI='https://blockapps8018.blob.core.windows.net/system/Microsoft.Compute/Images/vhds/blockapps8018-osDisk.8bd1ff15-fd2e-41d1-84de-5dfdc1e374c7.vhd'
region='eastus'
netName='blockapps3056'

# force first argument
if [ -z "$1" ]; then
  echo ERROR: VM name must be specified
  exit 1
fi

# login to our account
echo "Logging into Azure - follow the prompt, enter the code, and click on 'Ryan Reich'"
azure login
# set ARM mode
azure config mode arm

name='cd-'$1
echo "The new VM name: $name"
azure vm create -g $resourceGroup -n $name -f ${name}nic -l $region -y Linux -z Standard_DS3 -i ${name}ip -w ${name} -F $netName -j default -Q $imageURI -o $storageAccount \
  --admin-username blockapps --admin-password 'blockAPPS123!' --disable-boot-diagnostics
echo "The new VM URL: $name.eastus.cloudapp.azure.com"
