#!/bin/bash

if [[ $# -ne 1 ]]; then
  echo >&2 "Must pass a VM name"
  exit 1
fi

name=$1

azure group deployment create -n $name -p "{\"vmName\": {\"value\": \"$name\"}}" -f nmchain.template.json blockapps-marketplace

