#!/bin/bash
set -e

resourceGroup='blockapps-marketplace'
release=${1:-2016-06_single-node}
templateFile='mainTemplate.json'

azure group deployment create -f $release/$templateFile $resourceGroup

echo
echo -n "Enter the node name you used to look up the public IP address: "
read nodeName
azure network public-ip show -g $resourceGroup -n ${nodeName}publicip
