name:                ethereum-discovery
version:             0.1.0.0
author:              jamshid
maintainer:          jim
build-type:          Simple
license:             Apache-2.0

dependencies:
  - base
  - base16-bytestring
  - binary
  - blockapps-data
  - blockapps-datadefs
  - blockapps-haskoin
  - blockapps-init
  - blockapps-util
  - bytestring
  - classy-prelude
  - cpu
  - cryptohash
  - crypto-pubkey-types
  - either
  - entropy
  - errors
  - ethereum-encryption
  - ethereum-rlp
  - exceptions
  - format
  - lifted-base
  - monad-alter
  - mtl
  - network
  - network-uri
  - persistent-postgresql
  - persistent-template
  - prometheus-client
  - random
  - resourcet
  - split
  - strato-conf
  - strato-model
  - text
  - time
  - unliftio
  - unliftio-core
  - monad-control

ghc-options: -Wall -O2

library:
  source-dirs: src/
  exposed-modules:
    - Blockchain.Strato.Discovery.Data.Peer
    - Blockchain.Strato.Discovery.UDP
    - Executable.EthereumDiscovery
    - Executable.EthDiscoverySetup

executables:
  ethereum-discover:
    source-dirs:       exec_src/
    main:             Main.hs
    dependencies:
      - ethereum-discovery
      - hflags

tests:
  ethereum-discover-test:
    source-dirs: test/
    main: Spec.hs
    ghc-options: -Wall -Werror
    dependencies:
      - ethereum-discovery
      - hspec
