import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import CustomNavbar from "../components/_navbar/page";
import { TokenProvider } from "@/context/TokenContext";
import { UserProvider } from "@/context/UserContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "STRATO Mercata",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon_large.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <TokenProvider>
            <CustomNavbar />
            {children}
          </TokenProvider>
        </UserProvider>
      </body>
    </html>
  );
}
