@startuml
autonumber

title "Bridge-Out Flow Diagram"

actor "\n User \n" as user
control "\n Mercata UI \n" as mercataUI
control "\n Mercata Backend \n" as mercataBackend
database "\n Safe Wallet \n" as safeWallet
control "\n Relayer \n" as bridgingService
control "\n Alchemy API \n" as alchemy
database "\n STRATO Node \n" as strato
actor "\n Mercata Owners \n" as owners
autonumber 100

== Step 1: Page visit ==
user -> mercataUI: Access application\n(AUTHENTICATED)

== Step 2: Bridge-Out Request on UI ==
user -> mercataUI: Request bridge-in \n(approval on confirmation popup screen)
mercataUI -> mercataBackend: Send bridge-out request\nw/ session/user access token, \ntoken_address, amount, to_address
mercataBackend -> bridgingService: Proxy the request

== Step 4: Propose txn to Safe and notify approvers ==
bridgingService -> bridgingService: verify (!) user access token and decode it
bridgingService -> strato: fetch user's address by username from decoded access token\nw/ relayer access token
bridgingService -> bridgingService: verify that the token_address matches one of the tokens in Mercata
bridgingService -> strato: verify (!) that the user has enough token balance for the withdrawal
bridgingService -> safeWallet: Submit withdrawal txn, get SafeTx hash\nw/ relayer private key (proposer role), token_address (?), amount, to_address, type(erc20|eth), safeOwnerPrivateKey
bridgingService -> strato: (TXN Mercata) Call MercataEthBridge.markWithdrawalPendingApproval\nw/ safe_txn_hash,relayer_access_token
strato --> bridgingService: get successful txn confirmation or create an exception case
bridgingService -> owners: Send email to owners w/ URL link to Safe approve page

== Step 5: Owners approve withdrawal in Safe ==
owners -> safeWallet: Approve SafeTx transaction manually
safeWallet -> safeWallet: (TXN Ethereum) Transfer amount to

== Step 6: Wait for the Withdrawal to be executed on Ethereum ==
alchemy -> bridgingService: Emit SafeTx approval details (via WebSocket)
bridgingService -> safeWallet: Obtain safe_txn_hash by eth_txn_hash (to filter the withdrawal event by safe_txn_hash)
loop
bridgingService -> alchemy: Poll for SafeTx approval details w/ safe_txn_hash
end

== Step 7: Confirm Withdrawal on MercataEthBridge contract ==
bridgingService -> strato: (TXN Mercata) Call MercataEthBridge.confirmWithdrawal\nw/ safe_txn_hash, relayer access token

== Step 8: UI to get withdrawal status ==
user -> mercataUI: refresh page on demand to see withdrawal status\n(calls to backend and strato api omitted here)
@enduml
