name: slipstream
version: 0.1.0.0
synopsis: Solidity datatypes
description: Solidity datatypes
homepage: https://github.com/blockapps/blockapps-haskell/slipstream
license: BSD3
license-file: LICENSE
copyright: 2016 BlockApps
category: Web


ghc-options: -Wall -Werror -rtsopts

dependencies:
  - base
  - bytestring
  - common-log
  - hflags
  - raw-strings-qq
  - resourcet
  - semigroups
  - text
  - transformers

library:
  source-dirs: src/
  dependencies: 
    - aeson
    - binary
    - blockapps-bloc22-server
    - blockapps-solidity
    - blockapps-util
    - bloomfilter
    - classy-prelude
    - conduit
    - containers
    - cross-monitoring
    - deepseq
    - extra
    - lens
    - lifted-base
    - lrucache
    - milena
    - mtl
    - network
    - ordered-containers
    - persistent
    - persistent-template
    - postgresql-typed
    - prometheus-client
    - retry
    - scientific
    - strato-model
    - template-haskell
    - time
    - unliftio
    - unliftio-core
    - unordered-containers

executables:
  slipstream:
    source-dirs: exec_src/
    main: Main.hs
    dependencies:
      - base
      - blockapps-bloc22-server
      - blockapps-init
      - hflags
      - http-client
      - milena
      - persistent-postgresql
      - postgresql-simple
      - postgresql-typed
      - resource-pool
      - servant-client
      - slipstream
      - template-haskell
      - wai-middleware-prometheus
      - warp

tests:
  slipstream-test:
    main: Main.hs
    source-dirs: tests/
    dependencies:
      - base
      - aeson
      - aeson-qq
      - base16-bytestring
      - blockapps-solidity
      - bytestring
      - classy-prelude
      - conduit
      - containers
      - hflags
      - hspec
      - hspec-expectations-lifted
      - persistent
      - persistent-sqlite
      - QuickCheck
      - slipstream
      - strato-model
      - text
      - time
      - vector
