name: slipstream
version: 0.1.0.0
synopsis: Solidity datatypes
description: Solidity datatypes
homepage: https://github.com/blockapps/blockapps-haskell/slipstream
license: BSD3
license-file: LICENSE
copyright: 2016 BlockApps
category: Web

library:
  source-dirs: src/

ghc-options: -Wall -Werror

dependencies:
  - base
  - aeson
  - base16-bytestring
  - lifted-base
  - blockapps-bloc22-api
  - blockapps-bloc22-server
  - blockapps-ethereum
  - blockapps-solidity
  - blockapps-strato-client
  - blockapps-strato-api
  - bytestring
  - conduit
  - conduit-combinators
  - containers
  - data-default
  - hflags
  - hslogger
  - http-client
  - largeword
  - lens
  - logging-effect
  - milena
  - MissingH
  - monad-control
  - mtl
  - network
  - postgresql-simple
  - postgresql-typed
  - resource-pool
  - scientific
  - semigroups
  - servant-client
  - template-haskell
  - text
  - time
  - transformers-base
  - transformers
  - unordered-containers
  - vector

executables:
  slipstream:
    source-dirs: exec_src/
    main: Main.hs
    dependencies:
      - base
      - hflags
      - milena
      - monad-control
      - mtl
      - slipstream
      - time

tests:
  slipstream-test:
    main: Test.hs
    source-dirs: tests/
    dependencies:
      - base >=4 && < 5
      - aeson
      - base16-bytestring
      - bytestring
      - containers
      - hspec
      - largeword
      - parsec
      - QuickCheck
      - raw-strings-qq
      - slipstream
      - text
