name: slipstream
version: 0.1.0.0
synopsis: Solidity datatypes
description: Solidity datatypes
homepage: https://github.com/blockapps/blockapps-haskell/slipstream
copyright: 2016 BlockApps
category: Web


ghc-options: -Wall -Werror -rtsopts

dependencies:
  - base
  - bytestring
  - common-log
  - hflags
  - kafka-monad
  - raw-strings-qq
  - resourcet
  - semigroups
  - sql-monad
  - text
  - transformers

library:
  source-dirs: src/
  dependencies: 
    - aeson
    - binary
    - bloc-sql-monad
    - bloc2
    - blockapps-data
    - blockapps-datadefs
    - blockapps-mpdbs
    - blockapps-solidity
    - blockapps-util
    - bloomfilter
    - classy-prelude
    - conduit
    - containers
    - core-api-monad
    - core-api2
    - cross-monitoring
    - deepseq
    - extra
    - lens
    - lifted-base
    - lrucache
    - milena
    - monad-alter
    - monad-control
    - mtl
    - network
    - ordered-containers
    - persistent
    - persistent-template
    - postgresql-typed
    - prometheus-client
    - QuickCheck
    - retry
    - solid-vm
    - scientific
    - source-tools
    - strato-model
    - template-haskell
    - time
    - unliftio
    - unliftio-core
    - unordered-containers
    - vm-tools

executables:
  slipstream:
    source-dirs: exec_src/
    main: Main.hs
    dependencies:
      - base
      - bloc-sql-monad
      - bloc2
      - blockapps-init
      - cache
      - clock
      - hflags
      - http-client
      - milena
      - persistent-postgresql
      - postgresql-simple
      - postgresql-typed
      - resource-pool
      - servant-client
      - slipstream
      - template-haskell
      - wai-middleware-prometheus
      - warp

tests:
  slipstream-test:
    main: Main.hs
    source-dirs: tests/
    dependencies:
      - base
      - aeson
      - aeson-qq
      - base16-bytestring
      - blockapps-solidity
      - bytestring
      - classy-prelude
      - conduit
      - containers
      - hflags
      - hspec
      - hspec-expectations-lifted
      - persistent
      - persistent-sqlite
      - QuickCheck
      - slipstream
      - strato-model
      - text
      - time
      - unliftio
      - vector
