name: solid-vm-fuzzer
license: Apache-2.0

dependencies:
  - base

library:
  source-dirs: src/
  exposed-modules:
    - SolidVM.Solidity.Fuzzer
    - SolidVM.Solidity.Fuzzer.Types
    - SolidVM.Solidity.SourceTools
  ghc-options: -Wall -O2
  dependencies:
  - aeson
  - blockapps-data
  - bytestring
  - common-log
  - containers
  - debugger
  - exceptions
  - lens
  - monad-alter
  - QuickCheck
  - servant-server
  - solid-vm
  - solid-vm-compiler
  - solid-vm-model
  - solid-vm-static-analysis
  - source-tools
  - strato-model
  - text
  - transformers
  - unliftio
  - vm-tools

executables:
  solid-vm-cli:
    source-dirs: exec_src
    main: Main.hs
    other-modules: []
    dependencies:
      - aeson
      - bytestring
      - containers
      - exceptions
      - hflags
      - monad-alter
      - solid-vm-compiler
      - solid-vm-fuzzer
      - solid-vm-model
      - solid-vm-static-analysis
      - source-tools
      - strato-model
      - text
      - unliftio
      - vm-tools
    ghc-options: -Wall -O2 -threaded -rtsopts -fprof-auto 

tests:
  solid-vm-spec:
    source-dirs: tests/
    main: Main.hs
    ghc-options: -Wall -O2 -dynamic
    dependencies:
      - hflags
      - hspec
      - raw-strings-qq
      - solid-vm-fuzzer
      - source-tools
      - text
      - vm-tools
