ARG STACK_RESOLVER

# BASE_IMAGE may be removed after bloc is moved to resolver LTS version
ARG BASE_IMAGE

FROM ${BASE_IMAGE:-fpco/stack-build:${STACK_RESOLVER}}

RUN apt-get update && \
    apt-get -y --allow-unauthenticated install autoconf libtool libblas-dev liblapack-dev libsodium-dev cmake && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean
