resolver: lts-10.10 #also duplicated in docker section below
compiler: ghc-8.0.2
compiler-check: newer-minor
packages:
- bloc/bloc22/api
- bloc/bloc22/client
- bloc/bloc22/server
- bloc/exe
- ethereum
- slipstream
- solidity
- strato/api
- strato/client
- strato/server
- vault-wrapper/api
- vault-wrapper/client
- location:
    git: https://github.com/echatav/secp256k1-haskell/
    commit: c27236f93ba2af4da0865558e2dedf2d8643cd8c
  extra-dep: true
- location:
    git: https://github.com/echatav/servant-aeson-specs/
    commit: cedbf002b0d5855c17dc91de97e966ee339604fa
  extra-dep: true
- location:
    git: https://github.com/iostat/relapse
    commit: 2b25839d1b75508301adde293b8c6ef8591ef00a
  extra-dep: true
extra-deps:
  - hflags-0.4.3
  - ordered-containers-0.1.0
  - saltine-0.0.0.4
  - servant-options-0.1.0.0
  - parsec3-numbers-0.1.0
  - milena-0.5.2.1
flags: {}

ghc-options:
  "$locals": -Wall -Werror

extra-package-dbs: []

extra-include-dirs:
- /usr/local/include

extra-lib-dirs:
- /usr/local/lib

docker:
  enable: true
  image: "stack-bloc-buildbase:lts-10.10"
  set-user: true
  run-args: ["--ulimit=nofile=60000"]
