name:                solidVM2022

dependencies:
- base
- blockapps-datadefs
- bytestring
- containers
- format
- ghc
- lens
- mtl
- parsec
- solid-vm-model
- solid-vm-parser
- strato-model
- text
- vm-tools

library:
  source-dirs: src
