name: strato-genesis
version: 0.0.1
build-type: Simple
author: Jamshid
license-file:  LICENSE
maintainer:    jamshidnh@gmail.com
synopsis: A tool to setup the DBs for a Strato instance
category:      Data Structures
license: Apache-2.0
description: A tool to setup the DBs for a Strato instance
github: blockapps/strato-platform/core-strato/strato-genesis

dependencies:
  - aeson
  - base
  - base16-bytestring
  - binary
  - blockapps-data
  - blockapps-haskoin
  - blockapps-milena
  - blockapps-mpdbs
  - blockapps-util
  - bytestring
  - containers
  - crypto-api
  - cryptonite
  - csv
  - directory
  - entropy
  - ethereum-rlp
  - format
  - json-stream
  - leveldb-haskell
  - memory
  - merkle-patricia-db
  - merkle-patricia-db
  - persistent-postgresql
  - resourcet
  - scientific
  - split
  - strato-conf
  - strato-model
  - strato-redis-blockdb
  - strato-statediff
  - text
  - time
  - transformers
  - unordered-containers
  - utf8-string
  - vector
  - yaml

library:
    source-dirs: src/
    ghc-options: -Wall -O2

executables:
  generate-genesis:
    source-dirs: exec_src/
    main: Main.hs
    other-modules: []
    dependencies:
      - aeson-extra
      - aeson-pretty
      - hflags
      - strato-genesis

  genesis-setup:
    source-dirs: exec_src/
    main: GenesisSetup.hs
    other-modules: []
    dependencies:
      - strato-genesis
      - hflags


tests:
  strato-genesis-test:
    source-dirs: test
    main: Main.hs
    dependencies:
      - aeson-diff
      - hspec
      - strato-genesis
    ghc-options: -Wall
