name: solid-vm-model

dependencies:
  - base

default-extensions:
  - BangPatterns
  - OverloadedStrings

library:
  source-dirs: src/
  dependencies:
  - attoparsec
  - base16-bytestring
  - binary
  - bytestring
  - deepseq
  - ethereum-rlp
  - format
  - hashable
  - scientific
  - strato-model
  - text
  - utf8-string

tests:
  storage-test:
    source-dirs: test/
    main: StorageTest.hs
    other-modules: []
    dependencies:
      - bytestring
      - ethereum-rlp
      - hspec
      - solid-vm-model
      - strato-model
      - unliftio

benchmarks:
  storage-bench:
    source-dirs: bench/
    main: StorageBench.hs
    other-modules: []
    dependencies:
      - binary
      - bytestring
      - cereal
      - criterion
      - ethereum-rlp
      - solid-vm-model
      - strato-model
