name: solid-vm-model

default-extensions:
  - BangPatterns
  - DeriveAnyClass
  - DeriveGeneric
  - OverloadedStrings

library:
  source-dirs: src/
  dependencies:
    - aeson
    - base
    - base16-bytestring
    - bytestring
    - deepseq
    - strato-model
    - text
