// Command blockroots generates a fixture for
// EthLightClient.anchorBlockHeaderViaBlockRoots -- the path for deposits
// inside the 8192-slot window, roughly the last 27 hours.
//
// The 19-level branch is the inner block_roots vector (13) plus the
// BeaconState container (6). The proof is verified against the ATTESTED state
// root, which the sync committee signs, so the committee, attested header and
// beacon state are ours -- forging a branch under a root you did not build is
// a sha256 preimage. The target is the real finalized header, so its execution
// payload, execution branch, block number and receipts root stay real.
//
// Committee and participation match cmd/historical, so the aggregate, the
// commitment and any proof over them are shared between the two fixtures.
//
//	go run ./cmd/blockroots > ../contracts/tests/Bridge/BlockRootsFixture.sol
package main

import (
	"fmt"
	"os"

	"github.com/blockapps/strato/app/circuits/sszfix"
)

// Shared with cmd/historical so both fixtures have the same committee.
const (
	committeeSeed = "strato-blockroots-fixture-key"
	committeeSize = 512
	signers       = 470
)

func main() {
	// Real values, from EthLightClientAnchor.test.sol.
	const (
		finalizedSlot     = uint64(10182848)
		finalizedProposer = uint64(5)
		attestedSlot      = uint64(10182912)
		attestedProposer  = uint64(1446)
	)
	finalizedParent := sszfix.MustRoot("909769c65157a1f487b063a82330e1ce3d5f5a36360e34969ced0a2a00532ac7")
	finalizedState := sszfix.MustRoot("e982a9f9a9ec24790ac1172fbf7458ee48caabc8c9b2f1eb2adef4cce6618b09")
	finalizedBody := sszfix.MustRoot("71dda7e512b87a1cbedb14a58d771c20c15dca9eb84ea162f337b44678325d28")
	attestedParent := sszfix.MustRoot("900fee03dc258712f7da869abffcd8a6858a2e1f38cd304243bfab9ec90e4d5f")
	attestedBody := sszfix.MustRoot("29f9342b67f92ba2fe69832cafe1a5d384cbd0f68a4808c863a0d47636e23d49")
	gvr := sszfix.MustRoot("d8ea171f3c94aea21ebc42a1ed61052acf3f9209c00e4efbaaddac09ed9b8078")
	forkVersion := [4]byte{0x90, 0x00, 0x00, 0x75}
	domainSync := [4]byte{0x07, 0x00, 0x00, 0x00}

	target := sszfix.HeaderRoot(finalizedSlot, finalizedProposer, finalizedParent, finalizedState, finalizedBody)

	// block_roots: Vector[Root, 8192], field 5 of the state container.
	blockRoots := make([]sszfix.Root, 8192)
	blockRoots[finalizedSlot%8192] = target
	brLevels := sszfix.Merkleize(blockRoots)

	// finalized_checkpoint{epoch, root} at field 20; index 41 = (20<<1)|1.
	cpLevels := sszfix.Merkleize([]sszfix.Root{sszfix.Uint64Leaf(finalizedSlot / 32), target})

	state := make([]sszfix.Root, 64)
	state[5] = sszfix.RootOf(brLevels)
	state[20] = sszfix.RootOf(cpLevels)
	stLevels := sszfix.Merkleize(state)
	attestedState := sszfix.RootOf(stLevels)

	blockRootsBranch := append(sszfix.BranchOf(brLevels, int(finalizedSlot%8192)), sszfix.BranchOf(stLevels, 5)...)
	finalityBranch := append(sszfix.BranchOf(cpLevels, 1), sszfix.BranchOf(stLevels, 20)...)

	attestedRoot := sszfix.HeaderRoot(attestedSlot, attestedProposer, attestedParent, attestedState, attestedBody)
	signingRoot := sszfix.H2(attestedRoot, sszfix.ComputeDomain(domainSync, forkVersion, gvr))
	c, err := sszfix.SignCommittee(committeeSeed, committeeSize, signers, signingRoot)
	if err != nil {
		panic(err)
	}

	w := os.Stdout
	p := func(format string, a ...any) { fmt.Fprintf(w, format, a...) }
	p("// GENERATED by app/circuits/cmd/blockroots -- do not edit by hand.\n//\n")
	p("// Fixture for EthLightClient.anchorBlockHeaderViaBlockRoots.\n//\n")
	p("// The block_roots proof is verified against the ATTESTED state root, which\n")
	p("// the sync committee signs, so this cannot reuse the real Sepolia attested\n")
	p("// header -- forging a branch under a root you did not build is a sha256\n")
	p("// preimage. The committee, attested header and beacon state are synthetic;\n")
	p("// the target is the real finalized header and its execution payload,\n")
	p("// execution branch, block number and receipts root are the real ones.\n//\n")
	p("// The contract cannot tell: it checks a real BLS aggregate over a real SSZ\n")
	p("// signing root, a real finality branch and a real 19-level block_roots\n")
	p("// branch. Only the keys behind them are ours.\n\n")
	p("library BlockRootsFixture {\n")
	p("    function attestedStateRoot() internal pure returns (bytes32) { return bytes32(hex\"%x\"); }\n", attestedState)
	p("    function targetBeaconRoot() internal pure returns (bytes32) { return bytes32(hex\"%x\"); }\n", target)
	p("    /// aggregate_pubkey of the whole synthetic committee, so a test can\n")
	p("    /// anchor by subtracting the 42 absentees rather than summing 470.\n")
	p("    function committeeAggregate() internal pure returns (bytes) { return hex\"%x\"; }\n\n", c.Aggregate.Bytes())

	p("    function participationBits() internal pure returns (bytes32[2]) {\n        return [\n")
	p("            bytes32(hex\"%x\"),\n            bytes32(hex\"%x\")\n        ];\n    }\n\n", c.Participation[:32], c.Participation[32:])

	sig := c.Signature.Bytes()
	p("    function signature() internal pure returns (bytes32[3]) {\n        return [\n")
	p("            bytes32(hex\"%x\"),\n            bytes32(hex\"%x\"),\n            bytes32(hex\"%x\")\n        ];\n    }\n\n",
		sig[0:32], sig[32:64], sig[64:96])

	emit := func(name string, br []sszfix.Root) {
		p("    function %s() internal pure returns (bytes32[]) {\n", name)
		p("        bytes32[] b = new bytes32[](%d);\n", len(br))
		for i, x := range br {
			p("        b[%d] = bytes32(hex\"%x\");\n", i, x)
		}
		p("        return b;\n    }\n\n")
	}
	emit("blockRootsBranch", blockRootsBranch)
	emit("finalityBranch", finalityBranch)

	p("    function committee() internal pure returns (bytes[]) {\n")
	p("        bytes[] pks = new bytes[](%d);\n", committeeSize)
	for i := range c.Pubkeys {
		p("        pks[%d] = hex\"%x\";\n", i, c.Pubkeys[i].Bytes())
	}
	p("        return pks;\n    }\n}\n")
}
