// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

/// @title Poseidon2 cross-language interop
/// @notice The committee commitment that EthLightClient computes on-chain and
///         the aggregation circuit re-derives in gnark must be the same hash,
///         produced by two independent implementations in two languages.
///         Nothing in either build catches a divergence — a mismatch shows up
///         as a proof that simply never verifies.
///
///         Vectors are generated by app/circuits/cmd/fixtures (gnark-crypto
///         ecc/bn254/fr/poseidon2, the default t=2 rF=6 rP=50 instance with a
///         zero-IV Merkle-Damgard wrapper). Regenerate with:
///
///             cd app/circuits && go run ./cmd/fixtures
contract Describe_Poseidon2Interop {

    // ---- poseidon2Compress(l, r): the raw 2-to-1 compression ----

    function it_compress_matches_gnark_on_zero() {
        require(
            poseidon2Compress(0, 0) ==
                18622970401557034651033185129330286139447343337105683528700775943440799145467,
            "compress(0,0) diverges from gnark-crypto"
        );
    }

    function it_compress_matches_gnark_on_small_inputs() {
        require(
            poseidon2Compress(1, 2) ==
                1313337560616139085277676701856612540166622156368305732529371734734451176752,
            "compress(1,2) diverges from gnark-crypto"
        );
        require(
            poseidon2Compress(7, 11) ==
                15215389992259459897428002828881531369930680900727614487496692990206834275749,
            "compress(7,11) diverges from gnark-crypto"
        );
    }

    /// p-1 exercises the canonical-reduction boundary, where an
    /// implementation that reduces lazily would diverge.
    function it_compress_matches_gnark_at_the_field_boundary() {
        require(
            poseidon2Compress(
                21888242871839275222246405745257275088548364400416034343698204186575808495616,
                1
            ) == 19719945374042619411379458596652736093199459828909764448819187031467967223907,
            "compress(p-1,1) diverges from gnark-crypto"
        );
    }

    // ---- poseidon2(x...): Merkle-Damgard over the compression ----

    function it_md_hash_of_one_element_matches_gnark() {
        require(
            poseidon2(1) ==
                12157562999385135173166708316607836110878334226144932937475223226141207470306,
            "hash([1]) diverges from gnark-crypto"
        );
    }

    /// A zero-IV Merkle-Damgard makes hash([0]) and compress(0,0) the same
    /// value; if this pair ever disagrees the IV or the chaining changed.
    function it_md_hash_absorbs_from_a_zero_iv() {
        require(poseidon2(0) == poseidon2Compress(0, 0), "MD chaining is not zero-IV");
    }

    function it_md_hash_of_two_elements_matches_gnark() {
        require(
            poseidon2(1, 2) ==
                4443443265955166080716935670700081889283598504231460571509928329665379862364,
            "hash([1,2]) diverges from gnark-crypto"
        );
    }

    function it_md_hash_of_four_elements_matches_gnark() {
        require(
            poseidon2(1, 2, 3, 4) ==
                5402851635480781446751342346210135834226319730389436212287936564310709451361,
            "hash([1,2,3,4]) diverges from gnark-crypto"
        );
    }

    /// EthLightClient.buildCommitteeCommitment absorbs a chunk of the
    /// committee per transaction, folding poseidon2Compress over a carried
    /// state. That is only the same digest as one poseidon2(x...) call if the
    /// MD chaining is exactly compress-from-zero, so pin the equivalence.
    function it_chunked_absorption_equals_a_single_hash() {
        uint256 state = 0;
        state = poseidon2Compress(state, 1);
        state = poseidon2Compress(state, 2);
        state = poseidon2Compress(state, 3);
        state = poseidon2Compress(state, 4);
        require(state == poseidon2(1, 2, 3, 4), "chunked absorption diverges from poseidon2()");
    }

    /// Wide, unstructured limbs — the shape the committee commitment actually
    /// absorbs, since each pubkey coordinate packs into ~192-bit halves.
    function it_md_hash_of_wide_limbs_matches_gnark() {
        require(
            poseidon2(12345678901234567890, 98765432109876543210, 5, 0, 7) ==
                9022727992505385583689961137337476072371225159412576759504452306643555729303,
            "hash(wide limbs) diverges from gnark-crypto"
        );
    }
}
