apiDebug: true
timeout: 600000
VM: SolidVM
configDirPath: 
deployFilename: config/docker.deploy.yaml
orgDeployFilename: 
serverHost: 
serverIP: 
orgName: blockapps

nodes:
  - id: 0
    label: 
    url: http://nginx:80
    port: 30303
    oauth:
      appTokenCookieName: asset_framework_session
      appTokenCookieMaxAge: 7776000000
      openIdDiscoveryUrl: >-
        https://keycloak.blockapps.net/auth/realms/mercata-testnet/.well-known/openid-configuration
      clientId: localhost
      clientSecret: 21092de3-a166-4ae3-90ca-4d5cc09d8dba
      scope: email openid
      serviceOAuthFlow: 
      redirectUri: http://localhost/api/v1/authentication/callback
      logoutRedirectUri: http://localhost
      tokenField: 
      tokenUsernameProperty: 
      tokenUsernamePropertyServiceFlow: 
