apiDebug: true
timeout: 600000
VM: SolidVM
configDirPath: ./config
deployFilename: localhost.deploy.yaml
orgDeployFilename: org.deploy.yaml
serverHost: 
serverIP: 
orgName: blockapps
bootMembersFilename: boot_members.yaml
cacheNonce: true
dockerized: false

nodes:
  - id: 0
    label: mercata-testnet-node1
    url: https://node1.mercata-testnet2.blockapps.net
    port: 30303
    oauth:
      appTokenCookieName: asset_framework_session
      appTokenCookieMaxAge: 7776000000
      openIdDiscoveryUrl: >-
        https://keycloak.blockapps.net/auth/realms/mercata-testnet2/.well-known/openid-configuration
      clientId: localhost
      clientSecret: ab85bdf6-9715-441f-b3e5-c8be53c3a55e
      scope: email openid
      serviceOAuthFlow: 
      redirectUri: http://localhost/api/v1/authentication/callback
      logoutRedirectUri: http://localhost
      tokenField: 
      tokenUsernameProperty: 
      tokenUsernamePropertyServiceFlow: 
