{-# LANGUAGE
      RecordWildCards
#-}

-- |
-- Module: Parser
-- Description: The Solidity source parser function
-- Maintainer: Ryan Reich <ryan@blockapps.net>
module BlockApps.Solidity.Parse.Parser (parseXabi) where

import           Text.Parsec                          hiding (parse)

import qualified Data.Map                             as Map
import           Data.Text                            (Text)
import qualified Data.Text                            as Text
import           Data.Traversable

import           BlockApps.Solidity.Parse.File
import           BlockApps.Solidity.Parse.ParserTypes

import           BlockApps.Solidity.Xabi              (Xabi(..), xabiTypes)
import           BlockApps.Solidity.Xabi.Def

-- | The 'parseSolidity' function parses a single Solidity source string (with
-- a given name) into a Haskell data type.  Parser errors are generated by
-- 'Parsec'.
parseXabi :: FileName -> String -> Either String [(Text, Xabi)]
parseXabi filename input = do
  xabis <- showError $ runParser solidityFile "" filename input
  let inheritanceFullXabis = map (fmap $ addInheritedDeclarations inheritanceFullXabis) xabis

  xabis' <-
    for inheritanceFullXabis $ \(name, xabiOrError) -> do
      case xabiOrError of
       Left e -> Left e
       Right v -> return (name, v)
     
  return $ map (fmap $ addContractNames $ map (Text.unpack . fst) xabis') xabis'

addContractNames::[String]->Xabi->Xabi
addContractNames contracts xabi =
  xabi{xabiTypes=xabiTypes xabi `Map.union` Map.fromList (map ((\x -> (x, Contract 0)) . Text.pack) contracts)}

addInheritedDeclarations::[(Text, Either String Xabi)]->(Xabi, [Text])->Either String Xabi
addInheritedDeclarations _ (xabi, []) = Right xabi
addInheritedDeclarations xabisWithInheritedDeclarations (xabi, parent:_) = do
  parentXabi <-
    errorMsg ("Contract was inherited from a non existant contract: " ++ Text.unpack parent)
    $ lookup parent xabisWithInheritedDeclarations
  fmap (xabiMerge xabi) parentXabi


xabiMerge::Xabi->Xabi->Xabi
xabiMerge x y =
  Xabi{
    xabiFuncs=xabiFuncs x `Map.union` xabiFuncs y,
    xabiConstr=xabiConstr x,
    xabiVars=xabiVars x `Map.union` xabiVars y,
    xabiTypes=xabiTypes x `Map.union` xabiTypes y
    }



------------
-- Some error conversion functions

showError::Show a=>Either a b->Either String b
showError (Left e) = Left $ show e
showError (Right x) = Right x

errorMsg::String->Maybe a->Either String a
errorMsg msg Nothing = Left msg
errorMsg _ (Just x) = Right x
