{-# LANGUAGE
      RecordWildCards
#-}

-- |
-- Module: Parser
-- Description: The Solidity source parser function
-- Maintainer: Ryan Reich <ryan@blockapps.net>
module BlockApps.Solidity.Parse.Parser (parseXabi) where

import           Text.Parsec                          hiding (parse)

import           Control.Arrow
import qualified Data.Map                             as Map
import           Data.Text                            (Text)
import qualified Data.Text                            as Text
import           Data.Traversable

import           BlockApps.Solidity.Parse.File
import           BlockApps.Solidity.Parse.ParserTypes

import           BlockApps.Solidity.Xabi              (Xabi(..), xabiTypes)
import           BlockApps.Solidity.Xabi.Def

-- | The 'parseSolidity' function parses a single Solidity source string (with
-- a given name) into a Haskell data type.  Parser errors are generated by
-- 'Parsec'.
parseXabi :: FileName -> String -> Either String [(Text, Xabi)]
parseXabi filename input = do
  xabis <- left show $ runParser solidityFile "" filename input
  let inheritanceFullXabis = map (addInheritedDeclarations inheritanceFullXabis) xabis

  xabis' <-
    for inheritanceFullXabis $ \(name, xabiOrError) -> do
      case xabiOrError of
       Left e -> Left e
       Right v -> return (name, v)
     
  return $ map (fmap $ addContractNames $ map (Text.unpack . fst) xabis') xabis'

addContractNames::[String]->Xabi->Xabi
addContractNames contracts xabi =
  xabi{xabiTypes=xabiTypes xabi `Map.union` Map.fromList (map ((\x -> (x, Contract 0)) . Text.pack) contracts)}

addInheritedDeclarations::[(Text, Either String Xabi)]->(Text, Xabi, [Text])->(Text, Either String Xabi)
addInheritedDeclarations _ (name, xabi, []) =
  (name, Right xabi)
addInheritedDeclarations xabisWithInheritedDeclarations (name, xabi, (parent:_)) =
  case lookup parent xabisWithInheritedDeclarations of
   Nothing -> (name, Left "error")
   Just (Left e) -> (name, Left e)
   Just (Right parentXabi) ->
     (name, Right $ xabiMerge xabi parentXabi)


xabiMerge::Xabi->Xabi->Xabi
xabiMerge x y =
  Xabi{
    xabiFuncs=xabiFuncs x `Map.union` xabiFuncs y,
    xabiConstr=xabiConstr x,
    xabiVars=xabiVars x `Map.union` xabiVars y,
    xabiTypes=xabiTypes x `Map.union` xabiTypes y
    }
