#!/usr/bin/env sh
set -x
set -e

export OAUTH_CLIENT_ID=tt-localhost
export OAUTH_CLIENT_SECRET=10352ea6-f286-47cf-936c-2cb7ce6c1c39
export OAUTH_DISCOVERY_URL=https://keycloak.blockapps.net/auth/realms/track-and-trace/.well-known/openid-configuration
export OAUTH_ENABLED=true
export OAUTH_TEMPORARY_MIXED_AUTH=true

reload.sh
docker exec -i strato_vault-wrapper_1 curl --silent -H "Content-Type: application/json" -d '"mixed"' localhost:8000/strato/v2.3/password || true
