flags: {}
packages:
- blockapps-milena
- strato-conf/
- miner-ethash/
- merkle-patricia-db/
- blockapps-data/
- ecrecover/
- fast-ecrecover/
- strato-init/
- ethereum-discovery/
- ethereum-encryption/
- ethereum-vm/
- blockapps-util/
- strato-api/
- blockapps-tools/
- strato-genesis/
- strato-adit/
- strato-index/
- strato-sequencer/
- ethereum-jsonrpc/
- strato-model/
- strato-p2p/
- strato-redis-blockdb/
- strato-statediff/
- test-suite/
- blockapps-haskoin/
- statsdi/
- ethereum-rlp/
- blockstanbul/
extra-deps:
- Crypto-4.2.5.1
- bytestring-arbitrary-0.1.1
- containers-0.5.11.0 # temp re-added, will remove
- dequeue-0.1.12
- diagrams-html5-1.4.1
- global-lock-0.1
- hflags-0.4.3
- json-rpc-client-0.2.5.0
- json-rpc-server-0.2.6.0
- monadIO-0.11.0.0
- murmur3-1.0.3
- nibblestring-0.0.3
- ordered-containers-0.1.0
- pbkdf-1.1.1.1
- yesod-raml-0.2.0
- static-canvas-0.2.0.3
- monad-logger-0.3.28.1 # temp re-added, will remove
- ether-0.5.1.0 # temp re-added, will remove
- random-bytestring-0.1.3.1
- pcg-random-0.1.3.5

resolver: lts-10.10 #also duplicated in docker section below
compiler: ghc-8.0.2 # temp re-added, will remove - @see https://blockapps.atlassian.net/browse/STRATO-1086
compiler-check: newer-minor
extra-include-dirs:
- /usr/local/include

extra-lib-dirs:
- /usr/local/lib

ghc-options:
  "$locals": -Wall -Werror
  strato-api: -Wall -Werror -fno-warn-orphans
  strato-p2p: -Wall -Werror  -XMonoLocalBinds
  strato-conf: -Wall -Werror -fno-warn-inline-rule-shadowing
  blockapps-haskoin: -Wall -Werror -fno-warn-overflowed-literals

docker:
  enable: true
  image: "stack-core-buildbase:lts-10.10"
  set-user: true
  run-args: ["--ulimit=nofile=60000"]
