flags: {}
packages:
- blockapps-milena
- strato-conf/
- miner-ethash/
- merkle-patricia-db/
- blockapps-data/
- ecrecover/
- fast-ecrecover/
- strato-init/
- ethereum-discovery/
- ethereum-encryption/
- ethereum-vm/
- blockapps-util/
- strato-api/
- blockapps-tools/
- strato-genesis/
- strato-adit/
- strato-index/
- strato-sequencer/
- ethereum-jsonrpc/
- strato-model/
- strato-p2p/
- strato-redis-blockdb/
- strato-statediff/
- test-suite/
- blockapps-haskoin/
- statsdi/
- ethereum-rlp/
extra-deps:
- Crypto-4.2.5.1
- bytestring-arbitrary-0.1.1
- containers-0.5.11.0
- dequeue-0.1.12
- diagrams-html5-1.4
- global-lock-0.1
- hflags-0.4.3
- json-rpc-client-0.2.5.0
- json-rpc-server-0.2.6.0
- monadIO-0.11.0.0
- murmur3-1.0.3
- nibblestring-0.0.3
- ordered-containers-0.1.0
- pbkdf-1.1.1.1
- yesod-raml-0.2.0
- optparse-applicative-0.13.2.0
- static-canvas-0.2.0.3
- category-extras-1.0.2
- monad-logger-0.3.28.1
- ether-0.4.2.0
- tasty-quickcheck-0.8.4
- temporary-1.3

resolver: lts-10.10 #also duplicated in docker section below
compiler: ghc-8.0.2
compiler-check: newer-minor
extra-include-dirs:
- /usr/local/include

extra-lib-dirs:
- /usr/local/lib

ghc-options:
  "$locals": -Wall -Werror
  strato-api: -Wall -Werror -fno-warn-orphans
  strato-conf: -Wall -Werror -fno-warn-inline-rule-shadowing

docker:
  enable: true
  image: "stack-core-buildbase:lts-10.10"
  set-user: true
  run-args: ["--ulimit=nofile=60000"]
