name:                ethereum-jsonrpc
version:             0.1.0.0
synopsis:            Initial project template from stack
description:         Please see README.md
category:            Web
build-type:          Simple

executables:
  ethereum-jsonrpc:
    source-dirs:      src
    main:             Main.hs
    dependencies:
      - base
      - aeson
      - base16-bytestring
      - binary
      - blaze-builder
      - blockapps-data
      - blockapps-datadefs
      - blockDB
      - core-api2
      - bytestring
      - case-insensitive
      - containers
      - format
      - http-client
      - http-types
      - json-rpc-server
      - kafka-monad
      - milena
      - mtl
      - seqevents
      - servant
      - servant-client
      - strato-conf
      - strato-model
      - strato-p2p
      - text
      - time
      - vector
      - wai
      - warp
