import { TraceLot } from "./types";

export interface ProtocolEventConfig {
  eventName: string;
  source?: TraceLot["source"];
  matchingStatus: "enabled" | "candidate" | "anchor" | "ignored";
  reason: string;
}

const EXPLICIT_PROTOCOL_EVENT_CONFIGS: ProtocolEventConfig[] = [
  {
    eventName: "Swap",
    source: "swap",
    matchingStatus: "enabled",
    reason: "Swap output transfers map to tokenOut/amountOut and trace back to tokenIn/amountIn.",
  },
  {
    eventName: "MetalMinted",
    source: "metal_mint",
    matchingStatus: "enabled",
    reason: "Metal output transfers map to metalToken/metalAmount and trace back to payToken/payAmount.",
  },
  {
    eventName: "DirectPSMMinted",
    source: "psm",
    matchingStatus: "enabled",
    reason: "PSM mint transfers map to mintAmount and trace back to againstToken/depositAmount.",
  },
  {
    eventName: "USDSTMinted",
    source: "cdp_mint",
    matchingStatus: "enabled",
    reason: "USDST mint transfers can be detected, but CDP collateral tracing remains unknown until verified.",
  },
  {
    eventName: "RewardsClaimed",
    source: "rewards",
    matchingStatus: "enabled",
    reason: "Rewards transfers can be detected, but reward source provenance remains unknown until verified.",
  },
  {
    eventName: "DepositCompleted",
    matchingStatus: "anchor",
    reason: "Standard bridge deposit trust anchor.",
  },
  {
    eventName: "NativeDepositCompleted",
    matchingStatus: "anchor",
    reason: "Native bridge deposit trust anchor.",
  },
  {
    eventName: "WithdrawalPayout",
    matchingStatus: "candidate",
    reason: "Yield vault withdrawal output event observed in debug dumps.",
  },
  {
    eventName: "WithdrawalPaidImmediately",
    matchingStatus: "candidate",
    reason: "Yield vault instant withdrawal output event observed in contracts/debug dumps.",
  },
  {
    eventName: "WithdrawalClaimed",
    matchingStatus: "candidate",
    reason: "Yield vault queued withdrawal claim event.",
  },
  {
    eventName: "WithdrawalCanceled",
    matchingStatus: "candidate",
    reason: "Yield vault withdrawal cancellation can explain share/accounting movements.",
  },
  {
    eventName: "QueueProcessed",
    matchingStatus: "candidate",
    reason: "Yield vault queue processing can explain withdrawal payout batches.",
  },
  {
    eventName: "RemoveLiquidity",
    matchingStatus: "candidate",
    reason: "Pool liquidity removal can produce user token outputs.",
  },
  {
    eventName: "RemoveLiquidityOne",
    matchingStatus: "candidate",
    reason: "Stable pool single-asset liquidity removal can produce user token outputs.",
  },
  {
    eventName: "RemoveLiquidityImbalance",
    matchingStatus: "candidate",
    reason: "Stable pool imbalanced liquidity removal can produce user token outputs.",
  },
  {
    eventName: "AddLiquidity",
    matchingStatus: "candidate",
    reason: "Liquidity additions can mint LP token outputs.",
  },
  {
    eventName: "Skim",
    matchingStatus: "candidate",
    reason: "Pool skim can produce token outputs to an address.",
  },
  {
    eventName: "TokensSwept",
    matchingStatus: "candidate",
    reason: "Auction sweep can move token proceeds.",
  },
  {
    eventName: "CurrencySwept",
    matchingStatus: "candidate",
    reason: "Auction sweep can move currency proceeds.",
  },
  {
    eventName: "BidExited",
    matchingStatus: "candidate",
    reason: "Auction bid exit can refund currency.",
  },
  {
    eventName: "TokensClaimed",
    matchingStatus: "candidate",
    reason: "Auction token claim can produce token outputs.",
  },
  {
    eventName: "TokensReceived",
    matchingStatus: "candidate",
    reason: "Auction token receipt can explain auction inventory movements.",
  },
  {
    eventName: "Deposited",
    matchingStatus: "candidate",
    reason: "Lending/vault deposit event can mint receipt/share token outputs.",
  },
  {
    eventName: "DepositedOnBehalfOf",
    matchingStatus: "candidate",
    reason: "Lending deposit-on-behalf event can mint receipt token outputs.",
  },
  {
    eventName: "Withdrawn",
    matchingStatus: "candidate",
    reason: "Lending/CDP/vault withdraw event can produce asset outputs.",
  },
  {
    eventName: "Deposit",
    matchingStatus: "candidate",
    reason: "ERC4626 deposit event can mint share token outputs.",
  },
  {
    eventName: "Withdraw",
    matchingStatus: "candidate",
    reason: "ERC4626 withdraw event can produce asset outputs.",
  },
  {
    eventName: "CollateralDeposited",
    matchingStatus: "candidate",
    reason: "CDP collateral movement affects provenance but output semantics need verification.",
  },
  {
    eventName: "CollateralWithdrawn",
    matchingStatus: "candidate",
    reason: "CDP collateral withdrawal can produce asset outputs.",
  },
  {
    eventName: "CollateralSeized",
    matchingStatus: "candidate",
    reason: "CDP liquidation can move collateral to liquidators.",
  },
  {
    eventName: "CollateralAdded",
    matchingStatus: "candidate",
    reason: "CDP engine collateral event observed in debug dumps.",
  },
  {
    eventName: "CollateralRemoved",
    matchingStatus: "candidate",
    reason: "CDP engine collateral event observed in debug dumps.",
  },
  {
    eventName: "SuppliedCollateral",
    matchingStatus: "candidate",
    reason: "CDP collateral supply event observed in debug dumps.",
  },
  {
    eventName: "WithdrawnCollateral",
    matchingStatus: "candidate",
    reason: "CDP collateral withdrawal event observed in debug dumps.",
  },
  {
    eventName: "USDSTBurned",
    matchingStatus: "candidate",
    reason: "CDP debt repayment event affects provenance of burned/moved USDST.",
  },
  {
    eventName: "LiquidationExecuted",
    matchingStatus: "candidate",
    reason: "CDP liquidation can move collateral and repay debt.",
  },
  {
    eventName: "JuniorNoteClaimed",
    matchingStatus: "candidate",
    reason: "Junior note claim can produce USDST payout.",
  },
  {
    eventName: "Borrowed",
    matchingStatus: "candidate",
    reason: "Lending borrow can produce asset outputs.",
  },
  {
    eventName: "Repaid",
    matchingStatus: "candidate",
    reason: "Lending repayment can explain transfers into protocol contracts.",
  },
  {
    eventName: "Liquidated",
    matchingStatus: "candidate",
    reason: "Lending liquidation can move collateral and repay debt.",
  },
  {
    eventName: "Staked",
    matchingStatus: "candidate",
    reason: "Safety module staking can mint receipt/share outputs.",
  },
  {
    eventName: "Redeemed",
    matchingStatus: "candidate",
    reason: "Safety module or escrow redemption can produce token outputs.",
  },
  {
    eventName: "ShortfallCovered",
    matchingStatus: "candidate",
    reason: "Safety module shortfall coverage can move assets.",
  },
  {
    eventName: "DirectPayoutApplied",
    matchingStatus: "candidate",
    reason: "Rewards direct payout can explain reward transfers.",
  },
  {
    eventName: "Locked",
    matchingStatus: "candidate",
    reason: "Native custody lock event can explain native bridge withdrawals.",
  },
  {
    eventName: "Unlocked",
    matchingStatus: "candidate",
    reason: "Native custody unlock event can explain native bridge deposits.",
  },
  {
    eventName: "AutoSaved",
    matchingStatus: "candidate",
    reason: "Bridge deposit auto-save transforms freshly minted funds into lending receipt assets.",
  },
  {
    eventName: "AutoForged",
    matchingStatus: "candidate",
    reason: "Bridge deposit auto-forge transforms freshly minted funds into metal assets.",
  },
  {
    eventName: "TopUpRequested",
    matchingStatus: "candidate",
    reason: "Credit card top-up creates withdrawal request and related escrow transfer flow.",
  },
  {
    eventName: "WithdrawalRequested",
    matchingStatus: "candidate",
    reason: "Bridge and vault withdrawal request events can explain escrow/request transfers.",
  },
  {
    eventName: "WithdrawalCompleted",
    matchingStatus: "candidate",
    reason: "Bridge withdrawal completion can explain burn/finalization transfers.",
  },
  {
    eventName: "WithdrawalAborted",
    matchingStatus: "candidate",
    reason: "Bridge withdrawal abort can explain refund transfers.",
  },
  {
    eventName: "NativeWithdrawalCompleted",
    matchingStatus: "candidate",
    reason: "Native withdrawal completion can explain finalized native bridge transfers.",
  },
  {
    eventName: "NativeWithdrawalAborted",
    matchingStatus: "candidate",
    reason: "Native withdrawal abort can explain refund/unlock transfers.",
  },
  {
    eventName: "NativeDepositInitiated",
    matchingStatus: "candidate",
    reason: "Native deposit initiation can explain bridge custody flow.",
  },
  {
    eventName: "NativeDepositPendingReview",
    matchingStatus: "candidate",
    reason: "Native deposit review can explain bridge custody flow.",
  },
  {
    eventName: "NativeDepositAborted",
    matchingStatus: "candidate",
    reason: "Native deposit abort can explain bridge custody flow.",
  },
  {
    eventName: "NativeWithdrawalPending",
    matchingStatus: "candidate",
    reason: "Native withdrawal pending state can explain bridge custody flow.",
  },
  {
    eventName: "NativeWithdrawalProposalRecorded",
    matchingStatus: "candidate",
    reason: "Native withdrawal proposal event can explain bridge custody flow.",
  },
  {
    eventName: "DepositInitiated",
    matchingStatus: "candidate",
    reason: "Bridge deposit initiation can explain pre-confirmation bridge flow.",
  },
  {
    eventName: "DepositPendingReview",
    matchingStatus: "candidate",
    reason: "Bridge deposit review can explain pre-confirmation bridge flow.",
  },
  {
    eventName: "DepositAborted",
    matchingStatus: "candidate",
    reason: "Bridge deposit abort can explain bridge refund/cancellation flow.",
  },
  {
    eventName: "WithdrawalPending",
    matchingStatus: "candidate",
    reason: "Bridge withdrawal pending can explain custody flow.",
  },
  {
    eventName: "BurnRequested",
    matchingStatus: "candidate",
    reason: "PSM burn request can explain redemption flow.",
  },
  {
    eventName: "BurnCompleted",
    matchingStatus: "candidate",
    reason: "PSM burn completion can produce redeem token outputs.",
  },
  {
    eventName: "BurnCancelled",
    matchingStatus: "candidate",
    reason: "PSM burn cancellation can explain returned funds.",
  },
  {
    eventName: "Cancelled",
    matchingStatus: "candidate",
    reason: "Escrow cancellation can return token balances.",
  },
  {
    eventName: "CapitalReturned",
    matchingStatus: "candidate",
    reason: "Yield vault strategy return can move assets back to vault.",
  },
  {
    eventName: "CapitalDeployed",
    matchingStatus: "candidate",
    reason: "Yield vault strategy deployment can move assets to strategy.",
  },
  {
    eventName: "StrategyLossReported",
    matchingStatus: "candidate",
    reason: "Yield vault loss reporting can affect provenance accounting.",
  },
  {
    eventName: "BadDebtRealized",
    matchingStatus: "candidate",
    reason: "CDP bad debt realization can affect provenance accounting.",
  },
  {
    eventName: "BadDebtRepaid",
    matchingStatus: "candidate",
    reason: "CDP bad debt repayment can move USDST.",
  },
  {
    eventName: "BadDebtCovered",
    matchingStatus: "candidate",
    reason: "Lending bad debt coverage can move assets.",
  },
  {
    eventName: "BadDebtRecognized",
    matchingStatus: "candidate",
    reason: "Lending bad debt recognition can affect provenance accounting.",
  },
  {
    eventName: "BadDebtWrittenOffFromReserves",
    matchingStatus: "candidate",
    reason: "Lending bad debt reserve write-off can affect provenance accounting.",
  },
  {
    eventName: "DepositorHaircutApplied",
    matchingStatus: "candidate",
    reason: "Lending depositor haircut can affect claimable asset provenance.",
  },
  {
    eventName: "IssueExecuted",
    matchingStatus: "ignored",
    reason: "Governance/admin execution metadata; useful context but not a direct provenance edge.",
  },
  {
    eventName: "Approval",
    matchingStatus: "ignored",
    reason: "Allowance metadata, not value movement.",
  },
  {
    eventName: "OwnershipTransferred",
    matchingStatus: "ignored",
    reason: "Admin metadata, not value movement.",
  },
  {
    eventName: "PauseToggled",
    matchingStatus: "ignored",
    reason: "Admin metadata, not value movement.",
  },
  {
    eventName: "StatusChanged",
    matchingStatus: "ignored",
    reason: "Token metadata, not value movement.",
  },
  {
    eventName: "Sync",
    matchingStatus: "ignored",
    reason: "Pool balance sync metadata.",
  },
  {
    eventName: "Accrued",
    matchingStatus: "ignored",
    reason: "Interest accounting metadata.",
  },
  {
    eventName: "IndexAccrued",
    matchingStatus: "ignored",
    reason: "Interest index metadata.",
  },
  {
    eventName: "ExchangeRateUpdated",
    matchingStatus: "ignored",
    reason: "Rate metadata, not value movement.",
  },
  {
    eventName: "VaultUpdated",
    matchingStatus: "ignored",
    reason: "CDP vault state metadata.",
  },
  {
    eventName: "FeesRouted",
    matchingStatus: "ignored",
    reason: "Fee accounting context, not direct user provenance.",
  },
  {
    eventName: "CollateralConfigured",
    matchingStatus: "ignored",
    reason: "Configuration metadata.",
  },
  {
    eventName: "AssetConfigured",
    matchingStatus: "ignored",
    reason: "Configuration metadata.",
  },
  {
    eventName: "PriceUpdated",
    matchingStatus: "ignored",
    reason: "Oracle metadata.",
  },
  {
    eventName: "BatchPricesUpdated",
    matchingStatus: "ignored",
    reason: "Oracle metadata.",
  },
  {
    eventName: "RebaseFactorsUpdated",
    matchingStatus: "ignored",
    reason: "Oracle metadata.",
  },
  {
    eventName: "ExchangeRatesUpdated",
    matchingStatus: "ignored",
    reason: "Oracle metadata.",
  },
  {
    eventName: "NewPool",
    matchingStatus: "ignored",
    reason: "Factory metadata.",
  },
  {
    eventName: "NewVault",
    matchingStatus: "ignored",
    reason: "Factory metadata.",
  },
  {
    eventName: "TokenCreated",
    matchingStatus: "ignored",
    reason: "Factory metadata.",
  },
  {
    eventName: "IssueCreated",
    matchingStatus: "ignored",
    reason: "Governance metadata.",
  },
  {
    eventName: "IssueVoted",
    matchingStatus: "ignored",
    reason: "Governance metadata.",
  },
  {
    eventName: "IssueDismissed",
    matchingStatus: "ignored",
    reason: "Governance metadata.",
  },
  {
    eventName: "ActionProcessed",
    matchingStatus: "ignored",
    reason: "Rewards processing metadata.",
  },
  {
    eventName: "ActionFailed",
    matchingStatus: "ignored",
    reason: "Rewards processing metadata.",
  },
  {
    eventName: "Transfer",
    matchingStatus: "ignored",
    reason: "Base event already fetched separately as funding evidence.",
  },
  {
    eventName: "RewardNotified",
    matchingStatus: "ignored",
    reason: "Reward accounting metadata until source semantics are implemented.",
  },
  {
    eventName: "VaultInitialized",
    matchingStatus: "ignored",
    reason: "Initialization metadata.",
  },
  {
    eventName: "Initialized",
    matchingStatus: "ignored",
    reason: "Initialization metadata.",
  },
];

const IGNORED_CONTRACT_EVENT_NAMES = [
  "AccessManagerIgnoredSet",
  "AccountAuthorized",
  "ActivityAdded",
  "ActivityIndexUpdated",
  "ActivityMinAmountUpdated",
  "ActivityNameUpdated",
  "ActivityWeightUpdated",
  "AdminChanged",
  "AdminRegistryUpdated",
  "ApplyNewFee",
  "ApprovalForAll",
  "AssetAdded",
  "AssetRemoved",
  "AssetToggled",
  "AssetUpdated",
  "AuctionStepRecorded",
  "AuthorityUpdated",
  "AuthorizationUsed",
  "AuthorizedOperator",
  "BaseDelaySet",
  "BatchMetadataUpdate",
  "BeaconUpgraded",
  "BidSubmitted",
  "BotExecutorUpdated",
  "BridgeUpdated",
  "BurnConfigSet",
  "BurnPauseSet",
  "Burned",
  "CallExecuted",
  "CallSalt",
  "CallScheduled",
  "CancelTransaction",
  "CardAdded",
  "CardRemoved",
  "CardUpdated",
  "ChainToggled",
  "ChainUpdated",
  "CheckpointUpdated",
  "ClearingPriceUpdated",
  "CoinAdded",
  "ComponentsUpdated",
  "ConsecutiveTransfer",
  "ContractURIUpdated",
  "CrosschainBurn",
  "CrosschainMint",
  "CustodyVaultUpdated",
  "DebtCeilingsUpdated",
  "DefaultAdminDelayChangeCanceled",
  "DefaultAdminDelayChangeScheduled",
  "DefaultAdminTransferCanceled",
  "DefaultAdminTransferScheduled",
  "DefaultBotExecutorUpdated",
  "DelegateChanged",
  "DelegateVotesChanged",
  "DepositActionRequested",
  "EIP712DomainChanged",
  "ERC20Released",
  "ERC6909DecimalsUpdated",
  "ERC6909NameUpdated",
  "ERC6909SymbolUpdated",
  "ERC7579TryExecuteFail",
  "ERC7913SignerAdded",
  "ERC7913SignerRemoved",
  "ERC7913SignerWeightChanged",
  "ERC7913ThresholdSet",
  "EmergencyBlockRollback",
  "EmissionRateUpdated",
  "EndpointsSynced",
  "EtherReleased",
  "ExecuteTransaction",
  "ExecutedForwardRequest",
  "FeeBpsUpdated",
  "FeeCollectorSet",
  "FeeCollectorUpdated",
  "FeeCollectorsUpdated",
  "FeeParametersUpdated",
  "FeeToReserveBpsSet",
  "HotWithdrawalThresholdUpdated",
  "InstantWithdrawalDelayUpdated",
  "InterfaceImplementerSet",
  "JuniorIndexSynced",
  "JuniorNoteClosed",
  "JuniorNoteCreated",
  "JuniorParamsSet",
  "LastProcessedBlockUpdated",
  "LateQuorumVoteExtensionSet",
  "LendingRegistryUpdated",
  "ManagerChanged",
  "MaxBatchSizeUpdated",
  "MercataBridgeUpdated",
  "MetadataUpdate",
  "MetalConfigUpdated",
  "MetalForgeUpdated",
  "MetalToggled",
  "MinDelayChange",
  "MinIdleBpsUpdated",
  "MinReserveUpdated",
  "MintCapUpdated",
  "MintConfigSet",
  "MintPauseSet",
  "Minted",
  "ModuleInstalled",
  "ModuleUninstalled",
  "NativeAssetUpdated",
  "NativeBridgeGuardianUpdated",
  "NativeBridgeOperatorUpdated",
  "NativeCustodyVaultGuardianUpdated",
  "NativeWithdrawalRequested",
  "NewAdmin",
  "NewDelay",
  "NewPendingAdmin",
  "NextActiveTickUpdated",
  "OperationCanceled",
  "OperationExecuted",
  "OperationScheduled",
  "OperatorSet",
  "OperatorUpdated",
  "OracleUpdated",
  "OverrideVoteCast",
  "OwnershipTransferStarted",
  "ParamsUpdated",
  "Paused",
  "PausedGlobal",
  "PayTokenUpdated",
  "PoolFeeParametersUpdated",
  "PoolsMerged",
  "PoolsMigrated",
  "PriceOracleUpdated",
  "ProposalCanceled",
  "ProposalCreated",
  "ProposalExecuted",
  "ProposalExtended",
  "ProposalGuardianSet",
  "ProposalQueued",
  "ProposalThresholdSet",
  "QueueTransaction",
  "QuorumNumeratorUpdated",
  "RampA",
  "RegistryUpdated",
  "ReservesSweptSafety",
  "ReservesSweptTreasury",
  "RevokedOperator",
  "RoleAdminChanged",
  "RoleGrantDelayChanged",
  "RoleGranted",
  "RoleGuardianChanged",
  "RoleLabel",
  "RoleRevoked",
  "SeasonAnnouncement",
  "Sent",
  "SetNewMATime",
  "SourceContractUpdated",
  "StopRampA",
  "StrategyApprovalUpdated",
  "SuperQuorumNumeratorUpdated",
  "TargetAdminDelayUpdated",
  "TargetClosed",
  "TargetFunctionRoleUpdated",
  "TickInitialized",
  "TimelockChange",
  "TokenFactoryUpdated",
  "TokensMigrated",
  "TokensRegistered",
  "TokensUpdated",
  "TransferBatch",
  "TransferSingle",
  "Transferred",
  "TreasurerUpdated",
  "URI",
  "USDSTAddressUpdated",
  "Unpaused",
  "UnstakeCooldown",
  "Upgraded",
  "UsdstUpdated",
  "UserStakeUpdated",
  "VaultsMigrated",
  "VoteCast",
  "VoteCastWithParams",
  "VoteReduced",
  "VotingDelaySet",
  "VotingPeriodSet",
];

export const PROTOCOL_EVENT_CONFIGS: ProtocolEventConfig[] = [
  ...EXPLICIT_PROTOCOL_EVENT_CONFIGS,
  ...IGNORED_CONTRACT_EVENT_NAMES.map((eventName) => ({
    eventName,
    matchingStatus: "ignored" as const,
    reason: "Contract event accounted for; not currently a direct provenance edge.",
  })),
];

export const PROTOCOL_ASSOCIATION_EVENT_NAMES = PROTOCOL_EVENT_CONFIGS
  .filter((config) => config.matchingStatus !== "ignored")
  .map((config) => config.eventName);

export const ENABLED_PROTOCOL_OUTPUT_EVENT_NAMES = PROTOCOL_EVENT_CONFIGS
  .filter((config) => config.matchingStatus === "enabled")
  .map((config) => config.eventName);

export const sourceForProtocolEvent = (
  eventName: string,
): TraceLot["source"] | undefined =>
  PROTOCOL_EVENT_CONFIGS.find((config) => config.eventName === eventName)?.source;
