name: blockapps-strato-client
version: 0.1.0.0
synopsis: Strato microservice
description: Strato microservice
homepage: https://github.com/blockapps/blockapps-haskell/blockapps-strato
author: Eitan Chatav
maintainer: eitan@blockapps.net
copyright: 2016 BlockApps
category: Web
build-type: Simple

ghc-options: -Wall

dependencies:
  - base
  - blockapps-strato-api
  - servant-client

library:
  source-dirs: src/
  dependencies:
  - servant

tests:
  blockapps-strato-client-test:
    source-dirs: test/
    main: Spec.hs
    dependencies:
      - QuickCheck
      - blockapps-strato-client
      - generic-random
      - hspec
      - http-client
