name: blockapps-strato-client
version: 0.1.0.0
synopsis: Strato microservice
description: Strato microservice
homepage: https://github.com/blockapps/blockapps-haskell/blockapps-strato
license-file: LICENSE
author: Eitan Chatav
maintainer: eitan@blockapps.net
copyright: 2016 BlockApps
category: Web
build-type: Simple

ghc-options: -Wall

dependencies:
  - base
  - blockapps-ethereum
  - blockapps-strato-api
  - binary
  - aeson
  - aeson-casing
  - generic-random
  - http-api-data
  - http-client
  - QuickCheck
  - quickcheck-instances
  - servant
  - servant-client
  - servant-docs
  - text
  - time
  - unordered-containers

library:
  source-dirs: src/

tests:
  blockapps-strato-client-test:
    source-dirs: test/
    main: Spec.hs
    dependencies:
      - blockapps-strato-client
      - hspec
