name: blockstanbul
 

dependencies:
  - base


library:
  source-dirs: src/
  ghc-options: -Wall -Werror
  dependencies:
  - QuickCheck
  - aeson
  - base16-bytestring
  - binary
  - blockapps-data
  - blockapps-datadefs
  - bytestring
  - common-log
  - conduit
  - containers
  - cross-monitoring
  - cryptonite
  - data-default
  - deepseq
  - ethereum-rlp
  - extra
  - format
  - generic-arbitrary
  - http-client
  - labeled-error
  - lens
  - mtl
  - prometheus-client
  - servant-client
  - servant-server
  - strato-model
  - text
  - transformers
  - unliftio
  - monad-alter
  - x509-certs

tests:
  blockstanbul-test:
    main: Main.hs
    source-dirs: test/
    ghc-options: -Wall -Werror -dynamic
    dependencies:
      - QuickCheck
      - aeson
      - base16-bytestring
      - blockapps-data
      - blockapps-datadefs
      - blockstanbul
      - bytestring
      - common-log
      - containers
      - cryptonite
      - ethereum-rlp
      - hflags
      - hspec
      - hspec-expectations-lifted
      - labeled-error
      - lens
      - monad-alter
      - mtl
      - strato-model
      - time
      - transformers
      - x509-certs


benchmarks:
  one-node:
    source-dirs: bench/
    ghc-options: -Wall -Werror -dynamic
    main: OneNode.hs
    dependencies:
      - blockstanbul
      - transformers
