#!/usr/bin/env bash
set -e

Green='\033[0;32m'
Red='\033[0;31m'
Yellow='\033[0;33m'
BYellow='\033[1;33m'
NC='\033[0m'

function outputLogo {
echo "

███████ ████████ ██████   █████  ████████  ██████      ██   ██ ██  ██████  ██   ██ ██     ██  █████  ██    ██ 
██         ██    ██   ██ ██   ██    ██    ██    ██     ██   ██ ██ ██       ██   ██ ██     ██ ██   ██  ██  ██  
███████    ██    ██████  ███████    ██    ██    ██     ███████ ██ ██   ███ ███████ ██  █  ██ ███████   ████   
     ██    ██    ██   ██ ██   ██    ██    ██    ██     ██   ██ ██ ██    ██ ██   ██ ██ ███ ██ ██   ██    ██    
███████    ██    ██   ██ ██   ██    ██     ██████      ██   ██ ██  ██████  ██   ██  ███ ███  ██   ██    ██    

"
}

function help {
  outputLogo
  echo -e "${BYellow}Highway server run script${NC}
Kickstart a highway server.

${Yellow}Optional flags:${NC}
The entrypoints are mutually exclusive.
--help|-h       - this help.
--down          - remove highway server containers and leave all volumes intact.
--wipe          - stop and remove highway server containers and wipe out volumes.
--pull          - pull images used in docker-compose.highway.yml.

${Yellow}Environment variables:${NC}
HTTP_PORT           - (default: 80) Port for HTTP traffic listener.
HTTPS_PORT          - (default: 443) Port for HTTPS traffic listener; only used with ssl=true.
OAUTH_DISCOVERY_URL         - (required) OAuth provider's OpenID Connect discovery URL.
OAUTH_CLIENT_ID             - (required) Client ID of OAuth provider valid for the future STRATO url (http(s)://<NODE_HOST>:<HTTP_PORT/HTTPS_PORT>).
OAUTH_CLIENT_SECRET         - (required) Client Secret for the client ID specified.
OAUTH_SCOPE                 - (default: 'openid email profile') The openid scopes used in session cookie verification
ssl                 - (default: false) [true|false] to run the node with SSL/TLS.
sslCertFileType     - (default: pem) [pem|crt] the SSL certificate type and file extension (should be accessible at ./ssl/certs/server.<sslCertFileType> at deploy time.)
"
}

function wipe {
  echo -e "${Yellow}Removing Highway containers and wiping out volumes${NC}"
  ${docker_compose} down -vt 0 --remove-orphans
}

function down {
  echo -e "${Yellow}Removing Highway containers${NC}"
  ${docker_compose} down --remove-orphans
}

function stop {
  echo -e "${Yellow}Gently stopping Highway containers${NC}"
  ${docker_compose} stop
}

function start {
  echo -e "${Yellow}Starting the earlier stopped Highway containers${NC}"
  ${docker_compose} start
}

function pullImages {
  ${docker_compose} pull
}

if ! docker ps &> /dev/null
then
    echo -e "${Red}Error: docker is required: https://www.docker.com/ . If you have it installed - you may need to execute as super user${NC}"
    exit 1
fi

if ! docker compose version  &> /dev/null && ! docker-compose -v  &> /dev/null
then
    echo -e "${Red}Error: Docker Compose is required: https://docs.docker.com/compose/install/"
    exit 2
else
  if ! docker compose version &> /dev/null
  then
    docker_compose="docker-compose -p highway -f docker-compose.highway.yml --log-level ERROR"
  else
    docker_compose="docker -l error compose -p highway -f docker-compose.highway.yml"
  fi
fi

while [ ${#} -gt 0 ]; do
  case "${1}" in
  --help|-h)
    help
    exit 0
    ;;
  --down)
    down
    exit 0
    ;;
  --wipe)
    wipe
    exit 0
    ;;
  --pull)
    pullImages
    exit 0
    ;;
  *)
    echo -e "${Red}Unknown flag ${1} provided, please check --help. Exit.${NC}"
    exit 5
    ;;
  esac
  shift 1
done

outputLogo

if [ "$ssl" = true ] ; then
  http_protocol=https
  main_port=${HTTPS_PORT}
else
  http_protocol=http
  main_port=${HTTP_PORT}
fi
export sslCertFileType=${sslCertFileType:-pem}

echo "" && echo "*** Common Config ***"
echo "HTTP_PORT: $HTTP_PORT"
echo "HTTPS_PORT: $HTTPS_PORT"
echo "ssl: $ssl"
echo "sslCertFileType: $sslCertFileType"

if [ ! -f docker-compose.highway.yml ]
then
  echo -e "${Red}docker-compose.highway.yml not found. Please download the docker-compose.highway.yml first or build the platform (see README.md).${NC}"
  exit 3
else
  echo -e "${Yellow}Using the docker-compose.highway.yml${NC}"
fi

# COMPOSE FILE PRE-PROCESSING
function cleanup {
  rm docker-compose-highway-temp.yml
}
trap cleanup EXIT

if [ "$ssl" != true ]; then
  sed -n '/#TAG_REMOVE_WHEN_NO_SSL/!p' docker-compose.highway.yml > docker-compose-highway-temp.yml
else
  if [ "$HTTPS_PORT" != "443" ]; then
    sed -n '/#TAG_REMOVE_WHEN_SSL_CUSTOM_HTTPS_PORT/!p' docker-compose.highway.yml > docker-compose-highway-temp.yml
  else
    cp docker-compose.highway.yml docker-compose-highway-temp.yml
  fi
fi
# END OF COMPOSE FILE PRE-PROCESSING

${docker_compose} -f docker-compose-highway-temp.yml up -d --remove-orphans
until curl --silent --output /dev/null --fail --insecure --location "${http_protocol}://localhost:${main_port}/_ping" ; do sleep 0.5; done

echo -e "\n${Green}STRATO Highway Server has awoken. Check ${http_protocol}://your.hostname:${main_port}${NC}"
