contract EchoError {

  enum EchoError {
    NULL,
    UID_EMPTY,
    UID_EXISTS,
    TRADER_ID_EMPTY,
    COUNTER_PARTY_ID_EMPTY,
    BUY_PARTY_EMPTY,
    SELL_PARTY_EMPTY,
    TRADER_ID_EQUAL_COUNTER_PARTY_ID,
    DEAL_DATE_EMPTY,
    BEGIN_FLOW_DATE_EMPTY,
    PIPELINE_EBB_EMPTY,
    RECEIPT_LOCATION_EMPTY,
    VOLUME_EMPTY,
    END_FLOW_DATE_EMPTY,
    SOURCE_EMPTY,
    SINK_EMPTY,
    VOLUME_UNIT_EMPTY,
    MAX_DEAL_PRICE_REACHED,
    INVALID_PRICE_INDEX
  }
}
