contract GasDealEvent {
    enum GasDealEvent {
        NULL,
        TRADER_PRICE,
        COUNTER_PARTY_PRICE,
        PRICE_MATCH,
        PRICE_MISMATCH,
        DISSAG_MATCH,
        DISSAG_MISMATCH,
        VOLUME_MATCH,
        VOLUME_MISMATCH,
        TRADER_CUTS_APPROVAL,
        COUNTER_CUTS_APPROVAL,
        COUNTER_CUTS_APPROVAL_REJECTED,
        TRADER_CUTS_RESUPPLY,
        COUNTER_CUTS_RESUPPLY,
        COUNTER_CUTS_RESUPPLY_REJECTED,
        RESUPPLY_COMPLETED,
        EXCEPTION_CUTS_BOOKOUT,
        BOOKOUT_COMPLETED,
        EXCEPTION_CUTS_ADJUSTMENT,
        ADJUSTMENT_COMPLETED,
        SETTLEMENT,
        PAID_OUT,
        DEAL_REJECTED,
        MAX
    }
}
