gocd.slack {
  login = "go"
  password = ""
  server-host = "http://blockapps-cd.eastus.cloudapp.azure.com:8153/"
  api-server-host = "http://localhost:8153/"
  webhookUrl = "https://hooks.slack.com/services/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"

  # optional fields
  channel = "#ci"
  slackDisplayName = "gocd-slack-bot"
  slackUserIconURL = "http://i.imgur.com/DmtLHWb.png"

  pipelines = [{
    name = ".*"
    stage = ".*"
    state = "all"
  }]
}
