name: logserver
synopsis: static file server for /var/lib/strato/logs
github: blockapps/strato-platform/core-strato/logserver

executables:
  logserver:
    source-dirs: exec_src/
    main: LogServer.hs
    dependencies:
      - aeson-pretty
      - base
      - blaze-builder
      - blockapps-init
      - containers
      - hflags
      - text
      - wai-app-static
      - wai-extra
      - wai-middleware-prometheus
      - warp
