name:                strato-conf
version:             0.1.0.0
license:             Apache-2.0
license-file:        LICENSE
author:              Jamshid
category:            Web
build-type:          Simple

library:
  source-dirs:      src
  dependencies:
    - base
    - bytestring
    - directory
    - filepath
    - hflags
    - network
    - yaml
    - postgresql-simple
    - containers
    - ethereum-encryption
    - file-embed
    - crypto-random
    - crypto-pubkey
    - milena
    - mtl
    - transformers
    - hedis
    - swagger2
  when:
  - condition: flag(embed)
    cpp-options: -DEMBED
flags:
  embed:
    description: "Use TH to embed runtime config files"
    manual: true
    default: false