apiVersion: apps/v1
kind: Deployment
metadata:
  name: strato-platform
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: strato-platform
  template:
    metadata:
      labels:
        app: strato-platform
    spec:
      containers:
      - image: <REPO_URL>smd:<VERSION>
        name: smd
        env:
        - name: NODE_NAME
          value: "localhost"
        - name: NODE_HOST
          value: "localhost"
      - image: <REPO_URL>apex:<VERSION>
        name: apex
        env:
        - name: NODE_HOST
          value: "localhost"
        - name: postgres_host
          value: "localhost"
        - name: postgres_password
          value: "api"
        - name: postgres_port
          value: "5432"
        - name: postgres_user
          value: "postgres"
        - name: prometheusHost
          value: "localhost:9090"
        - name: STRATO_HOSTNAME
          value: "localhost"
        - name: STRATO_PORT_API
        - name: STRATO_PORT_VAULT_PROXY
      - image: redis:3.2
        name: redis
        command: ["redis-server"]
        args: ["--appendonly", "yes"]
        volumeMounts:
          - mountPath: /data
            name: redis-data
      - image: <REPO_URL>strato:<VERSION>
        name: strato
        ports:
          - containerPort: 30303
          - containerPort: 30303
            protocol: UDP
        env:
        - name: blockstanbul
          value: "true"
        - name: gasOn
          value: "false"
        - name: generateKey
          value: "true"
        - name: genesis
          value: "gettingStarted"
        - name: isAdmin
          value: "false"
        - name: isRootNode
          value: "false"
        - name: kafkaHost
          value: "localhost"
        - name: kafkaPort
          value: "9092"
        - name: mineBlocks
          value: "false"
        - name: network
          value: "blockappsnet"
        - name: networkID
          value: ""
        - name: postgres_host
          value: "localhost"
        - name: postgres_password
          value: "api"
        - name: postgres_port
          value: "5432"
        - name: postgres_slipstream_db
          value: "cirrus"
        - name: postgres_user
          value: "postgres"
        - name: redisHost
          value: "localhost"
        - name: redisPort
          value: "6379"
        - name: splitinit
          value: "true"
        - name: stratoHost
          value: "localhost:3000"
        - name: VAULT_URL
          value: ""
        - name: zkHost
          value: "localhost"
        - name: indexEVM
          value: "false"
        - name: USE_OLD_STRATO_API
          value : "true"
        - name: validatorBehavior
          value: "true"
        volumeMounts:
          - mountPath: /var/lib/strato
            name: strato-data
      - image: <REPO_URL>postgrest:<VERSION>
        name: postgrest
        env:
        - name: blocHost
          value: "localhost:3000"
        - name: PG_ENV_POSTGRES_DB
          value: "cirrus"
        - name: PG_ENV_POSTGRES_HOST
          value: "localhost"
        - name: PG_ENV_POSTGRES_PASSWORD
          value: "api"
        - name: PG_ENV_POSTGRES_USER
          value: "postgres"
        - name: PG_PORT_5432_TCP_PORT
          value: "5432"
        - name: POSTGREST_LOG_LEVEL
          value: "error"
      - image: postgres:9.6
        name: postgres
        command: ["docker-entrypoint.sh"]
        args: ["-c", "max_connections=300", "-c", "shared_buffers=512MB"]
        env:
        - name: POSTGRES_PASSWORD
          value: "api"
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
          - mountPath: /var/lib/postgresql/data/
            name: postgres-data
      - image: <REPO_URL>nginx:<VERSION>
        name: nginx
        ports:
          - containerPort: 80
          - containerPort: 443
        env:
        - name: APEX_HOST
          value: "localhost:3009"
        - name: blockstanbul
          value: "true"
        - name: DOCS_HOST
          value: "localhost:8080"
        - name: OAUTH_CLIENT_ID
          value: "dev"
        - name: OAUTH_CLIENT_SECRET
          value: "d5e67b8c-4fbf-42c6-a8d9-29a4dd13575f"
        - name: OAUTH_DISCOVERY_URL
          value: "https://keycloak.blockapps.net/auth/realms/strato-devel/.well-known/openid-configuration"
        - name: OAUTH_JWT_USERNAME_PROPERTY
          value: ""
        - name: OAUTH_SCOPE
          value: ""
        - name: POSTGREST_HOST
          value: "localhost:3001"
        - name: PROMETHEUS_HOST
          value: "localhost:9090"
        - name: SMD_HOST
          value: "localhost:3002"
        - name: STRATO_HOSTNAME
          value: "localhost"
        - name: STRATO_PORT_API
          value: "3000"
        - name: STRATO_PORT_API2
          value: "3001"
        - name: STRATO_PORT_LOGS
          value: "7065"
        - name: STRATO_PORT_BLOCKSTANBUL_VOTE
          value: "8050"
        - name: VAULT_WRAPPER_HOST
          value: "localhost:8000"
      - image: wurstmeister/zookeeper:3.4.6
        name: zookeeper
        volumeMounts:
          - mountPath: /opt/zookeeper-3.4.6/data
            name: zookeeper-data
      - image: wurstmeister/kafka:1.1.0
        name: kafka
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "localhost"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "localhost:2181"
        - name: KAFKA_DELETE_TOPIC_ENABLE
          value: "true"
        - name: KAFKA_LOG_CLEANER_ENABLE
          value: "false"
        - name: KAFKA_LOG_DIRS
          value: "/kafka/kafka-logs"
        - name: KAFKA_LOG_RETENTION_HOURS
          value: "2147483647"
        - name: KAFKA_OFFSET_METADATA_MAX_BYTES
          value: "1048576"
        - name: KAFKA_OFFSETS_RETENTION_MINUTES
          value: "2147483647"
        - name: KAFKA_MAX_REQUEST_SIZE
          value: "100663296"
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "100663296"
        volumeMounts:
          - mountPath: /kafka
            name: kafka-data
      - image: <REPO_URL>prometheus:<VERSION>
        name: prometheus
        env:
        - name: NODE_HOST
          value: "localhost"
        volumeMounts:
          - mountPath: /prometheus
            name: prometheus-data
      - image: <REPO_URL>vault-wrapper:<VERSION>
        name: vault-wrapper
        env:
        - name: keyStoreCacheTimeout
          value: "60"
        - name: postgres_host
          value: "localhost"
        - name: postgres_password
          value: "api"
        - name: postgres_port
          value: "5432"
        - name: postgres_user
          value: "postgres"
        - name: postgres_vault_wrapper_db
          value: "oauth"
        - name: VAULTWRAPPER_DEBUG
          value: "true"
      - image: swaggerapi/swagger-ui:v3.22.1
        name:  docs
        env:
        - name: API_URL
          value: "/strato-api/eth/v1.2/swagger.json"
      volumes:
        - name: prometheus-data
          hostPath:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-pvc
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
        - name: zookeeper-data
          persistentVolumeClaim:
            claimName: zookeeper-pvc
        - name: strato-data
          persistentVolumeClaim:
            claimName: strato-pvc
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
