apiVersion: v1
kind: PersistentVolume
metadata:
  name: strato-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /strato-data
