apiDebug: false
password: '1234'
timeout: 20000

# WARNING - extra strict syntax
# DO NOT change the nodes order
# node 0 is the default url for all single node api calls
nodes:
  - id: 0
    blocUrl: 'http://rai-dev.centralus.cloudapp.azure.com:8000'
    explorerUrl: 'http://rai-dev.centralus.cloudapp.azure.com:9000'
    stratoUrl: 'http://rai-dev.centralus.cloudapp.azure.com:80'
