name:                blockapps-util
version:             0.1.0.0
license-file:        LICENSE
author:              jamshid
maintainer:          j
build-type:          Simple
license:             Apache-2.0

library:
  source-dirs: src
  dependencies:
    - base
    - aeson
    - binary
    - milena
    - bytestring
    - common-log
    - containers
    - lens
    - monad-alter
    - mtl
    - transformers
    - text
    - unix
    - time
    - strato-model
