{-# LANGUAGE OverloadedStrings #-}

module Blockchain.GenesisBlocks.ProductionGenesisBlock
  ( productionGenesisBlock
  , extraCerts
  , validators
  , admins
  ) where

import BlockApps.X509
import Blockchain.Data.GenesisInfo
import Blockchain.GenesisBlocks.Contracts.CertRegistry
import Blockchain.GenesisBlocks.Contracts.Governance
import Blockchain.Strato.Model.ChainMember
import qualified Data.ByteString as B
import qualified Data.ByteString.Char8 as BC

productionGenesisBlock :: GenesisInfo
productionGenesisBlock  =
  insertMercataGovernanceContract validators admins
  . insertCertRegistryContract extraCerts
  $ defaultGenesisInfo{
        genesisInfoDifficulty=8192,
        genesisInfoLogBloom=B.replicate 256 0,
        genesisInfoGasLimit=22517998136852480000000000000000,
        genesisInfoCoinbase= Org "00000000000000000000" True,
        genesisInfoAccountInfo=[
            NonContract 0xe1fd0d4a52b75a694de8b55528ad48e2e2cf7859 1809251394333065553493296640760748560207343510400633813116524750123642650624
            ]
        }

certStrings :: [[String]]
certStrings =
  [
    ["-----BEGIN CERTIFICATE-----", "MIIBjDCCATCgAwIBAgIRAI52ezCbmgohZ+tZH9+y4iIwDAYIKoZIzj0EAwIFADBI", "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF", "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIzMDIxMDIxMjQzOVoXDTI0MDIx", "MDIxMjQzOVowRjEQMA4GA1UEAwwHTm9kZU9uZTESMBAGA1UECgwJQmxvY2tBcHBz", "MRAwDgYDVQQLDAdNZXJjYXRhMQwwCgYDVQQGDANVU0EwVjAQBgcqhkjOPQIBBgUr", "gQQACgNCAASxFFREq3J1hCDp3sncIbWqsLhO1fcJZ3uem/5He43/zY6aiDOHafbR", "qVjDBjYgWT1QT2tODFb3Kmypj6586S63MAwGCCqGSM49BAMCBQADSAAwRQIhAP1w", "MFMuQmizH7ijmZZ2CNtGUbJwY4SLEJ9cf7hXsru9AiAjw5MfA+ctFRRV0wBdqtOr", "/QnFi7IXykn9Ie+//h59Zg==", "-----END CERTIFICATE-----", "-----BEGIN CERTIFICATE-----", "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI", "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF", "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy", "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU", "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG", "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs", "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8", "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n", "N8txKc8G9R27ZYAUuz15zF0=", "-----END CERTIFICATE-----"],


    ["-----BEGIN CERTIFICATE-----", "MIIBijCCAS+gAwIBAgIQaHFD5KfvdVe135kgfzmevjAMBggqhkjOPQQDAgUAMEgx", "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu", "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjMwMjEwMjEyNDM5WhcNMjQwMjEw", "MjEyNDM5WjBGMRAwDgYDVQQDDAdOb2RlVHdvMRIwEAYDVQQKDAlCbG9ja0FwcHMx", "EDAOBgNVBAsMB01lcmNhdGExDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEGBSuB", "BAAKA0IABMdIOBZnx7tlOygp92l8yFKO1ZutgE4ewVOmPrK/tg0o09Qb4eb96mpQ", "WVld6E7/jAruGV+1VOe6A7yiM8LQR5YwDAYIKoZIzj0EAwIFAANHADBEAiAiKQFe", "bluDLPC3piHrJhayXkpUzGu4QOQCc1NvcXRS7QIgaMfzceY/fq0eeelO2kohndi3", "cScH5vDuTM1KTKJNdj8=", "-----END CERTIFICATE-----", "-----BEGIN CERTIFICATE-----", "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI", "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF", "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy", "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU", "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG", "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs", "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8", "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n", "N8txKc8G9R27ZYAUuz15zF0=", "-----END CERTIFICATE-----"],

    ["-----BEGIN CERTIFICATE-----", "MIIBjDCCATGgAwIBAgIQH3mR/RXtVAXFLEyzBqZuKDAMBggqhkjOPQQDAgUAMEgx", "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu", "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjMwMjEwMjEyNDQwWhcNMjQwMjEw", "MjEyNDQwWjBIMRIwEAYDVQQDDAlOb2RlVGhyZWUxEjAQBgNVBAoMCUJsb2NrQXBw", "czEQMA4GA1UECwwHTWVyY2F0YTEMMAoGA1UEBgwDVVNBMFYwEAYHKoZIzj0CAQYF", "K4EEAAoDQgAEiC5GkH7LUQ1t3SyGltRoVsftcxKS/swq/vfmSp6prNCJdh2z3xVK", "Iww+RyuO0vuDwX9aVaaj/SWCCE2zAah3DzAMBggqhkjOPQQDAgUAA0cAMEQCIB0/", "p0+6sPvf6JRJmA/0OBADPp/oEPZClDJDC3YlefS4AiAXsdZZy1tZay013UEIeS77", "gexIR+gxweapdrHjU6X1sw==", "-----END CERTIFICATE-----", "-----BEGIN CERTIFICATE-----", "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI", "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF", "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy", "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU", "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG", "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs", "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8", "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n", "N8txKc8G9R27ZYAUuz15zF0=", "-----END CERTIFICATE-----"],

    ["-----BEGIN CERTIFICATE-----", "MIIBjTCCATGgAwIBAgIRANY68yBodj4lMstRjyTB+OgwDAYIKoZIzj0EAwIFADBI", "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF", "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIzMDIxMDIxMjQ0MFoXDTI0MDIx", "MDIxMjQ0MFowRzERMA8GA1UEAwwITm9kZUZvdXIxEjAQBgNVBAoMCUJsb2NrQXBw", "czEQMA4GA1UECwwHTWVyY2F0YTEMMAoGA1UEBgwDVVNBMFYwEAYHKoZIzj0CAQYF", "K4EEAAoDQgAES1+vpxI4NN1pCV9PeT3RndqqlvH0LH4BqceVN+4lbxe0PvmJM5Dx", "ahQzaMYQMHckpWd4SOgsJZ3UqW4cUyamDTAMBggqhkjOPQQDAgUAA0gAMEUCIQDl", "rzr+5SGj+BCBldJPAscnp7w8TA1LExoHfAf6Zlxc2QIgA3Il5RXTLuRDFh/IsPYs", "5FNHog9sg9Ae2b0vG0FgISc=", "-----END CERTIFICATE-----", "-----BEGIN CERTIFICATE-----", "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI", "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF", "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy", "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU", "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG", "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs", "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8", "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n", "N8txKc8G9R27ZYAUuz15zF0=", "-----END CERTIFICATE-----"],

    ["-----BEGIN CERTIFICATE-----", "MIIBlTCCATmgAwIBAgIQNLtR7aw6HT2b1aWtMAn8rDAMBggqhkjOPQQDAgUAMEgx", "DjAMBgNVBAMMBUFkbWluMRIwEAYDVQQKDAlCbG9ja0FwcHMxFDASBgNVBAsMC0Vu", "Z2luZWVyaW5nMQwwCgYDVQQGDANVU0EwHhcNMjMwMjEwMjEyNDQxWhcNMjQwMjEw", "MjEyNDQxWjBQMRowGAYDVQQDDBFCbG9ja0FwcHMgU3VwcG9ydDESMBAGA1UECgwJ", "QmxvY2tBcHBzMRAwDgYDVQQLDAdNZXJjYXRhMQwwCgYDVQQGDANVU0EwVjAQBgcq", "hkjOPQIBBgUrgQQACgNCAAS5CIUFfyjuaqy0vmYA8xV1gJxLvl+aebJlmhiSiGtG", "5fal30YxF91UsW60HCgBAYYw3AklvwP9nht9uvLza3FFMAwGCCqGSM49BAMCBQAD", "SAAwRQIhAJj4MF5prxqWC0kcDIdgOpRSLQYmm4jP9gJLKOYbbVDiAiANZS8R6cUw", "Rm5K1h2sVZ9HTaIRIfjBRBKIibp+4iMzFA==", "-----END CERTIFICATE-----", "-----BEGIN CERTIFICATE-----", "MIIBjTCCATKgAwIBAgIRAOPPkVoBp/GnwZGR32jcIjwwDAYIKoZIzj0EAwIFADBI", "MQ4wDAYDVQQDDAVBZG1pbjESMBAGA1UECgwJQmxvY2tBcHBzMRQwEgYDVQQLDAtF", "bmdpbmVlcmluZzEMMAoGA1UEBgwDVVNBMB4XDTIyMDQyMDE3NTcxM1oXDTIzMDQy", "MDE3NTcxM1owSDEOMAwGA1UEAwwFQWRtaW4xEjAQBgNVBAoMCUJsb2NrQXBwczEU", "MBIGA1UECwwLRW5naW5lZXJpbmcxDDAKBgNVBAYMA1VTQTBWMBAGByqGSM49AgEG", "BSuBBAAKA0IABFISUeMfsGYl/sWStpv6cDeNHLwktFAO2dAwe7J8uWZzS8ONyYCs", "9FEQ2NsmDj5IaCAKcRSvVFNwXOAUQDQ1pnUwDAYIKoZIzj0EAwIFAANHADBEAiA8", "R0UERQZbF3qJUt5A0ZFf2ZmB0l/ZPjIvM383gOF3xwIgbxbQ8NLkDEe2mWJ/qa4n", "N8txKc8G9R27ZYAUuz15zF0=", "-----END CERTIFICATE-----"]
  ]

extraCerts :: [X509Certificate]
extraCerts = map (\s -> either (error $ "can't parse cert: " ++ show s) id $ bytesToCert $ BC.pack $ unlines s) certStrings

validators :: [ChainMemberParsedSet]
validators = [
  CommonName "BlockApps" "Mercata" "NodeOne" True,
  CommonName "BlockApps" "Mercata" "NodeTwo" True,
  CommonName "BlockApps" "Mercata" "NodeThree" True,
  CommonName "BlockApps" "Mercata" "NodeFour" True
  ]

admins :: [ChainMemberParsedSet]
admins = [
  CommonName "BlockApps" "Mercata" "Kieren James-Lubin" True,
  CommonName "BlockApps" "Mercata" "Victor Wong" True,
  CommonName "BlockApps" "Mercata" "James Hormuzdiar" True
  ]

