name: blockapps-cirrus-api
version: 0.1.0.0
synopsis: Cirrus microservice
description: Cirrus microservice API definitions
github: blockapps/blockapps-haskell/cirrus/api
license-file: LICENSE
author: Eitan Chatav
maintainer: eitan@blockapps.net
copyright: 2016 BlockApps
category: Web
build-type: Simple

dependencies:
  - base
  - blockapps-solidity
  - aeson
  - QuickCheck
  - servant
  - servant-docs
  - text

ghc-options: -Wall -Werror

library:
  source-dirs: src/
