import assert from "node:assert/strict";
import test from "node:test";
import { Interface } from "ethers";
import { BRIDGE_DIGEST_ABI } from "../config/bridgeAbi";
import { buildBridgeDigestRequest, depositDigestArgs, parseBridgeDigest, matchesSourceWithdrawalAuthorization } from "./authorizationValidation";

const requested = {
  notBefore: "100",
  deadline: "200",
  signerSetVersion: "3",
};

test("requires exact STRATO withdrawal authorization timing and version", () => {
  assert.equal(
    matchesSourceWithdrawalAuthorization({ ...requested }, requested),
    true,
  );
  assert.equal(
    matchesSourceWithdrawalAuthorization(
      { ...requested, deadline: "201" },
      requested,
    ),
    false,
  );
  assert.equal(
    matchesSourceWithdrawalAuthorization(
      { ...requested, signerSetVersion: "4" },
      requested,
    ),
    false,
  );
  assert.equal(matchesSourceWithdrawalAuthorization(undefined, requested), false);
});

// Captured from helium EAB 394d276e3b6109d6c58444653c26996bf3ae3eda on 2026-09-27.
// These are contract outputs, not values generated by the off-chain implementation.
test("reads contract-derived deposit and refund digests without rehashing them", () => {
  assert.equal(parseBridgeDigest({ result: "0x3a9f5e6a40844430f1f61c4b614c965438da99da853e642aba9ca4ad0485800d" }),
    "0x3a9f5e6a40844430f1f61c4b614c965438da99da853e642aba9ca4ad0485800d");
  assert.equal(parseBridgeDigest({ result: "0xbe620f2a844e6b18a371d579311e6e4c28075c0b7292146b43954623110fde7f" }),
    "0xbe620f2a844e6b18a371d579311e6e4c28075c0b7292146b43954623110fde7f");
  for (const response of [undefined, {}, { result: "0x" }, { result: "0xgg" },
    { error: { message: "reverted" }, result: "0x" + "a".repeat(64) }]) {
    assert.throws(() => parseBridgeDigest(response), /Unable to read/);
  }
});

test("digest calls preserve the entire deposit intent and use read-only eth_call", () => {
  const address = "1".repeat(40), other = "2".repeat(40);
  const deposit = { externalChainId: "11155111", depositRouter: address, depositId: "18",
    externalSender: other, externalToken: "0".repeat(40), externalTokenAmount: "120000000000000000",
    externalBlockHash: "0x" + "cd".repeat(32), externalLogIndex: 0,
    externalTxHash: "ab".repeat(32), stratoRecipient: other, stratoToken: address,
    action: "4", actionToken: other, minFinalOut: "37701879348969019" };
  const request = buildBridgeDigestRequest(address, "getDepositSettlementDigest", depositDigestArgs(deposit));
  assert.equal(request.method, "eth_call");
  assert.equal(request.params[1], "latest");
  const call = request.params[0] as { to: string; data: string };
  assert.equal(call.to, "0x" + address);
  const decoded = new Interface(BRIDGE_DIGEST_ABI).decodeFunctionData("getDepositSettlementDigest", call.data);
  assert.deepEqual(Array.from(decoded, String), ["11155111", "0x" + address, "18", "0x" + other,
    "0x" + "0".repeat(40), "120000000000000000", "0x" + deposit.externalTxHash,
    "0x" + other, "0x" + address, "4", "0x" + other, "37701879348969019"]);
  const refund = buildBridgeDigestRequest(address, "getWithdrawalRefundDigest", ["900719925474099312345"]);
  assert.equal((refund.params[0] as { data: string }).data,
    "0x49a7c4f5" + BigInt("900719925474099312345").toString(16).padStart(64, "0"));
  assert.throws(() => buildBridgeDigestRequest(address, "refundWithdrawal", ["1"]));
});
