name: blockapps-data
version: 0.0.1
build-type: Simple
author: Jamshid
maintainer: jamshidnh@gmail.com
synopsis: A Haskell version of an Ethereum client
category: Data Structures
description: The client described in the Ethereum Yellowpaper

dependencies:
  - base

ghc-options: -Wall -O2

library:
  source-dirs: src/
  default-extensions: TemplateHaskell
  dependencies:
  - QuickCheck
  - aeson
  - base-unicode-symbols
  - base16-bytestring
  - binary
  - blockapps-datadefs
  - blockapps-util
  - bytestring
  - bytestring-arbitrary
  - clock
  - common-log
  - containers
  - data-default
  - deepseq
  - esqueleto
  - ethereum-rlp
  - filepath
  - format
  - generic-arbitrary
  - generic-random
  - json-stream
  - labeled-error
  - lens
  - merkle-patricia-db
  - milena
  - monad-alter
  - mtl
  - network
  - persistent
  - persistent-postgresql
  - persistent-template
  - quickcheck-instances
  - regex-compat
  - relapse
  - resourcet
  - secp256k1-haskell # remove
  - servant-docs
  - strato-conf
  - strato-model
  - swagger2
  - text
  - time
  - transformers
  - unliftio
  - unliftio-core
  - vector

executables:
  global-db:
    source-dirs: exec_src/
    main: GlobalDB.hs
    dependencies:
      - blockapps-data
      - strato-conf
      - hflags

tests:
  blockapps-data-test:
    source-dirs: test/
    main: Spec.hs
    dependencies:
      - aeson
      - aeson-diff
      - base16-bytestring
      - blockapps-data
      - blockapps-datadefs
      - blockapps-haskoin
      - bytestring
      - containers
      - ethereum-rlp
      - http-api-data
      - hspec
      - persistent
      - secp256k1-haskell
      - strato-model
      - text
      - unordered-containers
      - vector
      - QuickCheck
    ghc-options: -Wall -Werror -threaded -rtsopts -with-rtsopts=-N
