name: smd-ui-hs
version: 0.1.0.0
github: "githubuser/smd-ui-hs"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2024 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/smd-ui-hs#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - base16-bytestring
  - bloc2
  - bloc2api
  - bytestring
  - cache
  - clock
  - containers
  - core-api2
  - ethereum-discovery
  - filepath
  - file-embed
  - http-client
  - jsaddle
  - jsaddle-warp
  - jsaddle-wkwebview
  - jsaddle-dom
  - lens
  - reflex
  - reflex-dom
  - reflex-dom-core
  - scientific
  - servant
  - servant-client
  - servant-server
  - servant-websockets
  - strato-lite
  - strato-model
  - text
  - wai
  - wai-cors
  - wai-extra
  - wai-middleware-static
  - warp
  - websockets
  - wreq

library:
  source-dirs: 
    - src
  other-modules:
    - Paths_smd_ui_hs
  dependencies:
    - aeson
    - bytestring
    - containers
    - filepath
    - lens
    - jsaddle
    - jsaddle-warp
    - jsaddle-wkwebview
    - jsaddle-dom
    - reflex
    - reflex-dom
    - reflex-dom-core
    - servant
    - servant-client
    - servant-websockets
    - strato-lite
    - text
    - time
    - wai
    - wai-middleware-static
    - wai-cors
    - warp
    - wai-extra
    - websockets

executables:
  smd-ui-hs-browser:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - smd-ui-hs
      - jsaddle-dom

  smd-ui-hs-native:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - smd-ui-hs
      - jsaddle-wkwebview
      - jsaddle-dom

tests:
  smd-ui-hs-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - smd-ui-hs 