#!/bin/bash

set -e

function setEnv {
    [[ -n ${!1} ]] || eval $1=$2
    echo "$1 = ${!1}"
}

setEnv blocUrl "http://localhost:10001/bloc/v2.0"
setEnv stratoUrl "http://localhost/strato-api/eth/v1.2"

#setEnv blocUrl "http://localhost:8000/bloc/v2.0"
#setEnv stratoUrl "http://tester13.eastus.cloudapp.azure.com/strato-api/eth/v1.2"

