#!/bin/bash
set -e

if [ "$1" == "" ]
then
    echo "Error, you need to supply the contract" 1>&2
    exit 1
fi

function setEnv {
  [[ -n ${!1} ]] || eval $1=$2
  echo "$1 = ${!1}"
}

setEnv blocUrl "http://localhost:10001/bloc/v2.0"
setEnv stratoUrl "http://localhost/strato-api/eth/v1.2"
#setEnv stratoUrl "http://tester13.eastus.cloudapp.azure.com/strato-api/eth/v1.2"

contractName=`basename ${1%.*}`

function customHttp { # set behavior of http I like....  crash on error, print body to stderr, timeout longer

  set +e
  output=`http -b --check-status --timeout=60 "$@"`
  returnVal=$?
  set -e
  

  if [ "$returnVal" == "0" ]
  then
    echo "$output"
  else
    echo "$output" >&2
    exit $returnVal
  fi
}

echo "#################################################"
echo "# Creating a new address and running the faucet #"
echo "#################################################"

address=`customHttp --form $blocUrl/users/fred password=qqqq faucet=1`

echo "Here are the details of the new address '$address':"

customHttp $stratoUrl/account?address=$address | jq .
echo ""

src=$(cat ../Contracts/$contractName.sol)
echo $src

request=`echo '{"password":"qqqq", "args": {}, "value": 0, "txParams":{}}' | jq --arg src "$src" '.src= $src ' | jq --arg contractName "$contractName" '.contract= $contractName '`

echo $request

echo "########################"
echo "# Uploading a contract #"
echo "########################"

echo "$request" | customHttp POST $blocUrl/users/fred/$address/contract "Accept: */*"

echo ""

echo "##################################"
echo "# querying state in new contract #"
echo "##################################"

customHttp $blocUrl/contracts/$contractName/Latest/state/mapping/qqqq | jq .
