import "../../concrete/Bridge/BaseLightClient.sol";
import "../../concrete/Bridge/EthLightClient.sol";
import "../../libraries/Bridge/ILightClient.sol";

contract TestableEthLightClient4 is EthLightClient {
    constructor(address owner_) EthLightClient(owner_) {}
    function adminAnchor(
        uint256 blockNumber,
        bytes32 receiptsRoot,
        bytes32 stateRoot,
        uint64 beaconSlot,
        uint64 timestamp
    ) external onlyOwner {
        anchored[blockNumber] = AnchoredHeader({
            blockNumber: blockNumber,
            receiptsRoot: receiptsRoot,
            stateRoot: stateRoot,
            beaconSlot: beaconSlot,
            timestamp: timestamp
        });
    }
}

/**
 * @title  Describe_BaseLightClientCannon
 * @notice End-to-end test of {BaseLightClient.anchorBaseBlockViaCannon}
 *         against a real Base Sepolia block header + a synthetic L1
 *         DisputeGameCreated log.
 *
 *         The Base side is fully real (header bytes, stateRoot,
 *         receiptsRoot, withdrawalStorageRoot — all captured live and
 *         verified via keccak256(headerRLP) == block.hash).
 *
 *         The L1 side is synthesized because real DisputeGameCreated
 *         events commit to *proposed* outputRoots, which for unresolved
 *         games may not match the actual Base state. Synthesizing the
 *         log lets us bind to a known-good Base block we can verify
 *         independently — it exercises every code path the production
 *         Cannon flow runs (MPT inclusion, log decode, address/sig
 *         checks, outputRoot decomposition).
 *
 *         Fixture generated by tests/Bridge/fixtures/base-cannon-fixture.js.
 */
contract Describe_BaseLightClientCannon {
    BaseLightClient bc;
    TestableEthLightClient4 lc;
    address admin;

    /// Base Sepolia DisputeGameFactory (live address).
    address constant FACTORY = address(0xd6E6dBf4F7EA0ac412fD8b65ED297e64BB7a06E1);
    bytes32 constant DISPUTE_GAME_CREATED_SIG =
        bytes32(hex"5b565efe82411da98814f356d0e7bcb8f0219b8d970307c5afb4a6903a8b2e35");

    // === Generated by base-cannon-fixture.js ===
    // Real Base header fields captured from block 41122615:
    //   block.hash         = 0x9389e2e2569fcaeb1ac37e34545479d2f91a25a4c65065638bfba862b1dfbc5e
    //   block.stateRoot    = 0x938b28b47bad443e0fbd679a57d4781296a64e28f3ef07df9a4c6d72b1b29d08
    //   block.receiptsRoot = 0x8fa3728047fce21a06aaa30141432eb8c3fbb255384370b1aa941b4fa2bc9dbe
    //   withdrawalStorageRoot = 0xd9979659de27885765c860fb8c9f3e0c48c697fddacf3a1ecbd60ff5e156fc2b
    //   outputRoot           = 0x8180f63bb1d3cb6b4468e4c363143806ae6628ada80907f065ebaed7f80b70a9
    uint256 constant L1_BLOCK_NUMBER = 12345;
    uint256 constant TX_INDEX  = 1;
    uint256 constant LOG_INDEX = 0;
    uint256 constant BASE_BLOCK_NUMBER = 41122615;

    function _l1ReceiptsRoot() internal pure returns (bytes32) {
        return bytes32(hex"ddc26bb59eb916c5b7af11750f7b08ca9545ce302d6a50525b36db83442adb46");
    }
    function _expectedBaseReceiptsRoot() internal pure returns (bytes32) {
        return bytes32(hex"8fa3728047fce21a06aaa30141432eb8c3fbb255384370b1aa941b4fa2bc9dbe");
    }
    function _withdrawalStorageRoot() internal pure returns (bytes32) {
        return bytes32(hex"d9979659de27885765c860fb8c9f3e0c48c697fddacf3a1ecbd60ff5e156fc2b");
    }

    function _baseHeaderRLP() internal pure returns (bytes) {
        return hex"f90279a059f4997dc9bcd72aa87f921f2c76435182a45cfb5ebd0c1c9e261311d144eba4a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347944200000000000000000000000000000000000011a0938b28b47bad443e0fbd679a57d4781296a64e28f3ef07df9a4c6d72b1b29d08a0b406911b50ebd9113432169ff56c5fc66e9c571f77e09ff37e5b5eae45a5d175a08fa3728047fce21a06aaa30141432eb8c3fbb255384370b1aa941b4fa2bc9dbeb901004408002014028002c0c8112028d24808418ca094400042202000440050a1280062977c0488242420000034800c48c858040c10290208c010e004884a9a4041080c08b2108112822000000059388400002b4044040600084848002222598454891b070010012803080288805820165241461a4020410808400008a01002c1901842084001204608b64803150007060840000c00d18169c14b6020002104a0c403d911400001e10884804801014224248910bc0308008296041068a10000444b1082020822589a00c184800010c840011000042928a4a0001400118102460082c01808822236250a01802040004024000a20102001819508020520044400100502808402737b378417d7840083437b518469fa554e9101000000640000000500000000004c4b40a06d04bdf70ce31177eb5452904c4cb777fead1df74247f19ead5c623d20c5637d880000000000000000834c4b40a0d9979659de27885765c860fb8c9f3e0c48c697fddacf3a1ecbd60ff5e156fc2b8307fa8480a0322226e869e6b614b6d1d3d47d95d154d1046cbedd78a39310a6ed9289f7b098a0e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";
    }

    function _receiptValueBytes() internal pure returns (bytes) {
        return hex"02f901a8018382cafeb9010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f89ef89c94d6e6dbf4f7ea0ac412fd8b65ed297e64bb7a06e1f884a05b565efe82411da98814f356d0e7bcb8f0219b8d970307c5afb4a6903a8b2e35a0000000000000000000000000b9c83f8d89c4d13ed3b93021f90d59d57bdda6c1a00000000000000000000000000000000000000000000000000000000000000001a08180f63bb1d3cb6b4468e4c363143806ae6628ada80907f065ebaed7f80b70a980";
    }

    function _mptProof() internal pure returns (bytes[] memory proof) {
        proof = new bytes[](3);
        proof[0] = hex"f851a05f27ae99c4e4449c5470bfe619bd9e8f210c04f1777256fa9f0e7f2d939eb82480808080808080a0cc38d2208d78c8e2c3b63660627fb95881aec8923de22623e3ff3164241e45d58080808080808080";
        proof[1] = hex"f87180a0d05f838b3c8d0fced181f74c75eeee7e0287804a1f099fdd0d1fd062257b207fa069a30841e12aea055e245507fe44e86fd8be72bc0f48151c7e8f0e9e34a400aba009dc7b15bfff962a6920fb6bf74494ed2a05b83352d73b7f067913f304954d7e80808080808080808080808080";
        proof[2] = hex"f901b020b901ac02f901a8018382cafeb9010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f89ef89c94d6e6dbf4f7ea0ac412fd8b65ed297e64bb7a06e1f884a05b565efe82411da98814f356d0e7bcb8f0219b8d970307c5afb4a6903a8b2e35a0000000000000000000000000b9c83f8d89c4d13ed3b93021f90d59d57bdda6c1a00000000000000000000000000000000000000000000000000000000000000001a08180f63bb1d3cb6b4468e4c363143806ae6628ada80907f065ebaed7f80b70a980";
    }

    function beforeEach() {
        admin = address(this);
        lc = new TestableEthLightClient4(admin);
        bc = new BaseLightClient(
            admin,
            EthLightClient(address(lc)),
            FACTORY,
            DISPUTE_GAME_CREATED_SIG
        );
        // Stage the L1 receipts root.
        lc.adminAnchor(L1_BLOCK_NUMBER, _l1ReceiptsRoot(), bytes32(0), uint64(0), uint64(0));
    }

    function it_anchors_via_cannon_end_to_end() {
        OutputReceiptProof memory proof = OutputReceiptProof({
            l1BlockNumber: L1_BLOCK_NUMBER,
            txIndex: TX_INDEX,
            logIndex: LOG_INDEX,
            receiptValueBytes: _receiptValueBytes(),
            mptProof: _mptProof()
        });
        (uint256 anchoredBlockNumber, bytes32 anchoredReceiptsRoot) =
            bc.anchorBaseBlockViaCannon(proof, _baseHeaderRLP(), _withdrawalStorageRoot());
        require(anchoredBlockNumber == BASE_BLOCK_NUMBER, "block number");
        require(anchoredReceiptsRoot == _expectedBaseReceiptsRoot(), "receipts root");
        require(bc.getReceiptsRoot(BASE_BLOCK_NUMBER) == _expectedBaseReceiptsRoot(), "view");
        require(bc.isAnchored(BASE_BLOCK_NUMBER), "isAnchored");
    }

    function it_rejects_wrong_factory_address() {
        // Point at a different factory; the log's emitter address won't match.
        bc.setDisputeGameFactory(address(0xc0DE000000000000000000000000000000000099));
        OutputReceiptProof memory proof = OutputReceiptProof({
            l1BlockNumber: L1_BLOCK_NUMBER,
            txIndex: TX_INDEX,
            logIndex: LOG_INDEX,
            receiptValueBytes: _receiptValueBytes(),
            mptProof: _mptProof()
        });
        bool reverted = false;
        try {
            bc.anchorBaseBlockViaCannon(proof, _baseHeaderRLP(), _withdrawalStorageRoot());
        } catch {
            reverted = true;
        }
        require(reverted, "should revert on wrong factory");
    }

    function it_rejects_wrong_cannon_sig() {
        bc.setDisputeGameCreatedSig(bytes32(uint256(0x1234)));
        OutputReceiptProof memory proof = OutputReceiptProof({
            l1BlockNumber: L1_BLOCK_NUMBER,
            txIndex: TX_INDEX,
            logIndex: LOG_INDEX,
            receiptValueBytes: _receiptValueBytes(),
            mptProof: _mptProof()
        });
        bool reverted = false;
        try {
            bc.anchorBaseBlockViaCannon(proof, _baseHeaderRLP(), _withdrawalStorageRoot());
        } catch {
            reverted = true;
        }
        require(reverted, "should revert on wrong sig");
    }
}
