name: blockapps-strato-server
version: 0.1.0.0
synopsis: Strato microservice
description: Strato microservice API definitions
github: blockapps/strato-platform/blockapps-haskell/strato/api
license-file: LICENSE
author: Kristoffer Josefsson
maintainer: kristoffer@blockapps.net
copyright: 2017 BlockApps
category: Web
build-type: Simple

ghc-options: -Wall

dependencies:
  - base
  - QuickCheck
  - aeson
  - aeson-casing
  - binary
  - blockapps-ethereum
  - blockapps-solidity
  - blockapps-strato-api
  - containers
  - generic-random
  - http-api-data
  - http-client
  - largeword
  - lens
  - quickcheck-instances
  - prettyprinter
  - servant
  - servant-client
  - servant-docs
  - servant-server
  - servant-swagger
  - swagger2
  - text
  - time
  - unordered-containers
  - wai-cors
  - warp

executable:
  source-dirs: src/
  main: Main.hs
