name: blockapps-strato-server
version: 0.1.0.0
synopsis: Strato microservice
description: Strato microservice API definitions
github: blockapps/strato-platform/blockapps-haskell/strato/api
license-file: LICENSE
author: Kristoffer Josefsson
maintainer: kristoffer@blockapps.net
copyright: 2017 BlockApps
category: Web
build-type: Simple

ghc-options: -Wall

dependencies:
  - base
  - blockapps-init
  - blockapps-strato-api
  - lens
  - servant
  - servant-server
  - servant-swagger
  - swagger2
  - wai-cors
  - warp

executable:
  source-dirs: src/
  main: Main.hs
