#!/bin/bash

#set -e

if [ -e .scurl.config ]
then
    . .scurl.config
else
    echo "Fill in the following information:"
    read -p " - OAUTH Discovery URL: " OAUTH_TOKEN_URL
    read -p " - OAUTH Client ID: " OAUTH_CLIENT_ID
    read -s -p " - OAUTH Client Secret: " OAUTH_CLIENT_SECRET
    echo
fi

authdata=`echo -n "$OAUTH_CLIENT_ID:$OAUTH_CLIENT_SECRET" | base64 -w0`

returnValue=`curl -s -X POST $OAUTH_TOKEN_URL -H 'Content-Type: application/x-www-form-urlencoded' -H "Authorization: Basic $authdata" --data-urlencode 'grant_type=client_credentials'`

if [ "`echo $returnValue | jq 'has("error")'`" = "true" ]
then
    error=`echo $returnValue | jq -r ".error"`
    error_description=`echo $returnValue | jq -r ".error_description"`
    echo "$error: $error_description"
    exit 1;
elif [ "`echo $returnValue | jq 'has("access_token")'`" = "true" ]
then
    token=`echo $returnValue | jq -r ".access_token"`
else
    echo "malformed response from login server: $returnValue"
    exit 1;
fi

echo "Login succeeded"

echo "$token" > .token

