-- |
-- Module: Parser
-- Description: The Solidity source parser function
-- Maintainer: Ryan Reich <ryan@blockapps.net>
module Parser (parseSolidity) where

import Text.Parsec hiding (parse)

import File
import ParserTypes

-- | The 'parseSolidity' function parses a single Solidity source string (with
-- a given name) into a Haskell data type.  Parser errors are generated by
-- 'Parsec'.
parseSolidity :: FileName -> String -> Either ParseError SolidityFile
parseSolidity = runParser solidityFile "" 

