name:                strato-api2

dependencies:
- base
- blockapps-util
- hflags
- lens
- monad-alter
- servant-server
- servant-swagger
- swagger2
- sql-monad
- unliftio
- wai

library:
  source-dirs: src
  ghc-options: -Wall -O2
  dependencies:
    - aeson
    - base16-bytestring
    - blockapps-data
    - blockapps-datadefs
    - bytestring
    - clock
    - conduit
    - deepseq
    - directory
    - esqueleto
    - ethereum-discovery
    - filepath
    - format
    - http-types
    - insert-ordered-containers
    - persistent-postgresql
    - process
    - QuickCheck
    - servant-client
    - seqevents
    - servant-swagger-tags
    - strato-conf
    - strato-model
    - template-haskell
    - text
    - unordered-containers

executables:
  strato-api2:
    main:                Main.hs
    source-dirs:         exec_src
    other-modules:
    - SelectAccessible
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blockapps-init
    - servant-swagger-ui
    - mtl
    - strato-api2
    - transformers
    - vault-monad
    - wai-cors
    - wai-extra
    - wai-middleware-prometheus
    - warp


