#!/bin/bash

set -e

address=`curl -d 'password=abcd' http://localhost/bloc/v2.2/users/fred | perl -pe "s/\"//g"`

echo "address is $address"

curl -X POST http://localhost/bloc/v2.2/users/fred/$address/fill?resolve


echo
echo "################ Calling POST /contract"
echo

contractAddress=`curl -d'{"src": "contract qq{ int theValue; string v2; constructor() {int x=10; int y = x+1; if (y > x) theValue=x;} function setTheValue(int x, string y) { theValue = x; v2=y; } function getTheValue() returns (int) { return theValue; } function getTheString() returns (string) { return v2; } }", "metadata":{"VM": "SolidVM"}, "password": "abcd"}' -H "Content-Type: application/json" http://localhost/bloc/v2.2/users/fred/$address/contract?resolve | perl -pe 's/.*contractsCreated\"\:\"(.*?)\".*/\$1/'`

echo "newly created contract address is $contractAddress"



echo
echo "################ Calling POST /call: Setting the value"
echo


curl -d'{"method": "setTheValue", "args": {"x": "20", "y": "believe the weasel"}, "password": "abcd"}' -H "Content-Type: application/json" -i http://localhost/bloc/v2.2/users/fred/$address/contract/qq/$contractAddress/call?resolve

echo
echo "################ Calling POST /call: getTheValue"
echo

curl -d'{"method": "getTheValue", "args": {}, "password": "abcd"}' -H "Content-Type: application/json" -i http://localhost/bloc/v2.2/users/fred/$address/contract/qq/$contractAddress/call?resolve

echo
echo "################ Calling POST /call: getTheString"
echo

curl -d'{"method": "getTheString", "args": {}, "password": "abcd"}' -H "Content-Type: application/json" -i http://localhost/bloc/v2.2/users/fred/$address/contract/qq/$contractAddress/call?resolve

echo
echo
