name:                certificateDB

dependencies:
  - base

library:
  source-dirs: src
  ghc-options: -Wall -Werror -O2
  dependencies:
  - bytestring
  - hedis
  - monad-alter
  - mtl
  - strato-conf
  - strato-model
  - strato-redis-blockdb
  - text
