name: blockapps-data
version: 0.0.1
build-type: Simple
author: Jamshid
license-file: LICENSE
maintainer: jamshidnh@gmail.com
synopsis: A Haskell version of an Ethereum client
category: Data Structures
license: Apache-2.0
description: The client described in the Ethereum Yellowpaper
github: blockapps/strato-platform/core-strato/blockapps-data

dependencies:
  - base
  - aeson
  - ansi-wl-pprint
  - base-unicode-symbols
  - base16-bytestring
  - binary
  - blockapps-datadefs
  - blockapps-haskoin
  - blockapps-milena
  - blockapps-util
  - bytestring
  - bytestring-arbitrary
  - clock
  - conduit
  - conduit-combinators
  - containers
  - crypto-pubkey-types
  - data-default
  - deepseq
  - derive
  - esqueleto
  - ethereum-encryption
  - ethereum-rlp
  - fast-ecrecover
  - filepath
  - format
  - json-stream
  - lens
  - leveldb-haskell
  - lifted-base
  - merkle-patricia-db
  - monad-control
  - monad-logger
  - mtl
  - network
  - nibblestring
  - persistent
  - persistent-postgresql
  - persistent-template
  - QuickCheck
  - resourcet
  - strato-conf
  - strato-model
  - text
  - time
  - transformers
  - unliftio
  - unliftio-core
  - unordered-containers
  - vector

ghc-options: -Wall -O2

library:
  source-dirs: src/
  default-extensions: TemplateHaskell

executables:
  global-db:
    source-dirs: exec_src/
    main: GlobalDB.hs
    dependencies:
      - blockapps-data
      - strato-conf
      - hflags

tests:
  blockapps-data-test:
    source-dirs: test/
    main: Spec.hs
    dependencies:
      - aeson-diff
      - blockapps-data
      - directory
      - hspec
      - hspec-expectations-lifted
      - HUnit
      - unix
      - unordered-containers
      - vector
    ghc-options: -Wall -Werror -threaded -rtsopts -with-rtsopts=-N
