name: 'Check Branch Merge Flow'

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch 3
        if: github.base_ref == 'devel' && github.head_ref != 'my-non-existent-branch'
        run: |
          echo "ERROR: You can only merge to 'devel' from 'my-non-existent-branch' (TESTING). Trigger GitHub Action \#1"
          exit 1
